### ISSUE TITLE
Terraform crash during apply

### ISSUE THREAD

**Issue by franzramadhan** [Telmate/terraform-provider-proxmox#1]
Hi there,

Got some issue while trying to use this provider

**OS**
Ubuntu 16.04 LTS 4.10.0-041000-generic

**Terraform Version**
Terraform v0.9.6

**Affected Provider**
proxmox

**Affected Resource**
proxmox_vm_qemu

**Panic Output**
https://gist.github.com/franzramadhan/1396b23198f8f9e59c4fd9c7f6e4ae17

Thanks

**Comment by ggongaware** [comment]
I just pushed an update to the https://github.com/Telmate/proxmox-api-go project, this uses, that should give better error logs about login problems.

**Comment by franzramadhan** [comment]
okay thanks for the update, now the problem seems to be clear

* provider.proxmox: Post https://x.x.x.x.:8006/api2/json/access/ticket: x509: certificate signed by unknown authority

**Comment by ggongaware** [comment]
How about we add an ENV variable option for skipping https/ssl validation?

**Comment by Kdecherf** [comment]
You should document how to trust self-signed certificate (using `update-ca-certificates`) instead of skipping validation.

**Comment by ggongaware** [comment]
@franzramadhan Would it work to install your cert as trusted with these steps - 

https://superuser.com/questions/97201/how-to-save-a-remote-server-ssl-certificate-locally-as-a-file
https://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list

**Comment by franzramadhan** [comment]
@ggongaware thanks for your suggestion.

I already installed and configured proxmox server using trusted certificate from trusted CA.

now this issue arises

> * provider.proxmox: Invalid login response

**PVE Version**
root@node:~# pveversion 
pve-manager/3.4-1/3f2d890e (running kernel: 2.6.32-37-pve)

**Comment by ggongaware** [comment]
I pushed another update to https://github.com/Telmate/proxmox-api-go to output the actual server response during login.

**Comment by ggongaware** [comment]
@franzramadhan you made need to add the realm to your pm_user.

pm_user = "root@pam"
or
pm_user = "root@pve"

**Comment by franzramadhan** [comment]
Hi @ggongaware 

Many thanks for your suggestion. 

Sorry for the late update, here is latest result of apply.

> 2017/07/03 13:57:32 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:
> 
> * proxmox_vm_qemu.testing: Vm INFO not found
> 2017/07/03 13:57:32 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
> 
> * proxmox_vm_qemu.testing: Vm INFO not found
> 2017/07/03 13:57:32 [TRACE] [walkApply] Exiting eval tree: proxmox_vm_qemu.testing
> 2017/07/03 13:57:32 [DEBUG] dag/walk: upstream errored, not walking "provisioner.remote-exec (close)"
> 2017/07/03 13:57:32 [DEBUG] dag/walk: upstream errored, not walking "provisioner.proxmox (close)"
> 2017/07/03 13:57:32 [DEBUG] dag/walk: upstream errored, not walking "provider.proxmox (close)"
> 2017/07/03 13:57:32 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
> 2017/07/03 13:57:32 [DEBUG] dag/walk: upstream errored, not walking "root"
> 2017/07/03 13:57:32 [TRACE] Preserving existing state lineage "74da8a6b-6b8f-46a7-8b97-c6931bbd8d8f"
> Error applying plan:
> 2017/07/03 13:57:32 [DEBUG] plugin: waiting for all plugin processes to complete...
> 
> 1 error(s) occurred:
> 
> * proxmox_vm_qemu.testing: 1 error(s) occurred:
> 
> * proxmox_vm_qemu.testing: Vm INFO not found
> 
> Terraform does not automatically rollback in the face of errors.
> Instead, your Terraform state file has been partially updated with
> any resources that successfully completed. Please address the error
> above and apply again to incrementally change your infrastructure.
>

**Comment by ggongaware** [comment]
Try the latest build proxmox-api-go and terraform-provider-proxmox updates. If there's still a problem try turning on the debug log so we can trace it 
```
TF_LOG=DEBUG terraform apply
```

**Comment by andrewfraley** [comment]
I have the same or similar issue, debug log here:  https://gist.github.com/andrewfraley/1bb2b80f63629549b908d626a2ca5f25

(thanks btw!)

**Comment by cc12258** [comment]
I think I'm having a similar issue with an error:

```
Error applying plan:
2017/11/07 16:51:54 [DEBUG] plugin: waiting for all plugin processes to complete...
2017-11-07T16:51:54.823-0700 [WARN ] plugin: error closing client during Kill: err="connection is shut down"

1 error(s) occurred:

* proxmox_vm_qemu.test01: 1 error(s) occurred:

* proxmox_vm_qemu.test01: unexpected EOF
```

**Comment by cc12258** [comment]
I found the part of the code from the API that it errors out at, I wonder if it needs to give a bit more time for creation of the VM?

```
func (c *Client) GetVmConfig(vmr *VmRef) (vmConfig map[string]interface{}, err error) {
	err = c.CheckVmRef(vmr)
	if err != nil {
		return nil, err
	}
	var data map[string]interface{}
	url := fmt.Sprintf("/nodes/%s/%s/%d/config", vmr.node, vmr.vmType, vmr.vmId)
	err = c.GetJsonRetryable(url, &data, 3)
	if err != nil {
		return nil, err
	}
	if data["data"] == nil {
>>>		return nil, errors.New("Vm CONFIG not readable")
	}
	vmConfig = data["data"].(map[string]interface{})
	return
}
```

**Comment by ggongaware** [comment]
This line 
```c.GetJsonRetryable(url, &data, 3)``` has 3 retries, you could raise it to see if it helps.

**Comment by cc12258** [comment]
I made a couple of small changes in proxmox-api-go which fixed this EOF error for me. The following:

```
func NewConfigQemuFromApi(vmr *VmRef, client *Client) (config *ConfigQemu, err error) {
	var vmConfig map[string]interface{}
	for ii := 0; ii < 6; ii++ { <---- Gave this a few more tries
		vmConfig, err = client.GetVmConfig(vmr)
		if err != nil {
			log.Fatal(err)
			return nil, err
		}
		// this can happen:
		// {"data":{"lock":"clone","digest":"eb54fb9d9f120ba0c3bdf694f73b10002c375c38","description":" qmclone temporary file\n"}})
		if vmConfig["lock"] == nil {
			break
		} else {
			time.Sleep(15 * time.Second) <---- made this longer
		}
	}
```

It consistently creates for me, I could fork and do a pull request if you want, but this may not be ideal for other cases.

**Comment by cc12258** [comment]
I also raised the timeout to 8 seconds instead of 5 in GetJsonRetryable and that seems to have smoothed out the errors.

**Comment by ggongaware** [comment]
I welcome more timeouts and retries to the code base if it increases stability.
