### ISSUE TITLE
Creating a VM using cicustom with network= triggers warning

### ISSUE THREAD

**Issue by avitacco** [Telmate/terraform-provider-proxmox#1011]
When I create VMs using `cicustom = "network=storage/whatever.yaml"` I get a warning saying that I'm not assigning a static IP or using DHCP.

Could the code to trigger this warning either check to see if `cicustom` contains a `network=` or be made optionally silent? In my case, networking _is_ configured and this warning represents a false positive.

For reference, the code in question is here:
https://github.com/Telmate/terraform-provider-proxmox/blob/263e663cc4389bae339309bc110650e709b11d09/proxmox/resource_vm_qemu.go#L1922

Thanks!

Edit: I also want to thank you for all the work on this module. Maintaining a project like this can often feel like a thankless task, but I am ever so grateful for it. Thank you!

**Comment by avitacco** [comment]
I am rendering templates for network configuration and uploading them to the Proxmox cluster on shared storage.

**Comment by Tinyblargon** [comment]
When `cicustom` is set and no ip config is found in the proxmox provided cloud-init settings, continue with normal execution. There is no way to get any information out of a `cicustom` file

**Comment by Tinyblargon** [comment]
https://github.com/Telmate/proxmox-api-go/pull/339

**Comment by Tinyblargon** [comment]
@avitacco Could you check if #1049 fixes this for you?

**Comment by maksimsamt** [comment]
> I get an error when I do an `apply` with a build from the `Tinyblargon/#1042` branch. This might be a problem with my config, but I don't get it with RC3.
> 
> ```json
> {
>   "data": null,
>   "errors": {
>     "ciupgrade": "property is not defined in schema and the schema does not allow additional properties"
>   }
> }
> ```
> 
> I will enable debugging output and reply tomorrow with more information.

As per [documentation](https://github.com/Tinyblargon/terraform-provider-proxmox/blob/%231042/docs/resources/vm_qemu.md) from #1049 and related issue https://github.com/Telmate/terraform-provider-proxmox/issues/997 you have to add in your variables and config `ciupgrade` attribute

**Comment by Tinyblargon** [comment]
Weird, when i go from master to #1049 the `ciupgrade` property is added automatically.
