### ISSUE TITLE
Stuck while destroying instance

### ISSUE THREAD

**Issue by jbaenaxd** [Telmate/terraform-provider-proxmox#1023]
Sometimes, I want to destroy an instance because there's a problem with the installation or some processes are blocked. It seems that the behaviour for this destroying a VM is to send a shutdown signal. Why not a stop signal? Anyway we are gonna destroy it, better to do it faster. If the VM state is unstable, the shutdown signal will fail and the destroy action can't be performed, after that, I have to cancel the shutdown action and send a stop action to let the destruction to continue.

Proposed action:
- Change VM destroy action from `shutdown` to `stop`

**Comment by k-w-d-e** [comment]
Problem does not seem to be fixed.

Running `terraform destroy` wont forcefully stop the VM.

I've waited >10min and in Proxmox Tasks log i see 'Description: VM <ID> - Shutdown' and Status is a rotating circle.

I too am trying to 'destroy' a running installation process.

**Comment by TomyLobo** [comment]
Someone reintroduced this issue in between 3.0.1-rc3 and 3.0.1-rc4, 5 months ago:
https://github.com/Telmate/terraform-provider-proxmox/commit/641d0963dd6ae37409206139184c310d655ce058#diff-104365919f693375882979581d9f36f5266991eef361948e56c220931fe886ddL1615

**Comment by TomyLobo** [comment]
This looks like changes between 3.0.1-rc2 and 3.0.1-rc3 were accidentally reverted in 3.0.1-rc4, as part of that commit.
@Tinyblargon, on the off-chance that this isn't the only change, can you take a look at the commit I linked and see if you accidentally reverted anything else?

**Comment by emoxam** [comment]
Well, any news ?
Destroying stuck at the shutdown..

**Comment by Tinyblargon** [comment]
@emoxam could you create a mew issue and post the debug log?

In RC6 it does a stop instead of a shutdown.
Terraform always has to do a preliminary read operation, that might be hanging.

**Comment by emoxam** [comment]
@Tinyblargon RC6 seems to work! I was using RC4.
Thanks!
