### ISSUE TITLE
Error: no provider exists with the given name

### ISSUE THREAD

**Issue by MarvinMedia** [Telmate/terraform-provider-proxmox#103]
Hi,
Sorry, I'm new here at terraform.
I have the error message: "Error: no provider exists with the given name"
Can someone help me?

**Comment by MarvinMedia** [comment]
### The complete message:


terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "proxmox" not available for installation.

A provider named "proxmox" could not be found in the Terraform Registry.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/linux_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".


Error: no provider exists with the given name

**Comment by staudstreet** [comment]
To install the provider you need to run 
"""
go get https://github.com/Telmate/terraform-provider-proxmox/
go install https://github.com/Telmate/terraform-provider-proxmox/
"""

**Comment by apollocreed** [comment]
Hello 
If you have problem with your PATH you should consider using
``terraform init -plugin-dir=$TF_PLUGIN_CACHE_DIR``
it will override default provider path to the  proxmox one
