### ISSUE TITLE
terraform plan showing changes when there are none

### ISSUE THREAD

**Issue by redhug1** [Telmate/terraform-provider-proxmox#1030]
Proxmox: v8.2.2
      source = "telmate/proxmox"
      version = "3.0.1-rc2"

After doing "terraform apply" and getting a working qemu VM (with cloud init stuff all working) against a packer built cloud-init image ...

When i run "terraform plan" (without making any changes), i get:

```text
module.cic1.proxmox_vm_qemu.test_server: Refreshing state... [id=prox4/qemu/200]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.cic1.proxmox_vm_qemu.test_server will be updated in-place
  ~ resource "proxmox_vm_qemu" "test_server" {
      - desc                   = "k8" -> null
        id                     = "prox4/qemu/200"
        name                   = "ci-c1"
        tags                   = "ci_c1"
        # (64 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by Tinyblargon** [comment]
Which error messages are you getting?

Also, the upstream PVE SDK now enforces the same limitations on `tag` names as the PVE web ui.

**Comment by redhug1** [comment]
Sorry, please ignore bit about tags, i was in the middle of deleting that section. Its just the plan indicating a change when there was none thats the problem.

**Comment by redhug1** [comment]
I've found the problem.
In my packer k8.pkr.hcl file i was setting:
```template_description = "k8"```
and then in my terraform file i had no ```desc = "k8"```
Adding that stopped the plan showing changes needed.
