### ISSUE TITLE
Output the public DNS or the public IP address of the created VM

### ISSUE THREAD

**Issue by SellamiRami** [Telmate/terraform-provider-proxmox#104]
Hello, 
I want to output the public DNS or the public IP address of the created VM once Terraform finish creating a new VM.
I did not find how to specify in the Terraform script this action.
Could you please give more details. 
Thanks in advance.
Rami.

**Comment by cc12258** [comment]
Have you tried the sample configuration, using the provisioner:

```
provisioner "remote-exec" {
    inline = [
      "ip a"
    ]
  }
```

Which should output the IP address configuration in the output, you could also script that to match the format you need.

**Comment by SellamiRami** [comment]
Thank you @cc12258 for the reponse. 
When add the provisioner, the execution of the VM instance does not stop and does not achieve.
In addition, could you please help me in attaching it to the output?
Thanks in advance !

**Comment by backaf** [comment]
I'd also be interested in this feature. Currently with a DHCP setup I don't see a way to retrieve the vm IP. But this IP would be exposed by the qemu agent so if we could retrieve that we could run provisioning with a DHCP setup as well. Or maybe there's a way which I am not seeing?

**Comment by zinefer** [comment]
Should the `remote-exec` work for lxc? I can tell the container came up but the terraform provider seems to keep retrying the connection forever.

**Comment by mrlesmithjr** [comment]
Adding that this functionality **WOULD** be extremely useful and shocked it isn't there already. The ability to scrape the TFSTATE using something like [terraform-to-ansible](https://github.com/mrlesmithjr/terraform-to-ansible) would be amazing!

Just adding my `.02` here.

**Comment by nmcbride** [comment]
I'm fighting the same battle trying to get the private ips after the vm is created.
Does this support any outputs?

**Comment by hanzou89** [comment]
Anyone can get the address ip?
remote-exec doesn't work for me.

**Comment by mleone87** [comment]
> Anyone can get the address ip?
> remote-exec doesn't work for me.

#271 for some hints. Rememeber your image must have qemu-agent enabled on proxmox and installed/active

**Comment by hanzou89** [comment]
> 
> 
> > Anyone can get the address ip?
> > remote-exec doesn't work for me.
> 
> #271 for some hints. Rememeber your image must have qemu-agent enabled on proxmox and installed/active

Thank you.
Do you know how install it in Alpine?

**Comment by hanzou89** [comment]
> 
> 
> > > Anyone can get the address ip?
> > > remote-exec doesn't work for me.
> > 
> > 
> > #271 for some hints. Rememeber your image must have qemu-agent enabled on proxmox and installed/active
> 
> Thank you.
> Do you know how install it in Alpine?

Install it and working.
Thanks again.

**Comment by ioagel** [comment]
In "proxmox_vm_qemu" resource do this:
```hcl
provisioner "local-exec" {
    when = create
    command = "echo \"The IP of vm '${self.name}' is '${self.default_ipv4_address}'\""
  }
```

**Comment by briandipalma** [comment]
A possible workaround; I set a MAC address via terraform and give those MAC addresses a fixed IP address in my firewall/router (OPNSense).

**Comment by needleshaped** [comment]
> Probably a bit late to the party on this one... But, if you create an `outputs.tf` file, you can populate it with code blocks to display DHCP addresses:
> 
> ```
> output "dhcp_ip" {
>   value = proxmox_vm_qemu.vmName.default_ipv4_address
> }
> ```
> 
> The one caveat to this is that you'll need to have qemu-guest-agent running... so install it before you convert your VM to a template.

Correct me if I'm wrong (as I'm new to Terraform), but this solution allows to output only for specific, hardcoded "vmName", and not for all VMs that are being created, right?

What worked for me, is `provisioner "local-exec"` approach.
