### ISSUE TITLE
Network parameters cannot be removed from cloudinit settings

### ISSUE THREAD

**Issue by maksimsamt** [Telmate/terraform-provider-proxmox#1042]
System details:

- Proxmox VE 8.2.2
- Terraform v1.8.4
- terraform-provider-proxmox v3.0.1-rc3

Affected cloudinit network parameters:

- `searchdomain`
- `nameserver`
- `ipconfig0-15`

Creating new resources works as expected, mentioned cloudinit network parameters are correctly created.

These parameters can be changed by provider.

Unfortunately, it is not possible to remove these parameters by provider.

By removing the `searchdomain` and `nameserver` arguments from the config, provider ignores this change and does not take any action with the output: `No changes. Your infrastructure matches the configuration.`

By removing `ipconfig0-15`, provider tries to remove this, but after apply the previously created `ipconfig` it still exists. When I try to run terraform apply again, it tries to remove this again and again with no success. The similar situation is with network device removing - https://github.com/Telmate/terraform-provider-proxmox/issues/1027.

These parameters can only be removed through the Proxmox GUI.

**Comment by Tinyblargon** [comment]
@maksimsamt I noticed so weird behavior with cloud-init. Sadly, the scope of the problem got too big for the RC3 release. I'm working on it in https://github.com/Telmate/proxmox-api-go/pull/339

**Comment by Tinyblargon** [comment]
@maksimsamt Could you check if #1049 fixes this for you?

**Comment by maksimsamt** [comment]
> @maksimsamt Could you check if #1049 fixes this for you?

@Tinyblargon ,
Could please for #1049 create additional branch or tag?

**Comment by maksimsamt** [comment]
> @maksimsamt Could you check if #1049 fixes this for you?

- `searchdomain` - works, can add and remove
- `nameserver` - works, can add and remove
- `ipconfig0-15` -  doesn't work, can add, but remove cannot
