### ISSUE TITLE
rc3 broken for tags with hyphen

### ISSUE THREAD

**Issue by cmmarslender** [Telmate/terraform-provider-proxmox#1044]
New error with rc3:
`Error: tag validation failed: tag may only include the following characters: abcdefghijklmnopqrstuvwxyz0123456789_`

Seems like there was some tag validation added to rc3 (or possibly rc2 - I'm not sure I had a successful run of this project on rc2) that is breaking any tags I try to add that contain `-`. In previous versions, this worked fine and in proxmox, tags with `-` work fine as well. Can the allowed characters for tags be expanded to include `-`?

**Comment by cmmarslender** [comment]
Seems like this may have actually been introduced in rc2. The error seems to come from here I think https://github.com/Telmate/terraform-provider-proxmox/pull/1007/files#diff-d218b4c62dacc2f3bc02d11e0e732aa1cf57acc61262d17aef194629e36d0d78R43

**Comment by Tinyblargon** [comment]
@cmmarslender created the issue upstream in the Proxmox SDK https://github.com/Telmate/proxmox-api-go/issues/340

**Comment by Tinyblargon** [comment]
Fixed in main
