### ISSUE TITLE
Windows Deployment?

### ISSUE THREAD

**Issue by gentoo9ball** [Telmate/terraform-provider-proxmox#105]
I'm sorry if this is the wrong place to post this. Can anyone help me find a way to deploy/build windows images by supplying an autounattend file? The Packer Proxmox Builder doesn't seem to support supplying floppy_files. 

My end goal is to auto-build and host a test windows domain with AD, clients, logging, etc. Right now, I'm at step -1, so all ideas are welcome.

Thank you for any suggestions or ideas.

**Comment by gentoo9ball** [comment]
Got some related feedback here. https://github.com/hashicorp/packer/issues/7950

One person has made it work via Ansible and Proxmox CLI, so it can be done, but not easily

**Comment by jahmelharris** [comment]
I'd also like to be able to do this. I've taken a look today and from what I can see, the Proxmox API doesn't support creating multiple drives when creating a VM. The API does allow for mounting an ISO/creating drives once a VM is created.

I'm hoping it should be easy enough modify the "Creating VM" step to make another call to the Proxmox API.
