### ISSUE TITLE
Disk not resized on creation

### ISSUE THREAD

**Issue by SySamu-Hallon** [Telmate/terraform-provider-proxmox#1050]
Hi all!
After the new disk scheme, we have to run apply twice to resize disk on creation.
Now I'm using the self-compiled code you suggest to use to solve the problem after Proxmox8 Upgrade.
Here's my tf provider:

```
terraform {
  required_version = ">= 0.13.0"

  required_providers {
    proxmox = {
        source = "registry.example.com/telmate/proxmox"
        version = ">=1.0.0"
        #source = "telmate/proxmox"
        #version = "3.0.1-rc3"
        #version = ">=1.0.0"
    }
  }
}
```

And my main.tf:
```
resource "proxmox_vm_qemu" "vm" {
    name = "vm1"
    desc = ""
    vmid = "235"
    target_node = "mynode2"

    agent = 1
    os_type = "cloud-init"
    clone = "ubuntu-server-2204-template-docker"
    cores = 4
    sockets = 1
    cpu = "host"
    memory = 65536
    balloon = 32768
    hotplug= "disk,network,usb"
    numa = false
    tags = "testing"
    qemu_os="other"

    network {
      bridge = "vmbr1"
      model = "virtio"
    }

    #disk {
    #  storage = "local"
    #  type = "virtio"
    #  size = "400G"
    #}

    disks {
        virtio {
            virtio0 {
                disk {
                    size = 400
                    storage = "local"
                }
            }
        }
    }

    #cloudinit_cdrom_storage = "local"
 
    bootdisk = "virtio0"


    ipconfig0 = "ip=192.168.35.85/19,gw=192.168.32.1"
    nameserver = "192.168.35.82"
    ciuser = var.tsg_user
    cipassword = var.tsg_password
    sshkeys = <<EOF
    ${var.tsg_key}
    EOF
```
    
    ------rest of stuff code(scripts, executions, etc).

}

So in summary, when I created the VM, on first apply, the disk is not being resized, it is grabbing template disk size. If I apply second time(with vm created) I'm getting the disk resized.

In advance, thanks a lot at all team behind telmate, keeping this plugin updated :)

**Comment by maksimsamt** [comment]
@SySamu-Hallon,
Did you try to change these config values?
```hcl
#
qemu_os="other"
# change to
qemu_os="l26"
```
```hcl
#
bootdisk = "virtio0"
# comment out this line
#bootdisk = "virtio0"
# as per doc:
# Enable booting from specified disk. You shouldn't need to change it under most circumstances.
```
As well, try to change virtio to scsi disk, if possible

**Comment by SySamu-Hallon** [comment]
Let me try it this morning and come back. My template has been created with virtio instead scsi, it will be a problem change on creation? i can fit the template to scsi anyway, but, just to know.
Now i'm using Terraform 1.8.5:

**Comment by maksimsamt** [comment]
> Let me try it this morning and come back. My template has been created with virtio instead scsi, it will be a problem change on creation? i can fit the template to scsi anyway, but, just to know.

Better to change in source template and afterwards use it in VM creation.
As I observed, `scsi` behavior ir more stable in PVE.

> Now i'm using Terraform 1.8.5:

OK, it is good.
You can change it in config to prevent using outdated versions, like:
```hcl
terraform {
  required_version = ">= 1.8.5"
...
```

**Comment by SySamu-Hallon** [comment]
@maksimsamt  Ok, just last details on my .tf. Another question, my template has been created with CloudInit drive, it should be detached too and added on creation on the new vm? I understood that's the correct way now on another thread I posted this question: https://github.com/Telmate/terraform-provider-proxmox/pull/892#issuecomment-2191486865

**Comment by maksimsamt** [comment]
> Another question, my template has been created with CloudInit drive, it should be detached too and added on creation on the new vm?

Cloud-init drive could stay in your template, during VM creation terraform provider will re-create cloud-init drive.

So, I recommend to configure cloud-init in your terraform config, for example in case of `scsi`:
```hcl
    disks {
        scsi {
            scsi0 {
                disk {
                    size    = "15G"
                    storage = "local"
                }
            }
            scsi1 {
                cloudinit {
                    storage = "local"
                }
            }
        }
    }
```
This correctly works if cloud-init drive in your template is not `scsi1`.
FYI, related issue: https://github.com/Telmate/terraform-provider-proxmox/issues/1024

BTW, disk size not correct in your config, it should be as string, not integer:
```hcl
#
                disk {
                    size = 400
                    storage = "local"
                }
# =>
                disk {
                    size = "400G"
                    storage = "local"
                }
```
Check out the documentation: https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/resources/vm_qemu.md

**Comment by SySamu-Hallon** [comment]
following your steps i'm getting stucked on terraform plan. Updated code here:

```
resource "proxmox_vm_qemu" "vm" {
    name = "${var.hostname}"
    desc = "${var.description}"
    #vmid = 0
    target_node = "${var.proxmox_node}"

    agent = 1
    clone = "${var.template}"
    cores = var.cpu_cores
    sockets = var.cpu_sockets
    vcpus = var.cpu_vcpu
    cpu = "${var.cpu_type}"
    memory = var.ram
    balloon = var.balloon
    hotplug= "disk,network,usb"
    numa = var.numa
    onboot = var.onboot
    tags = "${var.vm_tags}"

    network {
      bridge = "vmbr1"
      model = "virtio"
    }

    disks {
        scsi {
            scsi0 {
                disk {
                    size = "${var.disk_size}G"
                    storage = "${var.datastore}"
                }
            }
            scsi1 {
                cloudinit {
                    storage = "${var.datastore}"
                }
            }
        }
    }

    bootdisk = "scsi0"
    boot = "order=scsi0"
    os_type = "${var.os_type}"
    ipconfig0 = "ip=${var.ip}/19,gw=${var.gateway}"
    
    ---rest of main config---
    
    }
```

Note that vars are declared and setted, as datastore. To use string on disk size i've just added "G" between quotes. That trick allow us to only change a number instead a string. I also  detach and attach template disk as scsi instead virtio as you suggest :)

The error:

```
terraform plan
╷
│ Error: Unsupported block type
│
│   on main.tf line 34, in resource "proxmox_vm_qemu" "vm":
│   34:                 cloudinit {
│
│ Blocks of type "cloudinit" are not expected here.

```

My cloud init drive on template is on ide0. Attaching pic of template config:
<img width="443" alt="image" src="https://github.com/Telmate/terraform-provider-proxmox/assets/94912518/8fb508bb-7236-461e-bfbc-0454bedb0645">

**Comment by SySamu-Hallon** [comment]
@maksimsamt thanks a lot for your support, changing provider to latest version from telmate solve all:

```
terraform {
  required_version = ">= 1.8"

  required_providers {
    proxmox = {
        source = "telmate/proxmox"
        version = "3.0.1-rc3"
    }
  }
}


```

**Comment by SySamu-Hallon** [comment]
Closing the issue.
Thanks a lot again, you save me hours of work 😄
