### ISSUE TITLE
LXC Feature: Add Support for Managing Firewall Policies for Proxmox

### ISSUE THREAD

**Issue by safesploit** [Telmate/terraform-provider-proxmox#1053]
## Description:

I propose the addition of a new resource, `resource_firewall`, to the Terraform provider for Proxmox `Telmate/proxmox`. This new resource will enable users to manage firewall policies for specific container (LXC) IDs within Proxmox. The implementation should allow the creation, reading, updating, and deletion of firewall rules directly from Terraform configurations.

## PVE API

`https://<domain_name>:8006/api2/json/nodes/pve/lxc/<ct_id>/firewall/rules`

### Actual output

```
{"data":[{"enable":1,"action":"auth-ips","pos":0,"digest":"9582a21d6e019c3c64018fc3b257325c80ea2f76","type":"group"}]}\n
```

### Reformatted output

```json
{
  "data": [
    {
      "enable": 1,
      "action": "auth-ips",
      "pos": 0,
      "digest": "9582a21d6e019c3c64018fc3b257325c80ea2f76",
      "type": "group"
    }
  ]
}
```

## Example Resource

This resource `add_lxc_firewall_group` would add the firewall Security Group `auth-ips` to the LXC with ID `100`

```hcl
resource "proxmox_firewall" "add_lxc_firewall_group" {
  vmid = "100" # New LXC ID

  rule {
    action  = "auth-ips"
    enable  = true
    type    = "group"
    pos     = 1
    comment = ""
    digest  = null
  }
```

**Comment by Koleon** [comment]
There has been a running discussion about Container/VM's firewall for a while. Please see https://github.com/Telmate/terraform-provider-proxmox/issues/340
