### ISSUE TITLE
cloud-init is broken with `3.0.1-rc3`

### ISSUE THREAD

**Issue by ironicbadger** [Telmate/terraform-provider-proxmox#1057]
First, huge thanks for this provider! 
I have been trying to get a cloud-init config pieced together from multiple issues in this repo the last couple of days. Unfortunately either I'm just not finding the right documentation that points the state of rc3 specifically for cloud-init on an ubuntu2404 image OR it is currently broken.

Copying the example from here - https://github.com/Telmate/terraform-provider-proxmox/blob/master/examples/cloudinit_example.tf - (with the basic variables changed to fit my setup) results in:

```
proxmox_vm_qemu.cloudinit-test: Still creating... [10s elapsed]
╷
│ Error: error updating VM: 500 Internal Server Error, error status: {"data":null} (params: map[agent:1 bios:seabios boot:order=virtio0 cores:2 cpu:host delete:ide2,scsi0 description:A test for using terraform and cloudinit hotplug:network,disk,usb ide3:local:cloudinit,format=raw kvm:true memory:2048 name:terraform-test-vm net0:virtio=7A:C7:F3:C1:72:4B,bridge=vmbr0 numa:false onboot:false protection:false scsihw:lsi sockets:1 sshkeys:%20%20%20%20ssh-rsa%209182739187293817293817293871%3D%3D%20user%40pc%0A%0A tablet:true virtio0:local:32,cache=writeback,discard=on,format=raw,iothread=1,replicate=0 vmid:103])
│ 
│   with proxmox_vm_qemu.cloudinit-test,
│   on providers.tf line 87, in resource "proxmox_vm_qemu" "cloudinit-test":
│   87: resource "proxmox_vm_qemu" "cloudinit-test" {
│ 
```

There are numerous interpretations on the state of using the ISO injection method vs not. I'd be super grateful for a little guidance on how to inject a standard cloud-init file into a VM with rc3. I'm looking to deploy an existing mature cloud-init file in a similar format to what Tailscale show here - https://tailscale.com/kb/1293/cloud-init.

Any help much appreciated. Any other logs I can get you too, just ask. Thanks!

**Comment by maksimsamt** [comment]
@ironicbadger ,
could you please share your Terraform files?
