### ISSUE TITLE
Terraform apply never completes

### ISSUE THREAD

**Issue by PopeFelix** [Telmate/terraform-provider-proxmox#1058]
I'm attempting to deploy the template in [main.tf.txt](https://github.com/user-attachments/files/16354647/main.tf.txt) to my Proxmox server. The VM is created with the correct settings in cloud-init, but `terraform apply` never completes. It just says `Still creating...` for 8+ minutes. Is there something I'm doing wrong?

Variables are defined in [vars.tf.txt](https://github.com/user-attachments/files/16354648/vars.tf.txt)

**Comment by vokey** [comment]
Hi, @PopeFelix,
I ran a test using your `tf` files, modifying some variables such as storage name and template name, and it was successful. I found no issues with those files.
The target ProxmoxVE version is 8.1.4.

```
proxmox_vm_qemu.cloudinit-test: Creation complete after 5m55s [id=gemini/qemu/16000326]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Have you checked the task status on PVE? Also, it might be helpful to check the Cloud-Init status in the VM's console.

**Comment by PopeFelix** [comment]
How do I check the task status on PVE?

**Comment by PopeFelix** [comment]
This might be probitive:

```
proxmox_vm_qemu.cloudinit-test: Creation complete after 20m29s [id=thebeast/qemu/101]

│ Warning: Qemu Guest Agent is enabled but not working
│
│   with proxmox_vm_qemu.cloudinit-test,
│   on main.tf line 22, in resource "proxmox_vm_qemu" "cloudinit-test":
│   22: resource "proxmox_vm_qemu" "cloudinit-test" {
│
│ error from PVE: "500 QEMU guest agent is not running"
│ , Qemu Guest Agent is enabled in you configuration but non installed/not working on your vm

```

I'll check that out. Maybe the QEMU guest agent isn't installed on the Ubuntu image.

**Comment by PopeFelix** [comment]
Yeah, that must be it. This is cloned from the current (as of 2024-07-10) [Ubuntu 24.04 Cloud Image](https://cloud-images.ubuntu.com/noble/20240710/), and when I disable the `agent = 1` line, VM creation completes in under 30s. So I need to update my Terraform template to install `qemu-guest-agent` on VM creation.
