### ISSUE TITLE
Creating clone always results in unused disk

### ISSUE THREAD

**Issue by DennisSerafin** [Telmate/terraform-provider-proxmox#1067]
#### Description

When cloning a Windows template using the PVE GUI, everything works as expected and Windows boots perfectly. However, when cloning the template using Terraform with the `telmate/proxmox` provider, the boot disk is in an unused state, as shown in the attached screenshot.

#### Terraform Configuration
modules/vm/main.tf

```
terraform {
  required_providers {
    proxmox = {
      source = "telmate/proxmox"
    }
  }
}

resource "proxmox_vm_qemu" "vm" {
  name        = var.name
  target_node = var.target_node

  clone      = var.template_name
  full_clone = true

  os_type    = "cloud-init"
  ciuser     = "user"
  cipassword = "password"

  cores   = var.cores
  sockets = 1
  memory  = var.memory

  network {
    bridge = "vmbr0"
    model  = "virtio"
  }

#     disks {
#       scsi {
#         scsi1 {
#           disk {
#             storage = "cephvm"
#             size    = var.disk_size
#           }
#         }
#       }

#    }

  ipconfig0  = "ip=${var.ip_address}/24,gw=${var.gateway}"
  nameserver = join(" ", var.dns_servers)
}

```

#### Steps to Reproduce

1. Use the provided Terraform configuration to clone a Windows template.
2. Observe that the disk is in an unused state.

#### Expected Behavior

The cloned VM should boot up with the disk properly attached, as it does when cloned via the PVE GUI.

#### Actual Behavior

The disk is in an unused state, preventing the VM from booting properly.

#### Additional Context

- **Proxmox Version**: 8.2.2
- **Terraform Version**: v1.7.2-dev
- **Provider Version**: v3.0.1-rc3

I have `cloudbase-init` installed on the Windows template.

#### Workaround

If there is a workaround or manual steps that need to be performed to resolve the issue, please describe them here.

![Screenshot_20240801_140336](https://github.com/user-attachments/assets/a041f72c-979b-465b-aace-212728980e77)

**Comment by Tinyblargon** [comment]
@DennisSerafin the disk has to be configured in Terraform, as Terraform will make the cloned vm as configured. Any properties that are not configured in the TF file but are carried over from the original VM are bugs or lack of implementation.

**Comment by Tinyblargon** [comment]
@DennisSerafin if you configure a disk in the same slot as the disk from the original vm, Terraform will see that the disk is an intended part of the configuration and keep it. Do keep in mind that the configured dis has to be at least as big as the original, or else it will be recreated.

**Comment by DennisSerafin** [comment]
@Tinyblargon, thanks for the info. The problem is, when I create the new disk the same size as the cloned disk, Terraform replaces the old one, making the disk appear empty. The disk size from the template is 80GB, and here is what I added in modules/vm/main.tf:

```
  disks {
    scsi {
      scsi0 {
        disk {
          storage = "cephvm"
          size    = "80G"
        }
      }
    }
  }

  boot     = "cdn"
  bootdisk = "scsi0"
```

Now, the unused disk is gone, but it can't boot the OS that was installed in the template.

**Comment by Tinyblargon** [comment]
@DennisSerafin currently we only detach the disk, so if it isn't detached it should still be tge same drive. I think `boot="scsi0"` and `bootdisk` should not be specified.

**Comment by DennisSerafin** [comment]
@Tinyblargon  I removed `bootdisk = "scsi0"` but unfortunately he didn't boot the disk. The vm didn´t seems to know that it has a bootable device like shown in the next screenshot:

![Screenshot_20240802_074701](https://github.com/user-attachments/assets/e6606729-3de6-429d-897c-fc9d4f5c397f)


so i tried to boot manually from disk, but this didn't work eithter:

![Screenshot_20240802_074845](https://github.com/user-attachments/assets/e07e86b5-4202-4311-b62a-e373d7ec29f2)


i used the same .yml with the disk part. So I must be overlooking something, any ideas?
just to take out mistakes: My Template has 80GB and there is Windows Server 2022 installed with Cloudbase-Init. When i Manually clone the Template, everything works as intended.
thanks for the help

**Comment by thiraphi** [comment]
Hello @DennisSerafin, I got the same error. And after a huge amount of time searching I got the solution from this [https://github.com/Telmate/terraform-provider-proxmox/issues/770#issuecomment-1552567416](url)
. By adding `scsihw      = "virtio-scsi-pci"  in 'Resource' section

FYI: this is my main.tf

``` 
    resource "proxmox_vm_qemu" "cloudinit-test" {
        name = "terraform-test-vm"
        desc = "A test for using terraform and cloudinit"
        target_node = "localhost"
   
        clone = "VM 9000"
    
        agent = 1
    
        os_type = "cloud-init"
        cores = 2
        sockets = 1
        vcpus = 0
        cpu = "host"
        memory = 2048
    
        scsihw  = "virtio-scsi-pci"
    
        hotplug  = "network,disk,usb"
    
        disks {
            scsi {
                scsi0 {
                    disk {
                      storage = "local-lvm"
                      size = 12
                    }
                }
            }
            ide {
                ide3 {
                    cloudinit {
                      storage = "local-lvm"
                    }
                }
            }
        }

        bootdisk = "scsi0"

    }
```

**Comment by DennisSerafin** [comment]
@thiraphi thanks for your answer, unfortunately this din´t work. I think it din´t clone the Disk, it create a new Disk instead.

main.tf
`resource "proxmox_vm_qemu" "vm" {
  name        = "TEST"
  target_node = "rhbhstp004"

  clone      = "Template"
  //full_clone = true

  agent = 1

  os_type    = "cloud-init"
  ciuser     = "User"
  cipassword = "Password"

  cores   = "4"
  sockets = 1
  memory  = "8096"

  scsihw = "virtio-scsi-pci"
  hotplug  = "network,disk,usb"

  network {
    bridge = "vmbr0"
    model  = "virtio"
  }

  disks {
    scsi {
      scsi0 {
        disk {
          storage = "cephvm"
          size    = "80G"
        }
      }
    }

    ide {
      ide3 {
        cloudinit {
          storage = "cephvm"
        }
      }
    }
  }

  bootdisk = "scsi0"

}

`

it dint´t boot from disk. It seems like the Disk is empty.

the Template:
![image](https://github.com/user-attachments/assets/39780353-39f0-45fd-826d-1006ccb9e828)

and when i manually clone the Template, everything works as expected

**Comment by thiraphi** [comment]
@DennisSerafin 
Can you try to create a new template by following the steps in this [doc](https://pve.proxmox.com/wiki/Cloud-Init_Support)? I think the issue is related to the VirtIO SCSI controller. After I added --scsihw virtio-scsi-pci when creating the template, it worked.

**Comment by mammalmaster** [comment]
> @thiraphi thanks for your answer, unfortunately this din´t work. I think it din´t clone the Disk, it create a new Disk instead.
> 
> main.tf
> 
> ```
> resource "proxmox_vm_qemu" "vm" {
>   name        = "TEST"
>   target_node = "rhbhstp004"
> 
>   clone      = "Template"
>   //full_clone = true
> 
>   agent = 1
> 
>   os_type    = "cloud-init"
>   ciuser     = "User"
>   cipassword = "Password"
> 
>   cores   = "4"
>   sockets = 1
>   memory  = "8096"
> 
>   scsihw = "virtio-scsi-pci"
>   hotplug  = "network,disk,usb"
> 
>   network {
>     bridge = "vmbr0"
>     model  = "virtio"
>   }
> 
>   disks {
>     scsi {
>       scsi0 {
>         disk {
>           storage = "cephvm"
>           size    = "80G"
>         }
>       }
>     }
> 
>     ide {
>       ide3 {
>         cloudinit {
>           storage = "cephvm"
>         }
>       }
>     }
>   }
> 
>   bootdisk = "scsi0"
> 
> }
> ```
> 
> it dint´t boot from disk. It seems like the Disk is empty.
> 
> the Template: ![image](https://private-user-images.githubusercontent.com/116063357/357709380-39780353-39f0-45fd-826d-1006ccb9e828.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjA4NTUsIm5iZiI6MTcyNDE2MDU1NSwicGF0aCI6Ii8xMTYwNjMzNTcvMzU3NzA5MzgwLTM5NzgwMzUzLTM5ZjAtNDVmZC04MjZkLTEwMDZjY2I5ZTgyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxMzI5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2FkNzA5NmQ2MjAzMjZkMTY5MjhmMDUzNzBkMjRmN2ZmODg5YmVhNjg0YmFjYWRlODBhMDFjMTMxODY0NGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5w9h4ktWGJTfzgCB81jiCL6pL_0JCElRAhIBFa4-OK8)
> 
> and when i manually clone the Template, everything works as expected

This worked for me on a linux install. I was trying a bunch of things but the disk was always unmounted, thank you for this!
