### ISSUE TITLE
Feature: Add management of resource pools

### ISSUE THREAD

**Issue by Sonlis** [Telmate/terraform-provider-proxmox#1078]
## Description

Add the feature to manage cluster's resource pools. This feature would allow to read, create, modify and delete resource pools.

## Relevant PVE API path
`/api2/json/pools`

## How would the resource look like

```hcl
resource "proxmox_pool" "example_pool" {
  pool_id = "example" # required
  comment = "A pool to enable easier management of permissions"
}
```

If this feature is accepted, I can work on it and open a PR.

**Comment by Sonlis** [comment]
Right after creating this PR, I checked the source code and realised the feature already exist 🤡 . That would teach me to completely trust the documentation and not check the source code before opening an issue. Feel free to close to issue 😄

**Comment by Tinyblargon** [comment]
@Sonlis the pool feature was built, but never communicated it was built/released. It also uses a lot of deprecated code, it should use the code from https://github.com/Telmate/proxmox-api-go/blob/b6deb236b502b5eb20fb8e192855aaf3f22a42d0/proxmox/config_pool.go as this has proper error handling. Also, we shouldn't let users update the pool members with the pool resource. This is already done by the qemu and lxc resource and would just create state issues.
The schema you suggested is pretty much how i would do it, maybe change `pool_id` to `name` or `pool_name`, but that's just semantics.
