### ISSUE TITLE
terraform 0.12 support

### ISSUE THREAD

**Issue by ndemeshchenko** [Telmate/terraform-provider-proxmox#109]
Hello.
Is this plugin ready for terraform 0.12? I saw one recent commit mentioning "0.12" in description, however I can't make this plugin work with 0.12.

this is the error I have:
`Error: Failed to instantiate provider "proxmox" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5] `

**Comment by cospeedster** [comment]
It works with `0.12`. What Version is your Proxmox?

**Comment by ndemeshchenko** [comment]
Hi @cospeedster, my PVE is 5.4-13

**Comment by cospeedster** [comment]
I'm using Proxmox Virtual Environment 5.4-13 and Terraform 0.12.13 and it works.

What errors do you get? How did you write the provider in your `.tf` file?

**Comment by ndemeshchenko** [comment]
@cospeedster, thx for the followup.

I have the following provider in my main.tf, which I have copied from terraform off. site
`provider "proxmox" {
  pm_tls_insecure = true
  // Credentials here or environment
  pm_api_url = "https://p-01.acme.net:8006/api2/json"
  pm_password = "*****"
  pm_user = "root@pam"
  //Optional
  // pm_otp = "otpcode"
}`

**Comment by ritterwolf** [comment]
I had this issue. What's happening is that the Terraform source code you are building against is older than your Terraform binary. In my case the provider was built with 0.11.13 which I had checked out for other reasons several months ago, but my binary is 0.12.12.

To fix:

```
cd ~/go/src/github.com/hashicorp/terraform
git pull
git checkout v0.12.12 # Change this to your Terraform version
```

After doing this you should be able to rebuild the provider and have it work.

**Comment by cospeedster** [comment]
> I had this issue. What's happening is that the Terraform source code you are building against is older than your Terraform binary. In my case the provider was built with 0.11.13 which I had checked out for other reasons several months ago, but my binary is 0.12.12.
> 
> To fix:
> 
> ```
> cd ~/go/src/github.com/hashicorp/terraform
> git pull
> git checkout v0.12.12 # Change this to your Terraform version
> ```
> 
> After doing this you should be able to rebuild the provider and have it work.

@ndemeshchenko does this work for you?

**Comment by br627** [comment]
I'm running into this same issue. I've checked out version v0.12.21 and my binary install is:

terraform version
Terraform v0.12.21
+ provider.proxmox (unversioned)

However when I run a terraform plan I'm still getting the same error message:

Error: Failed to instantiate provider "proxmox" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

Is there anything else I'm missing?
