### ISSUE TITLE
Bug: Creating an LXC container with start = true does not start the container

### ISSUE THREAD

**Issue by Sonlis** [Telmate/terraform-provider-proxmox#1092]
Setting `start = true` or not in the LXC resource does not start the lxc container when creating it.

From what I understood, LXC is getting a revamp. However this is an easy fix I believe, as it is just a matter of moving the check whether `start` is set out of the block ran only if we're updating the container:  https://github.com/Telmate/terraform-provider-proxmox/blob/f027071ead4886df28275aeac7323e38795143b6/proxmox/resource_lxc.go#L581

**Comment by gilkudik** [comment]
I'm having the same problem, setting the start parameter to true always causes the creation to fail.
