### ISSUE TITLE
Getting error in for disks section - Blocks of type disks are not expected here. Did you mean disk? 

### ISSUE THREAD

**Issue by narenkvibind** [Telmate/terraform-provider-proxmox#1094]
Getting error in for disks section - Blocks of type disks are not expected here. Did you mean disk? 

Can you please let me know how to solve this issue 

Sample 

disks {
        scsi {
            scsi0 {
                disk {

**Comment by pavelhmeljov** [comment]
Exact the same problem. If I try to comment out disk section:

**Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:

panic: interface conversion: interface {} is string, not float64

goroutine 9 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc00032c718, 0x189e92a?)
        github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0000d1e00, {0x1767860?, 0xc000093ef0})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:972 +0x2c4d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x19d8be0?, {0x19d8be0?, 0xc0006b4b10?}, 0xd?, {0x1767860?, 0xc000093ef0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000192ee0, {0x19d8be0, 0xc0006b4b10}, 0xc00049cf70, 0xc0000d1c80, {0x1767860, 0xc000093ef0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00040ff68, {0x19d8be0?, 0xc0006b49f0?}, 0xc0004bc4b0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002d0320, {0x19d8be0?, 0xc0006b4000?}, 0xc00018a070)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x186d600?, 0xc0002d0320}, {0x19d8be0, 0xc0006b4000}, 0xc00018a000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002583c0, {0x19dc840, 0xc0004829c0}, 0xc0000d66c0, 0xc00041d890, 0x1e95900, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0002583c0, {0x19dc840, 0xc0004829c0}, 0xc0000d66c0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!**

**Comment by Tinyblargon** [comment]
The `disks` schema was introduced in 3.0.1-rc1
