### ISSUE TITLE
virtio0 (required) not found in current config

### ISSUE THREAD

**Issue by raarts** [Telmate/terraform-provider-proxmox#11]
I've got this problem creating an instance. It looks like an API incompatibility to me, but of course it can be my foolishness too.

ProxMox version: 5.1-41

Here's my terraform config:

```
provider "proxmox" {
  pm_api_url = "https://192.168.192.222:8006/api2/json"
  pm_user = "root@pam"
  pm_password = "<REDACTED>"
}
```

Here's the VM description:

```
resource "proxmox_vm_qemu" "test" {
  name = "node-20"
  desc = "tf description"
  target_node = "pve"

  clone = "centos-7-x8664-template"
  storage = "local-lvm"
  cores = 2
  sockets = 1
  memory = 2560
  disk_gb = 25
  nic = "virtio"
  bridge = "vmbr0"
  ssh_forward_ip = "192.168.192.81"
  ssh_user = "terraform"
  ssh_private_key = <<EOF
-----BEGIN RSA PRIVATE KEY-----
private ssh key terraform
-----END RSA PRIVATE KEY-----
EOF

  os_type = "centos"
  os_network_config = <<EOF
TYPE="Ethernet"
PROXY_METHOD="none"
BROWSER_ONLY="no"
BOOTPROTO="dhcp"
DEFROUTE="yes"
IPV4_FAILURE_FATAL="no"
IPV6INIT="yes"
IPV6_AUTOCONF="yes"
IPV6_DEFROUTE="yes"
IPV6_FAILURE_FATAL="no"
IPV6_ADDR_GEN_MODE="stable-privacy"
NAME="eth0"
DEVICE="eth0"
ONBOOT="yes"
EOF

  provisioner "remote-exec" {
    inline = [
      "ip a"
    ]
  }

  provisioner "proxmox" {
    action = "sshbackward"
  }
}
```

Here's the hardware configuration of the template:

![image](https://user-images.githubusercontent.com/3168197/38522848-1f3fbad0-3c4a-11e8-9b51-3742caf2970f.png)

And this is the logging output:

[tfdebug.log](https://github.com/Telmate/terraform-provider-proxmox/files/1891793/tfdebug.log)

Cloning the template using the GUI works as expected.

**Comment by raarts** [comment]
Alright. I found out the template was created with the (default) SCSI disk, but a new template using VirtIO disk worked fine. So now this has become a feature request I guess.

**Comment by tevaum** [comment]
I'm having the same problem here. Is there any workarround?
