### ISSUE TITLE
cloning template with multiple disks not working properly

### ISSUE THREAD

**Issue by cospeedster** [Telmate/terraform-provider-proxmox#110]
Hello together,

I'm trying to deploy multiple VMs on Proxmox using a template with two disks. One disk is just for `/boot` and the second disk is for the `system`. I'm also planning to add a third disk for data.

An extract from my `.tf` file:
```HCL
  disk {
    #backup      = false
    #cache       = "none"
    #format      = "raw"
    id           = 0
    iothread     = false
    #replicate   = false
    size         = "256M"
    storage      = "DATAPOOL"
    storage_type = "rbd"
    type         = "scsi"
  }
  disk {
    #backup      = false
    #cache       = "none"
    #format      = "raw"
    id           = 1
    iothread     = false
    #replicate   = false
    size         = "5G"
    storage      = "DATAPOOL"
    storage_type = "rbd"
    type         = "scsi"
  }
```

Often in Proxmox one disk is used for both (scsi0 and scsi1) an the other disk is unused0:
![terraform_disk err](https://user-images.githubusercontent.com/52749645/68130043-f5d32980-ff1a-11e9-8d60-c60601e812a4.png)

Can you help me?

**Comment by cospeedster** [comment]
I'm using `Proxmox Virtual Environment 5.4-13` and `Terraform 0.12.13`. I tried also Terraform `0.12.10` and `0.12.12`

**Comment by cospeedster** [comment]
Any Ideas @V-Paranoiaque? @ggongaware ? :-)

**Comment by V-Paranoiaque** [comment]
I have never used two disks in a cloud-init template, will have a look. For the extra disk, I have made a patch but I need to test it more: https://github.com/V-Paranoiaque/proxmox-api-go/tree/fix/cloudinit-newdisk

**Comment by cospeedster** [comment]
Thank you for your response! It would be great if you take a look.
I'm also interested in adding extra disks ( look at #94 ). Thank you for developing here ;-)

**Comment by cospeedster** [comment]
## I found a workaround:
I just describe disk0 in my `.tf` file. Both disks from the template are cloned correct, because terraform did not touch the disk1.

```HCL
disk {
    #backup      = false
    #cache       = "none"
    #format      = "raw"
    id           = 0
    iothread     = false
    #replicate   = false
    size         = "256M"
    storage      = "DATAPOOL"
    storage_type = "rbd"
    type         = "scsi"
  }
```

Hopefully, this is just a temporary workaround. There is much more potential in this provider!

**Comment by V-Paranoiaque** [comment]
Hello @cospeedster 
I have made some tests and I think it's a global problem. When you create many VM some parameters are "forgotten" by terraform/Proxmox.

**Comment by V-Paranoiaque** [comment]
Hello @cospeedster
I have made some tests and I can't reproduce your problem. Do you get any error in Proxmox?
Sometimes I get a bug, terraform/proxmox in "forgetting" some parameters.

**Comment by V-Paranoiaque** [comment]
I think I have fixed your problem @cospeedster 
https://github.com/Telmate/proxmox-api-go/pull/61

**Comment by cospeedster** [comment]
Sorry for my delayed reply @V-Paranoiaque . I'll take a look :-)

**Comment by cospeedster** [comment]
@V-Paranoiaque 
That looks good to me. Even if I do not understand GO exactly ^^
Any idea when this will be merged?

**Comment by V-Paranoiaque** [comment]
No idea @cospeedster, not sure when @ggongaware will have time to do it

**Comment by cospeedster** [comment]
@ggongaware merged it. Thank you for that!
@V-Paranoiaque I will test it, if I'm able to reinstall the provider..
I have some Problems here: Telmate/terraform-provider-proxmox#116
I opened an issue here: hashicorp/terraform#23540

**Comment by cospeedster** [comment]
Adding and removing disks is now working properly.
Thank you @V-Paranoiaque !
