### ISSUE TITLE
Disk Resize Step Failed on Newly Cloned VM

### ISSUE THREAD

**Issue by johnnytan2885** [Telmate/terraform-provider-proxmox#1102]
Seems like whenever I'm cloning a VM out, it will always failed

proxmox_vm_qemu.vpn_vms["REDACTED"]: Creating...
proxmox_vm_qemu.vpn_vms["REDACTED"]: Still creating... [10s elapsed]
╷
│ Error: volume 'IFR000166_vol01:100/vm-100-disk-0.qcow2' does not exist
│ 
│   with proxmox_vm_qemu.vpn_vms["REDACTED"],
│   on vm-proviosioner.tf line 1, in resource "proxmox_vm_qemu" "vpn_vms":
│    1: resource "proxmox_vm_qemu" "vpn_vms" {

The VM is created, with the disk intact. For this case I think the resize step are "too fast" and didn't wait for the clone to finish before performing the step.

**Comment by Tinyblargon** [comment]
Currently, we resize as soon as proxmox tells us the clone was completed. Should be fairly easy to make it wait during that process.

**Comment by johnnytan2885** [comment]
Further testing on my end.

My environment are a Proxmox Cluster consists of 3 nodes. It has come to my attention that 1 out of 3 nodes doesn't have the same kernel / pve-manager version. Below are my test case. I would categorise them into "Latest Node" and Outdated Node"

Latest Node : Linux 6.8.12-1-pve | pve-manager/8.2.4
Outdated Node : Linux 6.8.4-3-pve | pve-manager/8.2.2

#Test 1
Clone Base Image : Latest Node
Target Clone : Latest Node
RESULT : OK

#Test 2
Clone Base Image : Latest Node
Target Clone : Outdated Node
RESULT : FAILED

#Test 3
Clone Base Image : Outdated Node
Target Clone : Outdated Node
RESULT : OK

#Test 4
Clone Base Image : Outdated Node
Target Clone : Latest Node
RESULT : FAILED

I will leave it to see if we can improve further on the minor version mismatch and if it's not worth the time, I can proceed to close this issue.

Many Thanks.

**Comment by incon** [comment]
I have this issue

<img width="201" height="89" alt="Image" src="https://github.com/user-attachments/assets/9385304b-5da9-4906-bd04-76c5f2e574e4" />
