### ISSUE TITLE
Passing through PCI device

### ISSUE THREAD

**Issue by braucktoon** [Telmate/terraform-provider-proxmox#1107]
I am attempting to passthrough iGPU using Terraform and Telmate provider.  I need the equivalent of this screen shot. 
<img width="301" alt="image" src="https://github.com/user-attachments/assets/6c4bd132-d591-4b93-bcb4-1c0df5091c72">
When I pass through manually, it works, when I pass through using args in terraform file like this, it does not work:
args = "-device vfio-pci,host=00:02.0,x-vga=off"

I did not see much in the doc on how to do this. Does Telmate support this?

**Comment by Tinyblargon** [comment]
@braucktoon yeah the pcie isn't that well supported. There are plans to overhaul it in the library we use to talk to PVE [proxmox-api-go](https://github.com/Telmate/proxmox-api-go), as the datastructure of the library does not match with PVE.

**Comment by jovermier** [comment]
I am also struggling to get this working
