### ISSUE TITLE
Add/Remove pools with Terraform

### ISSUE THREAD

**Issue by V-Paranoiaque** [Telmate/terraform-provider-proxmox#111]
Hello,

I'm starting to implement the feature to manage VM Pools with terraform. I'm not sure about how Rename and Delete should be managed. The problem will be with the VM's tfstate. My opinion is the rename and the delete shouldn't be possible if the pool is not empty. Another possibility could be to manage the pools directly from the VM part.
What do you think @ggongaware ?

**Comment by cospeedster** [comment]
In my opinion it sounds like we need a new ressource "proxmox_pool". I think, managing pools from the vm resource is not the best way.

**Comment by zimmertr** [comment]
I agree, just discovered this isn't already supported. It's possible to create and delete pools with the api using the pvesh command so it shouldn't be too heavy of a lift.

`pvesh create /pools -poolid "NAME --Comment "DESCRIPTION`

**Comment by mleone87** [comment]
I think that the change should also be implemented in the api module. There is no way to add a pool otherwise

**Comment by Syntax3rror404** [comment]
is there anything new about the problem here?

**Comment by vrubiolo** [comment]
Hi, I am also interested in the feature, it looks like some of it is implemented albeit undocumented: https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_pool.go

**Comment by LEI** [comment]
Switched to `pvesh` after attempting to use the `proxmox_pool` and encountering this error:

> When applying changes to module.proxmox.proxmox_pool.test_pool, provider "module.proxmox.provider[\"registry.terraform.io/telmate/proxmox\"]" produced an unexpected new value:
Root resource was present, but now absent.

I guess the resource is not documented because not ready for seamless apply/destroy, or maybe misuse on my part.
