### ISSUE TITLE
Error: user terraform-prov@pve has valid credentials but cannot retrieve user list, check privilege separation of api token

### ISSUE THREAD

**Issue by reynold-lariza** [Telmate/terraform-provider-proxmox#1118]
I was following this: https://registry.terraform.io/providers/Telmate/proxmox/latest/docs

`│ Error: user terraform-prov@pve has valid credentials but cannot retrieve user list, check privilege separation of api token
│
│   with provider["registry.terraform.io/telmate/proxmox"],
│   on providers.tf line 16, in provider "proxmox":
│   16: provider "proxmox" {
│`

What am I missing here?

**Comment by maksimsamt** [comment]
Duplicate:
https://github.com/Telmate/terraform-provider-proxmox/issues/784
