### ISSUE TITLE
Importing a vm forces replacement

### ISSUE THREAD

**Issue by lug-gh** [Telmate/terraform-provider-proxmox#1128]
I have a VM that I created with the terraform provider. However, I no longer have the state file for this VM. I would now like to import it into my existing state file (which contains many other VMs) using terraform import.

Unfortunately, terraform does not want to import the existing VM as a state, but create a new one, as the VM is to be created from a clone with cloud-init. However, the VM has already been created with exactly the clone image with which it is now to be imported.

How can I tell the provider that this VM does not need to be replaced as it is already a clone of the “ubuntu2204-ci” image?

### terraform code snippet
`main.tf`
```
module "example-vm" {
  source         = "./module"
  vm_name        = "example-vm"
  desc           = "to-do"
  target_node    = "node1"
  clone          = "ubuntu2204-ci"
  cores          = "4"
  memory         = "16384"
  [...shortened...]
}
```
`module/module.tf`
```
variable "vm_name" {}
variable "desc" {}
variable "target_node" {}
variable "clone" {}
variable "cores" {}
variable "memory" {}
[...shortened...]

resource "proxmox_vm_qemu" "vm" {
  name        = var.vm_name
  desc        = var.desc
  onboot      = true
  target_node = var.target_node
  agent       = 1
  clone       = var.clone
  qemu_os     = var.qemu_os
  cores       = var.cores
  sockets     = 1
  cpu         = "x86-64-v2-AES"
  memory      = var.memory
  boot        = "order=scsi0"
  tags        = "ha;terraform"
  scsihw      = "virtio-scsi-pci"
  pool        = var.pool
  bios        = var.bios
  [...shortened...]
}
```

![image](https://github.com/user-attachments/assets/e9fc9241-3d9b-4743-890d-c6934ef50fc4)

**Comment by Tinyblargon** [comment]
@lug-gh you could try the following:

- create the same vms with new names and ids.
- create a copy of the state file.
- tell terraform to remove the newly created vms.
- replace the statefile with the copy you made earlier.
- update the ids and names in the state file to your already existing vms.
- create a backup of the state file.
- `terraform refresh` & `terraform plan`.

You might still have to make minor changes to the state file.

There is probably a better way of doing this.

**Comment by lug-gh** [comment]
@Tinyblargon Thank you, that would have been my workaround too, but I figured there must be a better way that I don't know.
I'll try it out over the next few days and share my findings here.
