### ISSUE TITLE
Cannot create disk on CephFS

### ISSUE THREAD

**Issue by basvandijk** [Telmate/terraform-provider-proxmox#115]
I'm trying to create a QEMU VM on Proxmox with CephFS storage:

```
resource "proxmox_vm_qemu" "my_vm" {
  name = "my-vm"
  ...
  disk {
    id           = 0
    type         = "virtio"
    storage      = "vm-images"
    storage_type = "cephfs"
    iothread     = true
    format       = "raw"
    size         = 1 * 1024 * 1024 * 1024 # KiB
  }
```

However when I apply this I get the following error:

```
$ terraform apply
...
proxmox_vm_qemu.my_vm: Creating...

Error: Error creating VM: Cannot create VM disk vm-images:103/vm-103-disk-0.raw, error status:  (params: map[agent:0 boot:cd bootdisk:virtio0 cores:24 cpu:host description:My VM hotplug:network,disk ide2:local:iso/my-iso.iso,media=cdrom memory:189440 name:my-vm net0:virtio=5A:87:D4:F3:EA:26,bridge=vmbr0 numa:false onboot:true ostype:l26 scsihw:lsi sockets:1 virtio0:media=disk,size=1073741824,file=vm-images:103/vm-103-disk-0.raw,format=raw,iothread=1 vmid:103])
```

Surprisingly, after running that command, the disk `vm-103-disk-0.raw` on `vm-images` has been created.

Note that creating the VM with a disk using `storage_type=lvm` works.

How can I get this working on CephFS?

**Comment by M0NsTeRRR** [comment]
Hello @basvandijk 

i'm using this configuration for cephfs

```
  disk {
    id           = 0
    size         = var.disk_size
    type         = "scsi"
    storage      = "pool"
    storage_type = "cephfs"
    iothread     = true
  }
```

**Comment by basvandijk** [comment]
I discovered that the [following condition](
https://github.com/Telmate/proxmox-api-go/blob/991c5ce7826dfc0825ee0c5c1ce522b34eeeaf20/proxmox/client.go#L662) (`diskName != fullDiskName`) is failing since in my case:

```
diskName     == "vm-images:vm-100-disk-0.raw"
fullDiskName == "vm-images:100/vm-100-disk-0.raw"
```

Any idea where this discrepancy is coming from?

**Comment by basvandijk** [comment]
I think the discrepancy is caused by a missing `cephfs` on [this line](https://github.com/Telmate/proxmox-api-go/blob/991c5ce7826dfc0825ee0c5c1ce522b34eeeaf20/proxmox/config_qemu.go#L834).

I'm going to patch that line and see if that fixes my problem...
