### ISSUE TITLE
panic: interface conversion: interface {} is string, not float64

### ISSUE THREAD

**Issue by TDufau** [Telmate/terraform-provider-proxmox#1181]
Hello I encountered the following issue while trying to create vm on proxmox server.
Stacktrace :
`Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:

panic: interface conversion: interface {} is string, not float64

goroutine 98 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc00027b088, 0xc00027b088?)
        github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0xc000507280, {0xb66f60?, 0xc00014c000})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1475 +0x457
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(0x0?, {0xb66f60?, 0xc00014c000?})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1446 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xdd7840?, {0xdd7840?, 0xc0004903c0?}, 0xd?, {0xb66f60?, 0xc00014c000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000192ee0, {0xdd7840, 0xc0004903c0}, 0xc0004656c0, {0xb66f60, 0xc00014c000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00041fed8, {0xdd7840?, 0xc000490210?}, 0xc00055c880)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0002d6320, {0xdd7840?, 0xc0000b9860?}, 0xc0003003c0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xc6bc20?, 0xc0002d6320}, {0xdd7840, 0xc0000b9860}, 0xc0001ae000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00025a1e0, {0xddb420, 0xc000437520}, 0xc000330120, 0xc00042d8c0, 0x128f770, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00025a1e0, {0xddb420, 0xc000437520}, 0xc000330120, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

TF main file :
`resource "proxmox_vm_qemu" "server" {
 name       = "server"
 target_node = "proxmox"
 cores      = 1
 memory     = 2048
 os_type = "Linux"
 iso = "local:iso/20231109_raspi_4_bookworm.img"
 scsihw      = "virtio-scsi-single"
 bootdisk    = "scsi0"

 disk {
    slot = 0
    # set disk size here. leave it small for testing because expanding the disk takes time.
    size     = "20G"
    type     = "scsi"
    storage  = "ssd"
    iothread = 1
  }

  network {
    model  = "virtio"
    bridge = "vmbr0"
  }
}

resource "proxmox_vm_qemu" "node01" {
 name       = "node01"
 target_node = "proxmox"
 cores      = 1
 memory     = 2048
 os_type = "Linux"
 iso = "local:iso/20231109_raspi_4_bookworm.img"
 scsihw      = "virtio-scsi-single"
 bootdisk    = "scsi0"

 disk {
    slot = 0
    # set disk size here. leave it small for testing because expanding the disk takes time.
    size     = "20G"
    type     = "scsi"
    storage  = "ssd"
    iothread = 1
  }

  network {
    model  = "virtio"
    bridge = "vmbr0"
  }
}

resource "proxmox_vm_qemu" "node02" {
 name       = "node02"
 target_node = "proxmox"
 cores      = 1
 memory     = 2048
 os_type = "Linux"
 iso = "local:iso/20231109_raspi_4_bookworm.img"
 scsihw      = "virtio-scsi-single"
 bootdisk    = "scsi0"

 disk {
    slot = 0
    # set disk size here. leave it small for testing because expanding the disk takes time.
    size     = "20G"
    type     = "scsi"
    storage  = "ssd"
    iothread = 1
  }

  network {
    model  = "virtio"
    bridge = "vmbr0"
  }
}
`

**Comment by Tinyblargon** [comment]
@TDufau Currently 2.x is broken. The library used in 2.x has had lots of development, so back porting is reather difficult. For now, we recommend using 3.0.1rc6 as it also fixes lots of bugs that were lurking in 2.x. Do note that the schema has changed substantially since 2.x.
