### ISSUE TITLE
ciuser and cipassword doesn't work.

### ISSUE THREAD

**Issue by emoxam** [Telmate/terraform-provider-proxmox#1189]
VM creates, started, but i can't login to it.

```
terraform {
  required_providers {
    proxmox = {
      #      source  = "registry.local/telmate/proxmox"
      source  = "telmate/proxmox"
      version = "3.0.1-rc4"
    }
  }
}

provider "proxmox" {
  pm_api_url = "https://172.16.11.1:8006/api2/json"
  pm_api_token_id     = "terraform@pam!terraform"
  pm_api_token_secret = "redacted"
  pm_timeout = 7200
  pm_debug = true
  pm_log_enable = true
  pm_log_file   = "terraform-plugin-proxmox.log"
  pm_log_levels = {
    _default    = "debug"
    _capturelog = ""
}
}
variable "vm_ips" {
  default = ["172.16.10.161", "172.16.10.162", "172.16.10.163"]
}

resource "proxmox_vm_qemu" "vm" {

  ciuser     = "gsys"
  cipassword = "123"

  timeouts {
    create = "60m"
    delete = "10m"
  }

  count       = 1
  name        = "terraform-vm-${count.index}"
  agent       = 1
  boot        = "order=scsi0"
  target_node = "Node-5"
  clone      = "cloud-init-template"
  full_clone = true
  clone_wait        = 45
  scsihw     = "virtio-scsi-pci"
  cores  = 2
  memory = 4096

     disks {
       scsi {
         scsi0 {
           disk {
             size    = "4G"
             storage = "st"
             format = "qcow2"
           }
         }
       }
     }

  network {
    model  = "virtio"
    bridge = "vmbr0"
    tag      = 10
  }


  ciupgrade  = false
  nameserver = "172.16.10.2"
  ipconfig0 = "ip=${var.vm_ips[count.index]}/24,gw=172.16.10.254"


}
```

Any ideas what is going on ?

**Comment by Tinyblargon** [comment]
@emoxam are you using a special cloud init image, we have a cloud-init getting started guide in the docs folder.

**Comment by emoxam** [comment]
@Tinyblargon I believe i am using this one
https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img

cd /opt/st
wget https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
qm create 9000 --memory 2048 --net0 virtio,bridge=vmbr0 --scsihw virtio-scsi-pci
qm set 9000 --scsi0 st:0,import-from=/opt/st/noble-server-cloudimg-amd64.img
qm set 9000 --ide2 st:cloudinit

qm resize 9000 scsi0 4G

qm template 9000
qm set 9000 --boot order=scsi0

**Comment by maksimsamt** [comment]
@emoxam ,
In your config missing cloudinit disk.

As @Tinyblargon said:
> we have a cloud-init getting started guide in the docs folder.

check out this dock:
https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/guides/cloud-init%20getting%20started.md

**Comment by emoxam** [comment]
@maksimsamt 
You are awesome! 
I forgot 
```
ide {
      # Some images require a cloud-init disk on the IDE controller, others on the SCSI or SATA controller
      ide1 {
        cloudinit {
          storage = "local-lvm"
        }
      }
    }
```

All works even with ubuntu cloud-init image!
