### ISSUE TITLE
cloudinit_cdrom_storage is unsupported in 3.0.1-rc6

### ISSUE THREAD

**Issue by alsarins** [Telmate/terraform-provider-proxmox#1193]
I cannot add cloud-init drive to VM with telmate/proxmox ver 3.0.1-rc6 with terraform.
Proxmox version is 8.2.2
OS image is https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64-disk-kvm.img
Output is:

```
$ terraform plan
╷
│ Error: Unsupported argument
│
│   on main.tf line 43, in resource "proxmox_vm_qemu" "pve_vm_cloud":
│   43:   cloudinit_cdrom_storage = "hdd_storage"
│
│ An argument named "cloudinit_cdrom_storage" is not expected here.
```

main.tf is like:
```
resource "proxmox_vm_qemu" "pve_vm_cloud" {
  count = 1
  name = "terraform-vm-cloud${count.index + 1}"
  desc = "terraform multidisk linux vm"
  clone = "ubuntu-2204-cloud-template"
... skipped ...
  cicustom = "user=local:snippets/ubuntu2204-cloudimg-user.yml"
  cloudinit_cdrom_storage = "hdd_storage"
... skipped ..
}
```
Is it expected behaviour or a known bug? Is there a workaround?

**Comment by Tinyblargon** [comment]
@alsarins the syntax for adding a cloud-init disk has been changed. It's now treated like any other disk. See the `disk` and `disks` section in the documentation. Keep in mind that the provider treats unconfigured didks as disks that should be removed.

**Comment by alsarins** [comment]
Thank you for clarification. Everything works now as expected!
https://registry.terraform.io/providers/numbnp/proxmox/latest/docs/guides/cloud_init documentation, where I found 'cloudinit_cdrom_storage' parameter, turns out to be obsolete.
