### ISSUE TITLE
[WARN] ssh: handshake failed: read tcp a.b.c.d:58858->x.x.x.x:22108: read: connection reset by peer

### ISSUE THREAD

**Issue by raarts** [Telmate/terraform-provider-proxmox#12]
Ok, this is one I need help with. I'm using the pre-provision phase.
a.b.c.d is mylaptop. x.x.x.x is the proxmox api server. I'm just using the config from the main README.md

I'm adding a VM to the same server as the API server, so I filled in that address for the ssh_forward_ip.

The full error is as follows:

```
proxmox_vm_qemu.test: Still creating... (5m20s elapsed)
2018-04-10T23:28:34.176+0200 [DEBUG] plugin.terraform-provider-proxmox: 2018/04/10 23:28:34 [WARN] ssh: handshake failed: read tcp 192.168.2.212:59067->192.168.192.222:22108: read: connection reset by peer
2018-04-10T23:28:36.178+0200 [DEBUG] plugin.terraform-provider-proxmox: 2018/04/10 23:28:36 opening new ssh session
2018-04-10T23:28:36.178+0200 [DEBUG] plugin.terraform-provider-proxmox: 2018/04/10 23:28:36 ssh session open error: 'client not available', attempting reconnect
2018-04-10T23:28:36.178+0200 [DEBUG] plugin.terraform-provider-proxmox: 2018/04/10 23:28:36 connecting to TCP connection for SSH
2018-04-10T23:28:36.180+0200 [DEBUG] plugin.terraform-provider-proxmox: 2018/04/10 23:28:36 handshaking with SSH
proxmox_vm_qemu.test: Still creating... (5m30s elapsed)
```

What can I do to further debug this?

**Comment by ggongaware** [comment]
This can be tricky. The portforward from proxmox can end up on a different bridge network. Can you console into your proxmox and see what address the port 22108 was listening on? Or if you have a firewall or iptables blocking all but a few ports?

**Comment by raarts** [comment]
Ok, it's this process:

`/usr/bin/kvm -id 108 -chardev socket,id=qmp,path=/var/run/qemu-server/108.qmp,server,nowait -mon chardev=qmp,mode=control -pidfile /var/run/qemu-server/108.pid -daemonize -smbios type=1,uuid=8f778173-89eb-4ca9-82d7-7e2709a898cc -name node-20 -smp 2,sockets=1,cores=2,maxcpus=2 -nodefaults -boot menu=on,strict=on,reboot-timeout=1000,splash=/usr/share/qemu-server/bootsplash.jpg -vga std -vnc unix:/var/run/qemu-server/108.vnc,x509,password -cpu kvm64,+lahf_lm,+sep,+kvm_pv_unhalt,+kvm_pv_eoi,enforce -m 2048 -k en-us -device pci-bridge,id=pci.2,chassis_nr=2,bus=pci.0,addr=0x1f -device pci-bridge,id=pci.1,chassis_nr=1,bus=pci.0,addr=0x1e -device piix3-usb-uhci,id=uhci,bus=pci.0,addr=0x1.0x2 -device usb-tablet,id=tablet,bus=uhci.0,port=1 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x3 -iscsi initiator-name=iqn.1993-08.org.debian:01:4eea10855c31 -drive file=/var/lib/vz/template/iso/CentOS-7-x86_64-Minimal-1708.iso,if=none,id=drive-ide2,media=cdrom,aio=threads -device ide-cd,bus=ide.1,unit=0,drive=drive-ide2,id=ide2,bootindex=200 -drive file=/dev/pve/vm-108-disk-2,if=none,id=drive-virtio0,format=raw,cache=none,aio=native,detect-zeroes=on -device virtio-blk-pci,drive=drive-virtio0,id=virtio0,bus=pci.0,addr=0xa,bootindex=100 -drive file=/dev/pve/vm-108-disk-1,if=none,id=drive-virtio1,format=raw,cache=none,aio=native,detect-zeroes=on -device virtio-blk-pci,drive=drive-virtio1,id=virtio1,bus=pci.0,addr=0xb -netdev type=tap,id=net0,ifname=tap108i0,script=/var/lib/qemu-server/pve-bridge,downscript=/var/lib/qemu-server/pve-bridgedown,vhost=on -device virtio-net-pci,mac=B2:CB:AA:EF:C2:B2,netdev=net0,bus=pci.0,addr=0x12,id=net0,bootindex=300`

It's listening on 0.0.0.0:22108 

I can telnet to that port, and get a connection that does not do anything. ssh into that port just hangs.

In the vm itself, network config:

```
[root@localhost ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether b2:cb:aa:ef:c2:b2 brd ff:ff:ff:ff:ff:ff
    inet 192.168.192.52/24 brd 192.168.192.255 scope global dynamic eth0
       valid_lft 86057sec preferred_lft 86057sec
    inet6 fe80::c2bc:897b:f5bc:b422/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth1
       valid_lft 86055sec preferred_lft 86055sec
    inet6 fec0::f760:6a39:adb6:5bc5/64 scope site noprefixroute dynamic
       valid_lft 86264sec preferred_lft 14264sec
    inet6 fe80::ebc1:23f9:5f9d:649/64 scope link
```

network config on the proxmox api server:

```
vmbr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.192.222  netmask 255.255.255.0  broadcast 192.168.192.255
        inet6 fe80::8e0f:6fff:fe7c:af1b  prefixlen 64  scopeid 0x20<link>
        ether 8c:0f:6f:7c:af:1b  txqueuelen 1000  (Ethernet)
        RX packets 261298007  bytes 103258110818 (96.1 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 239075103  bytes 71681771605 (66.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

and a lot of tap interfaces of course.
No iptable rules to be found.

**Comment by raarts** [comment]
Found something. All packets are forwarded to the `eth1` interface on the VM. But then nothing happens. ssh to the eth1 interface from the VM itself works fine. 
Any idea why everything is forwarded to eth1?

**Comment by ggongaware** [comment]
During provisioning, eth1 is used as the primary since eth0 may be changing. eth1 is also used for the ssh channel from terraform since the port was easier to predicted, eth0 may be dhcp, or on a different vlan.

**Comment by raarts** [comment]
Can I change that? Wouldn't it be possible to forward to `lo` for example? I removed NetworkManager, and now `eth1` is not even up after VM creation. Before I removed NetworkManager, it was up, but did not respond.

**Comment by ggongaware** [comment]
The forwarding needs to go through a device that proxmox can fake insert. I'm open for other options on how to do that.

**Comment by raarts** [comment]
Ok, I'll try to fix this problem from the CentOS side. I'll post any solution back here.

**Comment by raarts** [comment]
I can't get it to work. I thought it would be rp_filter settings, symptoms were identical, but alas.
Can you point me to an ISO I can use to test provisioning with my setup? Is that the ubuntu iso repo here? Does that one work for you with preprovisioning? BTW, I forked that, and [modified it to support centos](https://github.com/raarts/terraform-proxmox-iso) as well, then I moved to cloning a template, which is faster. 

But anyway, I'm looking for an ISO that works for you, so I can test it on my setup.

**Comment by ggongaware** [comment]
unfortunately another team member manually created a centos template, so I don't have the repeatable steps to make it work... but it is possible
