### ISSUE TITLE
Feature request: Add parameter vcpus

### ISSUE THREAD

**Issue by cospeedster** [Telmate/terraform-provider-proxmox#120]
It would be very helpful, if we can set the `vcpus` optional in the resource.
Sometimes setting `sockets` and `cores` is not enough for configuration.

Hopefully, anyone can implement this. :grinning:

**Comment by V-Paranoiaque** [comment]
https://github.com/Telmate/proxmox-api-go/pull/64

**Comment by V-Paranoiaque** [comment]
https://github.com/Telmate/terraform-provider-proxmox/pull/122

**Comment by cospeedster** [comment]
Hope, @ggongaware will merge this soon :-)

**Comment by cospeedster** [comment]
It seems, that everything is merged. I'll test it soon and then I'll close this Issue.

**Comment by cospeedster** [comment]
@V-Paranoiaque Your implementation work fore me. Great Job!

**Comment by V-Paranoiaque** [comment]
Thank you :)
