### ISSUE TITLE
Validate node name.

### ISSUE THREAD

**Issue by Tinyblargon** [Telmate/terraform-provider-proxmox#1208]
Add validation to give errors when the user provides a syntactically incorrect node name.

Related to #1201

**Comment by Tinyblargon** [comment]
https://github.com/Telmate/proxmox-api-go/issues/391

**Comment by spettinichi** [comment]
thank you for adding checks here tinyblargon! is there a posted roadmap to final release on v3 anywhere? just curious if there's a to-do list prior to considering it ready for release

**Comment by Tinyblargon** [comment]
@spettinichi The big ticket items are getting the basics of LXC working again, so we can increase functionality with feature updates. And the work for the RC7. Well, unless someone finds some deeply broken functionality that requires breaking changes.

Small changes like this validation functionality isn't strictly necessary for the 3.0 realease, it show the project isn't abandoned. Also I like to get some code shipped from time to time.

Please keep in mind that the Terraform side is the easy part of the code, as there is also an SDK project that does all the heavy lifting dealing with the quirks of the PVE API.

**Comment by spettinichi** [comment]
okie dokie, I was just curious, would maybe be able to contribute some time to help if there were an easy way for me to view what's needed
