### ISSUE TITLE
Issue with deploying using 3.0.1-rc4 and later (a bool is required)

### ISSUE THREAD

**Issue by hestiahacker** [Telmate/terraform-provider-proxmox#1213]
I'm getting the following error message when I try to use the new version of the provider to destroy an existing VM:

```
╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "module.standard_vm.module.vm.proxmox_vm_qemu.server" from prior state: unsupported attribute "bridge"
╵
╷
│ Error: a bool is required
│ 
│   with module.standard_vm.module.vm.proxmox_vm_qemu.server,
│   on ../../templates/main.tf line 52, in resource "proxmox_vm_qemu" "server":
│   52: resource "proxmox_vm_qemu" "server" {
│ 
╵
```

This appears to be something like #933 but with some other property which is not named in the error message.

# Steps to reproduce
Deploy a VM with 3.0.1-rc3 and try to `terraform destroy` it with 3.0.1-rc4, 3.0.1-rc5 or 3.0.1-rc6.

# The Warning
The warning is relatively easy to manually fix, and being that it's just a warning it doesn't strictly need to be fixed for being able to use the provider.

If this attribute is not added in the 2.x series, I think it's safe to just continue handling it as it does now, as the only people affected are people who have been running release candidates. While that may be quite a few people, I still don't think it's worth any additional effort given that it's still usable and it's easy to fix.

For those following along at home, edit `terraform.tfstate` and remove the `"bridge": ""` line under the `instances/attributes` section of the module listed in the warning message.

# The Error & Workaround

I looked at the [code diff between rc3 and rc4](https://github.com/Telmate/terraform-provider-proxmox/compare/v3.0.1-rc3...v3.0.1-rc4) to see if I could find anything that changed type.

I was able to track it down to the following values, all of which had to be manually fixed in my tfstate file:

- discard (str to bool)
- iothread (int to bool)
- replicate (int to bool)
- cicustom (str to bool)

It's possible there are additional fields that have changed which simply are not present in my .tfstate file which may bite other people. If that's you, and you're reading this now, go to the diff I linked to above, and then just search for "bool" on that page. Every time you see it, check your .tfstate and see if it's in there and if it's already a boolean. If not, change it and try again. Once you figure out what it was, please post the full list as a comment on this ticket.

# Resolution
If this is an incompatibility that only affects VMs that were deployed with 3.0.1-rc3 (or an earlier release candidate) and it's not going to be fixed, I request that the error message be updated to indicate which fields are failing the type validation. If that request is rejected, please go ahead and close this ticket as "won't fix". I've already provided a workaround and that should be sufficient to help people out of a jam.

**Comment by Tinyblargon** [comment]
@hestiahacker Thank you for reporting this and proving a workaround. Currently my effort is best spend getting the LXC and the multi node features working so we can get the official 3.0 release out the door.

**Comment by nliechti** [comment]
I found one other property that needed to be updated.
* backup (int to bool)
