### ISSUE TITLE
400 Parameter verification failed. (vcpus)

### ISSUE THREAD

**Issue by rjducker** [Telmate/terraform-provider-proxmox#123]
Hello! I'm trying pve-6.1-3, Terraform v0.12.17  and simple tf configuration. I get error:

`400 Parameter verification failed.`

After running my tf with debug i get this

```
2019-12-06T02:00:51.145Z [DEBUG] plugin.terraform-provider-proxmox: {"data":null,"errors":{"vcpus":"value must have a minimum value of 1"}}
--
428 | 2019-12-06T02:00:51.145Z [DEBUG] plugin.terraform-provider-proxmox: 2019/12/06 02:00:51 400 Parameter verification failed.
```

I'm trying to use "vcpu" argument and i get `An argument named "vcpus" is not expected here. Did you mean "cpu"?`

And i see default `vcpus=0` in pve-api URL params, how to change this param?

How to fix this now? Maybe need to add this argument to api-plugin in future?

**Comment by V-Paranoiaque** [comment]
Hello,
Could you give me your tf file?

**Comment by rjducker** [comment]
> Hello,
> Could you give me your tf file?

```
resource "proxmox_vm_qemu" "cloudinit-test" {
  name = "tf-test"
  desc = "tf description"

  target_node = "pve-home"

  clone = "ubuntu-18.04.2-server-amd64"

  # The destination resource pool for the new VM

  #pool = "pool0"

  #storage = "local"
  cores = 3
  sockets = 1
  memory = 2048

  disk {
    id = 0
    type = "virtio"
    storage = "local"
    size = "10G"
   # backup = true
  }

  network {
    id = 1
    model = "virtio"
    bridge = "vmbr0"
  }

  #ssh_user = "ubuntu"

  #provisioner "remote-exec" {
  #  inline = [
  #    "ip a"
  #  ]
  #}
}
```

**Comment by V-Paranoiaque** [comment]
In accordance with the documentation, vcpus should be able to be 0
https://pve.proxmox.com/wiki/Manual:_qm.conf

Looking for a patch

**Comment by rjducker** [comment]
I looked this param in PVE 6 UI in kvm new creation master i can't set vcpus to 0, default setting is 1

**Comment by V-Paranoiaque** [comment]
I have made a patch, trying to make it as clean as possible, will be pushed maximum in 1-2h

**Comment by V-Paranoiaque** [comment]
Could you try this patch? @rjducker 
https://github.com/Telmate/proxmox-api-go/pull/65

**Comment by rjducker** [comment]
Yay! After trying now i get `Apply complete!` Thanks for help @V-Paranoiaque <3
