### ISSUE TITLE
Feature request: Add parameter balloon

### ISSUE THREAD

**Issue by cospeedster** [Telmate/terraform-provider-proxmox#124]
It would be very helpful, if we can set the `balloon` optional in the resource. It can be used to configure memory-ballooning.

From the [documentation](https://pve.proxmox.com/wiki/Manual:_qm.conf):
```
 balloon: <integer> (0 - N)
    Amount of target RAM for the VM in MB. Using zero disables the ballon driver.
```

Hopefully, anyone can implement this. 😀

**Comment by V-Paranoiaque** [comment]
Hello

Could you have a look @cospeedster?
The implementation was very similar to the vcpus one

https://github.com/V-Paranoiaque/proxmox-api-go/tree/feature/balloon
https://github.com/V-Paranoiaque/terraform-provider-proxmox/tree/feature/balloon

**Comment by cospeedster** [comment]
@V-Paranoiaque It looks good for me. I thought that this is very similar, too.

**Comment by V-Paranoiaque** [comment]
PR done to the API: https://github.com/Telmate/proxmox-api-go/pull/66

PS: I'm curious about how you use these features, could we talk in private?

**Comment by cospeedster** [comment]
@V-Paranoiaque 

Great!

Of course we can. How would you like to do that? Mail?

In my opinion, when ballooning is set greater than 0, the vm will get a minimum value of memory defined by the value of the balloon parameter. When the vm needs as more memory as the minimum, the ram balloons up to the value of the memory parameter.

**Comment by V-Paranoiaque** [comment]
Are you doing over-provisioning? Are you not scared to be OOM?

On my profile there is a link to my personal website, I think instant messages is the easiest way (Twitter, Linkedin, Hangouts).

**Comment by cospeedster** [comment]
@V-Paranoiaque I just created a twitter account, but I can't message you. You'll find me under same username.

Of course, I'm scared to be OOM, but I thought that Proxmox is managing that. Maybe you have further information for me ;-) Furthermore, I don't really know what over-provisioning means.

Looking forward to to hear from you on twitter.

**Comment by cospeedster** [comment]
> PR done to the API: [Telmate/proxmox-api-go#66](https://github.com/Telmate/proxmox-api-go/pull/66)

@V-Paranoiaque 
PR in API is merged Telmate/proxmox-api-go#66

**Comment by cospeedster** [comment]
Telmate/terraform-provider-proxmox#129 need to be merged.

**Comment by cospeedster** [comment]
Parameter is working.
