### ISSUE TITLE
bootdisk and scsihw need to be defined

### ISSUE THREAD

**Issue by basvandijk** [Telmate/terraform-provider-proxmox#131]
For some reason, `terraform apply` will think the settings below changed from the values below to `null` after the initial `terraform apply`. So I have to set them to these values to not cause a redeploy:

```
bootdisk = "virtio0"
scsihw   = "lsi"
```

This seems like a bug `terraform-provider-proxmox`.

**Comment by backaf** [comment]
I am seeing the same behavior, defining both bootdisk and scsihw fixes the issue for now.
