### ISSUE TITLE
Changing disk size appears as it's removing the disk

### ISSUE THREAD

**Issue by backaf** [Telmate/terraform-provider-proxmox#132]
When the disk size is changed (increased), the plan output appears as it's going to remove and add a new disk:

```
- disk {
    - backup       = true -> null
    - cache        = "none" -> null
    - format       = "raw" -> null
    - id           = 0 -> null
    - iothread     = false -> null
    - mbps         = 0 -> null
    - mbps_rd      = 0 -> null
    - mbps_rd_max  = 0 -> null
    - mbps_wr      = 0 -> null
    - mbps_wr_max  = 0 -> null
    - replicate    = false -> null
    - size         = "10G" -> null
    - storage      = "local-lvm" -> null
    - storage_type = "lvm" -> null
    - type         = "scsi" -> null
  }
+ disk {
    + backup       = true
    + cache        = "none"
    + format       = "raw"
    + id           = 0
    + iothread     = false
    + mbps         = 0
    + mbps_rd      = 0
    + mbps_rd_max  = 0
    + mbps_wr      = 0
    + mbps_wr_max  = 0
    + replicate    = false
    + size         = "15G"
    + storage      = "local-lvm"
    + storage_type = "lvm"
    + type         = "scsi"
  }
```

The following disk configuration is used:
```
  disk {
    id           = 0
    type         = "scsi"
    storage      = "local-lvm"
    storage_type = "lvm"
    size         = "15G"
    backup       = true
  }
```

Went ahead and applied the plan and realized it's simply increasing the disk size and not actually removing it but the plan output is misleading.

I've tried this with LVM and NFS based storage, same results. Terraform version is 0.12.16.

**Comment by spirkaa** [comment]
Increasing disk `size` when `backup = 1` argument present in `disk` block causes creation of new disk and replacement in specified `slot`:
>  update VM 8131:(...identical config skipped) -scsi0 local-lvm:20,discard=on,ssd=1,backup=1
Logical volume "vm-8131-disk-1" created.
TASK ERROR: 400 Parameter verification failed. scsi0: hotplug problem - can't unplug bootdisk 'scsi0' 

Without `backup = 1` disk resize working as intended:
> update VM 8132:(...identical config skipped) -scsi0 local-lvm:vm-8132-disk-0,size=20G,discard=on,ssd=1
TASK OK

Terraform plans output identical for both VMs (with and without backup argument):

> \# proxmox_vm_qemu.test1[0] will be updated in-place
  ~ resource "proxmox_vm_qemu" "test1" {
        id                        = "pve/qemu/8131"
        name                      = "test1-01"
        \# (42 unchanged attributes hidden)
      ~ disk {
          ~ size        = "10G" -> "20G"
            \# (14 unchanged attributes hidden)
        }
\# proxmox_vm_qemu.test2[0] will be updated in-place
  ~ resource "proxmox_vm_qemu" "test2" {
        id                        = "spmaxi/qemu/8132"
        name                      = "test2-02"
        \# (42 unchanged attributes hidden)
      ~ disk {
          ~ size         = "10G" -> "20G"
            \# (17 unchanged attributes hidden)
        }
