### ISSUE TITLE
Incorrectly urlencoded ssh keys

### ISSUE THREAD

**Issue by starcraft66** [Telmate/terraform-provider-proxmox#133]
When creating a cloud-init VM and specifying an ssh key, the `:` character is not correctly urlencoded into `%3A` when sent to the proxmox API and causes and error that looks something like `{"errors":{"sshkeys":"invalid format - invalid urlencoded string: ssh-rsa AAAAB` etc.

I ran into this issue while trying to add the following public key to my VM:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8wZwiCGx/LX3xJZ0Yr323Apl43SFG2ETZsCavU06WO1OnybJOrZ6KqYQiO9mmsPjjQYHJApaJPBV2xiuOynfTPrEwZyBl0WqyaicqdczxirIez+ktNM8y/CSQ6XpmhfI/+UtdtHvlikWVEKG6oSQOi+QenXmCnIjZSqMRCOj7x3DD+D7fhIN6I+Ssw6XuPdBzAvDlpJ7vDtL2We7gA2PipX1I7erGsL3CnJzk/7ui9ha7r6Fz4WWwgEMuwx+WUxUuy9kK25SMJWwtzaHbeW3CZoLO0s9Fz4w9Z71hON/j/5xh7ynulFEiuco8zfxW6ySRf1HjlzyUN9GO2OMqqiFs8UCtvLDicv8ooCX1UCUiuEr9TwvAPx2du86bXwKpd0pq0ZZD3ymPxajbPGLLT7FYgzxUXbCpY3OeyD85dJB/JZ+5sMdPyimK26w2abLC9VCOV/+BTf15VjL8qTbby+BQNW1vLPcxauhWXVfhVV8FEVri97fj7wa9z7BIBneiIxjzjkpEWRtR8NhCBczioog81EJAFafWhcLEKBwn05YpN92iLWysBBxefIiBoynkfm+1+Ztu3z351BWxFMBod9DmOE6jf2utD12lCm1KeZ+vhnSfsfsBbhJ7/XfKvZ9ZE3igWhFw3A8FzOuuExKEKQLEgn2gUUa9bfRhdCX7PTeFTw== cardno:000609769932
```

**Comment by dsaard** [comment]
Same here with yubikey as ssh agent

**Comment by Asharas** [comment]
Same, works fine when removing `:` character

**Comment by slangdaddy** [comment]
Same for me, but I wanted to add that troubleshooting this was hard - the actual error message was not displayed. Terraform only said "Error: 400 Bad Request". It would be cool to pass the api error message to the end user :-)

**Comment by Asharas** [comment]
You can enable logging with the provider by using the following options:  
```
provider "proxmox" {
  pm_api_url          = ""
  pm_api_token_id     = ""
  pm_api_token_secret = ""
  pm_log_enable       = true
  pm_log_file         = "terraform-plugin-proxmox.log"
  pm_debug            = true
  pm_log_levels = {
    _default    = "debug"
    _capturelog = ""
  }
}
```

**Comment by Tinyblargon** [comment]
@mleone87 after a new build this issue can be closed as it was fixed by [this pull request](https://github.com/Telmate/proxmox-api-go/pull/219).
