### ISSUE TITLE
Configure task fails when vga is not set

### ISSUE THREAD

**Issue by cospeedster** [Telmate/terraform-provider-proxmox#139]
After updating to the current version of this provider, the configure task in proxmox failed, when `vga` is not set.
The proxmox task's output:
```
update VM 116: .....
cannot delete 'vga' - not set in current configuration!
TASK ERROR: rbd error: rbd: error opening image vm-116-disk-1: (2) No such file or directory
```

When I add the following, it works without any problems:
```HCL
vga {
    type = "std"
}
```

Maybe @V-Paranoiaque can fix this? It was added in PR Telmate/terraform-provider-proxmox/pull/130

**Comment by V-Paranoiaque** [comment]
Hello,
I have created a VM without the vga attribute and I haven't got any problem.
Could you help me to reproduce it?

**Comment by cospeedster** [comment]
Mhh, thats confusing. My template has set the default adapter.

**Comment by cospeedster** [comment]
Well, maybe it was an temporary problem. When I now remove the vga part:

```
update VM 116: ...
cannot delete 'vga' - not set in current configuration!
TASK OK
```

**Comment by cospeedster** [comment]
For now I'll close this issue.
