### ISSUE TITLE
HA VM does not get destroyed if running.

### ISSUE THREAD

**Issue by dragon2611** [Telmate/terraform-provider-proxmox#145]
PVE Version 6.1.7.

When creating a VM with the HA state set, if the VM is running when terraform destroy is run the terraform reports success but the vm is not actually destroyed.

What actually happens is HA stop is called, then the HA entry is removed but the VM is left in a running state.

When stopping a HA VM there is usually a delay of a few seconds between HA stop being called and the VM stop command being issued by proxmox, I suspect the problem is that terraform is not waiting long enough between HA Stop being called and removing the HA entry from proxmox which causes proxmox not to go ahead and stop the VM.

**Comment by breitenj** [comment]
We also experience this issue. We are using PVE 6.3-3 and version 2.6.7 of the provider.

The provider log shows that the VM is not deleted because it is still running:
```
2021/02/05 17:53:51 >>>>>>>>>> REQUEST:
POST /api2/json/nodes/[...]/qemu/100/status/stop HTTP/1.1
[...]

2021/02/05 17:53:51 <<<<<<<<<< RESULT:
HTTP/1.1 200 OK
[...]

{"data":"UPID:[...]:0028213B:00962EE5:601D862F:hastop:100:[...]@pve:"}
2021/02/05 17:53:51 >>>>>>>>>> REQUEST:
GET /api2/json/nodes/[...]/tasks/UPID:[...]:0028213B:00962EE5:601D862F:hastop:100:[...]@pve:/status HTTP/1.1
[...]

2021/02/05 17:53:51 <<<<<<<<<< RESULT:
HTTP/1.1 200 OK
[...]

{"data":{"type":"hastop","node":"[...]","user":"[...]@pve","upid":"UPID:[...]:0028213B:00962EE5:601D862F:hastop:100:[...]@pve:","starttime":1612547631,"pid":2629947,"status":"running","id":"100","pstart":9842405}}
2021/02/05 17:53:53 >>>>>>>>>> REQUEST:
GET /api2/json/nodes/[...]/tasks/UPID:[...]:0028213B:00962EE5:601D862F:hastop:100:[...]@pve:/status HTTP/1.1
[...]

2021/02/05 17:53:53 <<<<<<<<<< RESULT:
HTTP/1.1 200 OK
[...]

{"data":{"starttime":1612547631,"upid":"UPID:[...]:0028213B:00962EE5:601D862F:hastop:100:[...]@pve:","user":"[..]@pve","node":"[...]","type":"hastop","exitstatus":"OK","pstart":9842405,"status":"stopped","id":"100","pid":2629947}}
2021/02/05 17:53:55 >>>>>>>>>> REQUEST:
DELETE /api2/json/cluster/ha/resources/100 HTTP/1.1
[...]

2021/02/05 17:53:55 <<<<<<<<<< RESULT:
HTTP/1.1 200 OK
[...]

{"data":null}
2021/02/05 17:53:55 >>>>>>>>>> REQUEST:
DELETE /api2/json/nodes/[...]/qemu/100 HTTP/1.1
[...]

2021/02/05 17:53:55 <<<<<<<<<< RESULT:
HTTP/1.1 500 VM 100 is running - destroy failed
[...]
```

**Comment by breitenj** [comment]
We are currently testing a fix for this. If it turns out to not cause any issues, I will create a PR for it (in the near future hopefully).
