### ISSUE TITLE
proxmox qemu vm resource gets assigned incorrect "ssh_host" and "ssh_port" values when there is only and ipv6 cloud-init configuration

### ISSUE THREAD

**Issue by starcraft66** [Telmate/terraform-provider-proxmox#147]
I am using this provider to create VMs which only have an IPv6 address and no IPv4 address. The provider makes the incorrect assumption that the first ip address it finds in the cloud-init definition is an ipv4 address.

The culprit code is here: https://github.com/Telmate/terraform-provider-proxmox/blob/4403acf4b236b8f2d19c351e578fbb3729b74103/proxmox/resource_vm_qemu.go#L1057

For example, my VM has `"ipconfig0": "ip6=2607:fa48:6c16:81b4::100:1/64,gw6=2607:fa48:6c16:81b4::1"` in its terraform file and the provider incorrectly assigns the following attributes on the vm resource. This causes provisioning to fail because the provisionner cannot connect to the server :

```
"ssh_host": "2607",
"ssh_port": "fa48",
```

**Comment by Syntax3rror404** [comment]
I also need ipv6 support

**Comment by Syntax3rror404** [comment]
@starcraft66 do you have a idea to fix this issue?
