### ISSUE TITLE
Create user and set password via cloudbase-init in windows server 2019

### ISSUE THREAD

**Issue by UnreleasedCode** [Telmate/terraform-provider-proxmox#150]
Hello Telmate, 
first, thanks for this great provider! 
Actually this is not a real issue..

I installed on a windows server 2019 cloudbase-init and activated the userdata and metadata plugins. After that I executed sysprep.exe and converted it to a template.
Cloning works now very well and fast with your terraform provider.

Now I am wondering how to set up the terraform file, to inject the user and password?

**Comment by gurubert** [comment]
The cloud-init attributes for the proxmox_vm_qemu resource are "ciuser" and "cipassword".
