### ISSUE TITLE
LXC: changing feature flags is only allowed for root@pam

### ISSUE THREAD

**Issue by syphernl** [Telmate/terraform-provider-proxmox#155]
I'm trying to create an LXC container using this provider following the example:
```tf
resource "proxmox_lxc" "alpine-test" { 
    hostname = "alpine-test"
    cores = 1
    memory = "1024"
    swap = "2048"
    network {
        name = "eth0"
        bridge = "vmbr0"
        ip = "192.168.1.50/24"  
        firewall = false
    }
    ostemplate = "local:alpine-3.10-default_20190626_amd64.tar.xz"
    password = "XXXXXXXXXXXXX"
    rootfs = "local-lvm:8" 
    storage = "local-lvm"
    target_node = "proxmox"
    unprivileged = true
}
```

Terraform runs as a pve user. 

Running this however results in an error:
```bash
proxmox_lxc.alpine-test: Creating...

Error: Error creating LXC container: 403 Permission check failed (changing feature flags is only allowed for root@pam), error status: {"data":null} (params: [123 34 111 115 <snip> 115 101 125])
```

According to the debug it is passing along `&features=` with no features.

**Comment by tkriviradev-falcon** [comment]
What does features means, I have the same problem.
Can I create container without features?

**Comment by tkriviradev-falcon** [comment]
I have enabled, 2FA for my root account, and I can't use the root@pam either.

**Comment by winggundamth** [comment]
I confirm @syphernl bug. My workaround right now is using root@pam instead.

**Comment by shbert** [comment]
Also tried to create an additional pam user, but did not manage to assign the correct rights to avoid this issue.

**Comment by rekahsoft** [comment]
There does not seem to be a way to provide this permission to any `pve` user. I gave a test user access to `/` with propagate set to true and the reported error still occurs.

**Comment by krzysztof-magosa** [comment]
Only root can control features, there is no way to allow others to set them.
I think the correct way here would be to not pass features at all in case nothing was explicitly specified.

https://git.proxmox.com/?p=pve-container.git;a=blob;f=src/PVE/LXC.pm;h=ab15ec09fb3a3fb1e859cb705375ef4bb42b279a;hb=HEAD#l1111

**Comment by syphernl** [comment]
@krzysztof-magosa With the most recent version (and changes of #77) I'm still getting the same error. I'm using the aforementioned resource where no explicit features are specified. Anything I'm doing wrong?

**Comment by Roman2dot0** [comment]
Hello. I have the same error with following config, what am i doing wrong? Local terraform-provider-proxmox has been updated

```
resource "proxmox_lxc" "test" {
    hostname = "test"
    cores = 2
    memory = 2048
    swap = 0
    network {
        name = "eth0"
        bridge = "vmbr0"
        ip = "dhcp"
    }
    ssh_public_keys = var.cloud_vars.ssh_key
    ostemplate = "shared:cephfs/ubuntu-20.04-lxc.tar.xz"
    storage = "pool"
    target_node = "server-n4"
    unprivileged = true
}
```

`Error: Error creating LXC container: 403 Permission check failed (changing feature flags is only allowed for root@pam), error status: {"data":null} (params:........`

**Comment by cgoubert** [comment]
Same thing here, no features in the container, but it's impossible to create one. Could the issue be reopened please ?

**Comment by syphernl** [comment]
@ggongaware Can this issue be reopened?

**Comment by syphernl** [comment]
Unfortunately the changes of https://github.com/Telmate/proxmox-api-go/pull/77 haven't helped and this still seems to be a problem with Terraform 1.0.11 / Provider 2.9.3:

```shell
│ Error: error creating LXC container: 403 Permission check failed, error status: {"data":null} (params: {"arch":"amd64","cmode":"tty","console":true,"cores":1,"cpulimit":0,"cpuunits":1024,"features":"","hostname":"alpine-test","memory":1024,"net0":"name=eth0,ip=x.x.x.x/xx,bridge=vmbr0","onboot":false,"ostemplate":"local:alpine-3.10-default_20190626_amd64.tar.xz","password":"xxxxxx","protection":false,"rootfs":"local-lvm:1","start":false,"storage":"local","swap":2048,"tags":"","tty":2,"unprivileged":true,"vmid":117})
```

**Comment by YusufMavzer** [comment]
This bug isn't fixed. Tested myself and it had to use root@pam or set unpriviliged to true
Terraform 1.1.0 / Provider 2.9.3

**Comment by tabnul** [comment]
> This bug isn't fixed. Tested myself and it had to use root@pam or set unpriviliged to true Terraform 1.1.0 / Provider 2.9.3

its not a bug. its a proxmox feature.

**Comment by andymilga** [comment]
bump
pve 7.1-8, _feature_ still here
