### ISSUE TITLE
Unable to create a container with a mountpoint

### ISSUE THREAD

**Issue by zinefer** [Telmate/terraform-provider-proxmox#157]
When trying to create a container with a mount, like:

```
resource "proxmox_lxc" "container" {
  target_node  = "proxmox"
  ostemplate   = "local:vztmpl/ubuntu-19.10-standard_19.10-1_amd64.tar.gz"
  storage      = "local-lvm"
  unprivileged = true
  
  network {
    gw     = "192.168.1.1"
    name   = "eth0"
    ip     = "192.168.1.6/24"
    ip6    = "dhcp"
    bridge = "vmbr0"
    firewall = true
  }

  ssh_public_keys = var.proxmox_pub_keys

  hostname = "help"
  vmid     = 10006
  cores    = 1
  memory   = 256
  swap     = 256
  start    = true
  rootfs   = "vdisk:2"
  cpuunits = 0

  mountpoint {
    volume = "/mnt/pve/hot/skunkworks"
    mp = "/mnt/skunkworks"
  }

  lifecycle {
    ignore_changes = [
      start,
      ostemplate,
      ssh_public_keys,
      storage,
      ostype,
      password,
      network,
      rootfs
    ]
  }
}
```

However, it throws the following error:

```
2020-03-17T21:46:39.496-0600 [DEBUG] plugin.terraform-provider-proxmox: 2020/03/17 21:46:39 [ERR] Error writing fields: Invalid address to set: []string{"mountpoint", "1622140574", ""}
2020/03/17 21:50:38 [DEBUG] module.help_container.proxmox_lxc.container: apply errored, but we're indicating that via the Error pointer rather than returning it: Provider produced inconsistent result after apply: When applying changes to module.help_container.proxmox_lxc.container, provider "registry.terraform.io/-/
proxmox" produced an unexpected new value for was present, but now absent.
```

An interesting note is that if I remove the `mountpoint` and allow Terraform to create the container but then replace the `mountpoint` and run another `apply` then everything is fine.

**Comment by zinefer** [comment]
A better workaround is to import the container into Terraform after the failure:

```bash
terraform import -config $CONFIG_PATH proxmox_lxc.container proxmox/lxc/10006
```

**Comment by Jungo495** [comment]
any news?
got this error
Error creating LXC container: 500 mount points configured, but 'rootfs' not set

**Comment by Jungo495** [comment]
new error
Error: Error creating LXC container: 500 unable to parse volume ID

**Comment by Jungo495** [comment]
after patching get this error
2020-07-11T17:24:46.880+0300 [DEBUG] plugin.terraform-provider-proxmox: {"data":{"cpuunits":1024,"mp1":"local-lvm:vm-1
006-disk-1,mp=/vault,size=1G","console":1,"tty":2,"net1":"name=eth0,bridge=vmbr1,hwaddr=62:75:36:5D:9D:F6,ip=dhcp,ip6=
dhcp,type=veth","swap":512,"onboot":1,"rootfs":"local-lvm:vm-1006-disk-0,size=8G","cores":1,"cpulimit":"0","memory":25
6,"digest":"","arch":"amd64","ostype":"debian","hostname":"fisherman","protect
ion":0,"cmode":"tty","description":"debian\n","features":"nesting=1"}}
2020-07-11T17:24:46.883+0300 [DEBUG] plugin.terraform-provider-proxmox: panic: interface conversion: interface {} is string, not int


main.tf contains:
    mountpoint {
      mp = "/vault"
      volume = "local-lvm:1"
    }
but when i remove mountpoint definition, terraform apply works well
however, the node is created
but the condition is not recorded
