### ISSUE TITLE
Terraform doesn't regenerate cloud-init image on changes

### ISSUE THREAD

**Issue by christophetd** [Telmate/terraform-provider-proxmox#160]
It looks like the terraform provide doesn't "regenerate" the cloud init image when changes are performed. As an example, if I assign the IP 192.168.4.100 to a VM, run `terraform apply`, change the IP to 192.168.4.10**1**, run `terraform apply` again, here is what happens the modification is correctly performed by Terraform:

![image](https://user-images.githubusercontent.com/136675/77251180-d841fa80-6c44-11ea-82bf-b38f40b42eb4.png)

... but proxmox shows that the cloud init image needs to be regenerated:

![image](https://user-images.githubusercontent.com/136675/77251189-f0197e80-6c44-11ea-9e59-091a1927dd9a.png)

More precisely, I need to manually click the "Regenerate image" button in order for changes to take effect.

![image](https://user-images.githubusercontent.com/136675/77251205-ff98c780-6c44-11ea-91f2-58cc7442aa1c.png)

Any chance to have this capability integrated in the provider? FYI, here's the API request made when the button is pressed:

```
PUT /api2/extjs/nodes/proxmox/qemu/102/config HTTP/1.1
Host: proxmox.home:8006

ide0=nas-nfs-main%3Acloudinit
```

(nas-nfs-main is the name of my storage pool)

**Comment by frederikbosch** [comment]
This would require work in the [Proxmox API Go repository](https://github.com/Telmate/proxmox-api-go/blob/master/proxmox/client.go). Specifically, I guess it requires a method to be added in the `client`.

**Comment by christophetd** [comment]
Alright, maybe out of scope for this repository then? Still, seems like an important feature to have because it essentially breaks automation if you want to use cloud init

**Comment by frederikbosch** [comment]
Well, it doesn't break it. You cannot play tennis with IP addresses; that is another story. The API go repo is maintained by the same person as this repo. If you are capable, maybe you can create a PR at that repo? Then I can help getting the feature in here.
