### ISSUE TITLE
Quick Idea/Request - Resiliency for the provider

### ISSUE THREAD

**Issue by gentoo9ball** [Telmate/terraform-provider-proxmox#161]
I regularly get proxmox errors such as this during terraform apply:
```
trying to acquire lock...
trying to acquire lock...
 OK
TASK ERROR: clone failed: can't lock file '/var/lock/pve-manager/pve-storage-local' - got timeout
```
I believe if terraform just did a quick retry then it would be fine. I've made changes here before, but I think this one is a little over my head. Can anyone help?

https://www.terraform.io/docs/extend/resources/retries-and-customizable-timeouts.html

**Comment by RobertSkawinski** [comment]
I have a similar issue, when cloning a bunch of vm's (more than 2) I get this issue:
`create full clone of drive ide2 (local:9003/vm-9003-cloudinit.qcow2)
trying to acquire lock...
TASK ERROR: clone failed: can't lock file '/var/lock/pve-manager/pve-storage-ZFS_Main1' - got timeout`
Seems like there is a need to for a wait/retry after receiving a timeout
