### ISSUE TITLE
proxmox_lxc : changing disk size

### ISSUE THREAD

**Issue by belkone** [Telmate/terraform-provider-proxmox#163]
I am looking for a way to change the size of the container disk (increase).
If I change the rootfs declaration:
```
rootfs = "local:101/vm-101-disk-0.raw,size=10G"
```
the change is visible correctly in terraform:
```
~ rootfs = "local:101/vm-101-disk-0.raw,size=4G" -> "local:101/vm-101-disk-0.raw,size=10G"
```
but in proxmox it causes:
![screenshot](https://i.imgur.com/q8Ho6XM.png)

is there any way to changing the disk size in lxc?

**Comment by cw1797** [comment]
I'm looking for a way to do this on my qemu vm and wondering if there is also the option to move disks as it only seems to be done at pre-provisioning stage

**Comment by SimonBaeumer** [comment]
@belkone Did you tried to reboot the machine after you applied your terraform changes?

**Comment by belkone** [comment]
> @belkone Did you tried to reboot the machine after you applied your terraform changes?

Hi, after reboot it's ok.
is a reboot necessary? normally Proxmox can extend it without rebooting. 
If necessary, is it possible to force a reboot from the terraform?

**Comment by Matchlighter** [comment]
I'm running into this as well. Rebooting does update the parameter, but I don't think the backing storage is actually resized - at least it's not for `lvm` (the LV continues to report the original size while the param displays the new size). I'm also running into issues that it expects `rootfs` to be in the format `local-lvm:8`, on the initial create, but things blow up a little down the road if that format is passed for an update.
