### ISSUE TITLE
400 parameter verification failed.

### ISSUE THREAD

**Issue by 0xC4DE** [Telmate/terraform-provider-proxmox#164]
New to using this provider so I'm not sure what im doing wrong... whenever I try to use this

```
provider "proxmox" {
    pm_api_url = "https://url:port/api2/json"
    pm_tls_insecure = true
    pm_user = "root@pam"
    pm_password = "password"
}
resource "proxmox_vm_qemu" "example" {
    name = "tf-test"
    target_node = "nodename"
    clone = "Debian-Basic"
    full_clone = true
}
```
Assuming the url, user, password, and node are correct (just didnt want those in an issue), running terraform plan works fine, and initially apply works just fine until you approve it, which throws 

```
Error: 400 Parameter verification failed.

  on terraformfile.tf line 7, in resource "proxmox_vm_qemu" "example":
   7: resource "proxmox_vm_qemu" "example" {
```
I'm not sure exactly what's wrong here.

**Comment by bogdanfe** [comment]
I had a similar issue, but with a bit more complex .tf file. Your code seems ok to me.

In the console, enable tracing for terraform by running 
`export TF_LOG=TRACE`

When you run the `terraform apply` command you would get a very detailed output and around the last lines before the error message you should notice which parameter is causing trouble and which are the supported values. Or at least that's how I fixed this issue.

Don't forget to turn off tracing once you're done troubleshooting:
`export TF_LOG=ERROR`

**Comment by jda** [comment]
I was running into 400 parameter verification failed when cloning as well.
Looking at the trace showed error
`plugin.terraform-provider-proxmox: {"data":null,"errors":{"storage":"invalid format - storage ID '' contains illegal characters\n"}}`. If you are hitting the same error, I just opened a PR for the api library that's upstream of the terraform provider: https://github.com/Telmate/proxmox-api-go/pull/76

**Comment by querplis** [comment]
copied this from your ticket
```
2020-04-24T20:33:09.737-0700 [DEBUG] plugin.terraform-provider-proxmox: full=1&name=terraform-test-vm&newid=102&pool=managed&storage=&target=tachikoma
```
this is part is from http request to api  and offending param is this
```
storage=
```
if someone runs into similar problem , turn on debug look for parameter without value, define it => profit

i hope it helps someone.

**Comment by leodotcloud** [comment]
Enabling provider debug logs gives more insights: https://github.com/Telmate/terraform-provider-proxmox/issues/455#issuecomment-984324159
