### ISSUE TITLE
Instance - example file

### ISSUE THREAD

**Issue by replay111** [Telmate/terraform-provider-proxmox#166]
Hi,

I am just starting my journey with this plugin and proxmox itself, but I was not able to even create machine from attached example file ("cloudinit_example.tf").

Terraform apply ends run with message:

```bash
proxmox_vm_qemu.cloudinit-test: Creating...

Error: Vm 'linux-cloudinit-template' not found

  on instances.tf line 1, in resource "proxmox_vm_qemu" "cloudinit-test":
   1: resource "proxmox_vm_qemu" "cloudinit-test" {

```

any idea what is this about? Maybe anyone of you already had such error?

**Comment by bbichero** [comment]
Have you followed correctly the README.md ?
You must create cloud init template with [proxmox doc](https://pve.proxmox.com/wiki/Cloud-Init_Support)
After that you must enter your template name in `clone` variable

**Comment by replay111** [comment]
No - I just installed my customized version of centos7, I've installed cloudinit tools, powerdown my host an converted it from gui to template - is this not enough?

**Comment by replay111** [comment]
Also - do I have to prepare cloudinit? Can't I use just simple template for creating virtual machiine?

**Comment by bbichero** [comment]
I think you must follow the tutorial to be sure the problem don't come your side.

**Comment by bbichero** [comment]
Sorry but I don't have muck experience with this provider, from my side, I strictly follow the cloud init example and I got the exact same error you have.
Terraform can't get the Vm name, or get it wrong ...

**Comment by replay111** [comment]
I was doing as it was shown here:

**Comment by replay111** [comment]
OK - I did the compilation of plugins in wrong way. Right now it seems to be working fine.
