### ISSUE TITLE
Better cluster compatibility / Idempotence

### ISSUE THREAD

**Issue by tabnul** [Telmate/terraform-provider-proxmox#168]
Hi, first of all: great work on this plugin. 
I do think there might be improvements in the cluster area.

The nature of a virtual machine cluster is that you are able to migrate workloads and able to cope with downtime of a specific hypervisor.
It looks like the current implementation of this proxmox provider does not cope with this scenario; it assumes that the created VMs are on the same hypervisor they were initially created on (statefile has a hard link to the host and checks on this host for the VM when it needs to change something)

I think this can be fixed by changing the UID in the statefile and/or change some logic.

Of course you will still (initially) have to give a host parameter to create the resource, but afterwards in the statefile or logic behind it should look om the cluster where the VMID is and dynamically use that hypervisor when adjusting the resource. (VMID is still a unique id within the cluster)

**Comment by fa-itnoobs** [comment]
Absolutely, much appreciate your work on this great plugin.
Just to add, this is also true for all optional network parameters. If they're not specified, the next run of terraform apply/plan will pick the default values assigned and change them.

I am currently using lifecycle to get around this.
```
lifecycle { 
     ignore_changes = [
                   network,
                   target_node,
     ]
}
```

**Comment by gostega** [comment]
I would like this functionality too. I have a proxmox cluster and would like the provider to check for the VM existence on any node of the cluster. At the moment, I have to specify a single node. If a VM, let's say VM1 migrates to a different node, NODE2, the terraform provider thinks it has been destroyed and tries to create it again on NODE1. It also tries to destroy the VM1 on NODE2 for the same reason. I know that proxmox itself requires the exact node as an argument when creating the VM, but I want the provider to be 'cluster-aware' and basically decouple the node name from the VM state. When checking for the existence of a VM, it should check all nodes (in a list, provided by the user) to see if the VM exists on any of them. If the VM does not exist on any node, choose a node at random from the list. Likewise for the clone source. Example syntax

```terraform
# list of VMs to create
# list of terraform managed VMs in our environment
variable "vm_deploy_list" {
  description = "list of VMs to provision for XX deploy environment"
  type        = map
  default     = {
    XXFRONTENDDEV1 = {
      ip    = "ip=192.168.1.23/24,gw=192.168.1.1",
      desc  = "Dev deploy server for xx app",
      env   = "master"
    },
    XXFRONTENDDEVPUB1 = {
      ip    = "ip=192.168.1.24/24,gw=192.168.1.1",
      desc  = "temp public dev deploy server for XXapp-frontend",
      env   = "dev"
    }
}
# Create the VM(s)
resource "proxmox_vm_qemu" "bbx_vms" {

    ## Wait for the cloud-config file to exist
    #depends_on = [
    #  null_resource.cloud_init_deb10
    #]

    for_each = var.vm_deploy_list

    # Per VM settings (from variable)
    name        = each.key
    ipconfig0   = each.value.ip
    desc        = each.value.desc

    # specify a list, or something.
    target_node = var.cluster

    # The template name to clone this vm from
    clone = "deb10-current"
.....etc
}
```

**Comment by faranoosh** [comment]
@gostega and @tabnul, I ended creating an Ansible playbook to do exactly that, you can find it here https://gitlab.com/itnoobs-automation/ansible/proxmox-vm

**Comment by eldengates** [comment]
Actual
