### ISSUE TITLE
Error: 400 Parameter verification failed

### ISSUE THREAD

**Issue by cw1797** [Telmate/terraform-provider-proxmox#170]
Hello,

I'm making use of this proxmox terraform repo which has been great but i've ran into a little issue

Promox VE 6.1
Terraform 0.12.14

**What I am trying to do:**
I am trying to provision 3 compute 'proxmox_vm_qemu' resources from a cloud-init template to use for my kuberentes cluster setup. Here is a link to the terraform file im running: https://github.com/cw1797/terraform-provider-proxmox/blob/master/k8s_qemu.tf

**The error:**
When I run terraform plan I see all the things to be changed as expected with no errors. After when I run terraform apply I receive the following error :

Error: 400 Parameter verification failed.

on main.tf line 8, in resource "proxmox_vm_qemu" "kubernetes-master":
8: resource "proxmox_vm_qemu" "kubernetes-master" {

Error: 400 Parameter verification failed.

on main.tf line 49, in resource "proxmox_vm_qemu" "kubernetes-node-01":
49: resource "proxmox_vm_qemu" "kubernetes-node-01" {

Error: 400 Parameter verification failed.

on main.tf line 91, in resource "proxmox_vm_qemu" "kubernetes-node-02":
91: resource "proxmox_vm_qemu" "kubernetes-node-02" {

**Workaround:**
I found a workaround that get's it working but it's not ideal. I have to change the id of the drives being provisioned for each instance to 0 which the produces the following error for each resource:

Error: 500 disk 'virtio0' does not exist

on main.tf line 8, in resource "proxmox_vm_qemu" "kubernetes-master":
8: resource "proxmox_vm_qemu" "kubernetes-master" {

After getting this error I can then change the id drive to what it was before i.e. id 1, id2, id3 from the 1-3 resource and then it starts working.

**Comment by cw1797** [comment]
Sorry user error pls ignore

**Comment by Gabisonfire** [comment]
@cw1797 Please provide your fix, had the same issue

**Comment by gverbist** [comment]
please enlighten me,, I have the same issue
