### ISSUE TITLE
How to create default disk on Ceph

### ISSUE THREAD

**Issue by uhlhosting** [Telmate/terraform-provider-proxmox#172]
When I use no `rootfs` in my .tf I will get default disk size of 4 GB:

Once the LXC was created, running again the commad will show:

`rootfs: hdd:vm-119-disk-0,size=4G`

Now I am wondering how do we define the disk name, especially when using rbd ceph pools. 

I tried with `#rootfs = "hdd:size=10G"` yet that will fail in proxmox for `TASK ERROR: unable to parse rbd volume name '10'` .

How can I change the disk size for LXC the right way.

**Comment by Folamh** [comment]
From #137 
You can set the starting size with:
> ```varnish-vcl
> rootfs = "local-lvm:20" # size in GB
> ```
