### ISSUE TITLE
Error: 500 can't lock file

### ISSUE THREAD

**Issue by replay111** [Telmate/terraform-provider-proxmox#173]
Hi,

does anyone had similar error? Any solution for that?

```

Error: 500 can't lock file '/var/lock/qemu-server/lock-104.conf' - got timeout

  on vm-gitlab.tf line 2, in resource "proxmox_vm_qemu" "gitlab":
   2: resource "proxmox_vm_qemu" "gitlab" {



Error: 500 can't lock file '/var/lock/qemu-server/lock-103.conf' - got timeout

  on vm-squid.tf line 2, in resource "proxmox_vm_qemu" "squid":
   2: resource "proxmox_vm_qemu" "squid" {
```

**Comment by SiM22** [comment]
yup im getting that same error

**Comment by powerjc** [comment]
Same error here. Anyone make any progress working through this one?

**Comment by replay111** [comment]
In my case setting parallelism to 1 solve the case. I suspect that (maybe only for me) the problem is related with disk performance. When I am creating 2-3 machines parallel it is a problem, when I create them one by one - everything works. Maybe this is related with my proxmox configuration - I have Dell Laptop with 1TB disk - this is my playground ;-)

**Comment by rpelissi** [comment]
I have the same issue with only 1 vm at a time.I have try the parameter clone_wait but even if I put 3600 it still stop at 5m10 with a timeout.
I know that my disks maybe slow but the provider should respect the timeout parameter.
Or maybe there is something else to set in terraform for this timeout...not sure. First time I try this.
Thanks

**Comment by featheredtoast** [comment]
Hitting the same. I think it's an issue in proxmox where it's trying to assign multiple VMs the same ID. I'm imagining something like:

terraform starts creating vm1, requests next "free" ID from Proxmox. gets 100.
terraform starts creating vm2, requests next "free" ID from Proxmox. gets 100.
terraform starts creating vm1, proxmox's internal counter sets the next free ID to 101.
terraform tries to create vm2 with ID 100, Proxmox errors.

Would be cool to set a VM ID manually, to avoid this.

**Comment by replay111** [comment]
I didn't notice such behavior - it rather looked like I had 3 instances with 3 different ID but "extracting" template to VM was a problem like bottleneck with disk transfer which caused timeout. Maybe as you wrote problem is located with proxmox itself, not in a plugin...

**Comment by abigail-murray** [comment]
Same error here, with only a single VM. I'm running a little server with a load of very slow disks and trying to clone a 40Gb template. 

I'm going to create a smaller cloud-init template and try that but it would be awesome if there was another way.

**Comment by stefanvangastel** [comment]
Any progress / workarounds for this? Having the same issue.

**Comment by doransmestad** [comment]
@stefanvangastel   Are you attempting to clone a large VM disk here?   Looks like there are a few ideas in this ticket on what the issue could be, and so I'm curious if this due to something on the proxmox end taking longer than the code currently waits for.

**Comment by stefanvangastel** [comment]
A 12 gb disk. Though I try to create multiple (3) vm’s at a time. The error also seems random

**Comment by doransmestad** [comment]
Hm, I can't (yet) reproduce this on my end.   When you try running a terraform apply, can you look at the task list in proxmox?  I'm wondering if the clone is still in progress when we attempt to post the VM config.  If the clone is still occurring and terraform tries to apply a configuration update, I would expect a lock error like was posted above to happen.   If you set the `clone_wait` attribute in your `proxmox_vm_qemu` resource higher than the default of 15 seconds (say 120 seconds), does that make a difference?

**Comment by stefanvangastel** [comment]
I will try to do that. The lock error does occur. I’ll post my results
later

Op vr 6 nov. 2020 om 03:01 schreef Doran Smestad <notifications@github.com>

**Comment by doransmestad** [comment]
Aha!  Okay, I was able to reproduce this.  Looks like @rpelissi  was on the right path in suggesting the timeout parameter is not being honored somewhere.  I dropped the timeout to 5 seconds in my testing but I had to clone a massive enough VM to cause the lock error to occur after 5 minutes of waiting for the clone to finish.  I'll dive in here and update when I think I've found a solution.  In the meanwhile I do believe the `clone_wait` attribute should be a valid workaround.

**Comment by andkuzmich** [comment]
Is this going to be fixed? This problem is still relevant

**Comment by XReyRobert-IBM** [comment]
I think this is the same race condition than mentioned here (closed): #23 

I'm running into this or vm conflict that are created with same id in some cases.
In my case I'm using ( 5-10) partial clones created alltogether that are really quick to spawn, that might help to reproduce the bug...

I had to forcefully use fixed vmids to solve the issue or use pm_parallel = 1

**Comment by XReyRobert-IBM** [comment]
In fact this is more likely related to a lock on proxmox ve side that will prevent further operations...
cf (https://forum.proxmox.com/threads/concurrent-cloning-of-vm.97549/#post-422157)

I solved it by adding a delay for vm creation using the official time sync "hack"

https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep

In my case 1s delays were  enough to prevent error 500!

**Comment by XReyRobert-IBM** [comment]
[this might be a proxmox VE issue in fact... ](https://forum.proxmox.com/threads/race-conditions-for-mass-vm-creation.76839/)

**Comment by mleone87** [comment]
hammering proxmox with too many operations will cause a lot of problem, but lowering parallelism would fix 99% of the problems of lockfile and/or storage, the faster the system, the  higher the parallelism count!
I see a lot of people that thinks their system is an AWS datacenter, but it is not!

**Comment by rgumti** [comment]
I am running into this issue creating 2 VM's with the same template. Setting the parallelism to 1 fixes the problem. 

Naturally runs slower, but it goes through.

**Comment by kennyparsons** [comment]
I'm having this problem on version = "3.0.1-rc3" creating container templates. I even specify the vmid. How do i slow down the container creation to avoid this error?

**Comment by max-pfeiffer** [comment]
I just ran into the same problem using v3.0.1-rc4. I was creating multiple VMs in parallel cloning the same template.

I can confirm setting `pm_parallel = 1` in the provider config fixes the problem.

`pm_parallel` defaults to 4. I guess it's probably a good idea to change these default as a bunch of other users will run right away into that problem.
