### ISSUE TITLE
Error creating VM: 596 tls_process_server_certificate: certificate verify failed

### ISSUE THREAD

**Issue by devopsmyth** [Telmate/terraform-provider-proxmox#175]
It appears to be failing with a TLS cert error. However, my Linux machine fully trusts the self-signed CA certs on my ProxmoxVE cluster. And I've set what I think is supposed to negate TLS verification in the main.tf file like so:

## What I think should prevent the TLS error but is NOT doing so:
>provider "proxmox" {
>  - pm_api_url      = "https://server.domain.home:8006/api2/json"
>  - pm_user         = "terraform@pve"
>  - pm_tls_insecure = true
>  - pm_parallel     = 4
> }

## Here's the error:

`tf apply main-plan.tfplan`

> proxmox_vm_qemu.terraform_test1: Creating...
> 
> Error: Error creating VM: 596 tls_process_server_certificate: certificate verify failed, error status:  (params: map[agent:1 bios:seabios boot:cdn cores:4 cpu:kvm64 description:testing terraform deployment hotplug:network,disk,usb ide2:ISOs1/terraform-ubuntu-16.04.6-server-amd64.iso,media=cdrom memory:4096 name:terraform_test1 net0:virtIO=AE:05:4A:A4:2F:B5,bridge=vmbr1,tag=110 numa:false onboot:true ostype:l26 sockets:1 vmid:108])
> 
>   on main.tf line 10, in resource "proxmox_vm_qemu" "terraform_test1":
>   10: resource "proxmox_vm_qemu" "terraform_test1" {

### **Anyone have any experience with the above?** ###
I'm all for fixing the code myself, but I'm new to Terraform and to the Proxmox TF provider. Not sure where to start at, yet.

**Comment by devopsmyth** [comment]
For some reason the provider {} entry wasn't getting parsed correctly, and I was getting prompted for credentials and warned about missing pm_api_url which I made sure wasn't actually missing. I rewrote the provider section, included all of the options even if just set to blank "", and it worked. Here's my working provider section block:
`
provider "proxmox" {
  pm_tls_insecure = true
  pm_api_url = "https://server.domain.home:8006/api2/json"
  pm_password = "secret"
  pm_user = "terraform@pve"
  pm_otp = ""
}
`

**Comment by anandsuresh** [comment]
Seem to be running into this issue as well. The error I see is:
```
proxmox_vm_qemu.vms["tungsten_ic-001"]: Creating...

Error: Error creating VM: 596 tls_process_server_certificate: certificate verify failed, error status:  (params: map[agent:0 bios:seabios boot:cdn cores:2 cpu:host description: hotplug:network,disk,usb ide2:local:ic-os 08062020.iso,media=cdrom memory:16384 name:tungsten_ic-001 numa:false onboot:true ostype:l26 sockets:1 vmid:100])

  on main.tf line 65, in resource "proxmox_vm_qemu" "vms":
  65: resource "proxmox_vm_qemu" "vms" {
```

- `pm_tls_insecure = true` has been set on the provider and tested when set and unset. When unset, it fails to even get to the the plan. When set, it fails when `apply`ing.
- Tried changing the order of the declarations as specified above, but no luck.
- Tried blank options as well. No luck with those either.
- Running the latest master from `Telmate/terraform-provider-proxmox`

I'd love to dig myself out of this, but after a day of debugging, I got nowhere with this. Any suggestions?

**Comment by devopsmyth** [comment]
Not sure if this will help but here's my full `main.tf` minus the password and real server name...

```
provider "proxmox" {
  pm_tls_insecure = true
  pm_api_url = "https://server:8006/api2/json"
  pm_password = ""
  pm_user = "terraform@pve"
  pm_otp = ""
  pm_parallel = 4
}

resource "proxmox_vm_qemu" "terraform-test3" {
  name        = "terraform-test3"
  target_node = "server"
  iso        = "ISOs1:iso/terraform-ubuntu-16.04.6-server-amd64.iso"
  desc       = "testing terraform deployment"
  agent      = 1
  memory     = 4096
  cores      = 4
  sockets    = 1
  cpu        = "kvm64"
  os_type    = "ubuntu"
  disk {
    id = "0"
    type = "virtio"
    storage = "virt-farm1"
    storage_type = "nfs"
    size = "16384M"
    format = "qcow2"
    cache = "writeback"
  }
  full_clone = false
  network {
    id       = "0"
    model    = "virtio"
    bridge   = "vmbr1"
    tag      = 110
    firewall = false
  }

  #ssh_forward_ip = "10.0.110.59"
  ssh_user = "terraform"
  ssh_private_key = file("./terraform")

  os_network_config = <<EOF
    auto eth0
    iface eth0 inet dhcp
  EOF

  connection {
    certificate_verify = false
    type        = "ssh"
    user        = self.ssh_user
    private_key = self.ssh_private_key
    host = self.ssh_host
    port = self.ssh_port
  }
} 
```
Obviously you'll want to adjust your ISO, or template that you're deploying. Let me know if this helps.

**Comment by Magentron** [comment]
FWIW: I got this error when using an incorrect `target_node` (in this example `X.X.X.X`) with the corresponding error in `/var/log/daemon.log`:

    Mar 11 16:43:48 pve-lab-01 pveproxy[65990]: '/etc/pve/nodes/X.X.X.X/pve-ssl.pem' does not exist!#012

**Comment by devopsmyth** [comment]
> FWIW: I got this error when using an incorrect `target_node` (in this example `X.X.X.X`) with the corresponding error in `/var/log/daemon.log`:
> 
> ```
> Mar 11 16:43:48 pve-lab-01 pveproxy[65990]: '/etc/pve/nodes/X.X.X.X/pve-ssl.pem' does not exist!#012
> ```

**So you're suggesting it was an incorrect IP address for the PVE node that caused the issue?**

**Comment by Magentron** [comment]
In my case I used an IP address as `target_node` which did not work as the nodes have  names, so if you use the same name as used in the `/etc/pve/nodes` directory it should not be a problem (for me it worked).

E.g. if you have 3 nodes in the cluster: *node-1*, *node-2*, *node-3*, then in `/etc/pve/nodes` you should have 3 directories called the same, use one of them (e.g. *node-2*) as `target_node` and that fixed it for me.

**Comment by donhector** [comment]
I was also getting the `596 tls_process_server_certificate: certificate verify failed, error status:` message when cloning an LXC template. Several Google searches for that error suggested running:

```bash
pvecm updatecerts -force
systemctl restart pvedaemon pveproxy
```

but running it that did not make the problem go away.

Thanks to @Magentron's pointers I realized that I was incorrectly setting `target_node` to my node's FQDN (ie: *pve1.lan*) instead of its actual node name as it appears in the WebUI / Datacenter tree (ie: *pve1*). After fixing that it worked.

**PS:** After re-reading the `target_node` [documentation](https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/lxc#target_node), it actually never mentions host or hostname but **node name**
