### ISSUE TITLE
Please provide binary releases

### ISSUE THREAD

**Issue by esantoro** [Telmate/terraform-provider-proxmox#177]
Hello, 
as of subject it would be very helpful if you could start providing binary releases for the most common operating systems (I'd say linux-x86_64, mac os and windows) via the releases tab.

If you aren't interested, can't or currently don't have the time to do this then maybe I can help with it -- would you consider a PR about this?

**Comment by esantoro** [comment]
Hi, please disregard this issue and my willingness to create PRs.

I've just found out that Telmate profits off the US prison system and I don't want to be affiliated with such things.

**Comment by c33s** [comment]
@esantoro maybe this fork is also of interest for you https://github.com/Telmate/terraform-provider-proxmox/issues/218#issuecomment-696013579
