### ISSUE TITLE
Terraform init never finds proxmox plugin.

### ISSUE THREAD

**Issue by symgryph** [Telmate/terraform-provider-proxmox#18]
I have successfully compiled, and built all executables, but when I do terraform init, it doesn't find the proxmox provider. There are no directions on how to do this manually. Looks like the api is working, and binaries are in appropriate places.

Any idea on how to get the provider initialized in a new git repo?

**Comment by ggongaware** [comment]
This part - 
cp terraform-provider-proxmox $GOPATH/bin
cp terraform-provider-proxmox $GOPATH/bin/terraform-provisioner-proxmox

$GOPATH/bin may not match the path of your terraform. 

You can put the built binary in the same path of `which terraform` or on the path of the current working directory of *.tf template files your working on.

**Comment by symgryph** [comment]
I did the go path thing, they are found when I try to type in manually. I can type in terraform-provider ... finds it fine.

The directions on third party providers mention:


Operating system | User plugins directory
-- | --
Windows | terraform.d\plugins in your user's "Application Data" directory
All other systems | .terraform.d/plugins in your user's home directory

**Comment by symgryph** [comment]
Answered my question. You need to copy them to .terraform.d/plugins in your homer.

**Comment by symgryph** [comment]
Want me to make a markdown document for this?

**Comment by ggongaware** [comment]
sure, go head

**Comment by symgryph** [comment]
See pull request.
