### ISSUE TITLE
Multiple LXC networks

### ISSUE THREAD

**Issue by shuaibmunshi** [Telmate/terraform-provider-proxmox#182]
The following code doesn't work, it gives me a parameter verification error. Is there a different method of creating a second network? I tried making network a map but that didn't work either. 

```
   network {
        name = "eth0"
        bridge = "vmbr0"
        ip = "dhcp"
        ip6 = "dhcp"
    }
    network {
        name = "eth1"
        bridge = "vmbr1"
        ip = "dhcp"
        ip6 = "dhcp"
    }
```

**Comment by GamerBene19** [comment]
@shuaibmunshi I don't know if you still encounter this issue (if you don't I think it should be closed)

If you do:
 - Do you even have a `vmbr1` interface?
 - If you do and still encounter this issue you might want to [turn on logging](https://github.com/Telmate/terraform-provider-proxmox/issues/455#issuecomment-984324159) to see what causes the error.
