### ISSUE TITLE
Allow VMs without ISO and Clone

### ISSUE THREAD

**Issue by jonkerj** [Telmate/terraform-provider-proxmox#185]
I am trying to PXE-boot VMs on PVE using this Terraform provider. It seems I have to either specify `iso` or `clone`, otherwise I'm greeted with a message explaining I did not specify them. I can work around it by setting `iso = "none"`, of course. It would be nice if either this check is turned into a warning, or the workaround is documented.

**Comment by mcd1992** [comment]
Issue seems resolved by #495 and #492
