### ISSUE TITLE
Terraform Crash: interface conversion - interface {} is float64, not bool

### ISSUE THREAD

**Issue by jdebetaz** [Telmate/terraform-provider-proxmox#189]
Hi,

I'm tring to deploy a VM, but after a moment Terraform is crashing.

**Proxmox version:** 6.2-4
**Terraform -v output:** 
```
Terraform v0.12.28
+ provider.proxmox (unversioned)
```

**The config file:** 
https://hastebin.com/atigehohel

**The stacktrace:**
https://hastebin.com/acelodosih

Kind regards 😄

**Comment by MiguelNdeCarvalho** [comment]
Hey, 
I am having exactly the same problem. Did you find a fix for it?

Thanks,
MigueldeCarvalho

**Comment by jdebetaz** [comment]
Yes, i followed the [installation instructions](https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/installation.md).

**Comment by MiguelNdeCarvalho** [comment]
Thanks, it fixed :+1:

**Comment by johnpc35** [comment]
There was a bug in a recent version of the Proxmox API Go package used by this provider. Doing a `go get` or a `go install` was probably grabbing the recent version with the bug. Doing a `make` used the version specified in `go.mod` which was older.

Both the API package and this provider are now fixed, if you want to try and download/install again.
