### ISSUE TITLE
Custom Cloud-Init Network Interfaces

### ISSUE THREAD

**Issue by RickyGrade10** [Telmate/terraform-provider-proxmox#194]
Hello,

When I use the `cloud-init ipconfig0` setting to set my desired IP address, my network interface in my `50-cloud-init.cfg` is set to `eth0`. I would like to set it to 

```
auto ens18
iface ens18 inet static
```

instead of the following.

```
auto eth0
iface eth0 inet static
```
Is there any way to do this through the provider settings?

Thank you for your time.

**Comment by valentin2105** [comment]
You should check the UDEV rules that rename ens18 in eth0. (/etc/udev.d)

**Comment by RickyGrade10** [comment]
@valentin2105 Thank you for replying.

This file `/etc/udev/rules.d/70-persistent-net.rules` is the only file in this directory for me. It seems to be created by `cloud-init`. Which means that I would have to go into my Proxmox VM and modify it after creation right?

Do you know of any way to set my network interface to `ens18` on the `terraform-proxmox-provider` settings? Or during provisioning? I will have to do this to multiple VMs and I would like the VMs in the future to have the same setup automatically.

Thanks for your time!

**Comment by valentin2105** [comment]
@RickyGrade10 When you create your VM, it's cloud-init that put the `udev/rules.d` file to rename `ens18` to `eth0`. 
If you want to disable this "effect", you should check on your template VM, on the file `/etc/cloud/cloud.cfg` to disable this cloud-init behavior. (should be network-rename or something like that).

**Comment by Mithiiran05** [comment]
Hello, I would like to ask if the issue was resolved as I am trying to do something similar too.
