### ISSUE TITLE
Terraform crash during apply

### ISSUE THREAD

**Issue by ccameron** [Telmate/terraform-provider-proxmox#2]
Hi,

I had a crash that I was hoping for help on correcting:

panic: interface conversion: interface {} is nil, not string
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox:
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: goroutine 87 [running]:
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc420379838, 0xc4201867c0, 0x0, 0xc42005d838, 0xc4201867c0)
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: 	/golang/src/github.com/Telmate/proxmox-api-go/proxmox/config_qemu.go:151 +0x8ca
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.prepareDiskSize(0xc4201867c0, 0xc420379838, 0x4034000000000000, 0xa, 0x400)
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: 	/golang/src/github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:335 +0x3f
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc42001c690, 0x1625f40, 0xc420258020, 0x0, 0x0)
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: 	/golang/src/github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:177 +0x1854
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4202fbc80, 0xc420484050, 0xc42042a840, 0x1625f40, 0xc420258020, 0x1, 0x28, 0xc420160f90)
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: /golang/src/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x48d
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc420122230, 0xc420484000, 0xc420484050, 0xc42042a840, 0x1c79000, 0x0, 0x0)
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: /golang/src/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0x9b
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4202dc640, 0xc42042a0a0, 0xc42055dd30, 0x0, 0x0)
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: 	/golang/src/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: reflect.Value.call(0xc420248e40, 0xc4201e8ad8, 0x13, 0x17474da, 0x4, 0xc42023bf20, 0x3, 0x3, 0x0, 0x0, ...)
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: 	/usr/local/opt/go/libexec/src/reflect/value.go:434 +0x91f
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: reflect.Value.Call(0xc420248e40, 0xc4201e8ad8, 0x13, 0xc42022e720, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: 	/usr/local/opt/go/libexec/src/reflect/value.go:302 +0xa4
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: net/rpc.(*service).call(0xc4200cfe00, 0xc4200cfdc0, 0xc420124ae0, 0xc420218b80, 0xc4202b0b80, 0x16267c0, 0xc42042a0a0, 0x16, 0x1626800, 0xc42055dd30, ...)
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: 	/usr/local/opt/go/libexec/src/net/rpc/server.go:387 +0x144
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: created by net/rpc.(*Server).ServeCodec
2017/07/18 22:37:36 [DEBUG] plugin: terraform-provider-proxmox: 	/usr/local/opt/go/libexec/src/net/rpc/server.go:481 +0x404
2017/07/18 22:37:36 [DEBUG] root: eval: *terraform.EvalWriteState
2017/07/18 22:37:36 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/07/18 22:37:36 [DEBUG] root: eval: *terraform.EvalIf
2017/07/18 22:37:36 [DEBUG] root: eval: *terraform.EvalWriteState
2017/07/18 22:37:36 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/07/18 22:37:36 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/07/18 22:37:36 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* proxmox_vm_qemu.test: unexpected EOF
2017/07/18 22:37:36 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* proxmox_vm_qemu.test: unexpected EOF
2017/07/18 22:37:36 [TRACE] [walkApply] Exiting eval tree: proxmox_vm_qemu.test
2017/07/18 22:37:36 [DEBUG] dag/walk: upstream errored, not walking "provisioner.remote-exec (close)"
2017/07/18 22:37:36 [DEBUG] dag/walk: upstream errored, not walking "provisioner.proxmox (close)"
2017/07/18 22:37:36 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/07/18 22:37:36 [DEBUG] dag/walk: upstream errored, not walking "provider.proxmox (close)"
2017/07/18 22:37:36 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/07/18 22:37:36 [TRACE] Preserving existing state lineage "198b707a-00de-4156-b7a0-0f92f2ae3cf6"
2017/07/18 22:37:36 [DEBUG] plugin:/golang/bin/terraform-provider-proxmox: plugin process exited
2017/07/18 22:37:36 [TRACE] Preserving existing state lineage "198b707a-00de-4156-b7a0-0f92f2ae3cf6"
2017/07/18 22:37:36 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/07/18 22:37:36 [WARN] plugin: error closing client during Kill: connection is shut down
2017/07/18 22:37:36 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2017/07/18 22:37:36 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/07/18 22:37:36 [DEBUG] plugin:/golang/bin/terraform-provisioner-proxmox: plugin process exited
2017/07/18 22:37:36 [DEBUG] plugin:/golang/bin/terraform: plugin process exited

**Comment by ggongaware** [comment]
In this case, it looks like an existing node called "test" doesn't have a storage type "virtualio"
Currently virtualio (instead of IDE or SATA) is the only support storage for this plugin. I'm going to add some better error messaging to proxmox-api-go project

**Comment by ccameron** [comment]
That was it, I switched the storage and network interface to virtio and that fixed it. Thanks!
