### ISSUE TITLE
Error : Error: no provider exists with the given name

### ISSUE THREAD

**Issue by Givictor** [Telmate/terraform-provider-proxmox#200]
Hi ..
I am new to terraform. .I created some resources in cloud using azurerm and the provider has been installed Its been working earlier and suddenly facing the below error.

Provider "web" not available for installation.
A provider named "web" could not be found in the Terraform Registry.

Not sure what it means and why web provider is needed which is nothing related to my code  . My doubt is just because  by resources name starts with 'web', is it prompting me to install the web provider?

terraform providers
.
├── provider.azurerm 2.2.0
└── provider.web

Sample for my main.tf code:

provider "azurerm"{
  version = "2.2.0"
  features {}
}

resource "azurerm_resource_group" "new_webrg" {
  name     = var.web-server-rg
  location = var.web-server-loc
}

Some one help me please ...kindly provide solution ..I am using windows 10

**Comment by Shackelford-Arden** [comment]
@Givictor Hey man! Kinda looks like you're working with the Azure Terraform Provider. I'd recommend you create an issue in their specific repository, which can be found here:

https://github.com/terraform-providers/terraform-provider-azurerm

This repository is specifically for Proxmox. Are you intending to use Proxmox or Azure? :)

**Comment by Givictor** [comment]
Hi Arden, 
Thanks for your response. I have found the mistake i did and resolved it...Thanks for your suggestion so i can create an issue in the specific repository in future if needed.
Thanks again.
