### ISSUE TITLE
Golang  Error : not enough arguments in call to proxmox.NewClient 

### ISSUE THREAD

**Issue by AlexFatta** [Telmate/terraform-provider-proxmox#202]
Hi guys! 

I'm new with Golang and I'm trying to install Terraform Provider Proxmox on my systems. I'm following two tutorials but I have the same error for each. I tried on MacOS X and on Windows 10, but it's the same error, at the same step of the installation 

`axel@macbook-pro ~ % go get -v github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox
github.com/Telmate/terraform-provider-proxmox/proxmox
# github.com/Telmate/terraform-provider-proxmox/proxmox
go/src/github.com/Telmate/terraform-provider-proxmox/proxmox/provider.go:108:30: not enough arguments in call to proxmox.NewClient
	have (string, nil, *tls.Config)
	want (string, *http.Client, *tls.Config, int)`

I'm following these tutorials : 

- https://notamax.be/proxmox-v6-cluster-k8s-kubeadm-via-terraform-cloud-init/
- https://norocketscience.at/provision-proxmox-virtual-machines-with-terraform/

I search this error on internet but I did'nt find anything useful. Can someone help please ? 

Thank u guys, have a nice day. Sorry for my bad english,

AlexFatta

**Comment by Shackelford-Arden** [comment]
I was able to recreate the issue you reported, but then I walked through the installation instructions here:

https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/installation.md

This successfully installed for me.

**Comment by AlexFatta** [comment]
Okey I see. It's working for me, thank you very much!!
