### ISSUE TITLE
EOF Make terraform crash

### ISSUE THREAD

**Issue by AlexFatta** [Telmate/terraform-provider-proxmox#205]
Hi guys!

I just wrote a terraform script with a EOF inside of it. For an unknown reason, this EOF make terraform crashed. I really don't now why. Let me explain what am I trying to do.

On my proxmox installation, I can't use the line ipconfig0 = "parameters". I have to edit the /etc/network/interfaces file to have an internet access. This is my script and my crash.log.

`#### Définition de l'hôte ####

provider "proxmox" {
    pm_api_url = "url"
    pm_user = "admin@pam"
    pm_password = "pass"
    # Laisser à "true" si certificat auto-signé
    pm_tls_insecure = "true"
}

#### Variables de machines ####

variable "name" {
  type = string
}

variable "memory" {
  type = number
}

variable "macaddress" {
  type = string
}

variable "ipaddress" {
  type = string
}

variable "vmid" {
  type = number
}

variable "gateway" {
  type = string
}

# Définition de la VM à créer
resource "proxmox_vm_qemu" "node-DC-VM" {
  count             = 1
  name              = var.name
  # Nom du node sur lequel le déploiement aura lieu
  target_node       = "node"
  clone             = "debian-10-template"
  full_clone        = true
  os_type           = "cloud-init"
  cores             = 2
  sockets           = "1"
  cpu               = "host"
  memory            = var.memory
  scsihw            = "virtio-scsi-pci"
  bootdisk          = "scsi0"
  vmid              = var.vmid
  os_network_config =  <<EOF
auto eth0
iface eth0 inet static
        address ${var.ipaddress}
        netmask 255.255.255.255
        post-up route add ${var.gateway} dev eth0
        post-up route add default via ${var.gateway} dev eth0
        pre-down route del ${var.gateway} dev eth0
        pre-down route del default via ${var.gateway} dev eth0
EOF
  
  disk {
    id              = 0
    size            = 20
    type            = "scsi"
    storage         = "local"
    #storage_type    = "lvm"
    iothread        = true
  }
  network {
    id              = 0
    model           = "virtio"
    bridge          = "vmbr0"
    firewall        = true
    macaddr         = var.macaddress
  }

  sshkeys = "MYSSH KEY"

  ciuser = "user"
  cipassword = "somePassword"

  # Setup de l'IP statique
  #ipconfig0 = "ip=${var.ipaddress}/32,gw=51.91.35.254"

# Configuration relative à CloudInit
  
  # Déclaration du script de démarrage, en utilisant user + clé SSH privée

  provisioner "file" {
    source      = "./startup.sh"
    destination = "/tmp/startup.sh"
      connection {
      type     = "ssh"
      user     = "axeltricaud"
      private_key     = "${file("./proxmox_rsa")}"
      host     = var.ipaddress
   }
  }
  # Exécution du script de démarrage
  provisioner "remote-exec" {
    inline = [
      "chmod +x /tmp/startup.sh",
      "/tmp/startup.sh ${var.ipaddress} ${var.macaddress}",
    ]
    connection {
      type     = "ssh"
      user     = "user"
      private_key     = "${file("./proxmox_rsa")}"
      host     = var.ipaddress
   }
  }
}`

Crash.log : https://pastebin.com/yp2n20qt

Thanks to everyone ! 

Axel

**Comment by AlexFatta** [comment]
Problem fixed just with the line ipconfig0!

**Comment by donggoing** [comment]
> Problem fixed just with the line ipconfig0!

But if i need to use the os_network_config rather than ipconfig0, how can i make it?
