### ISSUE TITLE
Custom Cloud Init files not working with Flatcar Linux

### ISSUE THREAD

**Issue by zimmertr** [Telmate/terraform-provider-proxmox#208]
I'm trying to deploy [Flatcar][3] linux virtual machines using [Cloud Init][4] by passing files via [cicustom][5]. Based on the [example here][6], I have crafted the following Terraform file:

    variable "pve_user" {
    }
    variable "pve_password" {
    }
    variable "pve_host" {
    }
    
    provider "proxmox" {
      pm_tls_insecure = true
      pm_api_url      = "https://SNIP/api2/json"
      pm_user         = "SNIP"
      pm_password     = "SNIP"
      pm_parallel     = 4
    }
    
    resource "null_resource" "cloud_init_config_files" {
      connection {
        type     = "ssh"
        user     = var.pve_user
        password = var.pve_password
        host     = var.pve_host
      }
    
      provisioner "file" {
        source      = "./templates/cloud-config.yml"
        destination = "/var/lib/vz/snippets/cloud-config.yml"
      }
    }
    
    resource "proxmox_vm_qemu" "k8s-masters" {
      depends_on = [
        null_resource.cloud_init_config_files
      ]
    
      count      = 1
      name       = "VM-${count.index}"
      clone      = "VM-Template"
      full_clone = true
    
      target_node = "192.168.20.10"
      pool        = "VM"
    
      cores   = 2
      sockets = 1
      memory  = 10240
    
      network {
        id     = 0
        model  = "virtio"
        bridge = "vmbr0"
        tag    = 50
      }
    
      disk {
        id           = 0
        type         = "scsi"
        size         = 30
        storage      = "Pool"
        storage_type = "zfspool"
        backup       = true
        iothread     = true
      }
    
      onboot = true
      agent  = 1
    
      os_type         = "cloud-init"
      ssh_user        = "core"
      cicustom  = "user=local:snippets/cloud-config.yml"
      ipconfig0 = "ip=192.168.50.10/24,gw=192.168.50.1"

      sshkeys = "ssh-rsa SNIP"
      ssh_private_key = <<EOF
    -----BEGIN RSA PRIVATE KEY-----
    SNIP
    -----END RSA PRIVATE KEY-----
    EOF
    }

After running `terraform apply`, the VM is successfully created and Flatcar is bootstrapped. If you connect to the console via Proxmox, however, the VM shows that the IP Address is one received via DHCP instead of the one I provided. Furthermore, the SSH key does not work so I am unable to connect to the VM to troubleshoot. 

If I comment out the `cicustom` line, and simply rely on `ipconfig0` and the other normal options, the VM comes up and my SSH key does in fact work. However, the specified IP address is still not used; the VM just uses one provided by DHCP instead. Despite being able to access the VM, I still want to use a custom Cloud Init config file so I can have access to more powerful configuration options.

I've tried various combinations of my `cloud-config.yml` file. Including things as simple as:

    hostname: test

to things more detailed like:

    storage:
      files:
        - path: /opt/file1
          filesystem: root
          contents:
            inline: Hello, world!
          mode: 0644
          user:
            id: 500
          group:
            id: 501
    passwd:
      users:
        - name: core
          ssh_authorized_keys:
            - ssh-rsa SNIP

Despite all of this, my SSH keys never work after I pass something to `cicustom` and, based on the fact that the hostname is never manipulated, I'm assuming Cloud Init just outright isn't receiving the custom config file at all. I've tried passing in both [Ignition and Container Linux Config][7] formatted files. 

Is Flatcar Linux broken with Proxmox/cicustom?  Is the bug introduced by this provider? Searching Google for things like `"flatcar" "proxmox"`, `"coreos" "proxmox"`, `"container linux" "proxmox"`, `"flatcar" "cicustom"`, etc don't seem to turn up much results. I guess there aren't a lot of people out there bridging Cloud Native operating systems with bare metal? hehehe

What does come up, however, is [this interesting script][8]. Lines 104-132 discuss creating a Flatcar/CoreOS template for Proxmox. So someone else has done this before, at least? Who knows if they passed in a custom cloud init config file afterwards? 

Any ideas? 

  [1]: https://github.com/Telmate/terraform-provider-proxmox
  [2]: https://proxmox.com/en/
  [3]: https://www.flatcar-linux.org/
  [4]: https://cloudinit.readthedocs.io/en/latest/
  [5]: https://pve.proxmox.com/wiki/Cloud-Init_Support
  [6]: https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/cloud_init_guide.md
  [7]: https://docs.flatcar-linux.org/os/provisioning/
  [8]: https://gist.github.com/chriswayg/43fbea910e024cbe608d7dcb12cb8466

**Comment by zimmertr** [comment]
Relevant links:

Script mentioning this issue: https://gist.github.com/chriswayg/43fbea910e024cbe608d7dcb12cb8466#file-create-cloud-template-sh-L107

ServerFault post: https://serverfault.com/questions/1030291/cloud-init-with-flatcar-linux-configuration-not-applying-when-passing-custom

**Comment by zimmertr** [comment]
These `qm` commands produce a working Flatcar VM using `cicustom`. 

```bash
qm create 101 --name test --cores 2 --memory 2048 --net0 "virtio,bridge=vmbr0"

qm set 101 --net0 "virtio,bridge=vmbr0,tag=50"

qm importdisk 101 /mnt/RAIDPool_Templates/template/iso/flatcar_production_qemu_image.img FlashPool

qm set 101 --scsihw virtio-scsi-pci --scsi0 FlashPool:vm-101-disk-0 --ide2 FlashPool:cloudinit --boot c --bootdisk scsi0 --serial0 /dev/tty0 --ipconfig0 ip=dhcp --citype configdrive2

qm set 101 --cicustom user=RAIDPool_Templates:snippets/user-data.yml

qm start 101
ssh -i ~/.ssh/sol.milkyway.kubernetes core@192.168.50.219
```

**user-data.yml:**
```bash
#cloud-config
hostname: test
manage_etc_hosts: true
ssh_authorized_keys:
  - ssh-rsa REDACTED
chpasswd:
  expire: False
users:
  - default
package_upgrade: true
```

Passing the same `user-data.yml` to `cicustom` within the `proxmox_vm_qemu` resource doesn't seem to be working though.

**Comment by h-wb** [comment]
I'm having the same issue with an Ubuntu image. Cicustom just won't work, I don't know if i'm doing something wrong. Does someone actually manage to get it working (I can't really find anything on the web except this issue) ? Did it work maybe in previous versions of proxmox and not now ?

**Comment by zimmertr** [comment]
Debian works for me. Here is an example.

https://github.com/zimmertr/TKS-Bootstrap_Kubernetes

**Comment by h-wb** [comment]
I was actually thinking of using your repo, it’s really great ! Can’t wait for the ArgoCD part !

It works because you use the `qm set cicustom` via ansible rigth ? Because I was using the cicustom option in the terraform file, and I can’t get it to work ! 
I was only using terraform but I really like your solution with ansible, I’ll try it. I’m kinda new to this so it’s still a bit confusing where I should use ansible and where I should use terraform.

**Comment by zimmertr** [comment]
[This project](https://github.com/zimmertr/Bootstrap-Kubernetes-with-QEMU) uses pure Ansible to deploy VMs (Kubernetes) to Proxmox. [Here](https://github.com/zimmertr/Bootstrap-Kubernetes-with-QEMU/blob/master/playbooks/main/deploy_qcow2_vms.yml) is the gist of it. 

The project I just linked uses Ansible to build a template, and Terraform to deploy VMs from it. You're right though, `cicustom` is passed in during the [template-building](https://github.com/zimmertr/TKS-Bootstrap_Kubernetes/blob/3322f0174f803f1f344ea088f6a8b911b55591b6/Ansible/roles/Create_Template/tasks/main.yml#L48) stage and not during the [VM deployment](https://github.com/zimmertr/TKS-Bootstrap_Kubernetes/blob/3322f0174f803f1f344ea088f6a8b911b55591b6/Terraform/k8s_control_plane.tf#L38) stage. 

After that, I use a combination of `file` and `remote-exec` provisioners to further configure VMs post-deployment. 

With respect to Terraform and Ansible, I think they compliment each other well and there's no reason to only use one or the other. Ansible is purpose-built for configuration and Terraform is purpose-built for deployment. But you can deploy with Ansible modules and configure with Terraform provisioners.

A common pattern I see, is using Ansible to build a template, AMI, etc. And then using Terraform to deploy from that template. Following that, if you need to perform simple tweaks to the template, use a Bash script executed with a `remote-exec` provisioner. If you're applying more complicated configurations, however, you can simply install & execute Ansible on the guest using a `remote-exec` Terraform provisioner.

**Comment by glitchcrab** [comment]
I appreciate that this is quite an old issue now, but I'm not sure if you're aware that there is now an (undocumented) fix which I've just tested and it works. 

I spotted this commit https://github.com/Telmate/terraform-provider-proxmox/commit/217cbfd5a7b87a068f47855ceeb069c353a8a517 and with the following config I brought up an instance which has the correct hostname configured by CI:

```
  os_type                 = "cloud-init"
  cicustom                = "user=local:snippets/${local.hostname}.yml"
  cloudinit_cdrom_storage = "local-lvm"
```

```
$ cat snippets/terraform-test.domain.com.yml
#cloud-config
hostname: terraform-test.domain.com
```

**Comment by roninhockley** [comment]
I'm curious how the flatcar/terraform/cloud-init is going now. Flatcar says on their website that it can still use cloud-init, but also heavily favors ignition. I am running a terraform install on proxmox now, but unable to get it to use the cloud-init file, even with the necessary _cloudinit_cdrom_storage_ parameter in place.

**Comment by roninhockley** [comment]
I really wish the proxmox provider would support ignition, but dont see that it does yet.

**Comment by roninhockley** [comment]
> coreos-cloudinit is no longer under active development

Yea I'd say that is my answer...:)

**Comment by roninhockley** [comment]
Success. It CAN be done. With a little help from the --args parameter in the VM config file on proxmox. 
With that little trick that I got from [here](https://discussion.fedoraproject.org/t/coreos-on-proxmox/26714/3), the Proxmox VM will pick up the ignition file.
