### ISSUE TITLE
Need help with documenting a way to write terraform main.tf?

### ISSUE THREAD

**Issue by symgryph** [Telmate/terraform-provider-proxmox#21]
I did try using the default terraform scripts, but admit that I am a bit perplexed how to customize them and make them useful. 

I would be willing to work with someone on writing a comprehensive doc on how to customize .tf templates to various scenarios.

For my first one, I just want to 'clone' an existing cloud-init template I have created, choose the username to login to, and have n number of them.

I find the sections about the 'root' user private key confusing. Why do we use this? How do we just 'provision' vanilla vm that is a copy of something I have created with some cloud-init paramaters?

Same with the 'ssh forwarding' which seems opaque. Again I will happily write a doc so you never have to answer these again, just RTFM line.

Thomas

**Comment by symgryph** [comment]
I also just use DHCP and don't want to assign IP addresses.

**Comment by ggongaware** [comment]
Terraform provides some provisioners for the next step after the VM is created. All my use cases remote in via ssh and run shell commands or run chef.

To be able to ssh in, you need a predictable host address.

DHCP with cloud-init works well assuming no followup provisioning via terraform.

You can probably put dummy stuff in the ssh settings.

**Comment by symgryph** [comment]
One thing I do is use dhcp autoregister hostname, so IP would be unecessary, just use hostname from dns server. Also can't the provider query proxmox for appropriate IP ala aws? Or is that not part of the provider?

**Comment by ggongaware** [comment]
In your case, put your hostname in the ssh_forward_ip attribute, and the rest of the provisioners should work.

I haven't found any builtin proxmox / qemu utilities for discovering the assigned IP.

**Comment by cfarquhar** [comment]
FWIW, it looks like IPs are now available via the API:

```
$ ./proxmox-api-go --insecure getNetworkInterfaces 128 | jq '.[] | select(.Name == "eth0") | .IPAddresses'
[
  "192.168.115.22",
  "fe80::347a:30ff:fe41:aad4"
]
```
