### ISSUE TITLE
Need ways to automatically assign static and dynamic (dhcp) address to VM during creation using terraform script

### ISSUE THREAD

**Issue by sameermahajan-a10** [Telmate/terraform-provider-proxmox#212]
I want to create a VM using proxmox terraform script and assign it a static and (dhcp based) dynamic (in another execution) address to it automatically during script execution. Can you please let me know how to do it or provide a sample script for the same?

When I try what is given in https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/resource_vm_qemu.md I get an error of:

Error: "preprovision": conflicts with ssh_forward_ip

When I came across still open issue of: https://github.com/Telmate/terraform-provider-proxmox/issues/165

Hence I tried without

  preprovision = true

when my os network configuration gets ignored which is something like:

 os_network_config = <<EOF
DEVICE=eth0
BOOTPROTO=static
ONBOOT=yes
NETMASK=255.255.255.0
IPADDR=<my ip address>
GATEWAY=<my gateway>
DNS1=8.8.8.8
EOF

**Comment by sameermahajan-a10** [comment]
I had to remove 

preprovision = true

My configuration was getting ignored probably because my ssh key pair was not setup properly. After setting it up appropriately, it worked fine.

**Comment by ravecat** [comment]
@sameermahajan-a10 did you solve this issue?

Could you explain or shared your tf-config. My VM based on cloud-init template doesn't receive IP address. Maybe we have similar root of problem.
