### ISSUE TITLE
How to get rid of manually deleted vm from tfstate?

### ISSUE THREAD

**Issue by alexd88** [Telmate/terraform-provider-proxmox#215]
Hi!

I created a vm by means of terraform, then this vm was deleted manually through proxmox interface. After that it got impossible to do anything: all the time i get the same error "Vm 'xxx' not found". "terraform plan" and "terraform delete" operations fail with this error. 

What should be done to fix this problem?
Proxmox provider doesn't try to recreate it, and this behavior is a bit confusing imho. 

Terraform version v0.12.29

Need your assistance.

**Comment by ayshfm1** [comment]
Also had this.  

I had a backup of the original terraform.tfstate file so I copied that over (backed up the borked one as well), then did a destroy which worked fine.

Your's may be a little different, version etc.

ansible@ansible:~/terraform$ more terraform.tfstate.orig
{
  "version": 4,
  "terraform_version": "0.13.2",
  "serial": 11,
  "lineage": "2ff57cab-c334-d496-5578-8547e9fe39e3",
  "outputs": {},
  "resources": []
}

Not ideal though.

**Comment by alexd88** [comment]
@ayshfm1 yes, it will work if a manually deleted vm is absent in the backup file. But what if the tfstate backup file contains info of a deleted vm. I mean this trick won't work in such case.

I think i've found the workaround. It's a ```terraform state rm``` command. Manually deleted item can just be removed from tfstate file. But it would be nice ```terraform plan``` command shows us the difference between the state file and infrastructure.
