### ISSUE TITLE
Install against Terraform 13.0.2

### ISSUE THREAD

**Issue by ayshfm1** [Telmate/terraform-provider-proxmox#218]
Documentation on installation against latest terraform doesn't work.   terraform init fails it can't find the provider

Needed to define a version (I made one up) and add to path

versions.tf - note verson 1.0.0

terraform {
  required_providers {
    proxmox = {
      source  = "telmate/proxmox"
      version = "1.0.0"
    }
  }
}

Path now includes 1.0.0

ansible@ansible:~/.terraform.d/plugins/registry.terraform.io/telmate/proxmox/1.0.0/linux_amd64$

**Comment by morey-tech** [comment]
Some related content from Hashicorp on this.

- [Related blog post](https://www.hashicorp.com/blog/automatic-installation-of-third-party-providers-with-terraform-0-13), specifically under the "Third-party Providers" heading.
- [Related tutorial](https://learn.hashicorp.com/tutorials/terraform/provider-use#install-hashicups-provider) about installing a third-party provider.

**Comment by ondrejsika** [comment]
I've fixed for me. I've forked provider & published to Terraform registry.

You can use:

```tf
terraform {
  required_providers {
    proxmox = {
      source = "ondrejsika/proxmox"
      version = "2020.9.21"
    }
  }
}

provider "proxmox" {
  # Configuration options
}
```

I publish upstream master every day with tag like `2020.9.21`.

I try to merge my changes to upstream & I can also help you (mainteinere) with the publishing on Terraform Registry

**Comment by c33s** [comment]
quicklinks: 
- https://github.com/ondrejsika/terraform-provider-proxmox
- https://registry.terraform.io/providers/ondrejsika/proxmox/latest

**Comment by zinefer** [comment]
Thanks both @ondrejsika and @c33s - You guys got me up an running again.

**Comment by stefanvangastel** [comment]
> I've fixed for me. I've forked provider & published to Terraform registry.
> 
> You can use:
> 
> ```terraform
> terraform {
>   required_providers {
>     proxmox = {
>       source = "ondrejsika/proxmox"
>       version = "2020.9.21"
>     }
>   }
> }
> 
> provider "proxmox" {
>   # Configuration options
> }
> ```
> 
> I publish upstream master every day with tag like `2020.9.21`.
> 
> I try to merge my changes to upstream & I can also help you (mainteinere) with the publishing on Terraform Registry

@ondrejsika Do you have more recent builds? Latest I can find is `2020.9.21`
