### ISSUE TITLE
Support for network APIs.

### ISSUE THREAD

**Issue by devendra-bhatt-a10** [Telmate/terraform-provider-proxmox#219]
Hi team, 
I see in provider.go the comment says bridge resource is in todo, can someone please let me know if someone is working over that resource and if yes then till when shell we expect it comming?
.

**Comment by mleone87** [comment]
This needs works primary on the proxmox-api project before implementing it to proxmox terraform project

**Comment by devendra-bhatt-a10** [comment]
So you mean this API is still in progress? - https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/network

**Comment by mleone87** [comment]
No, what I mean is that this project, the terraform provider for proxmox, is based(uses) the proxmox-api-go project (https://github.com/Telmate/proxmox-api-go) from the same developer.

The api coverge in proxmox-api-go project is still limited and the project in general is a WIP 

So there are two possibilities:
- the developer implements networking support in proxmox-api-go and there
- someone else do the same
- mix of the above
