### ISSUE TITLE
Invite to Publish to the Terraform Registry

### ISSUE THREAD

**Issue by aicarmic** [Telmate/terraform-provider-proxmox#228]
👋  Hi there! We noticed this provider is on our list of community providers, however it has not yet been published to the newly-released Terraform Registry for Providers (registry.terraform.io). We'd like to invite you to get it published. Instructions for doing so are available [here](https://www.terraform.io/docs/registry/providers/publishing.html). Please note that we will soon be redirecting the [community listing page](https://www.terraform.io/docs/providers/type/community-index.html) to registry.terraform.io.

Thanks for your contributions and we look forward to seeing the Proxmox provider listed soon!

Thanks,
Team Terraform @ HashiCorp

**Comment by ggongaware** [comment]
Looks like @ondrejsika published a fork already. I'll take some time in the next could days to publish one too.

**Comment by doransmestad** [comment]
@ggongaware  did you have any luck here?   If there is a way I can help here please let me know, I think it would be great if this is published in the registry.

**Comment by ggongaware** [comment]
Working on the release actions today...

**Comment by stefanvangastel** [comment]
@ggongaware that would be awesome!! Started using this plugin this week and love it. If some of the open issues could be resolved and auto publishing/building could be realized (not a Go person so building is complex for me) that would be fantastic.

Keep up the good work!

**Comment by ggongaware** [comment]
Published! https://registry.terraform.io/providers/Telmate/proxmox/latest
