### ISSUE TITLE
[Q/A] missing vm - recreation error...

### ISSUE THREAD

**Issue by replay111** [Telmate/terraform-provider-proxmox#234]
Hi,

I've deleted host on proxmox and I was trying to run ```terraform apply``` - but I was given an error:

```
proxmox_vm_qemu.master: Refreshing state... [id=pve/qemu/102]
proxmox_vm_qemu.node[1]: Refreshing state... [id=pve/qemu/104]
proxmox_vm_qemu.node[0]: Refreshing state... [id=pve/qemu/103]

Error: Vm '104' not found
```

which is fine, but when I did similar action on MS Azure - the missing machines were recreated... is this some feature of plugin or feature of cloud provider? Can such a behavior be implemented in this provider/provisioner (if this is something than can be done on this part of terraform architecture).

**Comment by doransmestad** [comment]
Hey @replay111 -  I _think_ with the latest changes to master merged today, this should be resolved.  I believe it was related to how the state was updated prior to a machine update.  It should now detect the machine is missing and propose a plan to re-create it.  If it still doesn't work for you though, please let us know!

**Comment by ycote88** [comment]
Still hapenning. any update

**Comment by thigg** [comment]
Got the same issue I think
```
Plan: 0 to add, 9 to change, 1 to destroy.
╷
│ Error: vm '4099' not found
│
│   with proxmox_lxc.terraform_test["9"],
│   on main.tf line 38, in resource "proxmox_lxc" "terraform_test":
│   38: resource "proxmox_lxc" "terraform_test" {
