### ISSUE TITLE
Provider crash when cloning a VM template is completed

### ISSUE THREAD

**Issue by fguiet** [Telmate/terraform-provider-proxmox#235]
Hi,

I am trying to use Terraform Proxmox provider to create a VM from a cloutinit ready template I created with `Packer`.

Below some piece of information about versions I am using :

* Proxmox v 6.2-4

```bash
[root@localhost proxmox]# terraform --version
Terraform v0.13.5
+ provider registry.example.com/telmate/proxmox v1.0.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

When I enter the command : `terraform apply --auto-approve`

This is what I obtain:

```bash
proxmox_vm_qemu.vm-test-fred-01: Creating...
proxmox_vm_qemu.vm-test-fred-01: Still creating... [10s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [20s elapsed]

Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: index out of range [1] with length 0

...
...
```

At the end....the VM appears to be created on PVE Web interface.
It is always crashing when the VM goes from "running" state to "stopped" state (even if in the interface newly created VM is up and running...)

See

```bash
2020-11-01T17:36:07.547+0100 [DEBUG] plugin.terraform-provider-proxmox: {"data":{"node":"pve","type":"qmstart","pid":18471,"id":"102","status":"**running**","starttime":1604
248567,"user":"terraform@pve","upid":"UPID:pve:00004827:0096803A:5F9EE3F7:qmstart:102:terraform@pve:","pstart":9863226}}
2020-11-01T17:36:09.547+0100 [DEBUG] plugin.terraform-provider-proxmox: 2020/11/01 17:36:09 >>>>>>>>>> REQUEST:
2020-11-01T17:36:09.547+0100 [DEBUG] plugin.terraform-provider-proxmox: GET /api2/json/nodes/pve/tasks/UPID:pve:00004827:0096803A:5F9EE3F7:qmstart:102:terraform@pve:/sta
tus HTTP/1.1
2020-11-01T17:36:09.547+0100 [DEBUG] plugin.terraform-provider-proxmox: Host: pve.guiet.lan:8006
2020-11-01T17:36:09.547+0100 [DEBUG] plugin.terraform-provider-proxmox: User-Agent: Go-http-client/1.1
2020-11-01T17:36:09.547+0100 [DEBUG] plugin.terraform-provider-proxmox: Accept: application/json
2020-11-01T17:36:09.547+0100 [DEBUG] plugin.terraform-provider-proxmox: Cookie: PVEAuthCookie=PVE:terraform@pve:5F9EE3E1::UTfYPdn5+SJpn/lE2TCPZVKysVyj73Fng682yK5TJmaYRt1
1FFtZmRCW6is9Jfv+Vq1x8fqy3ebqvJs97XqlqWR8B26vuD8dLIty/vOw3jWkmdnLa+j2W22RZuxGMZwoDJYREhe6oWVvEXa7T9h1epEw+elVcOzjt32PPWgl3AdJbvuUafinzXHCwUxI6lBpnBFfS+SieMtmsTfMedUnl1ZP
tfjgfBbX3xC5GhK7sEMxPV2HMWxNeIyC2p1XUo919QBt8hfo57hpVyO62f+APb6hOLDTeRiXwjA9YJDvYVW0B1Us/Iw+ZvuUnjz4uTCzAbdDYRHivVqXxQpoiC4Rlg==
2020-11-01T17:36:09.547+0100 [DEBUG] plugin.terraform-provider-proxmox: Csrfpreventiontoken: 5F9EE3E1:TQmdmgE12D4Nz/JeEEny7fKOMqa0z+yJKSjKtrRvDYo
2020-11-01T17:36:09.547+0100 [DEBUG] plugin.terraform-provider-proxmox: Accept-Encoding: gzip
2020-11-01T17:36:09.547+0100 [DEBUG] plugin.terraform-provider-proxmox:
2020-11-01T17:36:09.551+0100 [DEBUG] plugin.terraform-provider-proxmox: 2020/11/01 17:36:09 <<<<<<<<<< RESULT:
2020-11-01T17:36:09.551+0100 [DEBUG] plugin.terraform-provider-proxmox: HTTP/1.1 200 OK
2020-11-01T17:36:09.551+0100 [DEBUG] plugin.terraform-provider-proxmox: Content-Length: 235
2020-11-01T17:36:09.551+0100 [DEBUG] plugin.terraform-provider-proxmox: Cache-Control: max-age=0
2020-11-01T17:36:09.551+0100 [DEBUG] plugin.terraform-provider-proxmox: Connection: Keep-Alive
2020-11-01T17:36:09.551+0100 [DEBUG] plugin.terraform-provider-proxmox: Connection: Keep-Alive
2020-11-01T17:36:09.551+0100 [DEBUG] plugin.terraform-provider-proxmox: Content-Type: application/json;charset=UTF-8
2020-11-01T17:36:09.551+0100 [DEBUG] plugin.terraform-provider-proxmox: Date: Sun, 01 Nov 2020 16:36:09 GMT
2020-11-01T17:36:09.551+0100 [DEBUG] plugin.terraform-provider-proxmox: Expires: Sun, 01 Nov 2020 16:36:09 GMT
2020-11-01T17:36:09.551+0100 [DEBUG] plugin.terraform-provider-proxmox: Pragma: no-cache
2020-11-01T17:36:09.551+0100 [DEBUG] plugin.terraform-provider-proxmox: Server: pve-api-daemon/3.0
2020-11-01T17:36:09.551+0100 [DEBUG] plugin.terraform-provider-proxmox:
2020-11-01T17:36:09.551+0100 [DEBUG] plugin.terraform-provider-proxmox: {"data":{"upid":"UPID:pve:00004827:0096803A:5F9EE3F7:qmstart:102:terraform@pve:","user":"terrafor
m@pve","pstart":9863226,"exitstatus":"OK","node":"pve","pid":18471,"type":"qmstart","status":"**stopped**","id":"102","starttime":1604248567}}
2020-11-01T17:36:09.554+0100 [DEBUG] plugin.terraform-provider-proxmox: panic: runtime error: index out of range [1] with length 0
```

I enclose to this issue the `crash.log` file and the Terraform file I am using

* [vm.zip](https://github.com/Telmate/terraform-provider-proxmox/files/5471351/vm.zip)
* [crash.zip](https://github.com/Telmate/terraform-provider-proxmox/files/5471353/crash.zip)

Thank,
Fred

**Comment by hicwic** [comment]
did you manage to get rid of this ?

i'have the exactly same error/problem

i use ubuntu cloudimage with cloudinit

terraform crash with the error "index out of bound" when the newly created VM start.

**Comment by hicwic** [comment]
this error come from thoses lines : 

`			} else {
				// parse IP address out of ipconfig0
				ipMatch := rxIPconfig.FindStringSubmatch(d.Get("ipconfig0").(string))
				sshHost = ipMatch[1]
			}`

if like me you did'nt specify ipconfig0, and use cicustom to pass a network cloud-init file, the ipMatch is always out of range.

workaround is to specify a ssh_forward_ip as sshHost will be set to this previously in the code : 

`sshHost = d.Get("ssh_forward_ip").(string)`

hope this will help

**Comment by fguiet** [comment]
Hi Hicwic,

If I remember well...I created a Centos 7 Template with `Packer`...In this template, network is configured to get the IP address from my dhcp server...and it is working well.

As a consequence I did not specify a ipconfig0 in my cloud init custom file because I do not know the IP...

Have to think about this problem...

Anyway, thank for sharing this workaround...

Fred

**Comment by fguiet** [comment]
Hi @titarenko 

I have just test your workaround. Thank you. Now it's now longer crashing !!! but...got this message now:

```bash
Error: Provider produced inconsistent result after apply

When applying changes to proxmox_vm_qemu.vm-test-fred-01, provider
"registry.example.com/telmate/proxmox" produced an unexpected new value: Root
resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

**Comment by hicwic** [comment]
Yes i got it too, you have to use the fork from issue #233 and finally it's working

**Comment by fguiet** [comment]
Hi @hicwic 

Ok for the fork...but how come all those fixes are not merged into this repo?

Fred

**Comment by doransmestad** [comment]
@fguiet   The updates from the fork were merged in earlier today.  Hopefully with those changes (either from the fork, or now in this repo) the issues you were seeing have been resolved?

**Comment by fguiet** [comment]
Hi, 

Just tried tags 2.6.2...
Documentation needs to be updated as 

```bash
#no longer works
go install github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provisioner-proxmox
```

Anyway...now I got this error : 

```bash
proxmox_vm_qemu.vm-test-fred-01: Creating...
proxmox_vm_qemu.vm-test-fred-01: Still creating... [10s elapsed]
proxmox_vm_qemu.vm-test-fred-01: Still creating... [20s elapsed]

Error: Proxmox does not support decreasing disk size. Disk 'virtio0' wanted to go from '8' to '8'
```

Dunno why...

Fred

**Comment by doransmestad** [comment]
Ah, I presume you hit that when cloning from an existing VM?   The if-statement I added doesn't account for when the disks are the same size.  I'll work on a quick fix for that.

**Comment by fguiet** [comment]
Hi,

Yes I am cloning a template...but template disk size is 8G...

it reports : Proxmox does not support decreasing disk size. Disk 'scsi0' wanted to go from '10' to '10' when I set size = "10G" in my `vm.tf` file

As if this line below was not working...

clonedDiskSize := pxapi.DiskSizeGB(clonedConfig.QemuDisks[diskID]["size"])

clonedDiskSize should reports 8G but it reports10G...

Fred

**Comment by fguiet** [comment]
Hi, 

Think I found the bug:

```bash
func prepareDiskSize(
	client *pxapi.Client,
	vmr *pxapi.VmRef,
	diskConfMap pxapi.QemuDevices,
) error {
	clonedConfig, err := pxapi.NewConfigQemuFromApi(vmr, client)
```

shoud be

```bash
func prepareDiskSize(
	client *pxapi.Client,
	vmr *pxapi.VmRef,
	sourceVmr*pxapi.VmRef,
	diskConfMap pxapi.QemuDevices,
) error {
	clonedConfig, err := pxapi.NewConfigQemuFromApi(**sourceVmr**, client)
```

I tried and I think it is working...

Fred

**Comment by fguiet** [comment]
But now...i have another issue...since 2.6.2...when cloning a template, it creates 2 drives

And it tries to boot on the non bootable one....wtf!!!

![proxmox](https://user-images.githubusercontent.com/13849639/98448753-d4f57380-212e-11eb-9266-a0fd9804d7e3.JPG)

**Comment by doransmestad** [comment]
Whoa, yeah that's odd.   I'm not sure why you're getting an unused disk there.  :thinking:    I do not get that when cloning in my infrastructure, but I was able to see it happening in the integration tests I'm writing.  Odd.   

I just opened a PR which should fix the disk resize bug you were seeing.  I'll investigate this unused disk thing next.

**Comment by fguiet** [comment]
Hi,

Regarding disk resize error....to me it is not working as expected...

In log I have got : 

````bash
Sun, 08 Nov 2020 10:20:13 +0100 DBG applications/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1186 > Disk is same size as before, skipping resize. Original '10', New '10' diskId=0 loggerName=prepareDiskSize
````

Orginal value is not correct...should display 8...My template has got a disk of 8Gb....

That a bit normal when I read the code...`UpdateConfig` is called before `prepareDiskSize` so...clone disk size will always be equal to wanted disk size...

```bash
err = config.UpdateConfig(vmr, client)
			if err != nil {
				// Set the id because when update config fail the vm is still created
				d.SetId(resourceId(targetNode, "qemu", vmr.VmId()))
				return err
			}

			// give sometime to proxmox to catchup
			time.Sleep(time.Duration(d.Get("clone_wait").(int)) * time.Second)

			err = prepareDiskSize(client, vmr, qemuDisks)
			if err != nil {
				return err
			}
````

**Comment by fguiet** [comment]
My bad...I think disk resizing is working...so I gonna close this long issue...
Will open a new one with the unused disk stuff..
Thank you for helping
Fred

**Comment by fguiet** [comment]
Sorry...bug is here and due to see : https://github.com/Telmate/terraform-provider-proxmox/issues/235#issuecomment-723552550

TIPS:

__Removing this part below will make it works__

```go
err = config.UpdateConfig(vmr, client)
			if err != nil {
				// Set the id because when update config fail the vm is still created
				d.SetId(resourceId(targetNode, "qemu", vmr.VmId()))
				return err
			}
```

Fred

**Comment by fguiet** [comment]
#239
