### ISSUE TITLE
Error: network.0.firewall: '' expected type 'bool', got unconvertible type 'int'

### ISSUE THREAD

**Issue by faragm** [Telmate/terraform-provider-proxmox#246]
After applying plan first time I got ` Error: 400 Parameter verification failed` without any clarity what failed.
When I trying to run `plan -destroy` I got he following error:
`Error: network.0.firewall: '' expected type 'bool', got unconvertible type 'int'`

**Comment by yukron** [comment]
Hello @faragm , is it related? https://github.com/Telmate/proxmox-api-go/pull/97

**Comment by faragm** [comment]
Yes!

**Comment by ggongaware** [comment]
Try v2.6.4 for this.

**Comment by faragm** [comment]
Issue still valid with lxc

```
proxmox_lxc.lxc-test: Creating...

Error: network.0.firewall: '' expected type 'bool', got unconvertible type 'int'
```

**Comment by yukron** [comment]
@faragm yup, seems like LXC api part is out of sync with QEMU. I'll think it's an easy fix, will look into it.

**Comment by malcom2073** [comment]
Any update? This is still an issue with LXC

**Comment by malcom2073** [comment]
Dug around a bit and figured out how to compile providers myself, I put the same change in config_lxc.go, and it worked! I can't get the tests to pass so I'd rather not put it in a PR, but that change does allow me to create LXC containers now. Thanks for that!

**Comment by amenome** [comment]
> Dug around a bit and figured out how to compile providers myself, I put the same change in config_lxc.go, and it worked! I can't get the tests to pass so I'd rather not put it in a PR, but that change does allow me to create LXC containers now. Thanks for that!

Can you share your fix?  Getting the same problem.

**Comment by malcom2073** [comment]
Sure, it's a simple fix patch below:
`
diff --git a/proxmox/config_lxc.go b/proxmox/config_lxc.go
index c1f33ec..38df551 100644
--- a/proxmox/config_lxc.go
+++ b/proxmox/config_lxc.go
@@ -212,6 +212,13 @@ func NewConfigLxcFromApi(vmr *VmRef, client *Client) (config *configLxc, err err
                }
                // add rest of device config
                nicConfMap.readDeviceConfig(nicConfList)
+
+               if nicConfMap["firewall"] == 1 {
+                       nicConfMap["firewall"] = true
+               } else if nicConfMap["firewall"] == 0 {
+                       nicConfMap["firewall"] = false
+               }
+
                // prepare empty network map
                if config.Networks == nil {
                        config.Networks = QemuDevices{}
`

**Comment by fwdIT** [comment]
@malcom2073 thx for the fix, made a pull request after testing it yesterday at home
