### ISSUE TITLE
Terabyte disk size passed in gigabytes causes disk to be resized

### ISSUE THREAD

**Issue by yukron** [Telmate/terraform-provider-proxmox#247]
When disk size is specified in gigs (1024G), it is later converted into "1T" on Proxmox side, which results in disk resize if we are re-applying configuration. It also occurs when importing existing VMs with 1/2/3T etc in disk's size: applying proper configuration (1024G) will lead to disk resize with "1024G".

You cannot set disk size to Terabytes (1T) directly both in Proxmox and in terraform.

disk configuration:
```
disk {
    type          = var.disk_type
    storage       = var.disk_storage
    size          = "1024G"
    format        = var.disk_format
    backup        = false
  }
```

terraform plan result:
```
...
   replicate   = false
 ~ size        = "1T" -> "1024G"
   slot        = 0
...
Plan: 0 to add, 1 to change, 0 to destroy.
```

I think we should convert GB to TB while doing change check on planning/applying.

Or we can query disk size when importing and save it into state in GBs if one received is in TB.

**Comment by stefanvangastel** [comment]
@yukron How can I work around this in the meanwhile? E.g. I'm defining a `12G` disk and getting a `disk wanted to go from 12.492 to 12.000`

**Comment by yukron** [comment]
@stefanvangastel I'll try to post a fix soon.
Can you please describe steps to repeat this behavior?

**Comment by stefanvangastel** [comment]
Well not exactly it seems to occur at random when resuming an apply after a fail. Then retrying fixes the issue. I'll try to collect more info

**Comment by yukron** [comment]
@stefanvangastel can you please try this PR: https://github.com/Telmate/proxmox-api-go/pull/98 ?
