### ISSUE TITLE
get vmid of current machine

### ISSUE THREAD

**Issue by kneufeld** [Telmate/terraform-provider-proxmox#254]
I'm a total newb with regards to terraform, using `terraform-provider-proxmox` is my first attempt at it so there may be a terraform way to accomplish what I want.

In my cluster I use the `vmid` to assign a static ip address. So if `test1` has `vmid=123` then I use static ip `10.1.1.123`.

When creating a new machine (`vmid=0`) I'd like to have something along the lines of:

```hcl
ipconfig0 = "ip=10.1.1.{vmid}/24,gw=10.1.1.1"
```

So is there way to get what I want, or make a vm in two steps and regenerate the cloud-init drive in stage two or something completely different?

Similarily, if vmid is 0 then how do you prevent terraform from forever recreating the machine? I currently have 

```hcl
lifecycle {
    ignore_changes  = [ vmid ]
}
```

but that doesn't seem right...

Thanks for providing this plugin, even if I can't get to nirvana it will still save me a lot clicking around in Proxmox.

**Comment by doransmestad** [comment]
Hey @kneufeld welcome to terraform!  :tada:   Glad to hear you're trying it out.

First, I just want to clarify that `vmid` here is going to be what we attempt to set the vmid to in proxmox.  If there is a VM that already exists with that `vmid` this will probably go poorly.  At best we'll throw an error, at worst, we'll alter that VM directly which may not be what you want.  Just a friendly warning to be careful with what already exists in your environment!   Also, it's worth noting that setting a `vmid` before 100 is not supported by proxmox as far as I know.

As you suspect, you'll need two steps here as you will not have access to the VM's computed `vmid` until after the machine is created if you use the `proxmox_vm_qemu` alone.  That first step though could simply be a local block like this:

```
locals {
  vms = {110 = {"name" = "vm110"}, 111 = {"name" = "vm111" }}
}

resource "proxmox_vm_qemu" "simpletest" {
  for_each = local.vms

  vmid = each.key
  name = each.value["name"]
  target_node = "testproxmox"
  clone = "pxtest-10-test"
  ipconfig0 = "ip=10.1.1.${each.key}/24,gw=10.1.1.1"
  disk {
    size = "50G"
    type = "scsi"
    storage = "local-lvm"
  }
}
```

That'll allow you to simply define the block in locals and then terraform will generate the rest!   Does this get close to what you're looking for?

**Comment by kneufeld** [comment]
Thanks for the reply.

Unfortunately it doesn't do what I'm looking for because you have to know in advance the vmid that you're creating. If you use `vmid=0` the "next" one is chosen, which is what I want, and I want to use that unknown-vmid-at-apply-time in the resource block.

**Comment by akadoya** [comment]
@kneufeld  I had a similar use case where I needed vmid to hit proxmox API to retrieve the dhcp assigned IP address without cloud-init set up. this provider outputs the proxmox API's qemu machine endpoint as `proxmox_vm_qemu.<your_resource_name>.id` which is like `<proxmox_target_nname>/qemu/<vmid>`.
You can cut out the vmid part by using terraform string functions.

**Comment by Strade28** [comment]
mother in hell j'ai pas pensé 


De: "akadoya" <notifications@github.com> 
À: "Telmate/terraform-provider-proxmox" <terraform-provider-proxmox@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Mardi 17 Novembre 2020 14:30:30 
Objet: Re: [Telmate/terraform-provider-proxmox] get vmid of current machine (#254) 





[ https://github.com/kneufeld | @kneufeld ] I had a similar use case where I needed vmid to hit proxmox API to retrieve the dhcp assigned IP address without cloud-init set up. this provider outputs the proxmox API's qemu machine endpoint as proxmox_vm_qemu.<your_resource_name>.id which is like <proxmox_target_nname>/qemu/<vmid> . 
You can cut out the vmid part by using terraform string functions.

**Comment by kneufeld** [comment]
Thanks @akadoya for the suggestion but I think I'm not understanding something. When I try something like:

```hcl
resource "proxmox_vm_qemu" "cloudhost" {
...
  vmd = proxmox_vm_qemu.cloudhost.id
...
}
```

I get terraform error

```
terraform plan
...
Error: Self-referential block

  on infra/cloudhost/cloudhost.tf line 19, in resource "proxmox_vm_qemu" "cloudhost":
  19:   vmid = proxmox_vm_qemu.cloudhost.id

Configuration for proxmox_vm_qemu.cloudhost may not refer to itself.
```

**Comment by mleone87** [comment]
@kneufeld what you're asking is not possible with terraform in general, there is no way to reference to a "self" attribute in a terraform resource
https://www.terraform.io/docs/configuration-0-11/interpolation.html

referencing to self is possible only in a provisioner

a solution for your problem would be to create a "proxmo_vmid_qemu" resource to be used in a "proxmox_vm_qemu" but thir require some work on the proxmox-api-go and on this provisioner

if you dont mind the extra work, create an output like(remember also to set a placeholder ip config to some unused ip)

```
output "vm_id" {
  value = proxmox_vm_qemu.<your_resource_name>.vmid
}
```

and run the .tf again updating vmid and ip config manually

**Comment by kneufeld** [comment]
@mleone87 Thanks for that. Yeah, what I've been doing is starting to make a new vm in proxmox to see which vmid is "next". Then I pass that `vmid` as a variable to my `cloudhost` resource.

Thanks for everybody's help, closing.
