### ISSUE TITLE
Terraform init fails to install version 2.6.4

### ISSUE THREAD

**Issue by goffinf** [Telmate/terraform-provider-proxmox#255]
**Terraform version**

```
terraform version
...
  ----
Terraform v0.13.5
```

This installs the Proxmox provider from the Hashicorp registry without any problem (note: the version is **2.6.3**):

```
terraform {
  required_providers {
   ...
    proxmox = {
      source  = "Telmate/proxmox"
      version = "2.6.3"
    }
  }
}
```

If I change this to 2.6.4 ...

```
terraform {
  required_providers {
   ...
    proxmox = {
      source  = "Telmate/proxmox"
      version = "2.6.4"
    }
  }
}
```

I get the following error:

```
    [1m[31mError: [0m[0m[1mFailed to query available provider packages[0m

    [0mCould not retrieve the list of available versions for provider
    telmate/proxmox: no available releases match the given constraints 2.6.4
```

My config appears to match that shown here (copied below): https://registry.terraform.io/providers/Telmate/proxmox/latest

**How to use this provider**

**To install this provider, copy and paste this code into your Terraform configuration. Then, run terraform init.**

**Terraform 0.13  Latest**

```
terraform {
  required_providers {
    proxmox = {
      source = "Telmate/proxmox"
      version = "2.6.4"
    }
  }
}

provider "proxmox" {
  # Configuration options
}
```

Any idea why this is ?

Regards

Fraser

**Comment by doransmestad** [comment]
@goffinf   That's odd.. I'm not sure why that doesn't work for you.  It works on my machine using the following full config:

```
terraform {
  required_providers {
    proxmox = {
      source  = "Telmate/proxmox"
      version = "2.6.4"
    }
  }
  required_version = ">= 0.13"
}

provider "proxmox" {
  pm_tls_insecure = true

  // Credentials here or environment
  pm_api_url  = "https://*******:8006/api2/json"
  pm_password = "******"
  pm_user     = "root@pam"
  pm_log_enable = true
  pm_log_file = "terraform-plugin-proxmox.log"
  pm_log_levels = {
    _default = "debug"
  }
}

locals {
  vms = {110 = {"name" = "vm110"}, 111 = {"name" = "vm111" }}
}

resource "proxmox_vm_qemu" "simpletest" {
  for_each = local.vms

  vmid = each.key
  name = each.value["name"]
  target_node = "testproxmox"
  clone = "pxtest-10-test"
  ipconfig0 = "ip=10.1.1.${each.key}/24,gw=10.1.1.1"
  disk {
    size = "50G"
    type = "scsi"
    storage = "local-lvm"
  }
}

```

Can you delete the `.terraform` file in your terraform folder and try again?  We'll see if that clears any state out that is causing issues.   Are you attempting to run this on an amd64-based linux platform?

**Comment by goffinf** [comment]
@doransmestad Thanks for the hint. It appears that it *was* some form of caching issue and also partly related to to way that I install Terraform plugins via Ansible (I set up a local file-system mirror cache).

Anyway I cleared out the cache and made a few adjustments to the Ansible playbook and version 2.6.4 install correctly.
