### ISSUE TITLE
Vm reboots after any changes in template

### ISSUE THREAD

**Issue by scrowbar** [Telmate/terraform-provider-proxmox#256]
I've just found that  commit 6c27554  forces VM to be rebooted even after minor changes in template.

For example we have main.tf

```
resource "proxmox_vm_qemu" "testvm" {
   ...
   name        = "test"
   ...
}
```

Then we change name = test2 and perform plan and apply

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
...
      ~ name                   = test" -> "test2"
...
```
AFAIK Some changes in proxmox are not require reboot VM. 

Is this expected behavior ? Can we make reboot optional ?

**Comment by msbence** [comment]
This is a blocker for me as well :( Most of the settings definitely not require a reboot to apply.

**Comment by sophiexiaoyan** [comment]
This is also a blocker for me. For example, adding more disks or increasing disk size should not require a VM reboot.

**Comment by msbence** [comment]
I might make a PR about it, but if anyone know which changes require a reboot exactly, that would be a huge help.

**Comment by msbence** [comment]
Okay, made the PR, but feel free to take a look at the code :)

**Comment by scrowbar** [comment]
Thank  you!
