### ISSUE TITLE
Support for citype flag

### ISSUE THREAD

**Issue by luiscachog** [Telmate/terraform-provider-proxmox#259]
Hi,

I'm wondering if you are planning to support the flag citype.
As [documentation](https://pve.proxmox.com/wiki/Cloud-Init_Support) reads:

```code
 citype: <configdrive2 | nocloud>

    Specifies the cloud-init configuration format. The default depends on the configured operating system type (ostype. We use the nocloud format for Linux, and configdrive2 for windows.

```

My use case is to install a rancherOS image using terraform on a proxmox host. I do see a possible solution [here](https://github.com/rancher/os/issues/2899) and it is using the `citype` flag, but sadly is not supported by this provider yet.

If you are not planning to supported, what is a good workaround for that?

Thanks

**Comment by elrender** [comment]
@mleone87 hey, is it possible to reopen this? I have found that [flatcar](https://www.flatcar.org) needs configdrive2 to use cloud-init and it's the only thing that I am forced to setup through other means using *citype* in Proxmox when I want to spin up flatcar VM with terraform. I would be good to have *citype* supported by terraform proxmox provider.

Just a side note for people that want to spin up flatcar images on Proxmox: it is possible to boot VM with flatcar iso, inject ssh key via cloud-init and then use ansible (with ssh) to provision (inject ignition and run flatcar-install). No need to create some weird templates with *-fw_cfg* parameter (root@pam only).
