### ISSUE TITLE
Remote-exec getting error

### ISSUE THREAD

**Issue by reesericci** [Telmate/terraform-provider-proxmox#262]
Whenever I run 'terraform apply', I get an error at the end about remote-exec, and the command doesn't execute. I am using cloud-init and using the same snippet that is in the docs. guides/cloud-init.md

error: `Error: host for provisioner cannot be empty`
main.tf snippet:
```
provisioner "remote-exec" {
    inline = [
      "ip a"
    ]
  }
}
```

**Comment by reesericci** [comment]
If I read the docs I would know the answer...
https://www.terraform.io/docs/provisioners/index.html

**Comment by qeba** [comment]
> If I read the docs I would know the answer... https://www.terraform.io/docs/provisioners/index.html

can you share which part of it and how do you solve this issues?. how you properly used the `provisioner "remote-exec"` after create the VM?

**Comment by reesericci** [comment]
um I haven't done it in a little while - i'll check my config once i get back. sorry about leaving such an unhelpful answer!

**Comment by qeba** [comment]
@reesericci hope you can share, haha I'm stuck with this i need to run few commands once VM created, btw is it required to have qemu-guest-agent installed when you're creating the template?.

**Comment by aequasi** [comment]
An answer here would be nice. The documentation on this specific provider doesn't show how to properly do this
