### ISSUE TITLE
Use remote-exec with DHCP

### ISSUE THREAD

**Issue by reesericci** [Telmate/terraform-provider-proxmox#263]
How do I find the DHCP-ed IP address so that way I can use remote-exec to provision the system?

**Comment by reesericci** [comment]
I am using cloud-init

**Comment by KingKeithC** [comment]
You need the [qemu-guest-agent](https://pve.proxmox.com/wiki/Qemu-guest-agent) to be running in the guest for Proxmox to be able to determine the IP Address of the guest, and therefore use remote-exec. Personally, I install and enable the service during provisioning of my VM template with Packer, then any VMs cloned from the template will have the agent running after they startup.

**Comment by reesericci** [comment]
ok makes sense
