### ISSUE TITLE
[BUG] Resizing Disk issue

### ISSUE THREAD

**Issue by soakes** [Telmate/terraform-provider-proxmox#269]
Hi Guys,

There seems to be an issue when you resize disk, while terraform does show its going todo it correctly, whats actaully happening is it creates a new disk instead which is then blank so it then can't boot.

You can tell this as if you check the UI as its running, you can see its trying to craete a new one to replce old, where usually you would only see it change size.

I have tried adding in slot as id is no longer supported, but this did not help.

After initial creation
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/813389/101681409-00cf8600-3a5a-11eb-8fa1-dffede05b6d1.png">

While second apply is done, after size change in manifest.
You can see its not going to destory it, but update in-place, but thats not what happens.

```
❯ terraform apply
proxmox_vm_qemu.vm[0]: Refreshing state... [id=pve01/qemu/271050]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # proxmox_vm_qemu.vm[0] will be updated in-place
  ~ resource "proxmox_vm_qemu" "vm" {
        id                     = "pve01/qemu/271050"
        name                   = "tf-testvm01"
        # (37 unchanged attributes hidden)

      ~ disk {
          ~ size        = "20G" -> "50G"
            # (13 unchanged attributes hidden)
        }


        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
```

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/813389/101681626-586df180-3a5a-11eb-8018-ebcaeea9db29.png">

```
❯ terraform apply
proxmox_vm_qemu.vm[0]: Refreshing state... [id=pve01/qemu/271050]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # proxmox_vm_qemu.vm[0] will be updated in-place
  ~ resource "proxmox_vm_qemu" "vm" {
        id                     = "pve01/qemu/271050"
        name                   = "tf-testvm01"
        # (37 unchanged attributes hidden)

      ~ disk {
          ~ size        = "20G" -> "50G"
            # (13 unchanged attributes hidden)
        }


        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

proxmox_vm_qemu.vm[0]: Modifying... [id=pve01/qemu/271050]
proxmox_vm_qemu.vm[0]: Still modifying... [id=pve01/qemu/271050, 10s elapsed]
proxmox_vm_qemu.vm[0]: Still modifying... [id=pve01/qemu/271050, 20s elapsed]
proxmox_vm_qemu.vm[0]: Still modifying... [id=pve01/qemu/271050, 30s elapsed]
proxmox_vm_qemu.vm[0]: Still modifying... [id=pve01/qemu/271050, 40s elapsed]
proxmox_vm_qemu.vm[0]: Modifications complete after 45s [id=pve01/qemu/271050]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

After the apply finishes, you now see the disk-1 not disk-0 showing.  The machine then gets stuck in a reboot loop because theres now now OS on the disk (its blank).

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/813389/101681867-b8fd2e80-3a5a-11eb-9555-1977a076b5bf.png">

Now if you just resize disk via UI while machine is on, it just changes size, it doesn't create a new one, so im not sure why terraform is behaving like this.

You can also see on the zfs dataset that its created an extra one, didnt delete the original either, it just created another disk then removed original (just not data).  It should of just adjusted the size of the original and not reaplce it.

```
root@pve01:~# zfs list|grep 27
rpool/prod/vm/vm-271050-cloudinit   135K  5.62T      135K  -
rpool/prod/vm/vm-271050-disk-0     1.35G  5.62T     1.35G  -
rpool/prod/vm/vm-271050-disk-1     99.5K  5.62T     99.5K  -
```

What should of happened is, it should of just adjusted the size of disk-0.

To duplicate this issue easily, you can see my example code below.  Just change size after initial build and re-apply to see issue.

```
# https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/resource_vm_qemu.md

terraform {
  required_providers {
    proxmox = {
      source  = "telmate/proxmox"
      version = "~> 2.6.5"
    }
  }
}

provider "proxmox" {
  pm_parallel       = 4
  pm_tls_insecure   = true
  pm_api_url        = var.pm_api_url
  pm_password       = var.pm_password
  pm_user           = var.pm_user
}

resource "proxmox_vm_qemu" "vm" {

  #
  # Machine Specifications
  #

  count             = 1
  name              = var.vm_hostname
  desc              = var.vm_desc
  vmid              = var.vm_id

  target_node       = var.pm_node

  cpu               = var.vm_cpu
  numa              = true
  memory            = var.vm_memory

  cores             = var.vm_cores
  sockets           = var.vm_sockets

  clone             = var.vm_template
  full_clone        = true

  pool              = var.vm_pool

  agent             = 1
  os_type           = "cloud-init"

  hotplug           = "network,disk,usb,memory,cpu"
  scsihw            = "virtio-scsi-pci"
  bootdisk          = "scsi0"
  boot              = "c"

  disk {
    slot            = 0
    size            = "20G"
    storage         = "prod-vm"

    type            = "scsi"
    ssd             = "true"
  }

  vga {
    memory = 0
    type   = "serial0"
  }

  #
  # Connectivity
  #

  # net/linux (vLAN 4001)
  network {
      model = "virtio"
      bridge = "vmbr1"
      tag = 4001
  }

  network {
      model = "virtio"
      bridge = "vmbr1"
      tag = 4002
  }

  ipconfig0 = "ip=${var.vm_ip}/24,gw=${var.vm_gw}"
  ipconfig1 = "ip=172.27.2.50/24"

  # Terraform
  ssh_user = "ubuntu"
  ssh_private_key = file("${path.module}/keys/id_rsa_terraform")

  # User public SSH key
  sshkeys = file("${path.module}/keys/id_rsa_netspeedy.pub")

  provisioner "remote-exec" {

    connection {
      type     = "ssh"
      user     = "root"
      host     = var.vm_ip
      private_key = file("${path.module}/keys/id_rsa_terraform")
    }

    inline = [
      "ip a"
    ]
  }

  #
  # Lifecycle
  #
  lifecycle {
    ignore_changes  = [
      network
    ]
  }

}
```

Any ideas on fix? 

Only solution I have right now is to ignore the disks and manually make changes but that kinda defeats the object of terraform.

**Comment by tomKL25** [comment]
Hi,

I have the same problem. When the disk is resized, a new blank disk is created and the original one switches to the Unused disk state.

terraform version 1.0.1
telmate/proxmox provider 2.7.1

![image](https://user-images.githubusercontent.com/86769031/124087386-3cf82180-da52-11eb-8f0f-c8d55beec210.png)


```
resource "proxmox_vm_qemu" "vm" {

        additional_wait           = 15
        agent                     = 1
        balloon                   = 0
        bios                      = "seabios"
        boot                      = "c"
        clone                     = "ubuntu-cloudinit"
        clone_wait                = 0
        cores                     = 4
        cpu                       = "host"
        define_connection_info    = true
        force_create              = false
        full_clone                = true
        guest_agent_ready_timeout = 600
        hotplug                   = "network,disk,cpu,memory,usb"
        kvm                       = true
        memory                    = 4096
        name                      = "cloudinit"
        numa                      = true
        onboot                    = false
        os_type                   = "cloud-init"

        sockets                   = 2
        target_node               = "virt-devel01-test"
        vcpus                     = 0
        ipconfig0                 = "ip=dhcp"

   disk {
        backup       = 0
        cache        = "none"
        iothread     = 0
        mbps         = 0
        mbps_rd      = 0
        mbps_rd_max  = 0
        mbps_wr      = 0
        mbps_wr_max  = 0
        replicate    = 0
        size         = "130G"
        ssd          = 0
        storage      = "ceph"
        type         = "scsi"
        }
}
```

**Comment by AjdinDev** [comment]
I'm facing the same issue.

Have you guys found any workarounds in the meantime?
@soakes @tomKL25

**Comment by soakes** [comment]
Currently no I haven't, only work around I am using is to destory and rebuild with the new disk values.  Thankfully most of my stuff is ansiblized so not a major issue but for some this is.  Its a pain to do but thankfully I dont need to resize too oftern.

**Comment by christheradioguy** [comment]
Just wanted to chime in here and say I am experiencing the same issue.  Does anyone know of an older version of the proxmox provider I can revert back to where this works?  Currently experiencing it on 2.6.5.

**Comment by pgporada** [comment]
Our strategy has been to update the disk size in the proxmox web UI, and then edit the TF state. It works, but is definitely not ideal or how it should be.

**Comment by Daemonslayer2048** [comment]
I am experiencing a similar issue however it is a bit worse than just regrowing the disk. Any attempt to run terraform again (re-sizing the disk or not) will create a new blank disk. So simply applying your terraform apply twice will casue this provider to create a new disk (even if you have made no changes at all).

**Comment by avekrivoy** [comment]
I'm experiencing the same issue. Any news?

Proxmox 7.1
Terraform v1.0.11

**Comment by fguiet** [comment]
Hey all,

Same thing here:

If I use 

```text
disk {
    size            = "20G"
    type            = "virtio"
    storage         = "local-lvm"
 }
```

to resize template VM disk with proxmox then it create an unused disk 0 and I cannot boot anymore...

The only solution I got : I create a VM template with the correct size with Packer then I avoid to use `disk` with Proxmox...

Proxmox 7.8.1
Terraform 1.1.3
Telmate/proxmox v2.6.4

**Comment by fguiet** [comment]
Hi guys,

Found a solution that works now, here it is

```text
disk {
    slot            = 0
    size            = "20G"
    type            = "virtio"
    storage         = "local-lvm"
 }
```

Even resizing a disk works :)

Hope it can help 

Fred

**Comment by christheradioguy** [comment]
Oh, very nice.  I'll try this out in our dev environment,

> Hi guys,
> 
> Found a solution that works now, here it is
> 
> ```
> disk {
>     slot            = 0
>     size            = "20G"
>     type            = "virtio"
>     storage         = "local-lvm"
>  }
> ```
> 
> Even resizing a disk works :)
> 
> Hope it can help
> 
> Fred

**Comment by christheradioguy** [comment]
yeah confirmed that adding `slot=0` to our main.tf works.  This is on TF 1.0.9

**Comment by soakes** [comment]
Awesome find guys, thats one thing I never tried.

**Comment by avekrivoy** [comment]
@soakes an official documentation has weird description for the slot parameter
```
slot | int |   | _(not sure what this is for, seems to be deprecated, do not use)_.
```
https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/vm_qemu

It would be great if someone from provider authors would give an explanation here.

Also, terraform is trying to modify base VM image on each plan
```
      ~ disk {
          ~ size         = "2252M" -> "30G"
          ~ type         = "scsi" -> "virtio"
            # (15 unchanged attributes hidden)
        }
```

**Comment by soakes** [comment]
Yeah it does.

**Comment by avekrivoy** [comment]
Also, this option adds block device with partitions
```
vda     252:0    0   20G  0 disk 
├─vda1  252:1    0  2.1G  0 part 
├─vda14 252:14   0    4M  0 part 
└─vda15 252:15   0  106M  0 part 
```
Not sure what's happening here

**Comment by avekrivoy** [comment]
Here's description from provider's source code
https://github.com/Telmate/terraform-provider-proxmox/blob/a222eb626fa30eda9b7670578c6180c3c8d50fe7/proxmox/resource_vm_qemu_test.go#L90
```
// slot setting to assign a non-standard disk position (scsi5 vs scsi0)
```
Also, adding slot 0 in terraform leads to a collision, where hard disk definitions point to the same file on filesystem
![image](https://user-images.githubusercontent.com/19726616/149624756-d5310caf-d496-4405-a61a-863d25733463.png)

So I'm afraid that @fguiet answer is not suitable

**Comment by fguiet** [comment]
Hi All,

Yeah it seems that this option is not suitable for our problem...

We'll have to wait for a fix...sorry

Fred

**Comment by risayew** [comment]
Hi Everybody. I have the same issue, even with the latest version of the telmate/proxmox 2.9.6
<img width="575" alt="Screenshot 2022-02-15 at 23 21 53" src="https://user-images.githubusercontent.com/2446408/154159569-4311d0c9-d451-4ef0-bdde-9680a54a17ce.png">
<img width="274" alt="Screenshot 2022-02-15 at 23 22 24" src="https://user-images.githubusercontent.com/2446408/154159644-5594cf2a-f70e-47e6-932d-7a6021ab5301.png">
The provider for some reason "interchanges" the boot disc and the other disk, configured in the script. And tries to update the boot disc with the params defined for another one.
<img width="491" alt="Screenshot 2022-02-15 at 23 24 22" src="https://user-images.githubusercontent.com/2446408/154159985-f5d3ceac-84a9-46d7-a7dc-3f69c098a598.png">

**Comment by risayew** [comment]
i have the solution - just use another virtio number for bootdisc instead of 0

**Comment by bradleyhession1** [comment]
This is still a blocking issue when using the provider. Anyone have any suggestions? From what I can see the proxmox api doesn't provide any easy way to identify disks (no ID returned from the api for example)

**Comment by karolzlot** [comment]
Should this be reopened?

**Comment by AjdinDev** [comment]
> Should this be reopened?

Yes, this is the only reason why we're not using this provider.

**Comment by soakes** [comment]
This is strange as its working fine for me as long as your using `telmate/proxmox v2.9.6` or greater then its working but previous to this it wasn't.  

```
❯ terraform plan
proxmox_vm_qemu.vm[0]: Refreshing state... [id=pve01/qemu/192101]
proxmox_vm_qemu.vm[1]: Refreshing state... [id=pve01/qemu/192102]
proxmox_vm_qemu.vm[2]: Refreshing state... [id=pve01/qemu/192103]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # proxmox_vm_qemu.vm[0] will be updated in-place
  ~ resource "proxmox_vm_qemu" "vm" {
        id                        = "pve01/qemu/192101"
        name                      = "gkube01.example.io"
        tags                      = ""
        # (59 unchanged attributes hidden)

      ~ disk {
          ~ size         = "20G" -> "40G"
            # (17 unchanged attributes hidden)
        }


        # (4 unchanged blocks hidden)
    }

  # proxmox_vm_qemu.vm[1] will be updated in-place
  ~ resource "proxmox_vm_qemu" "vm" {
        id                        = "pve01/qemu/192102"
        name                      = "gkube02.example.io"
        tags                      = ""
        # (59 unchanged attributes hidden)

      ~ disk {
          ~ size         = "20G" -> "40G"
            # (17 unchanged attributes hidden)
        }


        # (4 unchanged blocks hidden)
    }

  # proxmox_vm_qemu.vm[2] will be updated in-place
  ~ resource "proxmox_vm_qemu" "vm" {
        id                        = "pve01/qemu/192103"
        name                      = "gkube03.example.io"
        tags                      = ""
        # (59 unchanged attributes hidden)

      ~ disk {
          ~ size         = "20G" -> "40G"
            # (17 unchanged attributes hidden)
        }


        # (4 unchanged blocks hidden)
    }

```

Will reopen so we can get to the bottom of why it seems to work for me.

**Comment by leodotcloud** [comment]
```
terraform {
  required_providers {
    proxmox = {
      source = "telmate/proxmox"
      version = "2.9.6"
    }
  }
}
```

I was using v2.9.6 and it was working correctly, a few weeks back. Trying it out today seems to be failing.

Upgrading to v2.9.10 seems not to move the previous disk to unused0, but the VM doesn't boot.

**Comment by Denissa89** [comment]
I use version **telmate/proxmox v2.9.14**

The problem is current:
```
# proxmox_vm_qemu.this["k3s-master-0"] will be updated in-place
  ~ resource "proxmox_vm_qemu" "this" {
        id                        = "proxmox/qemu/104"
        name                      = "k3s-master-0"
        # (38 unchanged attributes hidden)

      ~ disk {
          ~ size               = "2G" -> "20G"
          ~ type               = "scsi" -> "virtio"
            # (25 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }
    ```

**Comment by argonius2412** [comment]
also facing this issue.

**Comment by TuncTaylan** [comment]
Any chance to get this fixed?
It workaround with "slot=0" doesn't work with scsi.

**Comment by gustavodrodriguez** [comment]
Well, the problem continues. I'm with the version
telmate v2.9.14
proxmox v8.1.4
terraform v1.7.1
It continues adding disks instead of expanding the disk it already has defined.

**Comment by devdnn** [comment]
Please reopen this as I still have issue and slot=0 is not working.

**Comment by soakes** [comment]
> Please reopen this as I still have issue and slot=0 is not working.

AFAIK you cant reopen a closed issue.  I would suggest you just create a new one and reference to this.
