### ISSUE TITLE
How to get private IP address?

### ISSUE THREAD

**Issue by nmcbride** [Telmate/terraform-provider-proxmox#271]
Hello everyone,

I'd like to use Terraform with my local ProxMox to spin up a VM and provision it. Spinning up the VM has not been any issues but I'm having a hard time being able to get the private IP address that gets assigned via DHCP to use for provisioning. I'm trying to use remote-exec which says there is no defined host but I'm not sure how to tell it to use the assigned private IP. 

The qemu-guest-agent is installed and working.

Any help would be great, thank you.

**Comment by alexkrebiehl** [comment]
You may need to configure the `connection` block with the host. You can reference the host that the guest agent finds with `self.ssh_host`.  

You may also be running into the issue that I did, which is that the provider doesn't wait long enough for the guest agent to have an IP ready (it was only waiting ~60 seconds, which wasn't enough for me). I've made a pull request (#293) to make the timeout configurable, as well as bump up the default to 600 seconds.

**Comment by ProfessorSalty** [comment]
I've got the same issue. `qemu-guest-agent` is installed, the service is running, and I can successfully ping (`qm agent 333 ping`) from the Proxmox host. 

```
resource "proxmox_vm_qemu" "proxmox_resource" {
  name        = "test"
  target_node = "vm1"
  vmid        = 333
  agent       = 1
  clone       = "ubuntu-20.04-template"
  cores       = 1
  memory      = 2048
  balloon     = 2048
  onboot      = true
  full_clone  = false
  boot        = "c"
  os_type     = "ubuntu"
  hotplug     = "network,disk,usb"
  define_connection_info = true

  network {
    model  = "virtio"
    bridge = "vmbr1"
  }

  ssh_user        = "toor"
  ssh_private_key = "myprivatekey"

  connection {
    type        = "ssh"
    host        = self.ssh_host
    user        = self.ssh_user
    private_key = self.ssh_private_key
    port        = self.ssh_port
  }

  provisioner "remote-exec" {
    inline = ["sudo hostnamectl set-hostname  ${var.hostname}"]
  }
}
```

This errors out with `Error: host for provisioner cannot be empty`. If I remove the remote-exec provisioner, the vm stands up and I can inspect the state. 

```
...
  "ssh_host" = ""
  "ssh_port" = "22333"
  "ssh_private_key" = "myprivatekey"
  "ssh_user" = "toor"
...
```

So, not only is the `ssh_host` empty, but `ssh_port` is completely wrong. I'd love some input on what to investigate next.

**Comment by pythonTaotao** [comment]
no method to get private IP address, this terraform-provider-proxmox bug ,only can get static ip ,if vm get ip by dhcp , Error: host for provisioner cannot be empty,please fix bug

this way is ok

 provisioner "remote-exec" {
    inline = [
      "sudo hostnamectl set-hostname servera"
    ]
    connection {
      host          = "10.19.8.119"
      type          = "ssh"
      user          = "test"
      #password      = "123456" 
      private_key   = "${file("~/.ssh/id_rsa")}"
    }
  }

**Comment by pythonTaotao** [comment]
no method to get private IP address, this terraform-provider-proxmox bug ,only can get static ip ,if vm get ip by dhcp ,` Error: host for provisioner cannot be empty`,please fix bug

this way is ok

```
provisioner "remote-exec" {
inline = [
"sudo hostnamectl set-hostname servera"
]
connection {
host = "10.19.8.119"
type = "ssh"
user = "test"
#password = "123456"
private_key = "${file("~/.ssh/id_rsa")}"
}
}
```

**Comment by ProfessorSalty** [comment]
I've figured it out. In order for `self.ssh_host` to have a value, you must either have `os_type = 'cloud-init'` **and** set `ipconfig0 = "ip=dhcp"` _or_ set `ssh_forward_ip` to some static value. It will _not_ get the VM's ip address unless one of these conditions are met. Also make sure that your template is set up to run cloud-init.

This is now my `main.tf` file:

```
resource "proxmox_vm_qemu" "proxmox_resource" {
  name        = "test"
  target_node = "vm1"
  vmid        = 333
  agent       = 1
  clone       = "ubuntu-20.04-template"
  cores       = 1
  memory      = 2048
  balloon     = 1
  onboot      = true
  full_clone  = false
  boot        = "c"
  os_type     = "cloud-init"
  hotplug     = "network,disk,cpu"
  ipconfig0   = "ip=dhcp"

  network {
    model  = "virtio"
    bridge = "vmbr1"
  }

  ssh_user        = "toor"
  ssh_private_key = file("~/.ssh/id_rsa")

  connection {
    type        = "ssh"
    host        = self.ssh_host
    user        = self.ssh_user
    private_key = self.ssh_private_key
    port        = self.ssh_port
  }

  provisioner "remote-exec" {
    inline = ["echo ${var.password} | sudo -S -k hostnamectl set-hostname mediaserver"]
  }
}
```

Now, if I run this with the `remote-exec` provisioner disabled (comment it out), then I can get `ssh_host` from `terraform output`, but if I try to run the provisioner, it gives me the same ol' error about host being empty. This seems like it's a race condition where the proxmox resource doesn't set `ssh_host` before running the `connect` block, but I just don't know. I tried using a null resource block, but the result doesn't change.

**Comment by pythonTaotao** [comment]
you way is ok i`m resolve my problem .thanks @ProfessorSalty

**Comment by mleone87** [comment]
nice! maybe this is not clear form the docs

can we close it @ggongaware ?

**Comment by nmcbride** [comment]
That's similar to how I figured it out as well. I wonder why this provider doesn't have any outputs like others do?

**Comment by ProfessorSalty** [comment]
@mleone87 Reading the documentation, my assumption was that `ssh_host` would be populated by the vm's ip unless overridden by other inputs:

> Read-only attribute. Only applies when define_connection_info is true. The hostname or IP to use to connect to the VM for preprovisioning. This can be overridden by defining ssh_forward_ip, but if you're using cloud-init and ipconfig0=dhcp, the IP reported by qemu-guest-agent is used, otherwise the IP defined in ipconfig0 is used.

**Comment by ProfessorSalty** [comment]
So, the above configuration works, but not every time. Sometimes `ssh_host` has a value, other times it doesn't, but I can't get it to work predictably.

**Comment by ProfessorSalty** [comment]
I now have a complete, reliable, and working solution. Create a helper script:

`wait_port`
```
#!/bin/bash

while ! nc -z $1 $2; do
  sleep 5
done
```

`main.tf`
```
esource "proxmox_vm_qemu" "proxmox_resource" {
  name        = "test"
  target_node = "vm1"
  vmid        = 333
  agent       = 1
  clone       = "ubuntu-20.04-template"
  cores       = 1
  memory      = 2048
  balloon     = 2048
  onboot      = true
  full_clone  = false
  boot        = "c"
  os_type     = "cloud-init"
  hotplug     = "network,disk,cpu"
  ipconfig0   = "ip=dhcp"

  ssh_user = "toor"

  network {
    model  = "virtio"
    bridge = "vmbr1"
  }
}

resource "null_resource" "wait_for_reboot" { // Use this to pause until the VM is built and accessible
  depends_on = [proxmox_vm_qemu.proxmox_resource]

  provisioner "local-exec" {
    command     = "${path.module}/wait_port ${proxmox_vm_qemu.proxmox_resource.ssh_host} ${proxmox_vm_qemu.proxmox_resource.ssh_port}"
    working_dir = path.module
  }
}

resource "null_resource" "set_hostname" {
  depends_on = [null_resource.wait_for_reboot] 

  connection {
    type     = "ssh"
    host     = proxmox_vm_qemu.proxmox_resource.ssh_host
    user     = proxmox_vm_qemu.proxmox_resource.ssh_user
    port     = proxmox_vm_qemu.proxmox_resource.ssh_port
  }

  provisioner "remote-exec" {
    inline = [
      "echo ${var.sudo_password} | sudo -S -k hostnamectl set-hostname testserver", 
      "echo ${var.sudo_password} | sudo -S -k reboot"
      ]
  }
}
```

**Comment by mleone87** [comment]
@ProfessorSalty I dont understand if it could be an issue caused by the performance of your proxmox server? Could it be?

**Comment by ProfessorSalty** [comment]
@mleone87 For all I know, it could be. I've got a really beefy system on a local gigabit network though, so I imagine this solution will apply for most people running homelabs on consumer hardware. Since I'm not running a super-optimized data center, there could be some latency in my setup somewhere that I just can't fix. I'm happy to pinpoint the issue with the help of someone more knowledgeable about the project if it's worth their time but I've reached the end of my capacity with Go, Proxmox, and Terraform.

**Comment by mleone87** [comment]
@ProfessorSalty does this scales nice with 3 or 4 vms created at one time?

**Comment by ProfessorSalty** [comment]
That's a very good question. I've never built more than one because this issue has blocked me from setting up my vms. I'll try it out tonight.

**Comment by alexkrebiehl** [comment]
The issue for me was the short timeout when waiting for an IP address, which I addressed in #293 - there's no need for a helper script. The build isn't released yet, but you can test with the artifact built here: https://github.com/Telmate/terraform-provider-proxmox/actions/runs/494029832 and let me know if that fixes the issue for you as well.

**Comment by patrick-mota** [comment]
Thank you @ProfessorSalty for the work around.
Doesn't work for me because I have muliple VM created with the count var.

Thank you @alexkrebiehl for the fix, can you explain how to use the artifact ?
I only know how to use the "version" in provider which is the release number.

**Comment by patrick-mota** [comment]
After some days trying nothing works I give up.
For the solution from @ProfessorSalty I don't see how it works because your script relies on /wait_port ${proxmox_vm_qemu.proxmox_resource.ssh_host} so if ssh_host is empty (which is the main problem here, ppl don't getting the host) you don't get it either as argument of wait.

**Comment by BaldFabi** [comment]
I created a PR (#316) (which is already merged). With a new release you should be able to use the var `default_ipv4_address` in your provisioners.
Obviously works only if the agent is running and vm tools are installed. Hope this helps, if I misunderstood something in this thread just ignore this post 😄

**Comment by patrick-mota** [comment]
Thank you @BaldFabi for the moment I can get the ip from ssh host with the fix from @alexkrebiehl but default_ipv4_address makes more sense since it's the ip and the host could be different.

Hope we get a release soon, I see a lot of people waiting for a new one but I don't know how we can help the maintainer to test the future release.

**Comment by ProfessorSalty** [comment]
What's the current status on this? Has @BaldFabi's fix been released?

**Comment by patrick-mota** [comment]
@ProfessorSalty if you look the commit, it's released:

https://github.com/Telmate/terraform-provider-proxmox/commit/0db239b9370eadb309f6d5e5f3006cba56417558

2.6.8

I have stop using this provider ( and terraform ) because I've always problems with multiple vm creation with dynamic ip...

Now I just use Ansible and does the job... wished I could continue to use Terraform :(
