### ISSUE TITLE
Using cloud-init on non-clones

### ISSUE THREAD

**Issue by prologic** [Telmate/terraform-provider-proxmox#274]
When I try to use cloud-nit  parameters on a standard VM with an OS booted either via Disk or CD-ROM that supports cloud-init I get this error:

```#!console
proxmox_vm_qemu.test[0]: Creating...

Error: Cloud-init parameters only supported on clones or updates
``

Why do we restrict this? I know for a fact that you can create a VM in Proxmox manually via the GUI with a "Cloud Drive" attached and "Cloud Init" parameters filled in and with a valid OS that understands how to deal with that, things just work™

Can we lift this restriction, create a "Cloud Drive" and attach it to the VM as part of it's "Hardware" for non-clone(s)?

**Comment by prologic** [comment]
Is there any traction at all on this? Am I the only one that _believes_ this limitation of this provider is insane? :D

**Comment by mleone87** [comment]
How would be the creation flow in this case? Create a vm with a (cloud-init ready) disk Image? Thats a tricky thing to do also from the cli

It would be the same procedure to create an actual clone, plus I think that only root can manipulate disks

**Comment by prologic** [comment]
That's exactly how you do it from the GUI now:

- Create VM
- Attach/create a Clouddrive
- Configure said Clouddrive

No clone necessary.

**Comment by mleone87** [comment]
still missing the point, if i do this in the gui i will end up in boot nothing

**Comment by prologic** [comment]
> still missing the point, if i do this in the gui i will end up in boot nothing

It's in fact you that missed the point. I can create a VM from an ISO today, install to Disk and create a CloudDrive (ISO) to configure it as boot time. I do this all the time.

What I don't understand is why we ever have to bother with clones at all. If I have an ISO, I should be able to just install to disk, create an appropriate CloudDrive with the user-data I want and reboot the newly created VM.

**Comment by blackliner** [comment]
Any updates here? I really do not want to have to create templates manually :-/

**Comment by blackliner** [comment]
Thanks @vrubiolo , thats more or less the exact copy of what I have in place 😄

**Comment by vrubiolo** [comment]
> Thanks @vrubiolo , thats more or less the exact copy of what I have in place smile

Hahaha, yes I figured you might have that already in place, that was mostly for sharing/comparing approaches :)

> 
> Regarding your comment towards @prologic: I guess what we are looking for is a way to tell the "create new VM" GUI to populate the new disk with the content from a cloud-init-ready IMG?

Ah! You mean that instead of choosing an ISO, you can directly pick up a disk raw image? That would be very useful indeed: just start a new VM from this disk image (instead of an ISO), add in the cloud-init config and off you go, w/o the need for an existing template.

I agree it looks elegant. In my case I use Terraform and I have to manuall run the template creation shell script as this cannot be setup w/ Terraform AFAIK (which relies on either clone or ISO). Not sure if this is a Proxmox API limitation though ...
