### ISSUE TITLE
Issue with field desc

### ISSUE THREAD

**Issue by DblK** [Telmate/terraform-provider-proxmox#281]
Hi,

First, thx for your provider, it is very useful!
The issue I have, is a template with a `desc` field (`Notes` inside proxmox ui).

During the clone process, the value is set to something `temporary value clone` and then set back to the template value.
Everytime, I launch `terraform apply`, it shows a diff because of this field. If I remove it manually from the ui then the `terraform apply` does not bother me anymore.

I do not know if you need additional informations, if yes ping me ;)

**Comment by markopolo123** [comment]
hi @DblK 

I find that Proxmox like to add a new line at the end of the notes created via API, which may be the source of your diff. 

Try adding `\n` to your template (may need escaping for terraform to handle it)

Example from my use case with Ansible groups:
```
  description = "{\"groups\": [\"consul\"]}\n"
```
