### ISSUE TITLE
Bootdisk empty after clone

### ISSUE THREAD

**Issue by tabnul** [Telmate/terraform-provider-proxmox#282]
When i clone my newly created images ( ubuntu 20.0.4 ) for some reason the boot order gets messed up.
Value: (no bootdisk), any CD-ROM, any net
For this reason,the machine does not boot or perform cloud-init.

At first i had this early in my pipeline where i create the image, this exact same behaviour occurred in PAcker since last proxmox release. See the following isssue.
https://github.com/hashicorp/packer/issues/10252

So now , even though my source image is functioning (after patching packer and re-creating the image), the clone has the exact issue as described in the packer issue.

For the record, when i manually set the bootorder, it boots up correctly and performs cloud-init...
Note: My old ubuntu images (18.0.4. create in older proxmox version back in 07-2020) do not have this issue! 
Settings of old and new image are identical, at least in the GUI!

Can it be a combination issue?
- image create in latest proxmox version (maybe even with packer?)
- image cloned by latest terraform and terraform provider

**Comment by tabnul** [comment]
Ok, i think the cloning issue is caused by the missing ' bootdisk' . 
The question is then; is bootdisk mandatory? Apparently latest packer does not add the bootdisk specifically. However the boot order is accepted by Proxmox and visually ok, untill the terraform provider clones this image.

Config of working old image:
```
agent: 1
boot: cdn
bootdisk: scsi0
cores: 2
cpu: kvm64
hotplug:
ide2: none,media=cdrom
ide3: local-lvm:vm-115-cloudinit,media=cdrom
memory: 1024
name: ubuntu1804
net0: e1000=0E:FD:F2:1E:AE:C9,bridge=vmbr0
numa: 0
onboot: 0
ostype: other
scsi0: local-lvm:base-115-disk-0,format=raw,media=disk,size=3G
scsihw: lsi
smbios1: uuid=4603cefa-713e-4c0f-9d7e-f4ca14032478
sockets: 1
template: 1
vmgenid: 8b82407f-142a-45c7-b2f9-108efac517e8
```

Config of broken image (after clone it does not boot)
```
agent: 1
boot: order=scsi0;ide2;net0
cores: 2
cpu: kvm64
ide2: none,media=cdrom
kvm: 1
memory: 1024
name: ubuntu2004-bios
net0: e1000=F2:D4:2E:81:52:AA,bridge=vmbr0,firewall=0
numa: 0
onboot: 0
ostype: other
scsi0: local-lvm:base-122-disk-0,format=raw,iothread=0,media=disk,size=5G
scsihw: lsi
smbios1: uuid=10ef4944-2fc2-4544-870e-f7f70adce2cb
sockets: 1
template: 1
vmgenid: 6cc7039d-c64c-4218-906a-65bc3d4784ad

```

**Comment by tabnul** [comment]
manually cloning the new image results in a  correct clone.
i see in the code that 'bootdisk' is specifically read from the VM config . Why is that, and is it neccesary?

**Comment by clayshek** [comment]
I have the same issue outlined above. I am able to work around by applying the suggestion here: https://github.com/hashicorp/packer/issues/10353#issuecomment-753697549

Passing `boot = "order=scsi0;ide2;net0`" to the provider enables the clone to start correctly.

**Comment by elreydetoda** [comment]
> I have the same issue outlined above. I am able to work around by applying the suggestion here: [hashicorp/packer#10353 (comment)](https://github.com/hashicorp/packer/issues/10353#issuecomment-753697549)
> 
> Passing `boot = "order=scsi0;ide2;net0`" to the provider enables the clone to start correctly.

This seems to be the preferred, and future, behavior at least in proxmox 6.4-4. It appears that the `cdn` (which is the current default behavior of this provider) is legacy and deprecated (at least according to the api docs on my proxmox instance).

![image](https://user-images.githubusercontent.com/10230166/120875775-96685000-c57b-11eb-8b68-f91ac58d0545.png)

**Comment by daks** [comment]
After hours of playing with Packer and Terraform on Proxmox I finally found this issue

> Passing `boot = "order=scsi0;ide2;net0`" to the provider enables the clone to start correctly.

And this solve my problem, thanks @clayshek
