### ISSUE TITLE
proxmox insists on creating a new disk when update cloud-init/qemu resource

### ISSUE THREAD

**Issue by mgebundy** [Telmate/terraform-provider-proxmox#283]
Despite there only being a single disk defined in hcl, when I update the resource, a brand new disk is created, breaking the vm.

Here's the resource definition I start with:

```hcl
resource "proxmox_vm_qemu" "vm" {
    depends_on        = [
        null_resource.vm_user_data
    ]
    name              = "vm1"
    target_node       = "home"

    clone             = "vm-cloud-init-template"

    os_type           = "cloud-init"
    cores             = 1
    sockets           = "1"

    cpu               = "host"
    memory            = 4096
    scsihw            = "virtio-scsi-pci"
    bootdisk          = "scsi0"

    cicustom = "user=local:snippets/user-data.yml"

    disk {
        size            = "5G"
        type            = "scsi"
        storage         = "local-lvm"
        iothread        = true
    }

    network {
        model           = "virtio"
        bridge          = "vmbr0"
    }

    lifecycle {
        ignore_changes  = [
            network,
            desc
        ]
    }
}
```

When I make a change to the resource, such as ONLY bumping `cores` from 1 to 2, a new disk is created.

![image](https://user-images.githubusercontent.com/584925/103487305-520d3400-4dd2-11eb-9a33-f39b5c928963.png)

Adding "disk" to the `ignore_changes` list doesn't seem to make any difference, I'm stumped.

**Comment by mleone87** [comment]
can you make some test with a simpler config? this issue should be fixed

**Comment by mgebundy** [comment]
> can you make some test with a simpler config? this issue should be fixed

can you please point to where this is fixed? I can try making a simpler config, but to what end?

**Comment by mleone87** [comment]
> 
> 
> > can you make some test with a simpler config? this issue should be fixed
> 
> can you please point to where this is fixed? I can try making a simpler config, but to what end?

PR #266 and #253 should have fixed this issues, the acceptance test in the cose works correclty with cloning/updating disk resources.

You could also delete all terraform files and make it download latest version of api and go provider

Also, what version of proxmox do you use?

**Comment by mgebundy** [comment]
Thanks.

I'm using the latest version of the provider that exists in the terraform registry, 2.6.6, I expect both those fixed made it into that release. I'm using Proxmox VE 6.2.

**Comment by mgebundy** [comment]
I think I've narrowed it down to the `disk.iothread`, if I don't set that value it, the drive isn't recreated.

I can reproduce the issue with this configuration:

```hcl
resource "proxmox_vm_qemu" "vm-1" {
    name              = "vm-1"
    target_node       = "home"

    clone             = "vm-template"

    cores             = 2

    disk {
        size            = "5G"
        type            = "scsi"
        storage         = "local-lvm"
        iothread        = true
    }
}
```

**Comment by mleone87** [comment]
@mgebundy you are right

the iothread parameter is declared ad bool in the provider but proxmox espects an int
somehow, when creating a resource with iothread = true, the parameter gets converted to an int and it works, but when changed the api gives an int that confuses the api

changing the parameter to int in the provider code should fix, I've done some quick tests and it works

we should submit a PR

**Comment by msbence** [comment]
The PR is merged, but it should have contain an updated documentation as well. now it's outdated :(

**Comment by msbence** [comment]
This is fixed by https://github.com/Telmate/terraform-provider-proxmox/pull/287 and https://github.com/Telmate/terraform-provider-proxmox/pull/286, I think it can be closed! @ggongaware
