### ISSUE TITLE
Unused disk is created on change unless I specify volume and file.

### ISSUE THREAD

**Issue by asenmx** [Telmate/terraform-provider-proxmox#284]
Hello, I've noticed that when i change something new unused disk is created and used as "boot" which breaks my vm.

```
resource "proxmox_vm_qemu" "dc0test" {
  provider = "proxmox.dc0"
  target_node = "dc0n5"
  vmid = "8407"
  clone             = "Ubuntu-18.04LTS-wCI-4-tpl"
  full_clone      = true
  name              = "vm-1-tf-test"
  cores             = 2

  bootdisk = "scsi0"
  disk {
    size            = "5G"
    type            = "scsi"
    storage         = "vm-ssd"
    file = "vm-8407-disk-0"
    volume = "vm-ssd:vm-8407-disk-0"

  }
}
```

If I do it like this it works, however if I remove the following 2 lines it creates new disk and puts it as boot drive.

```
    file = "vm-8407-disk-0"
    volume = "vm-ssd:vm-8407-disk-0"

```

Terraform v0.14.3
Installed telmate/proxmox v2.6.6

**Comment by mleone87** [comment]
@dabicata  why do you specify volume an file? it's redundant

also, removing them should create a new disk as you remove all the references to the working disk

**Comment by dabicata** [comment]
@mleone87 I want the first time created disk after the cloning to stay, but if I don't specify the volume and file new disk is created every time i apply the terraform.

**Comment by mleone87** [comment]
mm that's quite unusual and breaks the purpose of terraform

can you post the resource definition that creates a new disk every time you apply it?

**Comment by dabicata** [comment]
> mm that's quite unusual and breaks the purpose of terraform
> 
> can you post the resource definition that creates a new disk every time you apply it?

sure just remove the file and volume from the one i posted like this

resource "proxmox_vm_qemu" "dc0test" {
  provider = "proxmox.dc0"
  target_node = "dc0n5"
  vmid = "8407"
  clone             = "Ubuntu-18.04LTS-wCI-4-tpl"
  full_clone      = true
  name              = "vm-1-tf-test"
  cores             = 2

  bootdisk = "scsi0"
  disk {
    size            = "5G"
    type            = "scsi"
    storage         = "vm-ssd"

  }
}

**Comment by yukron** [comment]
That's definitely what is happening, new unused disk is created all the time if not strictly specified.

**Comment by mleone87** [comment]
@yukron 

can you post your terraform resource definition and you clone template configuration?

**Comment by yukron** [comment]
Hey @mleone87 ! Looks like it was already fixed and I've just were using quite old provider version for some reason. :) Updated it and everything works fine now.

**Comment by gsomoza** [comment]
This is happening to me as well using telmate/proxmox version 2.6.7. Proxmox VE is version 6.3-3 (without support license).

Here's my resource configuration:

```terraform
resource "proxmox_vm_qemu" "k3s_node" {
  name        = "k3s-node"
  desc        = "K3S Node"
  target_node = var.target_node

  os_type         = "cloud-init"
  clone           = var.template_name
  agent           = 1
  boot            = "c"

  cpu     = "kvm64"
  cores   = 8
  sockets = 1
  memory  = 8192

  disk {
      type    = "scsi"
      storage = "local-lvm"
      size    = "12G"
      backup  = 1
      ssd     = 1
      discard = "on"
    }
  }

  network {
    model  = "virtio"
    bridge = "vmbr0"
    tag    = var.vlan_id
  }

  lifecycle {
    ignore_changes = [
      network,
    ]
  }

  # Cloud-init params
  ipconfig0 = "ip=${cidrhost(var.subnet, count.index + 1)}/24,gw=${var.gateway}"

  ssh_user = "ubuntu"
  sshkeys  = var.ssh_keys
}
```

The cloud-init aspect works perfectly so I think you can ignore that. I'm pretty sure I was able to reproduce without cloud-init too, but that was several weeks ago.

Every single time I apply any changes to the VM created by the above definition (for example change "ssd" to 0, or even only change the number of cpu cores), the "scsi0" (boot) device on the VM gets replaced by a completely new volume created in "local-lvm". Under "hardware", the old volume then appears as "unattached". And the VM can't boot of course.

**Comment by gsomoza** [comment]
Seems this is similar (or the same) as #283

**Comment by gunzy83** [comment]
> Every single time I apply any changes to the VM created by the above definition (for example change "ssd" to 0, or even only change the number of cpu cores), the "scsi0" (boot) device on the VM gets replaced by a completely new volume created in "local-lvm". Under "hardware", the old volume then appears as "unattached". And the VM can't boot of course.

@gsomoza I have run into this also when trying to run `plan` with a second new VM in the configuration. I am new to using this resource and I was doing repeated apply/destroy cycles while testing cloud-init config. I commented out the new VM and still got this:

```
terraform plan
module.instance_student.null_resource.cicustom_snippets: Refreshing state... [id=6929365069489726756]
module.instance_student.proxmox_vm_qemu.vm: Refreshing state... [id=hive/qemu/100]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.instance_student.proxmox_vm_qemu.vm will be updated in-place
  ~ resource "proxmox_vm_qemu" "vm" {
        id                     = "hive/qemu/100"
        name                   = "student"
        # (30 unchanged attributes hidden)

      - disk {
          - backup       = 0 -> null
          - cache        = "none" -> null
          - file         = "vm-100-disk-0" -> null
          - format       = "raw" -> null
          - iothread     = 0 -> null
          - mbps         = 0 -> null
          - mbps_rd      = 0 -> null
          - mbps_rd_max  = 0 -> null
          - mbps_wr      = 0 -> null
          - mbps_wr_max  = 0 -> null
          - replicate    = 0 -> null
          - size         = "20G" -> null
          - slot         = 0 -> null
          - ssd          = 0 -> null
          - storage      = "local-zfs" -> null
          - storage_type = "zfspool" -> null
          - type         = "virtio" -> null
          - volume       = "local-zfs:vm-100-disk-0" -> null
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```
The problem to me appears to be that when you create a clone, proxmox creates a disk in the cloning process (I don't have a disk in my config because I am only using the root disk from the clone and noticed an empty disk attached in an earlier apply so removed it) but when the provider updates state it does not know about the disk from the clone and wants to remove it. 

I think what we need here is a fix or advice on how to marry the disk created from the clone to a disk that is defined in the resource configuration. I haven't had time to look through the code yet but I will tonight after work.

**Comment by gunzy83** [comment]
I had a few mins to check out the source code and found a link to this issue in the code:
https://github.com/Telmate/terraform-provider-proxmox/issues/239

I am not doing a full clone though so the issue might be different. Based on that issue and the code, it seems that the slot variable may be the key here:
```
  disk {
    slot = 0
    size = "20G"
    storage = "local-zfs"
    type = "virtio"
  }
```
If I include the above it seems to work consistently and without issues (been through a number of quick create/destroy and update cycles.

I am not sure if this solves your issue but this might need to be documented.

**Comment by gsomoza** [comment]
Nice, thanks for taking the time to do that! I'll check if that works for me too in the next few days.

**Comment by lesykm** [comment]
Still reproducible (using version 2.7.4).
Any change to the VM (for example change cpu cores 2->1) lead to detaching original root disk and inserting empty one leaving machine unbootable.
Interesting fact:
Disc is always replaced with "raw" regardless of format of the initial disk and even if it is hardcoded as "qcow2" anyway it will be replaced with empty raw.
For example this is my disk config, and "qcow2" will be replaced with "raw" on "terraform apply"
```
  disk {
    type    = "scsi"
    storage = "shared"
    format  = "qcow2"
    size    = "16Gb"
    backup  = 1
    discard = "on"
  }
```

**Comment by onaimat** [comment]
Still producable on 
Terraform v 1.0.0
Telmate v 2.9.6
Proxmox v 7.1-11

**Comment by jsbrain** [comment]
Same issue here

**Comment by DoktorAerzt** [comment]
We had the same error. After digging around i found the problem. 

Terraform was reporting 
```
[ERROR] setting state: disk.1.backup: '' expected type 'int', got unconvertible type 'bool', value: 'true'
``` 
And after that the volume name was not set in the tfstate file. 

So when you don`t set the backup value (Witch is just a workaround) then the volume name should be in the tfstate file.

**Comment by ol3d** [comment]
Same issue here
Terraform v1.3.0
Telmate v2.9.14
Proxmox v7.4-14

**Comment by Barsonax** [comment]
Happens for me sometimes as well. If I run terraform apply multiple times it will sometimes try to change the disk and sometimes not. Really inconsistent.

**Comment by lotusnoir** [comment]
Same issue here
Terraform v1.6.3
Telmate v2.9.14
Proxmox v8.0.4

**Comment by dung-tien-nguyen** [comment]
Configure the disk according to the new version syntax. It's worked for me. ([link](https://github.com/Telmate/terraform-provider-proxmox/blob/master/examples/pxe_example.tf#L52C1-L72C1))
```
    disks {
        scsi {
            scsi0 {
                disk {
                    backup             = true
                    cache              = "none"
                    discard            = true
                    emulatessd         = true
                    iothread           = true
                    mbps_r_burst       = 0.0
                    mbps_r_concurrent  = 0.0
                    mbps_wr_burst      = 0.0
                    mbps_wr_concurrent = 0.0
                    replicate          = true
                    size               = 32
                    storage            = "local-lvm"
                }
            }
        }
    }

```
