### ISSUE TITLE
add this to terraform community providers

### ISSUE THREAD

**Issue by billimek** [Telmate/terraform-provider-proxmox#29]
Is there any interest in adding this to the [Terraform Community Providers page](https://www.terraform.io/docs/providers/type/community-index.html)?

If so, there is a [form](https://docs.google.com/forms/d/e/1FAIpQLSeenG02tGEmz7pntIqMKlp5kY53f8AV5u88wJ_H1pJc2CmvKA/viewform#responses) to add the repo.

**Comment by ggongaware** [comment]
Yes, I think see Proxmox 5.2 started supporting cloud-init, we are much closer to sharing with the whole community.

This project probably needs a Makefile and some unit tests still. But I'll start the process

**Comment by sticky-note** [comment]
@ggongaware 
To have an example of a meta-issue 
This project is soon pushable to the module registry.
https://github.com/dmacvicar/terraform-provider-libvirt/issues/605
If hands are needed I want myself to contribute/monitor this provider to "standardize" it

**Comment by sticky-note** [comment]
@ggongaware Provider is now listed on community providers
https://www.terraform.io/docs/providers/type/community-index.html

**Comment by ggongaware** [comment]
Becoming official sounds appealing. I don't get to spend a lot of time supporting this project, I would love the help making it better. I'll look into the proxmox partner process.

**Comment by sticky-note** [comment]
Do we close this issue and open another for this problematic ?
