### ISSUE TITLE
2.6.6 - Disk format not being applied (raw instead of qcow2)

### ISSUE THREAD

**Issue by chicolatino** [Telmate/terraform-provider-proxmox#291]
I'm doing a full clone of a VM, that has a boot disk setup with qcow2 (this one stays qcow2), but any additional disks get created as "raw" even when format is set to "qcow2".

```
  disk {
    type         = "scsi"
    storage      = "VMs"
    size         = "100G"
    format       = "qcow2"
    discard	 = "on"
  }

  disk {
    type         = "scsi"
    storage      = "VMs"
    size         = "30G"
    format       = "qcow2"
    discard	 = "on"
  }
```
If I run `terraform plan` after creating the VM, terraform sees the issue and reports it:
```
      ~ disk {
          ~ format       = "raw" -> "qcow2"
            # (18 unchanged attributes hidden)
        }
````
Running `terraform apply` takes a while but nothing actually changes in the VM configuration.

I'm guessing that the desired value of "qcow2" is not actually being passed to Proxmox and the default value "raw" is being used instead.  I looked at the code but couldn't figure where this is being done.

**Comment by adepretis** [comment]
I can confirm this problem - only the first disk is created in qcow2-format, additional ones are always raw.

**Comment by antton** [comment]
Hi, 

Is there any intention to implement this functionality?

https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/move_disk

This would be the way to convert from one format to an other.

**Comment by adepretis** [comment]
This issue is not about converting or moving disks but retaining the existing disk format after initial creation. This is still a major issue when working with this provider and a dangerous situation in production environments!

**Comment by elreydetoda** [comment]
So, it looks like it might be happening during the clone request getting made...

I noticed that when the proxmox provider does the clone POST it doesn't specify a format, but it passing the target storage.

![image](https://user-images.githubusercontent.com/10230166/120876365-53f44280-c57e-11eb-9589-597a8d6f9677.png)

By the time the proxmox provider goes to read the config for the running vm before it applies the new config changes, the disk is already in a .raw form. So, that is why I think it is happening during the clone.

In my proxmox api it looks like the raw option is first, whenever you go to clone a vm, and so it is probably just defaulting to .raw since that is the first option. I also came to this conclusion, because in the web-ui if you don't specify a target source then it just says "Same as source" and the format option is greyed out.

![image](https://user-images.githubusercontent.com/10230166/120876491-f0b6e000-c57e-11eb-8a4c-a18e1b0e9992.png)

So, if they didn't specify a target source or if they sent along the format along with the clone request then either should ( I believe ) fix this issue.

Still very new to proxmox, so maybe I am completely wrong but that is just my take from observing the debug logs and looking at the web-ui.

**Comment by bryanpedini** [comment]
This happens on new-from-scratch VMs too, not just clones.
<details>
<summary>My config</summary>

```ini
resource "proxmox_vm_qemu" "firewall_casa_pedini_lan" {
  name                   = "firewall.casa.pedini.lan"
  target_node            = "homepve"
  vmid                   = 1000
  define_connection_info = false
  onboot                 = true
  boot                   = "c"
  agent                  = 0
  iso                    = "local:iso/pfSense-CE-2.5.2-RELEASE-amd64.iso"
  qemu_os                = "l26"
  memory                 = 1024
  balloon                = 1024
  sockets                = 1
  cores                  = 2
  cpu                    = "kvm64"
  numa                   = true
  scsihw                 = "virtio-scsi-pci"
  network {
    model    = "virtio"
    bridge   = "vmbr0"
    firewall = false
  }
  network {
    model    = "virtio"
    bridge   = "vmbr0"
    firewall = false
  }
  network {
    model    = "virtio"
    bridge   = "vmbr1"
    firewall = false
  }
  disk {
    type    = "scsi"
    storage = "local"
    size    = "20G"
    format  = "qcow2"
    backup  = 1
    discard = "on"
  }
}

resource "proxmox_vm_qemu" "docker_casa_pedini_lan" {
  name         = "docker.casa.pedini.lan"
  target_node  = "homepve"
  vmid         = 1001
  onboot       = true
  boot         = "c"
  agent        = 1
  clone        = "debian-11-amd64-cloudinit"
  qemu_os      = "l26"
  memory       = 1024
  balloon      = 1024
  sockets      = 1
  cores        = 2
  cpu          = "kvm64"
  numa         = true
  scsihw       = "virtio-scsi-pci"
  os_type      = "cloud-init"
  ciuser       = "root"
  cipassword   = "r00t"
  searchdomain = "casa.pedini.lan"
  nameserver   = "192.168.10.250"
  ipconfig0    = "ip=192.168.10.252/24,gw=192.168.10.254"
  sshkeys      = <<EOL
ssh-rsa AAAAB3NzaC1yc ........
EOL
  network {
    model    = "virtio"
    bridge   = "vmbr0"
    firewall = false
  }
  disk {
    type    = "scsi"
    storage = "local"
    size    = "20G"
    format  = "qcow2"
    backup  = 1
    discard = "on"
  }
}

resource "proxmox_vm_qemu" "orchestrang_casa_pedini_lan" {
  name                   = "orchestrang.casa.pedini.lan"
  target_node            = "homepve"
  vmid                   = 1002
  define_connection_info = false
  onboot                 = true
  boot                   = "c"
  agent                  = 0
  iso                    = "local:iso/CentOS-7-x86_64-Minimal-2009.iso"
  qemu_os                = "l26"
  memory                 = 6144
  balloon                = 4096
  sockets                = 1
  cores                  = 4
  cpu                    = "kvm64"
  numa                   = true
  scsihw                 = "virtio-scsi-pci"
  network {
    model    = "virtio"
    bridge   = "vmbr0"
    firewall = false
  }
  disk {
    type    = "scsi"
    storage = "local"
    size    = "30G"
    format  = "qcow2"
    backup  = 1
    discard = "on"
  }
}
```
</details>

And this creates indesired output as well (storage is not calculated as you can see from the difference between `1xxx` machines (terraform created) and `2xxx` machines (manually created), and with `define_connection_info = false` making terraform think that that needs to be changed every single time, it creates loads of copies of the disk, detaching the disk with the OS and attaching new blank disks. VERY VERY VERY BAD!):
![Screenshot_20211030_114309](https://user-images.githubusercontent.com/45012292/139528232-43aeee7f-02e2-4845-804e-a24899abf69e.png)
![Screenshot_20211030_114446](https://user-images.githubusercontent.com/45012292/139528233-367a2657-8c67-424f-a401-cecbbec8752f.png)

**Comment by mateusmuller** [comment]
for me too, even though I'm forcing disks to be raw, it still drifts on terraform not sure why

```
      ~ disk {
          + format               = "raw"
            id                   = 0
            # (28 unchanged attributes hidden)
        }
```
