### ISSUE TITLE
Remove disk/network doesn't work

### ISSUE THREAD

**Issue by sophiexiaoyan** [Telmate/terraform-provider-proxmox#298]
When I try to remove a disk or network interface, terraform apply shows it's successful. But when I check on Proxmox UI or check with terraform show, the disk or the network interface is still there. They are not really removed by the provider. 

Terraform v0.13.0
telmate/proxmox v2.6.7
Proxmox 5.4-5

**Comment by msbence** [comment]
Hi @sophiexiaoyan,

Is it shown as a pending change on PVE side (ie.: in orange)?
Did the VM reboot?

Ps.: Your PVE version is pretty out of date, I'm not sure this provider supports it.

**Comment by sophiexiaoyan** [comment]
@msbence  Thank you for your quick reply. It's not shown as pending change on PVE side. The VM did reboot. But in fact, removing a disk doesn't require VM to reboot to take effect. I also test with Proxmox 6.2-4, it doesn't work also. I find there was a issue open long time ago for proxmox-api-go: https://github.com/Telmate/proxmox-api-go/issues/67. Maybe it's related?

**Comment by mleone87** [comment]
@sophiexiaoyan this is a problem from the api and/or the provider for sure.
The disk/network part is still under heavy work, resource deletion/update is very buggy
