### ISSUE TITLE
How to enable PCI passthrough

### ISSUE THREAD

**Issue by pitwegner** [Telmate/terraform-provider-proxmox#299]
I want to extend my cluster with some GPU machines using Proxmox. Proxmox itself provides support for this using PCI passthrough, however this is does not seem to be currently supported by the terraform provider. What can I do to enable this?

**Comment by msbence** [comment]
I'm afraid you can not add PCI devices at this time. This requires work both in this repo, and the proxmox-api-go repo as well.

**Comment by yuqo2450** [comment]
Are there any plans to include this in future versions?

**Comment by yuqo2450** [comment]
Hi there,
if I am right @Neonox31 recently added support to passthrough USB devices to qemu vms in #490. In the GUI it seems kind of similar with PCI devices. So is this working as well now or can you probably add this easily?

**Comment by dronenb** [comment]
It seems like this issue, #632, and #638 are all addressing the same thing, but this feature is supposedly already in the master branch from [this PR](https://github.com/Telmate/terraform-provider-proxmox/pull/618) and was included in [release v2.9.12](https://github.com/Telmate/terraform-provider-proxmox/releases/tag/v2.9.12).

**Comment by yuqo2450** [comment]
Hey @dronenb,
I read the release notes and they state that this was added in v2.9.12.
As already mentioned in #632 there is still no documentation on how to use it, would be amazing to get some.
Do you have some examples?

**Comment by dronenb** [comment]
I would be happy to add this to the documentation. Sadly though, I'm currently blocked from testing until PR #720 is merged, as I'm experiencing #701. Once that PR gets merged and a new release is out, I will see if I can add that documentation.

**Comment by dronenb** [comment]
Now that release v2.9.14 is out, I was able to try this. The block @yuqo2450 provided is almost correct, should be something like:
```
hostpci {
  host = "0000:02:00"
  rombar = 1
  pcie = 0
}
```
In your `proxmox_vm_qemu` resource. Note the `pcie` instead of `hostpcie`. See the following screenshot to show what these options correspond to in the GUI:

<img width="602" alt="Screenshot 2023-03-27 at 11 43 52" src="https://user-images.githubusercontent.com/13852784/227993378-6fc36753-f900-4171-8b47-db43ad89138e.png">


The only caveat of doing this is that it seems this can only be done by the root user, otherwise you get an error like:
```
Error: error creating VM: 500 only root can set 'hostpci0' config, error status: {"data":null} 
```

**Comment by dronenb** [comment]
I'm also realizing this is dependent upon #659, as in order to do PCIe passthrough (`pcie = 0`) the machine type has to be Q35.

**Comment by dronenb** [comment]
So just realized this too has been added and not documented, so here is what would need to be added:
```
resource "proxmox_vm_qemu" "example_vm" {
  machine     = "q35"
  hostpci {
    host   = "0000:02:00"
    rombar = 1
    pcie   = 1
  }
  ...(whatever else you have in this resource block)
}
```
Looking at the source code, it doesn't look like there is an option yet for setting `x-vga`, which is what the "Primary GPU" toggle in the UI does, so this issue is still relevant until that is added in...

**Comment by brutesque** [comment]
I never enable `x-vga` and haven't run into any issues and never detected any difference. What does it do for you?

**Comment by dronenb** [comment]
> I never enable `x-vga` and haven't run into any issues and never detected any difference. What does it do for you?

Honestly I am not sure exactly what it adds, but the Proxmox wiki explicitly recommends it when doing GPU passthrough: https://pve.proxmox.com/wiki/PCI_Passthrough#GPU_OVMF_PCI_Express_Passthrough

**Comment by rafstef** [comment]
after adding hostpci disk I receive the same error.
are there some workaround ?

│ Error: Invalid address to set: []string{"hostpci", "0", "id"}
│ 
│   with proxmox_vm_qemu.rke-node-pool[3],
│   on worker_node.tf line 1, in resource "proxmox_vm_qemu" "rke-node-pool":
│    1: resource "proxmox_vm_qemu" "rke-node-pool" {
│

**Comment by beautyfree** [comment]
hi, is it able to use at the moment?

I want to use terraform for the next proxmox deployment

**Comment by Tinyblargon** [comment]
@beautyfree currently working on network interfaces and usb. After that, pcie will get some love.

**Comment by m4rkireland** [comment]
Any thoughts on this one?
