### ISSUE TITLE
Timeout while waiting for VM creation

### ISSUE THREAD

**Issue by chriscameron** [Telmate/terraform-provider-proxmox#3]
I get a timeout while waiting for the VM to create, but I'm not sure I'm using this as intended. I created a template that uses that ISO on first boot. Was the intention to create the custom ISO and then to build a VM from that and then subsequently use that new template? Thanks for the help!

**Comment by ggongaware** [comment]
Did you create an ISO that follows these conventions? 

https://github.com/Telmate/terraform-ubuntu-proxmox-iso

(centos/redhat can work too if it has the same eth1, ssh keys prepared)

I've mostly been testing the clone VM approach, so there maybe timeout problems with the ISO approach

**Comment by chriscameron** [comment]
I did, in fact I used that repo to customize and then create the ISO. It looks like the timeout is hard coded in and it's just taking longer for it to boot and do everything from the ISO. I'll try creating a custom VM template with everything baked in and see how that goes. I kind of like the ISO method so maybe I'll revisit that and add a longer timer.
