### ISSUE TITLE
Network install (PXE) of virtual machines prevented by checks

### ISSUE THREAD

**Issue by kiu345** [Telmate/terraform-provider-proxmox#302]
Line 862 in **resource_vm_qemu.go**
    return fmt.Errorf("Either clone or iso must be set")
prevents install of systems via PXE.

If boot options contain 'network' (.tf content like 'boot = "cn"') then it should not be necessary to add a (placebo) ISO image to the VM.

**Comment by jqueuniet** [comment]
This is an issue for us. The current provider model is assuming either ISO or cloud-init, but Proxmox also allows other means like PXE boot or qemu arguments. Removing the requirement for either the iso or clone parameter would allow us to get rid of the dummy ISO in the IDE drive.

Another way to think about it would be to disable the provisioning step entirely, just create the VM definition in Proxmox and not even start it. Doing things this way would allow the provisioning to be handled externally, ie with a Python script adding qemu args to the VM, starting it and removing the args afterward, or anything else really.

**Comment by devudopw** [comment]
+1 for PXE boot use case.

**Comment by mathianasj** [comment]
This should not require net to be the first in the boot order it should be able to be anywhere present as sometimes pxe is used to provision the VM not always boot from it, a use case is in the creation of a coreos VM that writes to the hard drive and then should boot from the hd on all subsequent boots

**Comment by mcd1992** [comment]
Issue seems resolved by #495 and #492
