### ISSUE TITLE
What about the new release?

### ISSUE THREAD

**Issue by josebrutalsys** [Telmate/terraform-provider-proxmox#304]
First of all, thank you very much for this fantastic project. I have seen that there is a commit that solves the problems with the reboot of machines every time changes are applied (f53fcdb5aefe73248515c3a79f2d6b6de6258c1e) but this commit is not available in the terraform register, would it be possible to update the master changes with this register? How often or so is the register updated?
Thank you very much.

**Comment by msbence** [comment]
@ggongaware Could you please take a look? My commit mentioned above was merged more than 2 months now, and it's important to many people. Thank you! :)

**Comment by DreamyProtect** [comment]
+1 on this, there has been many commits that I'm interested in that have been merged into the master branch and not released so I can't use them... (they are d7953a9a6e3e3d955f5634e00568b808ef5dc08b and 217cbfd5a7b87a068f47855ceeb069c353a8a517). @ggongaware can you please create a release ?
I can also help you setting up a sementical versionning pipeline that will automatically create releases and changelogs each time you merge an MR to the master branch if you want.

**Comment by msbence** [comment]
Thank you! The issue can be closed I think :)

**Comment by josebrutalsys** [comment]
Thank you!! :-D
