### ISSUE TITLE
Feature: Authentication via api token and secret

### ISSUE THREAD

**Issue by 0xErnie** [Telmate/terraform-provider-proxmox#305]
Proxmox supports authentication via api token instead of passwords. These can have restricted privileges and a date of expiration.
When running terraform not localy it can be good idea not storing the account password on the remote executor(like gitlab or jenkins), regardless if you use PAM, LDAP or PVE as user database.

Implemetation should be rather simple in comparison to password authentication. I did this for an ansible module, check out the changes here: https://github.com/0xErnie/ansible-proxmox-api/commit/b202b4867cc644d8d1a318e8a515a311d1e019ff

[Proxmox documentation](https://pve.proxmox.com/pve-docs/chapter-pveum.html#pveum_tokens)

**Comment by mraerino** [comment]
i recently contributed this on the go sdk: https://github.com/Telmate/proxmox-api-go/pull/108

**Comment by 0xErnie** [comment]
This feature has been implemented in #337
Thank you @pgporada!
