### ISSUE TITLE
Way to target multiple proxmox nodes in "target_node"

### ISSUE THREAD

**Issue by ginjiruu** [Telmate/terraform-provider-proxmox#309]
If you have a proxmox cluster already defined how to you go about spreading the creation out across multiple nodes?
Is there a way to just have it round robin create a resource on each node in a list?

**Comment by jperez3** [comment]
@ginjiruu I've been doing it like this:

```
resource "proxmox_vm_qemu" "vm" {

	count           = var.vm_count
	target_node = element(var.proxmox_hosts, count.index)
```

where `proxmox_hosts` is a list of the proxmox names

**Comment by ginjiruu** [comment]
Yeah that seemed to have worked perfectly for me. Thanks a ton

**Comment by ginjiruu** [comment]
Does this work if you want to do more than 1 resouce per proxmox host?
Say 6 resources across 3 nodes?

**Comment by Strade28** [comment]
j'ai ecris à fanny et pdh 


De: "ginjiruu" <notifications@github.com> 
À: "Telmate/terraform-provider-proxmox" <terraform-provider-proxmox@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Envoyé: Mercredi 3 Mars 2021 13:12:17 
Objet: Re: [Telmate/terraform-provider-proxmox] Way to target multiple proxmox nodes in "target_node" (#309) 





Does this work if you want to do more than 1 resouce per proxmox host? 
Say 6 resources across 3 nodes?

**Comment by jperez3** [comment]
@ginjiruu yup, so when terraform is told to create more VMs than proxmox hosts, it will use the count index until the last host, then circle back to the first like this:

vm1  ---> proxmox1
vm2 ---> proxmox2
vm3 ---> proxmox3
vm4 ---> proxmox1
vm5 ---> proxmox2
vm6 ---> proxmox3
vm7 ---> proxmox1
...
...
...
