### ISSUE TITLE
support serial and wwn disk attributes

### ISSUE THREAD

**Issue by gurubert** [Telmate/terraform-provider-proxmox#311]
Proxmox allows to set serial and wwn attributes of virtual disks directly in the config file. There is currently no GUI support for this.

Please support these attributes also in the Proxmox provisioner.

Currently I am getting this error when trying to rerun `terraform apply` after modifying the VM config with a text editor:

`Error: Proxmox Provider Error: proxmox API returned new disk parameter 'serial' we cannot process`

**Comment by ebCrypto** [comment]
I am receiving the same error: 

Steps to reproduce:
1. provision a VM using `terraform apply`
2. add a disk with serial number in the proxmox UI

--> Any subsequent `terraform apply` will trigger the error

```
 Error: proxmox Provider Error: proxmox API returned new disk parameter 'serial' we cannot process
```

**Comment by markussiebert** [comment]
Getting the same error!
