### ISSUE TITLE
Incorrect links to resource docs

### ISSUE THREAD

**Issue by mjbright** [Telmate/terraform-provider-proxmox#313]
In the main documentation page, the links to the resources: proxmox_vm_qemu and proxmox_lxc are incorrect in the line:

```
This provider exposes two resources: proxmox_vm_qemu and proxmox_lxc.
```

Both links require correction replacing master/docs/docs/resources by master/docs/resources.

**Comment by msbence** [comment]
It will break the links in the registry. #296
