### ISSUE TITLE
Feature Request: Accept a list of nodes for target_node

### ISSUE THREAD

**Issue by Tiggum** [Telmate/terraform-provider-proxmox#320]
target_node only accepts a single proxmox node for VM instantiation which means you deploy everything per resource onto one proxmox node instead of the proxmox cluster. 

By having it accept a list you can have it distribute every vm created to each node until it runs out. 

e.g.

  count                  = 9
  name                  = "vm-${count.index + 1}"
  target_node        = [
    "pve1",
    "pve2",
    "pve3",
]

In this scenario it would place 3 VM's on each node of a 3 node proxmox cluster

**Comment by msbence** [comment]
I think this is not the providers task, rather proxmox's. You want something like VMware DRS, but proxmox can not distribute VMs automatically based on resource consumption.
Sidenote: you would also lose the ability to migrate VMs by hand from terraform.

**Comment by Tiggum** [comment]
I'm not sure why the provider being able to select a group of nodes would be outside of things it can accomplish.

I already have it operating in a fairly similar fashion just with worse syntax and it requiring nodes with a specific naming structure. I have mine distribute across pve1, pve2, pve3 below but it would fail if the names weren't setup like they are or if for some reason a number was skipped. 
`  target_node       = "pve${(count.index % 3) + 1}" `

Also, I may not want to distribute it VMs to all the nodes in the cluster but only specific ones which seems like it would be more suited to the provider. 

Could you elaborate on how this would prevent being able to migrate the VMs?

**Comment by msbence** [comment]
As far as I know, you can't even do the requested functionality in Proxmox VE itself. You HAVE to select a node to deploy the VM on.

Migration: The current behavior of the `target_node` attribute change is to migrate from node A to node B. Given your example snippet above: how would you migrate a VM from `pve1` to `pve3` using Terraform only?

**Comment by Tiggum** [comment]
But, I am selecting what node to place them on. 

I don't see why that would preclude you from changing `target_node: pve1` to `pve3`. 

To provide context i'm trying to deploy groups of identical VM's for a kubernetes cluster. If I wanted to migrate those VM's the proposed change would just do a new round robin on the new list and migrate them accordingly. It wouldn't be the most efficient thing in the world but it would be far more flexible.

**Comment by Cylindric** [comment]
I'm not sure this belongs in the provider either, as it's not something that Proxmox itself does. 
You can achieve this already in Terraform by doing it the way you have already with a `list % index` sort of approach.
Providers should really stick to implementing backend functionality, not baking in new business-logic that varies from environment to environment. For example, my three nodes are very different hardware, I'd want the selection to be `[1, 1, 1, 2, 2, 3]` because node1 is three times the capacity of node 3.

Getting Proxmox to implement a DRS equivalent would be far more agreeable :)

**Comment by gurubert** [comment]
I am solving this issue with this snippet:

`target_node     = element(var.nodes, count.index)`

where var.nodes is the list of nodes.

**Comment by Budman17r** [comment]
> I am solving this issue with this snippet:
> 
> `target_node = element(var.nodes, count.index)`
> 
> where var.nodes is the list of nodes.

Great idea, the element wraps around so it allows you to at least work through the list.  Thank you!
