### ISSUE TITLE
Constant errors:  proxmox API returned new network parameter 'hwaddr' we cannot process

### ISSUE THREAD

**Issue by vladistan** [Telmate/terraform-provider-proxmox#323]
After creating a qemu VM this providers constantly detects changes in the network config that do not actually exist.  Also trying to apply the stack second time causes the following errors:

Error: Proxmox Provider Error: proxmox API returned new network parameter 'hwaddr' we cannot process
Error: Proxmox Provider Error: proxmox API returned new network parameter 'type' we cannot process
Error: Proxmox Provider Error: proxmox API returned new network parameter 'ip' we cannot process
Error: 501 Method 'POST /nodes/pve4/lxc/200/config' not implemented

Looks like the schema mismatch between provider and the proxmox cluster

ProxMox VE version:  6.1.7
ProxMox provider version:  2.6.8

VM resource configuration:

```
resource "proxmox_vm_qemu" "cnt-test" {

  name = "cicd-ubt-test"
  desc = "A test for using terraform"

  vmid = 220

  # Node name has to be the same name as within the cluster
  # this might not include the FQDN
  target_node = "pve4"

  # The template name to clone this vm from
  clone = "Centos-7.9"

  # Activate QEMU agent for this VM
  agent = 1

  os_type = "ubuntu"
  cores   = 2
  sockets = 1
  vcpus   = 0
  cpu     = "host"
  memory  = 2048
  scsihw  = "lsi"

  # Setup the disk
  disk {
    size    = "18G"
    type    = "scsi"
    storage = "local-lvm"
    discard = "on"
  }

 network {
    model  = "virtio"
    bridge = "vmbr0"
    tag    = -1
  }
}
```

**Comment by msbence** [comment]
I just tried your config and worked perfectly... 🤔 
The only difference is that I'm on latest PVE version. Could you test it on an upgraded node?

**Comment by sticky-note** [comment]
@vladistan Check in your states ( `terraform state pull > terraform.tstate` if you are storing them remotely )
that you have a `proxmox_vm_qemu` resource that DO NOT exists in your proxmox cluster.
I was experiencing this issue after removing "by hand" a terraformed `proxmox_vm_qemu`
