### ISSUE TITLE
Creating VM takes over 10 minutes 

### ISSUE THREAD

**Issue by madianas** [Telmate/terraform-provider-proxmox#325]
When creating a VM by cloning, Terraform runs for over 10 minutes and finished successfully. However, in Proxmox all of the tasks were finished in 63 seconds.

Proxmox VE 6.3-6
Terraform v0.14.9
+ provider registry.terraform.io/telmate/proxmox v2.6.8

Terraform `main.tf` :

```
terraform {
  required_providers {
    proxmox = {
      source  = "Telmate/proxmox"
      version = "2.6.8"
    }
  }
}

provider "proxmox" {
  pm_api_url      = "https://10.0.6.67:8006/api2/json"
  pm_user         = "terraform@pve"
  pm_password     = "PASS"
  pm_tls_insecure = true
}

resource "proxmox_vm_qemu" "cloudinit-test2" {
  name        = "tftest2"
  desc        = "tf tes2"
  target_node = "prox1"

  clone = "ubuntu-20-cloudinit-template"
}
```

Terraform job ran for 11 minutes and 21 seconds logs:
```
terraform apply --auto-approve
proxmox_vm_qemu.cloudinit-test2: Creating...
proxmox_vm_qemu.cloudinit-test2: Still creating... [10s elapsed]
proxmox_vm_qemu.cloudinit-test2: Still creating... [20s elapsed]
proxmox_vm_qemu.cloudinit-test2: Still creating... [30s elapsed]
proxmox_vm_qemu.cloudinit-test2: Still creating... [40s elapsed]
....
proxmox_vm_qemu.cloudinit-test2: Still creating... [11m10s elapsed]
proxmox_vm_qemu.cloudinit-test2: Still creating... [11m20s elapsed]
proxmox_vm_qemu.cloudinit-test2: Creation complete after 11m21s [id=prox1/qemu/110]
````

VM was cloned, configured and started within 63 seconds
![image](https://user-images.githubusercontent.com/7828566/113893046-74a35480-97e8-11eb-8937-18c75c74d108.png)

**Comment by madianas** [comment]
Found a cause for this problem. Providor expects guest agent to be running. I found this in terraform debug logs if I run `TF_LOG=DEBUG terraform apply --auto-approve`

```
HTTP/1.1 500 QEMU guest agent is not running
``` 
Work around for this problem is to set `agent = 1`. By default, the provider sets `agent=0` or off, even though it was enabled in the original VM template.

**Comment by remil1000** [comment]
- proxmox VE: 6.3-6
- terraform: 0.14.10
- provider: 2.6.8

I had the exact same issue with the same `HTTP/1.1 500 QEMU guest agent is not running` error in TF_LOG
I ended up by installing and enabling `qemu-guest-agent` in the template

Setting `agent=0` or `agent=1` in the Terraform resource or enabling/disabling agent support in the template didn't change the outcome.
My guess is, as how it's done with many other provider, the creating step is waiting for confirmation from API that VM is up and reachable.

I don't know if this is on purpose as disabling agent on the Terraform resource definition side would probably break support for remote_exec provisioner or network related attributes being populated on the newly created resource

**Comment by hbokh** [comment]
Adding `qemu-guest-agent` to an existing (Ubuntu 20.04 "Focal") cloudimg and enabling the agent on startup makes all the difference!
I used the steps described in the doc found here and went from app. 20 minutes for 4 VMs to 3m16s!!

https://registry.terraform.io/modules/sdhibit/cloud-init-vm/proxmox/latest/examples/ubuntu_single_vm

**Comment by jacobcrawford** [comment]
Is the only fix to this issue to install the `qemu-guest-agent` package in the VM you have running in Proxmox?
I have a linux image where installing such a package is not an option, because of client needs.

**Comment by jacobcrawford** [comment]
I found out that the 10min is just when the provider times out, trying to get a response from the guest agent. 
You can just overwrite this value with `guest_agent_ready_timeout = 120` when creating a `"proxmox_vm_qemu"` resource, to reduce it to 2min.
A bit weird that it is not in the documentation for the provider though. :)

**Comment by madianas** [comment]
The cause for this issue is that VM creation depends on on the guest agent to be installed and enabled, however `agent=0` is off by default at VM creation, even if the template has it enabled.

**Comment by rsalmond** [comment]
I know it seems unrelated, but try setting `define_connection_info = true` on your `proxmox_vm_qemu` resource.

**Comment by remil1000** [comment]
> I know it seems unrelated, but try setting `define_connection_info = true` on your `proxmox_vm_qemu` resource.

It seems it's already the default value, see https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L133
Do you mean to set if to false ? because from https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L1581 it looks like it's totally bypassing the guest agent probing to fetch some attributes (used in provisioner for example) and may in fact avoid issue with templates not having the guest agent running

**Comment by rsalmond** [comment]
> Do you mean to set if to false ? 

Heh, yep that's exactly what I should have written. Apologies!

**Comment by styleart** [comment]
We use templates to create VMs (clone), so it takes roughly around 40 second until the VM is up and running (see `Start: OK` in Proxmox log). And we also don't use qemu agent.

As a workaround (to avoid waiting 10 minutes), we just set `agent = 0` and `guest_agent_ready_timeout = 60` in the resource config. Not the optimal fix, but at least we don't have to wait 10 minutes for terraform even if the VM is already running after <60s.

**Comment by jess-sys** [comment]
> We use templates to create VMs (clone), so it takes roughly around 40 second until the VM is up and running (see `Start: OK` in Proxmox log). And we also don't use qemu agent.
> 
> As a workaround (to avoid waiting 10 minutes), we just set `agent = 0` and `guest_agent_ready_timeout = 60` in the resource config. Not the optimal fix, but at least we don't have to wait 10 minutes for terraform even if the VM is already running after <60s.
> 
> edit: oops, missed the [comment](https://github.com/Telmate/terraform-provider-proxmox/issues/325#issuecomment-822549556) of @jacobcrawford. Basically the same workaround.

This quick-and-dirty "fix" is working great.

**Comment by tomhaslett** [comment]
> * proxmox VE: 6.3-6
> * terraform: 0.14.10
> * provider: 2.6.8
> 
> I had the exact same issue with the same `HTTP/1.1 500 QEMU guest agent is not running` error in TF_LOG
> I ended up by installing and enabling `qemu-guest-agent` in the template
> 
> Setting `agent=0` or `agent=1` in the Terraform resource or enabling/disabling agent support in the template didn't change the outcome.
> My guess is, as how it's done with many other provider, the creating step is waiting for confirmation from API that VM is up and reachable.
> 
> I don't know if this is on purpose as disabling agent on the Terraform resource definition side would probably break support for remote_exec provisioner or network related attributes being populated on the newly created resource

I ended up creating a new template with the agent installed with agent = 1. Thank you!

**Comment by AjdinDev** [comment]
Is there an update planned for some fix? Right now we've configured a timeout for the guest agent but this is a lame workaround for us as some VM's take 2 minutes while others 5 take minutes. Installing the agent isn't really an option for us for some templates due to requirement complications :)

**Comment by rsalmond** [comment]
Hey @AjdinDev, to better publicize this workaround, and more clearly rectify the mistake I made [above](https://github.com/Telmate/terraform-provider-proxmox/issues/325#issuecomment-834009500): set the parameter `define_connection_info = false` on your proxmox_vm_qemu resource to skip waiting for the agent.

**Comment by FWest98** [comment]
Setting `define_connection_info = false` does indeed work, but this seems to not be stored in the local state. Every subsequent `plan` will cause a "change" to show up, setting this attribute from `true` to `false`...

**Comment by dfranco** [comment]
Hi, I'm almost sure I've found the root cause of it and will share at least the workaround I'm using to get this provider working with Terraform v1.0.6, ProxMox 6.4.13 (pve-manager/6.4-13/9f411e79) and telmate/proxmox = 2.7.4.
I'll update this bug report soon

**Comment by akashkroy** [comment]
Any updates @dfranco ?

**Comment by dfranco** [comment]
@akashkroy, I'll add a comment on this bug report later this week when I find a moment.

**Comment by habib-the-sweet** [comment]
@dfranco what about updates now?

**Comment by dfranco** [comment]
> @dfranco what about updates now? The same bug with 2.9.4

Hi,

Sorry, I totally overlooked this issue.

Do you still experience the same issue on your side ?
