### ISSUE TITLE
create firewall rules

### ISSUE THREAD

**Issue by locus313** [Telmate/terraform-provider-proxmox#340]
I am wondering if it's currently possible to set firewall rules for lxc? I see there is the option to enable/disable the firewall, but didn't see the option for adding the rules.

**Comment by AjdinDev** [comment]
The feature is not there right now. Hopefully it's something that's coming.

**Comment by anon8675309** [comment]
The API for adding firewall rules to a container is the same as for adding firewall rules to a VM.

However, it is important to note that the firewall settings need to be enabled on the entire cluster, the VM/container, and the VM/container's network interface. All of these are off by default. This is documented on the Proxmox wiki page on [firewall](https://pve.proxmox.com/wiki/Firewall) settings.

Here are the API endpoints which would need to be used:  
- [Cluster](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/cluster/firewall/options)
- [VM/container](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/firewall/options)
- [Network interface](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/config) (specifically "firewall=1" on net[n])

To apply firewall rules, there's two options: add a group of rules (called security groups), or adding an individual rule.

- [Individual rules](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/firewall/rules) are easy to implement, but likely not what would be ideal for managing
- Groups are easier to manage, but require more API calls to check to see if they exist and add them if they do not
  - [Create a new security group](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/cluster/firewall/groups)
  - [Create a rule in that group](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/cluster/firewall/groups/{group})
  - [Update a rule in the group](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/cluster/firewall/groups/{group}/{pos})

The part I'm not entirely clear on is how these concepts map into Terraform. I took a look at the AWS provider and it appears to have security groups as a [resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/connect_security_profile) but also as a [data](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/connect_security_profile) element.

Another thing I'm not clear on is what should happen if a terraform file has a definition for a group that doesn't match what is on the server. It seems that there would be 3 possible approaches:  
1. Overwrite what is there, possibly screwing up other VMs
2. Use what is there, giving you the wrong set of rules, or
3. Raising an error that the group exists and the definition doesn't match

If anyone can chime in here and explain how resources, data, and any other Terraform data types are intended to be used, it would get us one step closer to allowing someone to implement this feature. Even better yet would be some examples of another provider using firewall rules in a similar way to how they are implemented in Proxmox.

Having some examples that work on other providers and making the `terraform-provider-proxmox` API be as similar as possible, allowing for easier migration from one cloud provider to another.

I'd be willing to help contribute to this feature if I can better understand what the desired behavior would be.

**Comment by anon8675309** [comment]
I still want this feature, please do not automatically close it, @github-actions bot.

At some point, I may be able to try to take on this development effort, but if there's some way we could have the github actions bot not close feature requests, that'd be handy.  Otherwise we're going to end up with a bunch of comment that are meaningless just to please the robot.

**Comment by pescobar** [comment]
adding support to create security groups and assign them to VMs would be great

**Comment by jonahbohlmann** [comment]
I am also looking for this feature. +1

**Comment by anon8675309** [comment]
Wow, I guess if we don't implement ideas right away, the bots strike them from the plan. How unhelpful of them. Microsoft seems to be making GitHub worse by the week. :slightly_frowning_face:
