### ISSUE TITLE
Feature request: support EFI disks

### ISSUE THREAD

**Issue by jqueuniet** [Telmate/terraform-provider-proxmox#341]
To properly work, an UEFI Proxmox VM needs a special disk called the EFI disk.

https://pve.proxmox.com/pve-docs/chapter-qm.html#qm_bios_and_uefi

The disk sub-block should be modified to allow creation of this resource. It only asks for two parameters, storage and type. The size is fixed.

Something like:

```
  disk {
    type = "efi"
    format = "qcow2"
    storage = "local"
  }
```

**Comment by pgporada** [comment]
The upstream api will eventually get this functionality then it can be added to this provider. https://github.com/Telmate/proxmox-api-go/pull/116

**Comment by jqueuniet** [comment]
Good to know, thanks for the response and the linked issue.

**Comment by KnKay** [comment]
Nice to see, I am not alone with this! ;)

**Comment by AshDevFr** [comment]
Any update on this feature?

**Comment by KnKay** [comment]
This is in. I added it in Mai or June I guess.,

**Comment by brutesque** [comment]
Is there an example or documentation on how to use this in a terraform resource?

**Comment by scottbot95** [comment]
@brutesque Given @KnKay's contribution to the API package, it is "now" (as of 42a98880) *somewhat* possible to define EFI disks. If you add a new disk entry and set the type to `efidisk`, it looks like it will result in the expected API call. Ex
```
disk {
    type = "efidisk"
    size  = "1M"
}
```

The reason I say it is only "somewhat" possible however is that unlike all the other possible types for a disk, `efidisk` has a special set of options. Specifically this means it is not currently possible to set the `efitype` or `pre-enrolled-keys` so hopefully the PVE defaults work for your use-case. Additionally the lack of documentation in this package has meant that despite this being possible for nearly a year and a half, it appears that nearly nobody knew.

---

Given it is only valid to have at most one efidisk and the configuration is really only tangentially related to other disk types, I propose we should split `efidisk` into a new block within the qemu resource. We can then have the terraform schema validation ensure there is at most one efidisk and would allow for the separate configuration options. The result would look something like this:
```
resource "proxmox_vm_qemu" "efi_vm" {
    /* ... */
   efidisk {
      efitype = "4m"
      storage = "local"
      size = "1M"
      pre_enrolled_keys = 1
   }
}
```

Sadly I don't really know Go at all, but if this languishes long enough I might be motivated to learn it just to make a PR for this.

**Comment by riverar** [comment]
I added `efidisk` per @scottbot95's proposal and it seems to work. But I need to look into `pre_enrolled_keys` upstream. Proxmox wants to see this hyphenated as `pre-enrolled-keys`.

**Comment by riverar** [comment]
Not stale, awaiting upstream work.
