### ISSUE TITLE
Feature request: ipconfig3

### ISSUE THREAD

**Issue by zlatsv** [Telmate/terraform-provider-proxmox#345]
Hello!
In different environments, there are edge devices with 4 network interfaces, but in the current version of the plugin, only 3. ipconfig3 is not defined in the code. Is it possible to add support for 4 interfaces in the next version?

**Comment by pgporada** [comment]
Could you give an example of what you expect the config to look like?

**Comment by zlatsv** [comment]
Here is an example of what it looks like now:
```
    ipconfig0 = "ip=${var.bastion_hosts[count.index].external_ip}/26,gw=151.X.X.1"
    ipconfig1 = "ip=${var.bastion_hosts[count.index].backbone_ip}/27"
    ipconfig2 = "ip=${var.bastion_hosts[count.index].internal_ip1}/24"
#    ipconfig3 = "ip=${var.bastion_hosts[count.index].internal_ip2}/24" 
```
ipconfig3 is commented out, since in the plugin code it is possible to set a maximum of only 3 ip-addresses

**Comment by pgporada** [comment]
Aha, understood. Thank you for the example.

**Comment by mleone87** [comment]
We should then add the max ipiconfigs supported from the API(0-14 if I remember well)

**Comment by pgporada** [comment]
@ggongaware I think this ticket should be re-opened until `terraform-provider-proxmox` is updated to support more ipconfig#'s.
