### ISSUE TITLE
An unexpect second network-interface after a vm-clone

### ISSUE THREAD

**Issue by jeschero** [Telmate/terraform-provider-proxmox#352]
**OS**
Fedora 30

**Terrafrom version**
Terraform v0.15.3

**terraform-provider-proxmox version**
v2.7.1

**proxmox version**
Kernel Version Linux 5.4.114-1-pve #1 SMP PVE 5.4.114-1 (Sun, 09 May 2021 17:13:05 +0200)
PVE Manager Version pve-manager/6.4-6/be2fa32c

**Affected Provider**
proxmox

**Affected Resource**
proxmox_vm_qemu

**Description**

Clone a VM with only one network interface and configure the mac-address of this network-interface in the new VM. After power on this vm and boot Flarcar Linux or Fedora CoreOS over iPXE and Matchbox the vm has two network interfaces. The first network interface is the configure interface and the second is a Network with the IP-address 10.0.2.15.

The second interface is not configure in terraform and not visible in proxmox interface/gui. 
In proxmox is none network configure with the network 10.0.2.1 and from the proxmox host i can't ping 10.0.2.15.

If i power off the vm, change for example qemu guest agent and boot now Flarcar Linux or Fedora CoreOS over iPXE and Matchbox the second network interface is removed.

**Comment by devudopw** [comment]
Hello, I had same issue.
After testing, the IP 10.0.2.15 seems related to PXE boot.
My dirty fix, after the OS installation, poweroff (not reboot) the VM and start the VM. The IP 10.0.2.15 should be gone.
