### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by emmanuelvargas** [Telmate/terraform-provider-proxmox#356]
Hello,

Following installation guide and installation failed

`$ go get -v github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox
github.com/Telmate/terraform-provider-proxmox (download)
package github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox: cannot find package "github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox" in any of:
	/usr/lib/go-1.13/src/github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox (from $GOROOT)
`

even with

`$ export GO111MODULE=on

$ go get -v github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox
go: finding github.com/Telmate/terraform-provider-proxmox latest
go: downloading github.com/Telmate/terraform-provider-proxmox v0.0.0-20210518194742-0d6e7d75f408
go: extracting github.com/Telmate/terraform-provider-proxmox v0.0.0-20210518194742-0d6e7d75f408
go get github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox: module github.com/Telmate/terraform-provider-proxmox@upgrade found (v0.0.0-20210518194742-0d6e7d75f408), but does not contain package github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox
`

Same result with a up to date version of go (1.16)

What i'm doing wrong?
or this is a package issue?

Regards

**Comment by TheFrisianClause** [comment]
Hi,

I also had this issue and searched for a solution on the internet. This helped me and was also posted on this repository a few months back. Here is the link to it: #290
