### ISSUE TITLE
how to set timeout on resource create, plugin fails if clone takes more than default value

### ISSUE THREAD

**Issue by golgotow** [Telmate/terraform-provider-proxmox#358]
Hello,

Do this plugin provide option to set timeout in resource create, as clone in one cluster taking more time and job is failing that Plugin did not respond.

Best regards

**Comment by pgporada** [comment]
Possibly related to #355

**Comment by golgotow** [comment]
Hello,

Not sure if related, when storage is in good shape this problem do not exist, only during long clone time

Best regards

**Comment by MayamaTakeshi** [comment]
According to terraform docs, the plugin should implement support for it this way:
```
  timeouts {
    create = "60m"
    delete = "2h"
  }
```
https://www.terraform.io/docs/language/resources/syntax.html

However, I checked the code and this is not supported. Instead, it supports a generic pm_timeout:
```
            "pm_timeout": {
                Type:     schema.TypeInt,
                Optional: true,
                Default:  300,
            },
```
The default 300 seconds (5 minutes) seems to be around the timing I've been seeing in my tests (#355). So I increased it to 1800 (30 minutes) but it crashed the same way after 7 minutes.
But this time, the problem arrived from proxmox:
```
{"data":{"id":"104","pid":11109,"type":"qmclone","starttime":1621756783,"status":"stopped","upid":"UPID:labprox04221:00002B65:02CA13F6:60AA0B6F:qmclone:104:root@pam:","pstart":46797814,"user":"root@pam","node":"labprox04221","exitstatus":"clone failed: command '/sbin/lvs --separator : --noheadings --units b --unbuffered --nosuffix --options lv_size /dev/pve/vm-104-disk-0' failed: got timeout"}}
2021/05/23 17:52:23 <<<<<<<<<< RESULT:
```
But the cloning of the VMs was successful based on ProxMox Web Interface.

Based on this old thread:
  https://forum.proxmox.com/threads/proxmox-api-timeout.41939/
the proxmox API timeout is hard-coded, so even if you use a timeout in the plugin, you would still need to change proxmox code and rebuild it.
