### ISSUE TITLE
Increment static IP Address

### ISSUE THREAD

**Issue by mwhelanmachship** [Telmate/terraform-provider-proxmox#360]
I'm having an issue setting incremental IP address' in Terraform.
The error I'm getting is;
`Error: 400 Parameter verification failed.`
`{"errors":{"ipconfig0":"invalid format - format error\nipconfig0.ip: invalid format - value does not look like a valid ipv4 network configuration\n\n"},"data":null}`

The code used to set the incremental static IP is
`  ipconfig0 = "ip=10.200.5.139${count.index + 1}/22,gw=10.200.4.1"`

I have tested this code block with setting the IP using DHCP, with no issues
`    ipconfig0 = "ip=10.200.4.0/22,gw=10.200.4.1"`

I've seen many a lot of examples online using this format and having no errors. Is this something which has potentially been deprecated?

Thanks,
Mark

**Comment by mleone87** [comment]
Hi, the IP that you're generating is not a valid IP, read carefully what ip you're trying to pass
