### ISSUE TITLE
Destroying of vm fails when ha-manager is used

### ISSUE THREAD

**Issue by 0xErnie** [Telmate/terraform-provider-proxmox#362]
1. When destroying a vm which was created with ha=actvive I get the following error during destuction:

`Error: 500 VM 104 is running - destroy failed`

Rerunning terraform solves this.

2. When destroying a vm which was created with ha=active and is in error state I get the following error:

`Error: command 'ha-manager crm-command stop vm:104 0' failed: exit code 255`

I have to set the ha state manualy to "disabled" and can only delete the vm after that.

**Comment by breitenj** [comment]
Might be the same issue we had. My MR #354 fixed it for us, but it's not included in a release yet.
You could build the provider yourself and test if it also solves your issue or simply wait until the next release.

**Comment by 0xErnie** [comment]
This is probably fixed in #354
