### ISSUE TITLE
VM creation taking over 10 min this provider

### ISSUE THREAD

**Issue by ankycooper** [Telmate/terraform-provider-proxmox#364]
I'm creating a VM using this provider from scratch (no clone and cloud-init).

```
terraform -v
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/telmate/proxmox v2.7.1
```

`
resource "proxmox_vm_qemu" "talos-bootstrap-cluster" {
  name        = "test"
  desc        = "test"
  count       = 1
  target_node = "pve"
  iso         = "ISO:iso/talos-amd64.iso"
  memory      = "2048"
  sockets     = "2"
  cores       = "2"
  scsihw      = "virtio-scsi-pci"
  bootdisk    = "scsi0"

  network {
    model  = "virtio"
    bridge = "vmbr0"
    tag    = "100"
  }
  disk {
    type    = "scsi"
    storage = "storage01"
    size = "20G"
  }
}
`
Terraform keeps running for around 10-12 min however the VM is created within seconds and even boots up with the ISO.
What is the provider/terraform waiting for?

**Comment by martinseener** [comment]
I think this is a duplicate of https://github.com/Telmate/terraform-provider-proxmox/issues/325

**Comment by brnl** [comment]
Yes, sounds like the agent. :-)
