### ISSUE TITLE
ssh_forward_ip is unknown but the guest agent is installed

### ISSUE THREAD

**Issue by Syntax3rror404** [Telmate/terraform-provider-proxmox#370]
Hello, I would like to build a vm from a template without using cloud-init. The guest agent is already preinstalled and the VM is assigned an ip by a DHCP immediately after starting. According to the guide, ssh_forward_ip must be set for cloning without cloud init. However, this is initially unknown and can only be automatically recognized by the guest agent. How can I do that?

**Comment by BaldFabi** [comment]
You could try to use `default_ipv4_address`

**Comment by Syntax3rror404** [comment]
What exactly is `default_ipv4_address` Is it a variable that is filled automatically? The expectation is that `ssh_host` is automatically fed with the IP that is provided by the qemu agent

**Comment by BaldFabi** [comment]
`default_ipv4_address` holds the ip address provided by the qemu agent. `ssh_host` didn't work properly so I created a pr to introduce `default_ipv4_address` as it is for the vsphere provider

**Comment by Syntax3rror404** [comment]
self.ssh_host works for me
