### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by alegrey91** [Telmate/terraform-provider-proxmox#379]
Hi! Thanks for your amazing work.
Do you think it is possible to add more examples for the different use case?
Especially on preprovisioning for non cloud-init vms. :)

**Comment by brnl** [comment]
Can you specify your specific use case you're struggling with? Maybe I can help.

**Comment by alegrey91** [comment]
Hi @brnl and thanks for your reply.
Specifically when we use the `preprovision` keyword, it's not clear how to use it.
Can you provide more examples about this?

**Comment by brnl** [comment]
I must admit that I don't really get that feature myself. :thinking: 
I'm not the plugin author but I'm interested, so hopefully the author can explain but I'll have a look at it too. :-)
