### ISSUE TITLE
FedoraCoreOS qemu args

### ISSUE THREAD

**Issue by danielraq** [Telmate/terraform-provider-proxmox#385]
Hi
Is it possible to add qemu args to proxmox_vm_qemu? I need them to install fedora coreos and they need to be passed at the first boot. According to: https://github.com/coreos/fedora-coreos-tracker/issues/736 proxmox will handle it

https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-qemu/
https://pve.proxmox.com/pve-docs/chapter-qm.html

**Comment by throwaway876** [comment]
Thanks all. Can confirm it only works with root and even then with only root and password (no API token.) 

I guess for now I will continue to provision with an env vars for that and keep an eye on the thread.

Thread to keep an eye on is here- https://forum.proxmox.com/threads/root-pam-token-api-restricted.83866/ 

For now it appears there is little demand for such a case and the chance to check for those "super" privs in the token isn't present at all.

**Comment by hellraiserinchief** [comment]
I tried this git repo from a small company who posted it on proxmox's forum : https://forum.proxmox.com/threads/howto-wrapper-script-to-use-fedora-coreos-ignition-with-proxmox-cloud-init-system-for-docker-workloads.86494/

Can confirm that it works on a standalone basis. I have to tie it to the provider and make it work.

**Comment by elsbrock** [comment]
It would make sense to get `args` documented though.
