### ISSUE TITLE
Unable to specify network mac address

### ISSUE THREAD

**Issue by themouette** [Telmate/terraform-provider-proxmox#39]
Until https://github.com/Telmate/terraform-provider-proxmox/pull/13 was merged, it was possible to specify a mac address on a network interface.

If anyone has any guidance on how to make it work again, that would be great, because to use a public IP address, some provider (such as OVH) requires the interface to have a dedicated mac address, provided by them.

**Comment by ggongaware** [comment]
Using:

```
resource "proxmox_vm_qemu" "blah" {
	mac = "..."
}
```

Has been working for me still.

What have you tried, and with which version of Proxmox?

**Comment by themouette** [comment]
Hi,

Thanks for your answer.
I'm running proxmox 5.3-11, and when I specify `mac="*****"`, I get the following error:

```
Error: proxmox_vm_qemu.loadbalancer: "network": conflicts with mac
```

I guess I should stick to the old format, but that would be so much better to be able to use the new one with mac :)

Anyway thanks again for your answer and the provider :)

**Comment by ggongaware** [comment]
Did you try:

```
resource "proxmox_vm_qemu" "blah" {
	network {
		macaddr = "..."
	}
}
```

**Comment by themouette** [comment]
Yes, this ends with:

```
proxmox_vm_qemu.blah - *terraform.NodeValidatableResourceInstance
2019/03/07 08:53:52 [DEBUG] ReferenceTransformer: "proxmox_vm_qemu.loadbalancer" references: []
2019/03/07 08:53:52 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: ["network.0.macaddr": this field cannot be set]
2019/03/07 08:53:52 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: ["network.0.macaddr": this field cannot be set]

2019/03/07 08:53:52 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: proxmox_vm_qemu.loadbalancer: "network.0.macaddr": this field cannot be set
```

😞

**Comment by ggongaware** [comment]
just pushed a change to master that should help this

**Comment by themouette** [comment]
mac address does not seems to be an issue anymore, I'll check more later (it dies on a bad disk config, so I can't confirm it goes throught the whole process for now, even though it seems to be fixed)

Thank you so much for everything :)
