### ISSUE TITLE
error while attempting to connect via ssh

### ISSUE THREAD

**Issue by ninuxio** [Telmate/terraform-provider-proxmox#4]
Hi everyone,
i can't figure this out.

```bash
proxmox_vm_qemu.test1: Error executing command "echo $'auto eth0\\niface eth0 inet dhcp\\n' > /tmp/tf_eth0_payload": dial tcp 10.0.0.1:22903: i/o timeout
```

i have an error when i try to apply. is that 10.0.0.1 should be my proxmox IP?

**Comment by ninuxio** [comment]
so if i understand this right, ssh forward ip should be my promos node ip.

when i switch to debug mode i see correctly the reconfigure

```bash
2017/07/23 13:31:39 [DEBUG] plugin: terraform-provider-proxmox: command=netdev_add+user%2Cid%3Dnet1%2Chostfwd%3Dtcp%3A%3A22902-%3A22)
...
2017/07/23 13:31:39 [DEBUG] plugin: terraform-provider-proxmox: command=device_add+virtio-net-pci%2Cid%3Dnet1%2Cnetdev%3Dnet1%2Caddr%3D0x13)
```

nothing change when i ```qm config vmid```

```ssh proxmox_node_id -p22902 -l terraform -i .ssh/terraform -vvvvv``` doesn't work

i can ssh on the ip given by dhcp to my new vm so sshd is fine vm side.

**Comment by ggongaware** [comment]
Its important for this current implementation, that the start up state of the new VM not initialize eth0. 

"Bring up only eth1 for flexible user-net SSH port forwarding"

I suspect in your case the VM established a default gateway on eth0 and the ssh forwarding isn't routable over eth1 (user-net1).

I hope this make sense. If you think of other ways to reliably talk to a new VM, lets pack them into this plugin.

**Comment by ccameron** [comment]
I'm confused on how the ssh forwarding / provision part should be working. Can you give me the steps to take for configuration of the provisioner? I'm stuck at that part as well.

**Comment by ggongaware** [comment]
The VM config should only have net0. The OS on the internal VM should only have eth1.

During provisioning, the terraform-plugin makes a temporary net1. This net1 exists in proxmox as a private NAT network, with a port forward to SSH.

Sample /etc/network/interfaces
```
# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth1
iface eth1 inet dhcp
```

The preprovisioner then adds your real eth0 config but keeps a route to your terraforming host to finish provisioning over ssh.

**Comment by ninuxio** [comment]
@ggongaware it's ok for me if you want to close this issue, my ubuntu-iso made with your script configure an eth0 by default so if you know how i can force to configure an eth1 i'll take it but it's no longer the same issue.

For anyone in a same situation just up your template change eth0 by eth1 and clone from this new template
