### ISSUE TITLE
Cloud-Init example has changes on reapply

### ISSUE THREAD

**Issue by Teshel** [Telmate/terraform-provider-proxmox#40]
The Cloud-Init example in the Readme does not seem to be correct. It succeeds in creating a Cloud-Init VM okay, but running `terraform apply` again shows that several fields were given an empty value and need to be changed:

```Terraform will perform the following actions:

  ~ proxmox_vm_qemu.ubuntu_cloudinit_4
      bridge:  "" => "vmbr0"
      nic:     "" => "virtio"
      storage: "" => "local-lvm"
```

I guess this is probably due to the `bridge`, `storage` and `nic` fields being deprecated, with the first two moving to `network.bridge` and `disk.storage`. However, it is not clear how to use `disk` with Cloud-Init; the following results in a 500 error from the server:

```
  disk {
    id = 0
    type = "virtio"
    size = "10G"
    storage = "local-lvm"
    storage_type = "lvm"
    backup = false
  }
```

Result:
```
* proxmox_vm_qemu.ubuntu_cloudinit_4: 1 error(s) occurred:
* proxmox_vm_qemu.ubuntu_cloudinit_4: 500 disk 'virtio0' does not exist
```

How can we use Cloud-Init while having an idempotent plan?

**Comment by ggongaware** [comment]
The disk for cloud-init depends a great deal on your cloud-init template that you clone. For example, if you followed the proxmox cloud-init how-to, your disk type ends up being "scsi"

**Comment by Teshel** [comment]
Thanks @ggongaware, that was exactly the issue, changing it to `type = "scsi"` fixed the problem.
