### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by ssmyrd** [Telmate/terraform-provider-proxmox#41]
Hello
is there any documetacion about which parameters can be set ? for example when I am connecting do existing proxmox claster i trying to create new vm, terraform remove vm with id 101 and creates a new one in its place.

**Comment by QkiZMR** [comment]
this documentation is a complete mess. Installation steps are not complete, no info about how to set credentials to Proxmox servers.

**Comment by f0rkz** [comment]
Its a huge pain. Not to mention it not working or I am doing something wrong. Don't know why the TF apply wants to modify the host every time and fail.
