### ISSUE TITLE
allow to specify VM ID

### ISSUE THREAD

**Issue by tobjaw** [Telmate/terraform-provider-proxmox#42]
Hey there,  
first of all, thanks for this great plugin.  

I was wondering if there are any plans to add custom VM ID specification. From what I can tell from the source, it seems the provider just picks the next highest unused VIM ID: https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/provider.go#L99-L108  

Not sure if this makes sense in the context of Terraform, but in my home setup I like to match VM IDs and IPs for easier management - e.g. the VM with ID 123 on node 1 will have the IP 10.10.1.123, and so forth.  
Is this sensible? I could give it a try at implementing it.

**Comment by ggongaware** [comment]
Sure, I think adding control over the VM ID is ok. Currently the name of the VM is used as the unique key, as long as that still works too, give it shot.

**Comment by sl-ll** [comment]
Why the VM id is needed?
because when you're trying to create VMs in parallel on the different nodes of the same cluster, you get error

```* proxmox_vm_qemu.default.1: 500 close (rename) atomic file '/etc/pve/nodes/<node_name>/qemu-server/101.conf' failed: File exists```

also you receive similar error when create few VMs on the same node at one time
```
500 can't lock file '/var/lock/qemu-server/lock-104.conf' failed: got timeout```

I think terraform trying to use same ID for different VMs

Best regard

**Comment by ssgoburdhun** [comment]
For deployment of new VMs on different nodes, the VMID can act as an identifier for locating easily that specific vm on multiple clusters. It gets more friendly for statistics gathering. Based on experience, an ID ought to be unique but it is not always the case on multiple hosts (as terraform start with VMID 100 onwards)

We look forward to this implementation !
Good luck !
