### ISSUE TITLE
Vm 'cloudinit-ubuntu' not found

### ISSUE THREAD

**Issue by nitrique** [Telmate/terraform-provider-proxmox#432]
Hi,

I try to use the package, but I get the following error: Vm 'cloudinit-ubuntu' not found

I don't know why this is happening because the vm with the name (converted as template) exists.
<img width="327" alt="Capture d’écran 2021-11-03 à 13 55 23" src="https://user-images.githubusercontent.com/4180708/140063914-7a7a39cf-235c-4d9d-b73b-933a7848c5df.png">

<img width="520" alt="Capture d’écran 2021-11-03 à 13 55 09" src="https://user-images.githubusercontent.com/4180708/140063909-249668b9-cd7c-4e07-836f-42e15dbd2473.png">

Thanks a lot,
Regards.

Nicolas

**Comment by mabeltron** [comment]
I have this problem as well with Proxmox 6.4, and it looks like the issue is that Proxmox 6 expects a numeric `vmid` rather than a name, and the provider sends a string. 
`qm clone ubuntu-cloudinit-template 1xx --name test-vm`
on the server returns
```
400 Parameter verification failed.
vmid: type check ('integer') failed - got 'ubuntu-cloudinit-template'
qm clone <vmid> <newid> [OPTIONS]
```
So unless there's a way to enable names on Proxmox 6, the provider needs to be able to provide numeric IDs.

**Comment by nitrique** [comment]
@mabeltron is that the same thing on PVE 7 ?

**Comment by mleone87** [comment]
@mabeltron @nitrique  right, api need vm id's but under the hood, the hood the provider asks first whats the vmid of the vm you want to clone(based on the name you give) and then clone it

What I see is that you are using a clustered setup, I think that's could be an issue introduced by this PR https://github.com/Telmate/terraform-provider-proxmox/pull/373/files

do you have the same vm clone name on different host? are you connetting to the api endpoint of the node you're cloning to or just the first node on the cluster?

**Comment by mabeltron** [comment]
@mleone87 My problem was that I was trying to authenticate with the API and it wasn't working for some reason. Switching to username and password works. It's the first time I've used terraform so I'm feeling around a bit.

**Comment by bwks** [comment]
I am also hitting this issue.

**Comment by bwks** [comment]
I am not sure why, but for me I it works if I use a username/password. But with a the API token it does not work. I get the `Error: Vm '<vm-template-name>' not found` error

**Comment by nitrique** [comment]
@bwks you're right, it works with password but not with api keys, so it's a bug

**Comment by mleone87** [comment]
it's not a bug, your api token has not the correct permission

**Comment by nitrique** [comment]
@mleone87 followed the doc [here](https://registry.terraform.io/providers/Telmate/proxmox/latest/docs) , can you explain which is the missing one ?

**Comment by mleone87** [comment]
honestly I never needed to create a separate user to do proxmox operations. I simply create api tokens for the root user with no  privileges separation.
![immagine](https://user-images.githubusercontent.com/807457/141078478-01bb25db-e6d1-4915-bbf8-b79e514dbc37.png)

I honestly don't know what tests those who pushed that documentation did, but they certainly weren't correct.

If you want follow the path of the docs, just add permission to the role one by one starting from the ones most probable and then report it there so I can send a PR with the correct permissions

**Comment by bwks** [comment]
I am not sure that its a token permission issue. I assigned all permissions to the role and the token still does not work. 
I am using the same user, with the password and that uses the same role (I am pretty sure, but im not a proxmox expert) as if I am using a token.

**Comment by bwks** [comment]
@mleone87 Your comment about the privilege separation was a clue. Mine was set to `Yes`, I changed it to `No` and its working now. 

I think we could update the docs to make this clear

```
pveum user token add terraform-prov@pve terraform-token --privsep=0
```

@nitrique do you want to give changing the priv sep to no and see if it works for you?

**Comment by bwks** [comment]
From the Proxmox docs for reference.

https://pve.proxmox.com/wiki/User_Management

```
API tokens allow stateless access to most parts of the REST API by another system, software or API client. Tokens can be generated for individual users and can be given separate permissions and expiration dates to limit the scope and duration of the access. Should the API token get compromised it can be revoked without disabling the user itself.

API tokens come in two basic types:

    - separated privileges: the token needs to be given explicit access with ACLs, its effective permissions are calculated by intersecting user and token permissions.
    - full privileges: the token permissions are identical to that of the associated user.
```

**Comment by mabeltron** [comment]
Confirmed turning off privilege separation works.
Is there any reason why an authentication error can't be shown in `terraform plan`?

**Comment by pgporada** [comment]
There's no real reason it can't bubble up that information. We just haven't
plumbed the proxmox-api-go or this provider code to do so yet. As for the
privilege separation = no, that's exactly how I use it and implemented the
api auth for this provider. How to get priv separation working is not
something I've wanted to tackle yet.

**Comment by jonathanmf** [comment]
> our comment about the privilege separation was a clue. Mine was set to `Yes` (Default when creating a token), I changed it to `No` and its working now.

Thanks a lot, you'r a life saver ;) Working now!

**Comment by carbans** [comment]
It's work for me, the problem of this issue it's there are privilege separation at the token, and you need to declare explicit the permissions to access.
Thanks!

**Comment by flygav1** [comment]
By deleting VM's from the ui, you create an inconsistency between the state files and the real world. The intended solution by HashiCorp is to remove the ressource from the state file by using terraform state rm {ressource} .

```
devbox@devbox:~/Documents/DevOps$ terraform state list

proxmox_lxc.basic

devbox@devbox:~/Documents/DevOps$ terraform state rm proxmox_lxc.basic

Removed proxmox_lxc.basic

Successfully removed 1 resource instance(s).

Fixed it
