### ISSUE TITLE
Terraform lxc

### ISSUE THREAD

**Issue by tanguy-opendsi** [Telmate/terraform-provider-proxmox#44]
Hi it's possible to use terraform-provider-proxmox with lxc?

**Comment by ggongaware** [comment]
Not yet, but it's probably something not too difficult to add in

**Comment by gaalos** [comment]
Thx let me know when you do that :)

**Comment by in0rdr** [comment]
> Thx let me know when you do that :)

Trying to get something done in this direction, since I would love to see this happening as well:
* https://github.com/in0rdr/terraform-provider-proxmox/tree/feature/lxc
* https://github.com/in0rdr/proxmox-api-go/tree/feature/lxc

Far from perfect, but creating a simple container via terraform provider and api already works.

**Comment by ggongaware** [comment]
This is looking great! Let's merge it in when you have the update/delete methods working.

**Comment by in0rdr** [comment]
Just to update, there is a `resourceLxcRead` now as well. However, the read still seems a bit strange to me. For instance, it won't update the MAC address (`hwaddr`) correctly and tries to remove `ostype` and number of `cores`:

```
2019/06/26 00:00:36 [DEBUG] command: asking for input: "Do you want to perform these actions?"
  # proxmox_lxc.lxc-test will be updated in-place
  ~ resource "proxmox_lxc" "lxc-test" {
        arch                 = "amd64"
        bwlimit              = 0
        cmode                = "tty"
        console              = true
      - cores                = 1 -> null
        cpulimit             = 0
        cpuunits             = 1024
        force                = false
        hostname             = "terraform-writer"
        id                   = "wolke4/lxc/113"
        ignore_unpack_errors = false
        memory               = 512
        onboot               = false
      + ostemplate           = "shared:vztmpl/centos-7-default_20171212_amd64.tar.xz"
      - ostype               = "centos" -> null
      + password             = "rootroot"
      + pool                 = "terraform"
        protection           = false
        restore              = false
      - rootfs               = "local-lvm:vm-113-disk-0,size=4G" -> null
        start                = false
      ~ storage              = "local" -> "local-lvm"
        swap                 = 512
        target_node          = "node01"
        template             = false
        tty                  = 2
        unique               = false
        unprivileged         = true
        unused               = []

        features {
            fuse    = false
            keyctl  = false
            nesting = true
        }

      - network {
          - bridge   = "vmbr0" -> null
          - firewall = false -> null
          - gw       = false -> null
          - gw6      = false -> null
          - hwaddr   = false -> null
          - id       = 0 -> null
          - ip       = "dhcp" -> null
          - ip6      = "dhcp" -> null
          - name     = "eth0" -> null
          - rate     = 0 -> null
          - tag      = 0 -> null
          - type     = "veth" -> null
        }
      + network {
          + bridge = "vmbr0"
          + id     = 0
          + ip     = "dhcp"
          + ip6    = "dhcp"
          + name   = "eth0"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by ggongaware** [comment]
Nice work so far. The qemu nodes have problems with optionally-autogenerated fields like hwaddr too. I haven't checked into the proper terraform approach for this.

**Comment by in0rdr** [comment]
The PRs are ready to be discussed in further detail:
* https://github.com/Telmate/proxmox-api-go/pull/34
* https://github.com/Telmate/terraform-provider-proxmox/pull/63

I am not quite happy with the usability, even though the basic functionality of creating/updating/reading/destroying the LXC resource works fine so far. The differences shown for updates, for instance after a `terraform plan`, can be a bit confusing, as mentioned [above](https://github.com/Telmate/terraform-provider-proxmox/issues/44#issuecomment-505640321). However, it might be better to discuss the technical details in the PRs directly to keep this thread clean.

Thank you for your review. I can remove the `WIP` on both as soon as it's ready to merge.

**Comment by gentoo9ball** [comment]
@ggongaware @in0rdr I'm trying to use this feature with static networking. Why does the gw variable take a bool? Seems like it should be a ip addr string. I've tried to trace it down through the api, but I'm pretty new to all of this.

**Comment by in0rdr** [comment]
This looks clearly wrong to me as well, thanks for the report @gentoo9ball. #92 attempts to resolve this.

**Comment by gentoo9ball** [comment]
@in0rdr Awesome dude. Got one more for you, haven't traced this down as far ... I'm using a dynamic block to generate my network interfaces on the lxc...

This produces a 400 parameter verification error when building the LXC. In debug mode I yanked out the provider's output right before error. Apparently the ID field is required by net1. 

These are the fields generated in debug mode, I split the lines... 

net0=bridge%3Dvmbr2%2Cip%3D10.15.5.1%2F16%2Cname%3Deth0
net1=id%3D1%2Cip%3D10.20.5.1%2F16%2Cbridge%3Dvmbr3%2Cname%3Deth1

If I remove the id field completely from my content block, then I get 
       The argument "id" is required, but no definition was found.


`  dynamic "network" {
    for_each    = var.networks
    content {
      id        = network.value.id
      name      = "eth${network.value.id}"
      bridge    = network.value.bridge.interface
      gw        = false
      ip        = "%{ if network.value.bridge.dhcp }dhcp%{ else }${network.value.bridge.supernet}${var.subnet}${count.index + 1}${network.value.bridge.cidr}%{ endif }"
    }
  }
`

**Comment by in0rdr** [comment]
@gentoo9ball, what happens if you start the id numbering at 1 (not 0), so try `network.value.id + 1`?

**Comment by gentoo9ball** [comment]
@in0rdr 
> @gentoo9ball, what happens if you start the id numbering at 1 (not 0), so try `network.value.id + 1`?

No luck there either,
Error: Error creating LXC container: 400 Parameter verification failed., error status: {"errors":{"net2":"invalid format - format error\nnet2.id: property is not defined in schema and the schema does not allow additional properties\n","net1":"invalid format - format error\nnet1.id: property is not defined in schema and the schema does not allow additional properties\n"},"data":null} (params: [123 34 111 115 116 101 109 112 108 9

**Comment by in0rdr** [comment]
great, at least the error is now the same for all interfaces.

It means that the PVE API does not accept the `id` property as input. I need to think more deeply about this, because I rely on [DevicesSetToMap()](https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L806) to parse the networks which expects the `id`.

The solution would be to strip all the "ids" before passing the configuration down to [CreateLxc()](https://github.com/Telmate/proxmox-api-go/blob/master/proxmox/config_lxc.go#L302) in the API code.

I would prefer not to iterate the list of interfaces twice, just to remove the `id` again.

**Comment by gentoo9ball** [comment]
@in0rdr Thanks for the help and the great explanation. Just noticed you're in Zurich? I was at the 3 day festival this year with my girlfriend! Great times!

**Comment by in0rdr** [comment]
@gentoo9ball Yes, it is a great festival indeed. I could debug the issue with the device (for instance "network") ids and created two patches, identical in behavior, but different in configuration. Could you please have a look at issue #98 and let me know your thoughs? Thanks

**Comment by Jungo495** [comment]
im getting this error Error: Error creating LXC container: 500 storage 'shared' does not exists, error status: {"data":null}
on alone prox server with thinLVM
can you please explain why?

**Comment by in0rdr** [comment]
@Jungo495 seems like you use the template from the example ([lxc_example.tf#L21](https://github.com/Telmate/terraform-provider-proxmox/blob/master/examples/lxc_example.tf#L21)). What happens if you use a template which exists in your Proxmox virtual environment, i.e., replace "shared" by your desired storage location? You need to specifiy a valid template name as well:
```
ostemplate = "shared:vztmpl/centos-7-default_20171212_amd64.tar.xz"
```
You can use `pvesh get storage` to retrieve a list of storage or in the WebUI it is under the path "Datacenter > Storage". The template you can simply download by clicking on "Tempaltes" in the detail view of the storage ("shared" in this example).

**Comment by Jungo495** [comment]
@in0rdr Thank you! 
But im got some !!! TERRAFORM CRASH !!!
error: code = Unavailable desc = transport is closing
then I thought that I need to add a desc field
and got!
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
