### ISSUE TITLE
Creating lxc container: "error 500 no such resource"

### ISSUE THREAD

**Issue by Zapfmeister** [Telmate/terraform-provider-proxmox#445]
Im trying to create an lxc container on a proxmox 7.1-5:

```
terraform {
  required_providers {
    proxmox = {
      source  = "telmate/proxmox"
      version = ">=2.9.1"
    }
  }
}

provider "proxmox" {
  pm_tls_insecure = true
  pm_api_url      = "https://myip:8006/api2/json"
  pm_password     = "password"
  pm_user         = "terraform-prov@pve"
}

resource "proxmox_lxc" "lxc-test" {
  count = 1
  features {
    nesting = true
  }

  // Terraform will crash without rootfs defined
  rootfs {
    storage = "local-zfs"
    size    = "8G"
  }

  hostname = "tf-new"
  network {
    name   = "eth0"
    bridge = "vmbr0"
    ip     = "dhcp"
    ip6    = "dhcp"
  }
  ostemplate = local:vztmpl/ubuntu-21.04-standard_21.04-1_amd64.tar.gz
  password   = "rootroot"
  target_node  = "host1"
  unprivileged = true
}
```

The container gets created, but it seems it can't get the containers state?:
```
proxmox_lxc.lxc-test[0]: Creating...
proxmox_lxc.lxc-test[0]: Still creating... [10s elapsed]
proxmox_lxc.lxc-test[0]: Still creating... [20s elapsed]
╷
│ Error: 500 no such resource 'ct:111'
│
│   with proxmox_lxc.lxc-test[0],
│   on main.tf line 20, in resource "proxmox_lxc" "lxc-test":
│   20: resource "proxmox_lxc" "lxc-test" {
│
```

I tried also with using root@pam, but the same issue appears.

**Comment by Zapfmeister** [comment]
The ID 111 is correct

**Comment by niko-lay** [comment]
same issue with 2.9.1 provider version

**Comment by XDjackieXD** [comment]
I have the same issue (updated to 2.9.1 from 2.7.4) with all existing containers meaning I can't even get `terraform plan` to work because of the existing containers

**Comment by NULLx76** [comment]
I've also got the same issue with provider version 2.9.1 after upgrading from 2.9.0, the containers with the container id do definitely exist.

**Comment by gravyflex** [comment]
this worked for me after downgrading to 2.8.0.

**Comment by mleone87** [comment]
a fix is waiting to be merged in api repo and then there

**Comment by ebiekoelle** [comment]
this worked for me after downgrading to 2.9.0.

**Comment by briandipalma** [comment]
Just tested 2.9.2 and I'm seeing this, was using 2.9.1 before and it was fine.

**Comment by NULLx76** [comment]
I had this problem on 2.9.1 and it still persists on 2.9.2, 2.9.0 works fine though

**Comment by briandipalma** [comment]
Nope, it's broken with 2.9.1 too.

**Comment by briandipalma** [comment]
2.9.0 works great, much faster to run a plan too.

**Comment by mleone87** [comment]
post config and error please

**Comment by briandipalma** [comment]
The error is:

```
╷
│ Error: 500 no such resource 'ct:500'
│
│   with proxmox_lxc.traefik,
│   on traefik.tf line 1, in resource "proxmox_lxc" "traefik":
│    1: resource "proxmox_lxc" "traefik" {
│
```

What do you need in terms of better logs/config? Basically though 2.9.0 OK, 2.9.1 broken.
So it's somewhere in here: https://github.com/Telmate/terraform-provider-proxmox/compare/v2.9.0...v2.9.1
Can I use sha-ids in the versions to do a binary search?

**Comment by mleone87** [comment]
@briandipalma  nevermind the go.mod was not updated in my last PR, my bad. fyi the problem was in the api library, not in the provider, and yes it wil be a little slower now due to check for ha state of containers, if present

@ggongaware  please bump to 2.9.3 as soon as you can :)

**Comment by briandipalma** [comment]
2.9.3 worked, thanks :+1:
