### ISSUE TITLE
updated  VM (cloud-init) settings fails

### ISSUE THREAD

**Issue by lunne** [Telmate/terraform-provider-proxmox#46]
I have created a VM in Proxmox with a cloud-init template and it works great.
I have want to change something it fails. Is this a known bug?

looks like it sending in:
   agent=&ciuser....
 {"errors":{"agent":"invalid format - format error\nagent.enabled: property is missing and it is not optional\n"

**Comment by ggongaware** [comment]
The agent field is new, probably never tested on update, thank you for the bug report.
