### ISSUE TITLE
cloud-init sets hostname after dhcp on first boot, so another reboot is required for DNS to work

### ISSUE THREAD

**Issue by andrewfraley** [Telmate/terraform-provider-proxmox#481]
I'm using the following to provision Ubuntu Server 20.04 nodes, which works fine except that I have to reboot the nodes to get them to register their proper hostname with DHCP/DNS.  I'd guess this is due to the initial dhcp lease being obtained before cloud-init changes the hostname, as after manually rebooting, the node is properly registered with the correct hostname.  

What's the best way to resolve this?  It's fine with me if Terraform needs to reboot the node, but I don't think this provider can do that for me.

```
resource "proxmox_vm_qemu" "node1" {
  name        = "node1"
  target_node = local.proxmox_node
  clone       = local.vm_template
  sockets     = 2
  cores       = 4
  memory      = 4096 # in MB
  agent       = 1
  os_type     = "cloud-init"
}
```

**Comment by TobiasS1402** [comment]
I have experienced the same problem, maybe you could use the [terraform `provisioner remote-exec`](https://www.terraform.io/language/resources/provisioners/remote-exec) to force a reboot at the end of your file like this.
```
provisioner "remote-exec" {
    inline = [
        "reboot"
    ]
}
```

**Comment by mleone87** [comment]
not a provider issue, not even a proxmox issue would say
@TobiasS1402 provided solution
