### ISSUE TITLE
terraform plan Error: your API TokenID username should contain a !, check your API credentials

### ISSUE THREAD

**Issue by sfoubister** [Telmate/terraform-provider-proxmox#484]
Hi there
I am following your tutorial but get the following error when doing `terraform plan`:

```
│ Error: your API TokenID username should contain a !, check your API credentials
│
│   with provider["registry.terraform.io/telmate/proxmox"],
│   on main.tf line 10, in provider "proxmox":
│   10: provider "proxmox" {
```

Any idea what needs to be done?

Thanks
Steve

**Comment by TobiasS1402** [comment]
What does your token id look like @sfoubister?
Should be something along the lines of:

```
variable "pm_api_token_id" {
    description = "Proxmox API token id"
    default = "username@pam!xxxxxxxxxxxxxx"
}
```

**Comment by sfoubister** [comment]
Where is that block defined? I have generated an API token but where I do I specify it for terrform?

**Comment by pgporada** [comment]
You can export variables via the CLI which is what I would do, or hardcode them into the `provider` block. There's no explicit documentation showing that though.

https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/index.md#creating-the-connection-via-username-and-api-token

```
provider "proxmox" {
  pm_api_url = "https://proxmox-server01.example.com:8006/api2/json"
  pm_api_token_id = "somehardcodedvalue@pam!zxzxzxzxzcxczxczxczxc"
  pm_api_token_secret = "zxxxxzxzxxzxzxzxzxzx"
}

**Comment by sfoubister** [comment]
Thanks @pgporada - hard coding the pm_api_token_secret in the provider block worked.
