### ISSUE TITLE
Not able to import network and mountpoint config

### ISSUE THREAD

**Issue by ytiOS** [Telmate/terraform-provider-proxmox#493]
i'm currently trying to import existing containers into Terraform. The import is working without problems, except that the configuration for the network and mountpoints are missing. Is this behaviour wanted?

the command I'm using
 `terraform import proxmox_lxc.test123 PVE05/lxc/113`

The ressource configuration:

> resource "proxmox_lxc" "test123"
  target_node  = "PVE05"
  onboot       = false
  vmid         = 113

Heres is a snippet from the debug log, there is clearly a mountpoint and a network-device defined
`"data":{"features":"nesting=1","swap":512,"rootfs":"local-sas-4000GB:vm-113-disk-0,size=8G","unprivileged":1,"hostname":"test123","cores":1,"arch":"amd64","mp0":"local-lvm:vm-113-disk-0,mp=/test,size=8G","ostype":"debian","net0":"name=eth0,bridge=vmbr0,firewall=1,hwaddr=/,type=veth","memory":512,"digest":"/"
`
GET /api2/json//cluster/ha/resources/113 HTTP/1.1

And here is the state I get, without network-devices and mountpoints

> 
    {
      "mode": "managed",
      "type": "proxmox_lxc",
      "name": "test123",
      "provider": "provider[\"registry.terraform.io/telmate/proxmox\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "arch": "amd64",
            "bwlimit": 0,
            "clone": null,
            "clone_storage": null,
            "cmode": "",
            "console": true,
            "cores": 1,
            "cpulimit": 0,
            "cpuunits": 1024,
            "description": "",
            "features": [],
            "force": false,
            "full": null,
            "hagroup": "",
            "hastate": "",
            "hookscript": "",
            "hostname": "test123",
            "id": "PVE05/lxc/113",
            "ignore_unpack_errors": false,
            "lock": "",
            "memory": 512,
            "mountpoint": [],
            "nameserver": "",
            "network": [],
            "onboot": false,
            "ostemplate": null,
            "ostype": "debian",
            "password": null,
            "pool": null,
            "protection": false,
            "restore": false,
            "rootfs": [
              {
                "size": "8G",
                "storage": "",
                "volume": "local-sas-4000GB:vm-113-disk-0"
              }
            ],
            "searchdomain": "",
            "ssh_public_keys": null,
            "start": null,
            "startup": "",
            "swap": 512,
            "tags": "",
            "target_node": "PVE05",
            "template": false,
            "timeouts": {
              "create": null,
              "default": null,
              "delete": null,
              "read": null,
              "update": null
            },
            "tty": 2,
            "unique": false,
            "unprivileged": true,
            "unused": [],
            "vmid": null
          },
          "sensitive_attributes": [],
          "private": "/"
        }
      ]
    }

**Comment by IQNeoXen** [comment]
got the exact same problem. simply overwriting the network config is ok imo, but i really don't wanna try this with mountpoints
