### ISSUE TITLE
Changing ssh_public_keys causes LXC container to be destroyed

### ISSUE THREAD

**Issue by briandipalma** [Telmate/terraform-provider-proxmox#497]
Bit surprised by this but changing `ssh_public_keys`, even if all I do is delete a white space causes the provider to destroy the LXC. That seems unnecessary?

**Comment by mleone87** [comment]
In the proxmox WEB GUI, how do you change the ssh key in a LXC container without recreating it? :)

**Comment by briandipalma** [comment]
Is it because Proxmox wouldn't have access to the private keys that you have access to on your control node I guess, so it can't login to the container to update it? That's annoying. I guess this will have to be moved to an Ansible common role...

**Comment by mleone87** [comment]
this provider (tries to) replicate what can be done in GUI and/or CLI, boring or not, this is it.
As you said move to ansible for operating system management

**Comment by leondrefoto** [comment]
> this provider (tries to) replicate what can be done in GUI and/or CLI, boring or not, this is it.

But it can be done by CLI with **pct enter** command e.g.:
`"mkdir -p /root/.ssh && echo "<pub-key>" >> /root/.ssh/authorized_keys" | pct enter <vmid>`

source: https://forum.proxmox.com/threads/pct-exec-with-parameters.26053/

**Comment by leondrefoto** [comment]
> Oh, I think I see what you are saying. The provider can't login to the container and update the authorized_keys file? It's not something that terraform supports?

But it can be done by CLI with pct enter command e.g.:
"mkdir -p /root/.ssh && echo "<pub-key>" >> /root/.ssh/authorized_keys" | pct enter <vmid>

source: https://forum.proxmox.com/threads/pct-exec-with-parameters.26053/
