### ISSUE TITLE
Build fails. This project needs some CI.

### ISSUE THREAD

**Issue by f0rkz** [Telmate/terraform-provider-proxmox#50]
```
# github.com/Telmate/terraform-provider-proxmox/proxmox
terraform-provider-proxmox/proxmox/resource_vm_qemu.go:356:3: cannot use d.Get("agent").(string) (type string) as type int in field value
```

**Comment by f0rkz** [comment]
```
f0rkz@vdi:~/terraform-provider-proxmox$ make
 -> Building
# github.com/Telmate/terraform-provider-proxmox/proxmox
../../../go/src/github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:356:3: cannot use d.Get("agent").(string) (type string) as type int in field value
Makefile:7: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by ggongaware** [comment]
Any CI recommendations?

**Comment by f0rkz** [comment]
Travis is pretty rad.

I can come up with a basic pipeline for you to build commits. Would this help? I really like the promise of this project and want to help as much as I can.

**Comment by ggongaware** [comment]
That would totally help. I've accepted too many pull requests I didn't really test, just hoped someone else did already.

**Comment by f0rkz** [comment]
Will do. PR incoming soonish.

**Comment by f0rkz** [comment]
There will be a badge you can add to the README.md within travis. Once you see a build in progress, it will show you a badge you can add to the readme. Make sure you select markdown and copy and paste it in your README.md file.

**Comment by f0rkz** [comment]
I went ahead and added a badge to the README.md in PR #52

**Comment by f0rkz** [comment]
Thanks bud. Let's continue to work on this project :)

I don't know go, so I need some help. Its on my list of to learn languages.

This will help at least build the project and confirm any failures before they are merged in.

**Comment by ggongaware** [comment]
Build fixed, thanks for the help, Issue 47 needs some more work, adjusting the change detection for fields that can be auto-populated

**Comment by James9074** [comment]
+1 on this, @f0rkz + @ggongaware I'd like to get involved here. Would be happy to learn some go and help support the CI for this.
