### ISSUE TITLE
Latest version errors saying a number is required

### ISSUE THREAD

**Issue by briandipalma** [Telmate/terraform-provider-proxmox#502]
```
│ Error: a number is required
│ 
│   with proxmox_lxc.work-docker,
│   on work-docker.tf line 22, in resource "proxmox_lxc" "work-docker":
│   22:   network {
```

```
  network {
    name   = "eth0"
    bridge = "vmbr0"
    gw     = var.gateway_ip
    ip     = var.unifi_ip
    ip6    = "auto"
    hwaddr = var.unifi_mac
  }
```

This works fine on the last provider. Something to do with the MTU changes?

**Comment by gbschenkel** [comment]
I have the same issue, problem relate to MR #499.

**Comment by mleone87** [comment]
you have inconsistent state file from older version where mtu was a string, either edit the state file or start from scratch with latest version and a clean state file

**Comment by briandipalma** [comment]
OK, edit it to 0 I guess? -1?

**Comment by git-saj** [comment]
I manually set the MTU value to 0 in state and it has worked as expected.

**Comment by mleone87** [comment]
just put 1500 like it should be
