### ISSUE TITLE
upgrade memory - shutdown fail

### ISSUE THREAD

**Issue by leandroaur** [Telmate/terraform-provider-proxmox#506]
When we upgrade the memory for a VM into proxmox 7.1-7, terraform fails on sending a shutdown to the VM, got the following error:

`TASK ERROR: VM quit/powerdown failed`

Probably solution: replace the qm shutdown to qm stop

**Comment by leandroaur** [comment]
Please remove this issue, the function was not running due to the qemu agent stopped into the image.

**Comment by edikmkoyan** [comment]
@leandroaur, how did you solve the problem?

**Comment by leandroaur** [comment]
Hey @edikmkoyan it's been a while, but as I remember I think there was no issue, the qemu agent just stopped during the deployment...
