### ISSUE TITLE
vmid = 0 should be a valid value

### ISSUE THREAD

**Issue by XReyRobert-IBM** [Telmate/terraform-provider-proxmox#507]
Trying to setup a vm with a vmid = 0 returns an error.

 '''Error: proxmox [{{} vmid}] must be in the range (100 - 999999999), got 0
   with module.proxmox_haproxy.proxmox_vm_qemu.machine,
   on proxmox_machines/main.tf line 108, in resource "proxmox_vm_qemu" "machine":
 108:   vmid = 0'''

per [documentation](https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/resources/vm_qemu.md) a value of 0 should be allowed for auto-increment by proxmox

**Comment by mleone87** [comment]
omitting vmid should fix the problem, changing the documentation would fix the problem too!

**Comment by kencx** [comment]
This has been fixed by #530. Just tested on latest v2.9.14 and it works fine.
