### ISSUE TITLE
Applying with undefined "vmid" causes "Error: 501 no such file '/nextid'"

### ISSUE THREAD

**Issue by The-Judge** [Telmate/terraform-provider-proxmox#508]
I am using Terraform Cloud with VCS connection, so I can't run `terraform apply` and the following is the result as provided by the Terraform Cloud outputs.

I am trying to apply the following to my PVE Cluster:

```terraform
resource "proxmox_lxc" "basic1" {
  target_node  = "adev01"
  hostname     = "lxcbasic1"
  ostemplate   = "local:debian-11-standard_11.0-1_amd64.tar.gz"
  password     = "MySuperSecretPass"
  unprivileged = true
  cores        = 2
  memory       = 1024
  swap         = 1024
  #vmid         = 101

  rootfs {
    storage = "local-zfs"
    size    = "8G"
  }

  network {
    name   = "eth0"
    bridge = "vmbr4"
    gw     = "10.23.42.1"
    ip     = "10.23.42.100/24"
  }
}
```

[Docs](https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/lxc#vmid) say that it's fine to not define this:
> If set to 0, the next available VMID is used. Default is 0.

`terraform plan` seems to be OK with this, showing `vmid = 0`.

`apply` fails with

> Error: 501 no such file '/nextid'

Running `pvesh get /cluster/nextid` on any of the cluster's nodes seems to work fine, since it returns `101`:
```
root@adev03:~# pvesh get /cluster/nextid
101
root@adev03:~#
```

If I manually define `vmid = 101`, I receive another error:

```
Error: error creating LXC container: 501 no such file '/adev01/lxc', error status: (params: {
  "arch":"amd64",
  "cmode":"tty",
  "console":true,
  "cores":2,
  "cpulimit":0,
  "cpuunits":1024,
  "features":"",
  "hostname":"lxcbasic1",
  "memory":1024,
  "net0":"name=eth0,bridge=vmbr4,ip=10.23.42.100/24,gw=10.23.42.1",
  "onboot":false,
  "ostemplate":"local:debian-11-standard_11.0-1_amd64.tar.gz",
  "password":"MySuperSecretPass",
  "protection":false,
  "rootfs":"local-zfs:8",
  "start":false,
  "storage":"local",
  "swap":1024,
  "tags":"",
  "tty":2,
  "unprivileged":true,
  "vmid":101
})
```

I guess, this is worth another report (see #509); just mentioning it here for the sake of completeness, too.

**Comment by mleone87** [comment]
there is clearly some problem with the proxmox endpoint definition, not sure how you define it in tf cloud + vcs but the problem is there

**Comment by The-Judge** [comment]
I switched away from TF cloud to local execution to minimize the possibility of non-base TF/Provider issues with TF cloud.
Also, I completely re-setup a new Proxmox VE Cluster using the setup variant [PVE on Debian Buster](https://pve.proxmox.com/wiki/Install_Proxmox_VE_on_Debian_Buster) as well as using the [Proxmox VE 7.1 ISO Installer](https://www.proxmox.com/de/downloads/item/proxmox-ve-7-1-iso-installer) on bare metal system.

Nothing helped; all systems and combinations resulted in the same issue outlined before.

**Comment by marksie1988** [comment]
Anyone found a way to get around this, just moving to TF and have the same issue, dont really want to specify the vmid's if i can avoid it.

**Comment by fayeg21** [comment]
I'm getting this too

**Comment by rafaelarcanjo** [comment]
Similar issue
`roxmox_vm_qemu.main: Still creating... [10s elapsed]
╷
│ Error: 501 no such file '/resources'
│ 
│   with proxmox_vm_qemu.main,
│   on main.tf line 25, in resource "proxmox_vm_qemu" "main":
│   25: resource "proxmox_vm_qemu" "main" {
│ 
╵
`

**Comment by Gruffalo-ts** [comment]
same here:

Running the latest version of terraform (v.1.3.7 on ubuntu) as well as the provider (v2.9.11)

From the debug logs I see:

`2023-01-08T11:35:57.492+0100 [ERROR] provider.terraform-provider-proxmox_v2.9.11: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_severity=ERROR diagnostic_summary="501 no such file '/cluster/nextid'" tf_provider_addr=registry.terraform.io/telmate/proxmox tf_req_id=cf1a4b20-582b-33c6-ff84-dbf06189c12d tf_rpc=ApplyResourceChange @module=sdk.proto diagnostic_detail= tf_proto_version=5.3 tf_resource_type=proxmox_vm_qemu timestamp=2023-01-08T11:35:57.492+0100
`

**Comment by shauser** [comment]
If you run into this issue make sure that your provider's URL is set to https://x.x.x.x:8006/api2/json, not just https://x.x.x.x:8006/. This information is easily looked over in the documentation and is pretty hard to debug from these error messages...
