### ISSUE TITLE
LXC with clone did not set other parameters for a first time, only on second try

### ISSUE THREAD

**Issue by npdev453** [Telmate/terraform-provider-proxmox#514]
`memory` and some other tags did not set on first `terraform apply`
For example I have one template with preconfigured `memory = 1024`
When I'm trying to clone that template by `proxmox_lxc`:

```tf
 resource "proxmox_lxc" "worker1" {
   target_node = "node1"
   hostname = "worker1"
   clone = 100
   full = true
   memory = 1024
   start = true
   onboot = true
 }
```
After first `terrform apply` CT  will be created with 512mb (config from clone)
After second`terrform apply` CT will be updated to 1024mb 

Little bit confused.

**Comment by gregorydlogan** [comment]
I'm seeing similar behaviour, except that the second `terraform apply` fails completely with a 500 error from proxmox because the ct already exists on the node.
