### ISSUE TITLE
Disk size TB not allowed

### ISSUE THREAD

**Issue by XDjackieXD** [Telmate/terraform-provider-proxmox#521]
The disk size argument does not take "T" which is valid in the Proxmox API.
When setting the disk size to for example 4096GB, Proxmox returns this as "4T" when queried for the size which is why terraform now always tries to change the size back from 4T to 4096GB (which is probably a no-op in Proxmox) on every apply.

Allowing for "T" in the size config would fix this imo.

**Comment by XDjackieXD** [comment]
The issue has been fixed for LXC containers but not for QEMU VMs. See https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L373

**Comment by XDjackieXD** [comment]
Issue still exists.

**Comment by XDjackieXD** [comment]
https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L430 still an issue (could you *please* disable this absolutely annoying bot? issues don't just disappear by themself...)

**Comment by XDjackieXD** [comment]
https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L430 still an issue (could you please disable this absolutely annoying bot? issues don't just disappear by themself...)

**Comment by XDjackieXD** [comment]
![240843313-fc455bff-772e-486d-a05a-4f667de4c6ae](https://github.com/Telmate/terraform-provider-proxmox/assets/4963868/49d55a82-80b5-47d3-89c7-b14ad35312c9)

**Comment by Tinyblargon** [comment]
@XDjackieXD #929 will fix this once a new release is created.

**Comment by Tinyblargon** [comment]
Fixed in master branch
