### ISSUE TITLE
Is there an argument for QEMU VM start up order?

### ISSUE THREAD

**Issue by ralgar** [Telmate/terraform-provider-proxmox#525]
I see there is an argument `startup` for LXC, however I cannot seem to find any related argument for VMs in the docs.

I've tried using the same `startup` argument for VMs and Terraform returns `Unsupported argument`.

**Comment by BaldFabi** [comment]
Have a look at https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/resources/vm_qemu.md#top-level-block for the option `onboot`

**Comment by ralgar** [comment]
Hi @BaldFabi,

I did find the `onboot` option, however that is only a boolean whether to start the VM or not, there seems to be no option to set the startup order and delay, as there is with LXC.

You can [see here](https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/resources/lxc.md#optional) the option which I am talking about is called `startup`, and it is supplementary to the `onboot` option.

**Comment by BaldFabi** [comment]
Yes you're right. I misinterpreted the documention. As far as I know it's currently impossible. It could be implemented if the api provides it.

**Comment by ralgar** [comment]
It seems that the option is there for both POST and PUT, according to the [API docs](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/config).

I'm currently experimenting with this locally. I have no Go experience, but if I'm not mistaken it seems like only a few lines of code to implement it. If I can get it working, I'll submit a PR sometime this week.
