### ISSUE TITLE
Could not deploy more than 3 VMs at a time?!

### ISSUE THREAD

**Issue by JalenMak6** [Telmate/terraform-provider-proxmox#527]
Hi, I came up an issue with my main.tf and var.tf
I could successfully deploy 3 VM at a time perfectly. But When I deploy destroy all the VM and deploy 4 VM all together, it pops up an error, here is my code and error. After that, everything screw up. I cannot deploy a single VM in a the same tf file. I have to do delete the dataset in my rpool so that I could re-deploy it.

main.tf
```
`terraform {
    required_providers {
        proxmox = {
            source = "telmate/proxmox"
            version = "2.9.6"
        }
    }
}

provider "proxmox" {
    pm_tls_insecure = false
    pm_api_url = "https://myplace.com/api2/json"
    pm_api_token_id = "me@pam!metoken"
    pm_api_token_secret = "121231231231"
    pm_log_enable = true
    pm_log_file = "terraform-plugin-proxmox.log"
    pm_debug = true
    pm_log_levels = {
        _default = "debug"
        _capturelog = ""
    }
    
}

resource "proxmox_vm_qemu" "practisehour" {
    for_each = var.vminfo
    name = each.value.name
    vmid = each.value.vmid
    agent = each.value.agent
    target_node = each.value.target_node
    onboot = each.value.onboot
    oncreate = each.value.oncreate
    clone = each.value.clone 
    memory = each.value.memory
    sockets = each.value.socket
    cores = each.value.cores
    vcpus = each.value.vcpus
    cpu = each.value.cpu 
    scsihw = each.value.scsihw
    os_type = each.value.os_type
    ciuser = each.value.ciuser
    cipassword = each.value.cipassword
    nameserver = each.value.nameserver
    bootdisk = each.value.bootdisk

    disk {
         type = each.value.disk_type
         storage = each.value.disk_storage
         size = each.value.disk_size
         iothread = each.value.disk_iothread
    }


    network {
        model = var.network.model
        bridge = var.network.bridge
    }

    ipconfig0 = "ip=${each.value.ip},gw=${each.value.default_gateway}"

    sshkeys = <<EOF
     ${var.ssh_private_key1}
     ${var.ssh_private_key2}
    EOF

}
```
`

var.tf
```
`variable "vminfo" {
    default = {
        "Sebastian.Vettel" = {
            name = "Sebastian.Vettel",
            target_node = "Alonso",
            vmid = "203",
            ip = "192.168.1.203/24",
            default_gateway = "192.168.1.254", 
            nameserver = "192.168.1.254",
            desc = "My terraform practising time",
            onboot = true,
            oncreate = true,
            agent = 1,
            clone = "ubuntu-2004-cloudinit-template",
            memory = 2048,
            socket = 1,
            cores = 2,
            vcpus = 2,
            cpu = "host",
            scsihw = "virtio-scsi-pci",
            os_type = "cloud-init",
            ciuser = "jalen",
            cipassword = "password",
            bootdisk = "scsi0",
            disk_type = "scsi",
            disk_storage = "local-zfs",
            disk_size = "40G",
            disk_iothread = 1,
        },
        "Fernando.Alonso" = {
            name = "Fernando.Alonso",
            target_node = "Alonso",
            vmid = "204",
            ip = "192.168.1.204/24",
            default_gateway = "192.168.1.254", 
            nameserver = "192.168.1.254",
            desc = "My terraform practising time",
            onboot = true,
            oncreate = true,
            agent = 1,
            clone = "ubuntu-2004-cloudinit-template",
            memory = 6144,
            socket = 1,
            cores = 1,
            vcpus = 0,
            cpu = "host",
            scsihw = "virtio-scsi-pci",
            os_type = "cloud-init",
            ciuser = "jalen",
            cipassword = "password",
            bootdisk = "scsi0",
            disk_type = "scsi",
            disk_storage = "local-zfs",
            disk_size = "30G",
            disk_iothread = 1,
        },
       "Fernando.Alonso2" = {
            name = "Fernando.Alonso2",
            target_node = "Alonso",
            vmid = "207",
            ip = "192.168.1.207/24",
            default_gateway = "192.168.1.254", 
            nameserver = "192.168.1.254",
            desc = "My terraform practising time",
            onboot = true,
            oncreate = true,
            agent = 1,
            clone = "ubuntu-2004-cloudinit-template",
            memory = 6144,
            socket = 1,
            cores = 1,
            vcpus = 0,
            cpu = "host",
            scsihw = "virtio-scsi-pci",
            os_type = "cloud-init",
            ciuser = "jalen",
            cipassword = "password",
            bootdisk = "scsi0",
            disk_type = "scsi",
            disk_storage = "local-zfs",
            disk_size = "30G",
            disk_iothread = 1,
        },
       "Kimi.Raikkonen" = {
            name = "Kimi.Raikkonen",
            target_node = "Alonso",
            vmid = "205",
            ip = "192.168.1.205/24",
            default_gateway = "192.168.1.254", 
            nameserver = "192.168.1.254",
            desc = "My terraform practising time",
            onboot = true,
            oncreate = true,
            agent = 1,
            clone = "ubuntu-2004-cloudinit-template",
            memory = 4096,
            socket = 2,
            cores = 1,
            vcpus = 0,
            cpu = "host",
            scsihw = "virtio-scsi-pci",
            os_type = "cloud-init",
            ciuser = "jalen",
            cipassword = "password",
            bootdisk = "scsi0",
            disk_type = "scsi",
            disk_storage = "local-zfs",
            disk_size = "50G",
            disk_iothread = 1,
        },
    }
}


variable "ssh_private_key1" {
    default = "ssh-rsa AAAAB3NzaC1yck= fmf@fmf-MacBook-Air.local"
}

variable "ssh_private_key2" {
    default = "ssh-rsa AAAAB3NzaC1= xxx@xxx-ct"
  
}

variable "network" {
    default = {
        model = "e1000"
        bridge = "vmbr0"
    }
}

```

`
error log

```
 Error: Plugin did not respond
│ 
│   with proxmox_vm_qemu.practisehour["Fernando.Alonso"],
│   on main.tf line 25, in resource "proxmox_vm_qemu" "practisehour":
│   25: resource "proxmox_vm_qemu" "practisehour" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
│ more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with proxmox_vm_qemu.practisehour["Kimi.Raikkonen"],
│   on main.tf line 25, in resource "proxmox_vm_qemu" "practisehour":
│   25: resource "proxmox_vm_qemu" "practisehour" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
│ more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with proxmox_vm_qemu.practisehour["Sebastian.Vettel"],
│   on main.tf line 25, in resource "proxmox_vm_qemu" "practisehour":
│   25: resource "proxmox_vm_qemu" "practisehour" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
│ more details.
╵
2022-04-03T17:07:49.419-0700 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2022-04-03T17:07:49.419-0700 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2022-04-03T17:07:49.419-0700 [DEBUG] provider: plugin exited
```

**Comment by stanier** [comment]
When cloning VMs with a disk size greater than ~8GiB you should ensure the following:
* the template VM's boot disk has the `discard` option enabled, and potentially SSD emulation if appropriate
* `qemu-guest-agent` is installed on the VM's guest
* the QEMU Guest Agent option is enabled in PVE
* QEMU Guest Agent in PVE has 'Run guest-trim after a disk move or VM migration' **enabled**
* `fstrim -av` has been run on the template VM's guest
* the guest disk is SCSI, using the VirtIO SCSI controller

If these things and anything else I may be forgetting are right, then what this should do is shrink the logical size of the guest's filesystem by ignoring empty/unused space (zero blocks or w/e they are called, I can't remember), then automatically expand the filesystem on the cloned VM, reducing the amount of data PVE actually has to copy in order to clone the virtual disk.

There is some insight on this somewhere on the PVE wiki that I found the other night, but I unfortunately don't have a link handy for it.

I've tested this for up to 20 VMs, with parallelism set to 10, cloning ~2GiB Rocky Linux 8.5 minimal template and expanding them to 16GiB.  This means we went from copying ~340GiB to ~40GiB, bringing the time to completion from >30 mins to <4 mins, and eliminating any errors caused by API request timeouts.

Hope this helps!

**Comment by gostega** [comment]
> * fstrim -av

Is this inside the guest or on the proxmox host against the VM disk?

> * QEMU Guest Agent in PVE has 'Run guest-trim after a disk move or VM migration' **enabled**

Any chance you can point me where or how to set this? I have no idea where to start. Have looked in Datacenter > Options and VM specific options.

Thanks in advance

**Comment by stanier** [comment]
> > * fstrim -av
> 
> Is this inside the guest or on the proxmox host against the VM disk?
>

Inside the guest with no extra params
> 
> > * QEMU Guest Agent in PVE has 'Run guest-trim after a disk move or VM migration' **enabled**
> 
> Any chance you can point me where or how to set this? I have no idea where to start. Have looked in Datacenter > Options and VM specific options.
>

As tested on VE 7.2-4, can be found under [VM] > Options > QEMU Guest agent (Click) > Edit (Upper Right Button) > 
Run guest-trim after a disk move or VM migration

Hope this helps!

**Comment by IeatGerbils** [comment]
Starting with terraform recently and ran into the timeout issue aswell. The option to add in the resources section is full_clone= "false". Had deployments failing if doing more than 3 at a time. For the tutorials I found, none had that but they also only did one vm in their guides. With image prep with stanier posted it was still failing with terraform but doing a manual clone in proxmox was practically instant. Adding the full_clone= "false" option I was able to deploy 8 VMs in approx. 2 minutes. So it seems the telmate defaults to full clones, I think having it a required entry instead of optional, others will have to specify full or linked when creating the resource and hopefully avoid this.

**Comment by mjbright** [comment]
@leatGerbils
Interesting about your use of ```full_clone="false"```.

I was hoping this would solve the problems I've seen with this provider, but no luck for more than 4 VMs - so I have to keep using bash scripts to provision Proxmox ( arrgh !! )

I've been using qm + bash to create tens of 3-node clusters without any problems - still hoping to have this provider working correctly sometime.

Looks like I should try out the ```fstrim -av``` tip, though obviously I don't need this for qm+bash.

**Comment by mjbright** [comment]
This inspired me to go back to the examples, to see if I could make those scale.

I was able easily to reproduce the pxe-example, with a count of 25, with no problems - so it looks like yes, it's the cloning which causes me problems with my usual configs.

I'll play some more to see how I can get from the pxe-example, to something to replace my current config which uses clone ...

**Comment by mjbright** [comment]
I recreated my template VM, making sure to install the qemu-guest-agent, setting discard=on, full_clone=false
(btw - I checked my bash scripts that I use with qm, so no Terraform ... I don't specify either full_clone or discard values)

Creating a cloud-init VM  (from that template), works for a single VM - although it takes about 5 minutes.

It works also for up to 4 VMs, but beyond that none of the VMs get past the "starting" state.
Not sure what to try next.

**Comment by mjbright** [comment]
... that was with a TEMPLATE disk size of 4G, and a cloned disk of 16G by the way (but I'd forgotten to do the ```fstrim -av``` on the template guest)

**Comment by mjbright** [comment]
OK, I created a new TEMPLATE with 4G disk, qemu-guest-agent installed and after using fstrim -av.

That helped a little.

I was able to create 9 (out of 11 requested) VMs (cloned to 16G disk) before getting

```
│ Error: 400 Parameter verification failed.
│
│   with proxmox_vm_qemu.proxmox_vm[9],
│   on proxmox_vm_qemu.tf line 47, in resource "proxmox_vm_qemu" "proxmox_vm":
│   47: resource "proxmox_vm_qemu" "proxmox_vm" {
│
```

**Comment by mjbright** [comment]
OK, mea culpa for that error ... VM 10 would have broken my simplistic ip address calculation :)

```ipconfig0 = "ip=192.168.0.15${count.index + 1}/24,gw=192.168.0.254"```

I'll change that to

```ipconfig0 = "ip=192.168.0.${count.index + 151}/24,gw=192.168.0.254"```

and try again ... tomorrow ...

**Comment by Sm0rezDev** [comment]
Add parallelism to your terraform apply command: ### `terraform apply -parallelism=3` This will limit the amount of concurrent task at a time.
