### ISSUE TITLE
Terraform create new vm with 400 Parameter verification failed error

### ISSUE THREAD

**Issue by slchris** [Telmate/terraform-provider-proxmox#529]
main.tf:

```tcl
terraform {
  required_providers {
    proxmox = {
      source = "telmate/proxmox"
      version = "2.9.6"
    }
  }
}


provider "proxmox" {
  pm_api_url      = var.PROXMOX_API_ENDPOINT
  pm_password = var.PM_API_PASS
  pm_user = var.PM_API_USER
  pm_tls_insecure = true
  pm_log_enable = true
  pm_log_levels = {
    _default    = "debug"
    _capturelog = ""
  }
}

resource "proxmox_vm_qemu" "cloudinit-test" {
    name = "terraform-test-vm"
    desc = "A test for using terraform and cloudinit"

    # Node name has to be the same name as within the cluster
    # this might not include the FQDN
    target_node = var.PROXMOX_NODE
    clone = var.CLONE_TEMPLATE
    # Activate QEMU agent for this VM
    agent = 1

    os_type = "cloud-init"
    cores = 2
    sockets = 1
    vcpus = 0
    cpu = "host"
    memory = 2048
    scsihw = "lsi"

    # Setup the disk
    disk {
        size = "32G"
        type = "virtio"
        storage = "local-lvm"
        iothread = 1
    }

    # Setup the network interface and assign a vlan tag: 256
    network {
        model = "virtio"
        bridge = "vmbr0"
    }

    # Setup the ip address using cloud-init.
    # Keep in mind to use the CIDR notation for the ip.
    ipconfig0 = "ip=10.0.0.99/16,gw=10.0.0.1"
    sshkeys = <<EOF
    ${var.ssh_key}
    EOF
}
```

terraform.tfvars:

```hcl
# PROXMOX
PROXMOX_API_ENDPOINT = "https://10.0.0.4:8006/api2/json"
PM_API_USER = "terraform-prov@pve"
PM_API_PASS = "password"
PROXMOX_NODE = "workstation2"
DEFAULT_BRIDGE = "vmbr0"
CLONE_TEMPLATE = "ubuntu-server-22-04-packer-template"
ssh_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCs/m+4qHt0Xlc6AFCxB3HM8TeIxxGuLviPdZgv2kGN2Wwb+NAP2r6OXon1Sz7AY5PS23CXptR+SVsbWyn5sZxnvTkWp7meaTKBEVF8tbhaD1W3x4w86k/gcxrB/nIJ1et693/7nwnn2E3uVZdLvjMOBiQ8yNdtpkQVaQQacwLCJn+IPd4EpS1QqqGgbGISteg02BxouldeaZBtbezeBrrpv9YEGdNraFdyGmc7Prkv5XjGiAjJuCV8eHeykvtreq3vAhZsxdaIDb2QLhYyXfc2AhCK0WwbMB9/fJjsm5mlODImnLl17k84ZwseKTxxiNGtZOEyMkhjEHlY+5ACXoG/4QV4a5oVElh2hzCAYN1iRxynJQIuGVzOx6krxKvZ3apweATJ4+WSECj7mQ3ckDLvuLvB7GrwEUzIBDPxSzElu8iWQdwqz9iJ4pdCibMLi/5cAQQpmcsu1dkF36iMtUolugiw0f8fVXUtSZ03y/8hBUt8c9lqoDa0k+amUFfij48LMZPb0NWEFE0VB5PEC4VSb9FBw0qrdHfScx9dZ0wLseCjjSVDYHe8JbtzvunCh1FTATeH1HdEgEI2taKquAvAVJZZQ0/rIdNVwr93GpICkics+SESOcrz/9VkA6pdHtN1T7dx1VhErbrwzR3tGpZZDrOEM5tSh+fz5kF33Ee3Rw== cardno:11 023 204"
```

variables.tf:

```hcl
#Variables

variable "PROXMOX_NODE" {
  default     = "workstation2"
  description = "Node to use for VM creation in proxmox"
  type        = string
}

variable "PROXMOX_API_ENDPOINT" {
  description = "API endpoint for proxmox"
  type        = string
}


variable "PM_API_USER" {
  type        = string
}


variable "PM_API_PASS" {
  type        = string
}

variable "DEFAULT_BRIDGE" {
  description = "Bridge to use when creating VMs in proxmox"
  type        = string
}

variable "CLONE_TEMPLATE" {
  description = "Name of your template"
  type        = string
}

variable "ssh_key" {
  type = string
}
```

After I execute terraform apply, I can see that a new virtual machine is created on the proxmox web page, but the virtual machine is not bootup, and the ip information of this machine is not set correctly,  I see 400 in the terminal mistake.

Here is the specific log 
https://fars.ee/XfFv

**Comment by slchris** [comment]
terraform version
Terraform v1.1.7
on darwin_arm64
+ provider registry.terraform.io/telmate/proxmox v2.9.6

**Comment by mizhka** [comment]
Try to check status of task in proxmox. It may contain helpful information about source of problem.

**Comment by slchris** [comment]
> Try to check status of task in proxmox. It may contain helpful information about source of problem.

I see in the proxmox task that the virtual machine has been successfully created, but the corresponding virtual machine cloud init is not properly configured

**Comment by slchris** [comment]
I try to reinstall the proxmox system and use different operating systems, and the issue of granting users maximum privileges remains, But the result is still the same, here is the latest debug log:
https://fars.ee/ZXB4

**Comment by mleone87** [comment]
Sshkeys is wrong, or you put it inline with EOF, Or you use variabiles

**Comment by slchris** [comment]
> Sshkeys is wrong, or you put it inline with EOF, Or you use variabiles

Thanks for your reply, looks like a problem with this ssh key.
This ssh key is generated by my yubikey. This seems to be a bug, Looks like not support yubikey's ssh key.
Also, thanks @yqlbu for your patience and help,  for now on everything worked fine!

**Comment by lethargosapatheia** [comment]
I had the same error after adding an invalid option to 'vga' (I set it to 'default' - I wonder why this doesn't work, anyway, although not specifying it at all will set it to 'default', indeed).

Does it make sense to create an issue related to the error being too ambiguous? How would you normally go about debugging this? In my case I knew where to look because that was one of the latest parameters I had changed, but I wouldn't have had any ideas if I had taken over from someone else.
In /var/log/pveproxy I see only plain access requests and there's nothing relevant in the GUI. The error occurs after cloning the template (which finishes successfully),
