### ISSUE TITLE
v2.9.8 is crashing

### ISSUE THREAD

**Issue by risayew** [Telmate/terraform-provider-proxmox#541]
Hi Everybody. With version 2.9.6 and 2.9.7 all works like a charm, but the same script crashes with 2.9.8.
I observe some issues with boot disc, VM can't get its boot disc attached.

Please help me to provide relevant logs.

**Comment by mizhka** [comment]
Create pull request #542
https://github.com/Telmate/terraform-provider-proxmox/pull/542

**Comment by frozenfoxx** [comment]
Since the pull request was merged, can this be closed?
