### ISSUE TITLE
Permission issues are hard to troubleshoot due to lack of preflight checks

### ISSUE THREAD

**Issue by mbainrot** [Telmate/terraform-provider-proxmox#544]
This is more of a feature request though is also sort-of a bug.

Basically when you do not provide correct permissions (such as being a lazy home labber like me and doing a root token and forgetting to untick "Priviledge Seperation") you get obscure error messages such as "can't find template" when in reality the creds may have no permissions to do anything.

Digging through the API there is an API endpoint called /api2/json/access/permissions which allows the authenticated person (be it via auth ticket or via API token) to get a list of their permissions.

**Comment by gostega** [comment]
+1 this would have saved me hours of headaches when first learning to use this
