### ISSUE TITLE
Re-Create VM that was manually deleted.

### ISSUE THREAD

**Issue by ycote88** [Telmate/terraform-provider-proxmox#546]
If you deploy a vm using terraform proxmox provider and delete it manually in the proxomox interface terraform will crash.
│ Error: vm '100' not found

Expected behaviour would be to re-create the vm if missing from the infra and present in the code.
At least this is what happen on AWS.

**Comment by remedywilliams** [comment]
+1

**Comment by 8666** [comment]
Error: vm '161' not found


In my case a LXC container

**Comment by myaylaci** [comment]
By deleting VM's from the ui, you create an inconsistency between the state files and the real world. The intended solution by HashiCorp is to remove the ressource from the state file by using `terraform state rm {ressource}` . 

I am not sure if it's realy a great idea to differ from Terraforms default behavior here.

**Comment by 8666** [comment]
> I am not sure if it's realy a great idea to differ from Terraforms default behavior here.

Are you sure that it is default? I expect that I can 'fix' the infrastructure by terraform if someone made a manual mistake by clicking delete in AWS. Same should be with Proxmox
