### ISSUE TITLE
"preprovision" must be removed

### ISSUE THREAD

**Issue by bkmeneguello** [Telmate/terraform-provider-proxmox#55]
This "preprovision" stuff is too tied to someone needs. This should be replaced by a "provision" plugin.
The absolute minimum should be make this option "false" by default.

**Comment by ggongaware** [comment]
Preprovision is already skipped in favor of cloud-init. Unfortunately to support older Proxmox versions without cloud-init features, these method are needed to establish connectivity to the other cool built-in provisioners (remote, chef, etc....)

**Comment by bkmeneguello** [comment]
On older versions without cloud-init features it's possible to create ans attach a cloud-init ISO or VFAT handcrafted. It only requires meta-data and user-data files and NoCloud provider will use them (https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html)
