### ISSUE TITLE
Plugin crashes while creating a virtual machine

### ISSUE THREAD

**Issue by UmanGarbag** [Telmate/terraform-provider-proxmox#552]
Hello i have a similar error to the related issue open recently.

My proxmox version is **pve-manager/7.1-12/b3c09de3**  and i'm using the **2.9.10** version of the provider.

I review my configuration and followed the requirement for authentication purpose (create a specific terraform role and user) and generate a new token.

Here the stacktrace: 
![image](https://user-images.githubusercontent.com/57763989/166819321-5067994b-4bc6-4d00-b159-779b04b69bde.png)

**Comment by UmanGarbag** [comment]
I don't think so look  : 

![image](https://user-images.githubusercontent.com/57763989/167306995-28db66cc-d81c-454d-8bcd-3f70270ccf7e.png)

**Comment by mleone87** [comment]
ok, post your provider + resource configuration then, with particular attention with the user and how it's configured on proxmox side.

**Comment by UmanGarbag** [comment]
Here my providers.tf file outside of my modules : ![image](https://user-images.githubusercontent.com/57763989/168466631-43315df1-44b3-41e3-bbe3-1248fa0e3733.png)

My providers.tf in my module : 
![image](https://user-images.githubusercontent.com/57763989/168466656-ec6d683e-2b8e-466d-971a-a846c971f4c7.png)

The configuration of the service account in proxmox is the same as the documentation provide.

The service account is terraform-prov and his permissions are the following : 
![image](https://user-images.githubusercontent.com/57763989/168466808-27d10fd3-c6bf-4cb7-a8c2-638e35ef3bd2.png)

Ressource configuration :  

I have a module name "vms" with this file : 

main.tf : 
![image](https://user-images.githubusercontent.com/57763989/168466808-27d10fd3-c6bf-4cb7-a8c2-638e35ef3bd2.png)

locals.tf: 

![image](https://user-images.githubusercontent.com/57763989/168466818-26f391ee-1102-426b-b254-a52c13e28466.png)

(and the providers.tf file)

Under the modules vms i have the resource configuration :  

main.tf : 
![image](https://user-images.githubusercontent.com/57763989/168466856-c6f52af2-b558-46d5-bcea-1496b81e803f.png)

variables.tf: 
![image](https://user-images.githubusercontent.com/57763989/168466873-acc0a767-0474-4d1f-b938-17ff11468a71.png)
