### ISSUE TITLE
ipconfig6-15 for cloud-init

### ISSUE THREAD

**Issue by jsbrain** [Telmate/terraform-provider-proxmox#555]
Although the [docs](https://github.com/Telmate/terraform-provider-proxmox/blob/8fbef59b68147b284296dc16adfc322ce740a057/docs/resources/vm_qemu.md#provision-through-cloud-init) state that in theory `ipconfig0` - `ipconfig15` is supported, when using cloud-init, it only accepts until `ipconfig5`.

Is this actually still a limitation of cloud-init specifically or this just an outdating validation step?

**Comment by thorsteinbn** [comment]
Seems like this is a limitation in the provider as noted at the bottom of this section https://github.com/Telmate/terraform-provider-proxmox/blob/8fbef59b68147b284296dc16adfc322ce740a057/docs/resources/vm_qemu.md#argument-reference

`Note: Proxmox supports ipconfigN arbitrary numbers of interfaces, but at the moment this Terraform provider has support for 0-5 addresses only. If there is interest, this could be refactored to support any number of interfaces.`
