### ISSUE TITLE
hagroup and hastate lacking permission to apply setting

### ISSUE THREAD

**Issue by defib** [Telmate/terraform-provider-proxmox#557]
If you use the permissions that were suggested in the installation documents, you will be unable to edit the hagroup/hastate in the virtual machines. It is unclear from Proxmox's documentation what permission is needed to edit these. If you add the permission sys.console you can perform this.

If I use the root account Terraform can successfully edit the hagroup/hastate settings.

**Comment by timtorChen** [comment]
Agree, and I think we may update the doc to include some extra permissions, like `VM.Migrate` to move LXC/qemu between nodes, and `Sys.Audit` and `Sys.Console` to properly modify the ha resources.

Reference: https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/ha/resources/{sid}
