### ISSUE TITLE
HA problem on single node Proxmox

### ISSUE THREAD

**Issue by julienym** [Telmate/terraform-provider-proxmox#562]
Original error: 
```
Error: 400 Parameter verification failed.
```
In debug:
```
2022/06/03 12:00:45 [DEBUG][QemuVmCreate] cloning VM
2022/06/03 12:01:18 [DEBUG][GetJsonRetryable] Sleeping for 1 seconds before asking url /cluster/ha/resources/111
2022/06/03 12:01:19 [DEBUG][GetJsonRetryable] Sleeping for 2 seconds before asking url /cluster/ha/resources/111
2022/06/03 12:01:21 [DEBUG][GetJsonRetryable] Sleeping for 3 seconds before asking url /cluster/ha/resources/111
2022/06/03 12:01:24 [DEBUG] VM 111(%!s(<nil>)) has no HA config
2022/06/03 12:01:24 400 Parameter verification failed.
```
Provider version: v2.9.10
Proxmox version: 7.2-4
Terraform v1.1.9 on linux_amd64

I tried:
- no hastate configured
- hastate = null
- hastate = ""
- Testing older provider version

Always the same error!
Any ideas ?

**Comment by Tinyblargon** [comment]
Hi,

I just tested the following config and it passed. Does the user you use for Terraform have permission to change the HA status? Could you maybe do a minimal config clone test with the "hastate" configured like the test i ran?

Versions tested:
Provider: v2.9.10
Proxmox: 7.2-4
Terraform: v1.1.9 linux_amd64

User realm: 
```
@pve
```
User Permission:
```
Datastore.Audit,
Datastore.AllocateSpace,
VM.Audit,
VM.Allocate,
VM.Clone,
VM.Config.CDROM,
VM.Config.CPU,
VM.Config.Cloudinit,
VM.Config.Disk,
VM.Config.HWType,
VM.Config.Memory,
VM.Config.Network,
VM.Config.Options,
VM.Monitor,
VM.PowerMgmt,
```
User Permission Path:
```
/
```

Test config:
```
resource "proxmox_vm_qemu" "template" {
 name = "test"
 clone = "debian11-cloudinit-template"
 full_clone = false
 target_node = "pve"
 hastate = "started"
}
```

**Comment by julienym** [comment]
@Tinyblargon Sorry I forgot to mentionned it, running on root@pam

**Comment by Tinyblargon** [comment]
@julienym I've tested it with root@pam as well. Both `hastate = null`  and `hastate = ""` are valid settings.

These errors are normal and happen because HA has not been configured yet. Enabling HA happens at a later stage.
```
2022/06/03 12:01:18 [DEBUG][GetJsonRetryable] Sleeping for 1 seconds before asking url /cluster/ha/resources/111
2022/06/03 12:01:19 [DEBUG][GetJsonRetryable] Sleeping for 2 seconds before asking url /cluster/ha/resources/111
2022/06/03 12:01:21 [DEBUG][GetJsonRetryable] Sleeping for 3 seconds before asking url /cluster/ha/resources/111
2022/06/03 12:01:24 [DEBUG] VM 111(%!s(<nil>)) has no HA config
```


Looking at it now i think there might be some other setting in the VM config that couses this error:
```
400 Parameter verification failed.
``` 

Could you maybe post your terraform config?

**Comment by mleone87** [comment]
@julienym  post terraform code, it's an error there for sure

**Comment by julienym** [comment]
Thanks, I'll double check my code, the error msg in debug was misleading. I guess error code 400 from proxmox could get more details ?
