### ISSUE TITLE
Plugin Crash

### ISSUE THREAD

**Issue by pmatra** [Telmate/terraform-provider-proxmox#563]
Got this error after plugin crash. What does this mean?

`Stack trace from the terraform-provider-proxmox_v2.9.10 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 55 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xc3332a, {0xc0005aa510, 0x9})
        github.com/Telmate/proxmox-api-go@v0.0.0-20220427175411-e25c3463f0db/proxmox/client.go:197 +0x625
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
        github.com/Telmate/proxmox-api-go@v0.0.0-20220427175411-e25c3463f0db/proxmox/client.go:187
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000507100, {0xae93c0, 0xc000165bd0})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:795 +0x1385
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd1df00, {0xd1df00, 0xc0007a89f0}, 0xd, {0xae93c0, 0xc000165bd0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003dc700, {0xd1df00, 0xc0007a89f0}, 0xc0001411e0, 0xc000506f80, {0xae93c0, 0xc000165bd0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:837 +0xc29
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000305140, {0xd1de58, 0xc000502680}, 0xc0003143c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00036c3c0, {0xd1df00, 0xc0007a81e0}, 0xc0001c01c0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbe2c80, 0xc00036c3c0}, {0xd1df00, 0xc0007a81e0}, 0xc00043c1e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000326700, {0xd2b6c0, 0xc000102d00}, 0xc00057c000, 0xc0003fac30, 0x120cfa0, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1283 +0xcf2
google.golang.org/grpc.(*Server).handleStream(0xc000326700, {0xd2b6c0, 0xc000102d00}, 0xc00057c000, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.46.0/server.go:920 +0x294

Error: The terraform-provider-proxmox_v2.9.10 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
`

**Comment by pmatra** [comment]
I changed APIs, got a new API and it spit out this.

`goroutine 16 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xc3332a, {0xc0000345d0, 0x9})
        github.com/Telmate/proxmox-api-go@v0.0.0-20220427175411-e25c3463f0db/proxmox/client.go:197 +0x625
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
        github.com/Telmate/proxmox-api-go@v0.0.0-20220427175411-e25c3463f0db/proxmox/client.go:187
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000317e00, {0xae93c0, 0xc0005b2f00})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:795 +0x1385
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd1df00, {0xd1df00, 0xc0005b0990}, 0xd, {0xae93c0, 0xc0005b2f00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003dc700, {0xd1df00, 0xc0005b0990}, 0xc0000dd040, 0xc000317c80, {0xae93c0, 0xc0005b2f00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:837 +0xc29
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000315128, {0xd1de58, 0xc00080e3c0}, 0xc00031a410)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003723c0, {0xd1df00, 0xc0005b0000}, 0xc000242000)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbe2c80, 0xc0003723c0}, {0xd1df00, 0xc0005b0000}, 0xc00024c000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032c700, {0xd2b6c0, 0xc000001ba0}, 0xc0004990e0, 0xc0003facc0, 0x120cfa0, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1283 +0xcf2
google.golang.org/grpc.(*Server).handleStream(0xc00032c700, {0xd2b6c0, 0xc000001ba0}, 0xc0004990e0, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.46.0/server.go:920 +0x294

Error: The terraform-provider-proxmox_v2.9.10 plugin crashed!
`

**Comment by Tinyblargon** [comment]
Hi,

The reason of this crash is because Terraform tries to get the vmid using the name of the VM.  It expects a singular item. in this case it found multiple VMs or LXC containers with the same name. a quick workaround for this problem would be to give the VMs/LXC containers unique names.

**Comment by pmatra** [comment]
Trust me they have unique names

**Comment by pmatra** [comment]
There are no duplicates if that's what you mean

**Comment by pmatra** [comment]
Now Its this

goroutine 16 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xc3332a, {0xc0000345d0, 0x9})
        github.com/Telmate/proxmox-api-go@v0.0.0-20220427175411-e25c3463f0db/proxmox/client.go:197 +0x625
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
        github.com/Telmate/proxmox-api-go@v0.0.0-20220427175411-e25c3463f0db/proxmox/client.go:187
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000317e00, {0xae93c0, 0xc0005b2f00})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:795 +0x1385
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd1df00, {0xd1df00, 0xc0005b0990}, 0xd, {0xae93c0, 0xc0005b2f00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003dc700, {0xd1df00, 0xc0005b0990}, 0xc0000dd040, 0xc000317c80, {0xae93c0, 0xc0005b2f00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:837 +0xc29
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000315128, {0xd1de58, 0xc00080e3c0}, 0xc00031a410)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003723c0, {0xd1df00, 0xc0005b0000}, 0xc000242000)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbe2c80, 0xc0003723c0}, {0xd1df00, 0xc0005b0000}, 0xc00024c000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00032c700, {0xd2b6c0, 0xc000001ba0}, 0xc0004990e0, 0xc0003facc0, 0x120cfa0, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1283 +0xcf2
google.golang.org/grpc.(*Server).handleStream(0xc00032c700, {0xd2b6c0, 0xc000001ba0}, 0xc0004990e0, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.46.0/server.go:920 +0x294

Error: The terraform-provider-proxmox_v2.9.10 plugin crashed!

**Comment by mleone87** [comment]
I would go all in with the fact that you're using api keys and checked privilege separation, try with root@pam to be sure. We need a fix for that.

If not, post full terraform code please

**Comment by pmatra** [comment]
goroutine 100 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xc3332a, {0xc0003e24a0, 0x9})
        github.com/Telmate/proxmox-api-go@v0.0.0-20220427175411-e25c3463f0db/proxmox/client.go:197 +0x625
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
        github.com/Telmate/proxmox-api-go@v0.0.0-20220427175411-e25c3463f0db/proxmox/client.go:187
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0000cd200, {0xae93c0, 0xc000356b90})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:795 +0x1385
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd1df00, {0xd1df00, 0xc000910840}, 0xd, {0xae93c0, 0xc000356b90})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003e6700, {0xd1df00, 0xc000910840}, 0xc0004ae340, 0xc0000cd080, {0xae93c0, 0xc000356b90})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:837 +0xc29
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d170, {0xd1de58, 0xc0000f6380}, 0xc0000c62d0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000fe3c0, {0xd1df00, 0xc000910030}, 0xc0002c4000)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbe2c80, 0xc0000fe3c0}, {0xd1df00, 0xc000910030}, 0xc00048c060, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e0700, {0xd2b6c0, 0xc000482340}, 0xc000337680, 0xc000248b70, 0x120cfa0, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1283 +0xcf2
google.golang.org/grpc.(*Server).handleStream(0xc0000e0700, {0xd2b6c0, 0xc000482340}, 0xc000337680, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.46.0/server.go:920 +0x294

Error: The terraform-provider-proxmox_v2.9.10 plugin crashed!

**Comment by pmatra** [comment]
`terraform {
  required_providers {
    proxmox = {
      source = "telmate/proxmox"
      version = "2.9.10"
    }
  }
}

  provider "proxmox" {
# url is the hostname (FQDN if you have one) for the proxmox host you'd like to connect to to issue the commands. my proxmox host is 'prox-1u'. Add /api2/json at the end for the API
  pm_api_url = "http://10.1.10.193:8006/api2/json"
# api token id is in the form of: <username>@pam!<tokenId>
  pm_api_token_id = "terraform@pam!token"
# this is the full secret wrapped in quotes. don't worry, I've already deleted this from my proxmox cluster by the time you read this post
  pm_api_token_secret = "xxxxxxxxxxxxxxxxxx"
  # leave tls_insecure set to true unless you have your proxmox SSL certificate situation fully sorted out (if you do, you will know)
  pm_tls_insecure = true
}

# resource is formatted to be "[type]" "[entity_name]" so in this case

# we are looking to create a proxmox_vm_qemu entity named test_server

  resource "proxmox_vm_qemu" "test_server" {
  count = 1
 # just want 1 for now, set to 0 and apply to destroy VM
  name = "test-vm-${count.index + 1}"
 #count.index starts at 0, so + 1 means this VM will be named test-vm-1 in proxmox
# this now reaches out to the vars file. I could've also used this var above in the pm_api_url setting but wanted to spell it out up there. target_node is different than api_url. target_node is which node hosts the template and thus also which node will host the new VM. it can be different than the host you use to communicate with the API. the variable contains the contents "prox-1u"

  target_node = var.proxmox_host
  # another variable with contents "ubuntu-2004-cloudinit-template"
  clone = var.template_name
  # basic VM settings here. agent refers to guest agent
  agent = 1
  os_type = "cloud-init"
  cores = 2
  sockets = 1
  cpu = "host"
  memory = 2048
  scsihw = "virtio-scsi-pci"
  bootdisk = "scsi0"
  disk {
    slot = 0
    # set disk size here. leave it small for testing because expanding the disk takes time.
    size = "10G"
    type = "scsi"
    storage = "local-lvm"
    iothread = 1
  }
  
  # if you want two NICs, just copy this whole network section and duplicate it
  network {
    model = "virtio"
    bridge = "vmbr0"
  }
  # not sure exactly what this is for. presumably something about MAC addresses and ignore network changes during the life of the VM
  lifecycle {
    ignore_changes = [
      network,
    ]
  }
  
  # the ${count.index + 1} thing appends text to the end of the ip address
  # in this case, since we are only adding a single VM, the IP will
  # be 10.98.1.91 since count.index starts at 0. this is how you can create
  # multiple VMs and have an IP assigned to each (.91, .92, .93, etc.)
  ipconfig0 = "ip=10.1.10.20${count.index + 1}/24,gw=10.1.10.1"
  
  # sshkeys set using variables. the variable contains the text of the key.
  sshkeys = <<EOF
  ${var.ssh_key}
  EOF
}`

**Comment by pmatra** [comment]
terraform {
  required_providers {
    proxmox = {
      source = "telmate/proxmox"
      version = "2.9.10"
    }
  }
}

  provider "proxmox" {
# url is the hostname (FQDN if you have one) for the proxmox host you'd like to connect to to issue the commands. my proxmox host is 'prox-1u'. Add /api2/json at the end for the API
  pm_api_url = "http://10.1.10.193:8006/api2/json"
# api token id is in the form of: <username>@pam!<tokenId>
  pm_api_token_id = "terraform@pam!token"
# this is the full secret wrapped in quotes. don't worry, I've already deleted this from my proxmox cluster by the time you read this post
  pm_api_token_secret = "xxxxxxxxxxxxxxxxxx"
  # leave tls_insecure set to true unless you have your proxmox SSL certificate situation fully sorted out (if you do, you will know)
  pm_tls_insecure = true
}

# resource is formatted to be "[type]" "[entity_name]" so in this case

# we are looking to create a proxmox_vm_qemu entity named test_server

  resource "proxmox_vm_qemu" "test_server" {
  count = 1
 # just want 1 for now, set to 0 and apply to destroy VM
  name = "test-vm-${count.index + 1}"
 #count.index starts at 0, so + 1 means this VM will be named test-vm-1 in proxmox
# this now reaches out to the vars file. I could've also used this var above in the pm_api_url setting but wanted to spell it out up there. target_node is different than api_url. target_node is which node hosts the template and thus also which node will host the new VM. it can be different than the host you use to communicate with the API. the variable contains the contents "prox-1u"

  target_node = var.proxmox_host
  # another variable with contents "ubuntu-2004-cloudinit-template"
  clone = var.template_name
  # basic VM settings here. agent refers to guest agent
  agent = 1
  os_type = "cloud-init"
  cores = 2
  sockets = 1
  cpu = "host"
  memory = 2048
  scsihw = "virtio-scsi-pci"
  bootdisk = "scsi0"
  disk {
    slot = 0
    # set disk size here. leave it small for testing because expanding the disk takes time.
    size = "10G"
    type = "scsi"
    storage = "local-lvm"
    iothread = 1
  }
  
  # if you want two NICs, just copy this whole network section and duplicate it
  network {
    model = "virtio"
    bridge = "vmbr0"
  }
  # not sure exactly what this is for. presumably something about MAC addresses and ignore network changes during the life of the VM
  lifecycle {
    ignore_changes = [
      network,
    ]
  }
  
  # the ${count.index + 1} thing appends text to the end of the ip address
  # in this case, since we are only adding a single VM, the IP will
  # be 10.98.1.91 since count.index starts at 0. this is how you can create
  # multiple VMs and have an IP assigned to each (.91, .92, .93, etc.)
  ipconfig0 = "ip=10.1.10.20${count.index + 1}/24,gw=10.1.10.1"
  
  # sshkeys set using variables. the variable contains the text of the key.
  sshkeys = <<EOF
  ${var.ssh_key}
  EOF
}

**Comment by mleone87** [comment]
Pve api URL should be https, ignore_lifecycle it's not required.

**Comment by pmatra** [comment]
It doesn't work with https. Don't understand why since my SSLs are in place

**Comment by pmatra** [comment]
What does this mean now?

```
Stack trace from the terraform-provider-proxmox_v2.9.10 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 71 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xc3332a, {0xc0003aa450, 0x7})
        github.com/Telmate/proxmox-api-go@v0.0.0-20220427175411-e25c3463f0db/proxmox/client.go:197 +0x625
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
        github.com/Telmate/proxmox-api-go@v0.0.0-20220427175411-e25c3463f0db/proxmox/client.go:187
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000169480, {0xae93c0, 0xc000442a50})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:795 +0x1385
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd1df00, {0xd1df00, 0xc0005828a0}, 0xd, {0xae93c0, 0xc000442a50})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001ace00, {0xd1df00, 0xc0005828a0}, 0xc00057b450, 0xc000169300, {0xae93c0, 0xc000442a50})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:837 +0xc29
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003e64b0, {0xd1de58, 0xc00023cd00}, 0xc00020c230)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000217e00, {0xd1df00, 0xc000582090}, 0xc000150000)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbe2c80, 0xc000217e00}, {0xd1df00, 0xc000582090}, 0xc00057e000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ec8c0, {0xd2b6c0, 0xc000316680}, 0xc00028c360, 0xc0003f0f30, 0x120cfa0, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1283 +0xcf2
google.golang.org/grpc.(*Server).handleStream(0xc0002ec8c0, {0xd2b6c0, 0xc000316680}, 0xc00028c360, 0x0)
        google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.46.0/server.go:920 +0x294

Error: The terraform-provider-proxmox_v2.9.10 plugin crashed!

```

**Comment by UmanGarbag** [comment]
@pmatra  I think we have the same issue here... (https://github.com/Telmate/terraform-provider-proxmox/issues/552)

Does anyone have plan for fix this bug ?

**Comment by Tinyblargon** [comment]
@pmatra could you run terraform with debug enabled and send over all lines containing `[DEBUG][GetJsonRetryable]`?

To enable the debug log set this environment variable
```bash
export TF_LOG=DEBUG
```

**Comment by mleone87** [comment]
@Tinyblargon you're being fooled by the **GetVmRefsByName** function because it's the first to be called and to fail due to bad provider configuration(and bad error handling of course)
we have a lot of issues there with the same problem, main reasons are

1. wrong proxmox api url like @pmatra  
2. wrong user + token configuration like @UmanGarbag (and maybe @pmatra  too)

> It doesn't work with https. Don't understand why since my SSLs are in place

@pmatra proxmox has no http endpoint, the url must be https, posting the same error won't help you fixing the problem, you have to use a https endpoint **and** a correct configured api token


@UmanGarbag you dint post what I've asked
via ssh, on the proxmox node, post output of these commands
`pveum  user token list terraform-prov@pve`
`pveum  user token permission terraform-prov@pve **tokenname from previous command`
(@pmatra  this should help you too)

**Comment by UmanGarbag** [comment]
@mleone87 Here the output of the first command : 
![image](https://user-images.githubusercontent.com/57763989/172045553-7e5f82b2-eedc-4278-9285-c9df751174ab.png)

Second command :  
![image](https://user-images.githubusercontent.com/57763989/172045568-755b9bee-0f67-418d-b137-400df2fa5419.png)

Update :  

I retry creating a virtual machine by replace authentication metho (replace   pm_api_token_id   &
  pm_api_token_secret) by  pm_user and pm_password using the **terraform-prov@pve** user and it's works !

**Comment by mleone87** [comment]
@UmanGarbag nice! the other way is to **DO NOT USE** privilege separation, like in the first image!

**Comment by UmanGarbag** [comment]
@mleone87 I uncheck the privilege separation and the vm creation still working. Thanks for you help

**Comment by pmatra** [comment]
Priv Separation was my problem too. That solved it. Thanks!
