### ISSUE TITLE
Cannot set decimal number for Network Rate limit

### ISSUE THREAD

**Issue by TechDufus** [Telmate/terraform-provider-proxmox#569]
# Description
In the proxmox GUI, I am able to set a decimal value for the `Rate limit (MB/s)` value on the network device for a VM.

When setting this same decimal value from terraform, I get an error: `Error: Attribute must be a whole number, got 3.5`

# Expected Behavior
I would expect to keep my terraform variable a `number` type and be able to specify `3.5` as the Rate Limit.

```terraform
variable "rate" {
  type        = number
  default     = 3.5
}
```

I assume the issue lies in how this is defined, but I won't pretend to know that I know the fix.
https://github.com/Telmate/terraform-provider-proxmox/blob/ff0a5406753af31f96dfb686829b602e4815c2ef/proxmox/resource_vm_qemu.go#L267-L271

Here's a screenshot of my exact error:
![image](https://user-images.githubusercontent.com/46715299/175303562-1cee5ddd-66ea-4f59-a51b-ebec1a28328a.png)

**Comment by GRcwolf** [comment]
It might be able to fix this by simply changing
```go
 "rate": { 
 	Type:     schema.TypeInt, 
 	Optional: true, 
 	Computed: true, 
 }, 
```
to 

```go
 "rate": { 
 	Type:     schema.TypeFloat, 
 	Optional: true, 
 	Computed: true, 
 }, 
```

So changing the type from `TypeInt` to `TypeFloat`.

**Comment by TechDufus** [comment]
Ship it. LGTM 😎

**Comment by zukonake** [comment]
Same with LXC cpulimit

**Comment by omega1582** [comment]
Any update one this.  The type should match what can be set in the UI.  The rate limits I would like to set are decimals, but have been having to deal with the whole number to make this work.

**Comment by TechDufus** [comment]
> 

update
