### ISSUE TITLE
Plan shows disk deletion but `apply -refresh-only` shows no changes

### ISSUE THREAD

**Issue by ameyp** [Telmate/terraform-provider-proxmox#572]
I'm cloning from a template that already has a disk, so I'm not specifying a `storage` block. Here's my config:

```
terraform {
  required_providers {
    proxmox = {
      source = "Telmate/proxmox"
      version = "~> 2.9.10"
    }
  }
}

provider "proxmox" {
  pm_api_url = "https://192.168.1.42:8006/api2/json"
  pm_tls_insecure = true
}

resource "proxmox_vm_qemu" "k3s-master" {
  for_each = var.k3s_masters
  name = each.value.name
  desc = "k3s master node"
  target_node = each.value.target_node
  os_type = "cloud-init"
  full_clone = true
  memory = each.value.memory
  sockets = "1"
  cores = each.value.vcpu
  cpu = "host"
  scsihw = "virtio-scsi-pci"
  clone = var.k3s_source_template
  agent = 1

  network {
    model = "virtio"
    bridge = "vmbr0"
    tag = 80
  }

  # Cloud-init section
  ipconfig0 = "ip=${each.value.ip}/24,gw=${each.value.gw}"
  ssh_user = var.ssh_user
  sshkeys = var.ssh_pub_key
  cipassword = "password"
}
```

If I run `terraform apply -refresh-only`, I get this:

```
random_password.password: Refreshing state... [id=none]
proxmox_vm_qemu.k3s-worker["w1"]: Refreshing state... [id=proxmox/qemu/101]
proxmox_vm_qemu.k3s-master["m1"]: Refreshing state... [id=proxmox/qemu/109]
proxmox_vm_qemu.k3s-worker["w2"]: Refreshing state... [id=proxmox/qemu/111]
local_file.ansible_k3s_ip_inventory: Refreshing state... [id=d60215aa1427df3962eb8d3888b8090e38a80b7d]

No changes. Your infrastructure still matches the configuration.

Terraform has checked that the real remote objects still match the result of your most recent changes, and found no differences.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

k3s_vm_ids = [
  "109",
  "101",
  "111",
]
```

But running `terraform plan` shows that terraform wants to delete the (only) disk attached to each VM:

```
  # proxmox_vm_qemu.k3s-master["m1"] will be updated in-place
  ~ resource "proxmox_vm_qemu" "k3s-master" {
        id                        = "proxmox/qemu/109"
        name                      = "k3sm1"
        # (41 unchanged attributes hidden)

      - disk {
          - backup       = 0 -> null
          - cache        = "none" -> null
          - file         = "vm-109-disk-0" -> null
          - format       = "raw" -> null
          - iothread     = 0 -> null
          - mbps         = 0 -> null
          - mbps_rd      = 0 -> null
          - mbps_rd_max  = 0 -> null
          - mbps_wr      = 0 -> null
          - mbps_wr_max  = 0 -> null
          - replicate    = 0 -> null
          - size         = "25804M" -> null
          - slot         = 0 -> null
          - ssd          = 0 -> null
          - storage      = "vmdata" -> null
          - storage_type = "zfspool" -> null
          - type         = "scsi" -> null
          - volume       = "vmdata:vm-109-disk-0" -> null
        }

        # (1 unchanged block hidden)
    }
```

What gives? The converse also holds true btw: if I specify a storage block, `terraform plan` wants to delete the additional storage after first `apply`.

**Comment by mleone87** [comment]
the storage block should be always present if you clone a template

**Comment by ameyp** [comment]
Sure, but if I add a storage block, the resulting VM then has two disks instead of just one. It happens only if the storage type of the drive attached to the clone is different from the one specified for the VM: e.g. if the clone uses `scsi` and the VM uses `virtio`, or if they have different sizes. Only one drive is created if both specify the same storage size and the same storage type.

**Comment by mleone87** [comment]
At the moment threre is no logic in the provider to manage these scenarios. You should match template disk bus in your configuration and all should be ok

**Comment by ameyp** [comment]
Yep, that's what I ended up doing. Perhaps this should be mentioned as a note/caveat in the [cloud-init guide](https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/guides/cloud_init.md) to stop others from running into the same issue.

**Comment by alexdresko** [comment]
It's late and I'm so tired. Can someone post a sample configuration to show which parts need to match? This is where I'm stuck, but it's late and my brain stopped working. It would be super rad if someone could clarify the solution to this problem a little. I'm running Ansible, Packer to create a Ubuntu 22.04 template with autoinstall, and Terraform to clone the template. I can't believe I even understand what those words mean, but, right now, I can't match the tech to the solution recommended in this issue. 

Mega thanks.
