### ISSUE TITLE
Error: 500 update pools failed: VM is already a pool member

### ISSUE THREAD

**Issue by martin-carpenter** [Telmate/terraform-provider-proxmox#589]
For the proxmox_vm_qemu resource when assigning a VM to a pool with `pool = "testpool"` and using `terraform apply`, the VM is successfully created and the pool is successfully assigned.

When running `terraform apply` again with no change to the option `pool = "testpool"` the below error causes the apply to fail.

`terraform plan` also shows the pool as an addition when it is already in the pool.

apply output
`Error: 500 update pools failed: VM 30002 is already a pool member`

plan output
`+ pool = "testpool"`

**Comment by lsampaioweb** [comment]
Same happening here with me. 

Proxmox: Virtual Environment 7.2-7
Terraform: v1.2.7
Provider: registry.terraform.io/telmate/proxmox v2.9.11
OS: Ubuntu 22.04 - linux_amd64

**Comment by zenhighzer** [comment]
Proxmox: Virtual Environment 7.2-11
Terraform v1.2.9
Provider registry.terraform.io/telmate/proxmox v2.9.11
OS: Ubuntu 22.04.1 LTS 64bit

**Comment by comemaryvallee** [comment]
I also had the same problem, but turns out its only a problem of rights given to the terraform user in Proxmox.
#462
