### ISSUE TITLE
CloudInit IP Should override default_ipv4_address and ssh_host 

### ISSUE THREAD

**Issue by DoktorAerzt** [Telmate/terraform-provider-proxmox#593]
At the moment when you use cloudinit, the default_ipv4_address and ssh_host gets set on the temporary dhcp address witch gets overriden when the vm applys the cloudinit file. 

I think https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L1865 should be called after this https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L1892 block and the if https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L1869 needs to be removed or we need to search a other way. 

What are your opinions, should i make a pr?

**Comment by mleone87** [comment]
feel free to make a PR, my code is far from perfect!
