### ISSUE TITLE
Installation process no longer appears to work

### ISSUE THREAD

**Issue by m0pge** [Telmate/terraform-provider-proxmox#594]
The documentation for installation in the install guide https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/guides/installation.md appears to no longer work.

I installed, ie built the provider on a Debian 11 box using the supplied instructions on the 1st August. This appeared to work fine. I then wished to rebuild the provider to accomodate the latest Int/Bool bug fix in #582. Relevant dependancies including go1.19.linux-amd64 were installed first and verified as present and working correctly.

Using my bash history to look at the commands I previously had run which mirror the documentation I get the following. (all from within the /root directory, running as root)

`go install github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox

go: 'go install' requires a version when current directory is not in a module
        Try 'go install github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox@latest' to install the latest version
`

This has been built using the same version of Go as before, however this behaviour is unexpected.

Following the suggest to reference the latest version I get

`go install github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox@latest

go: downloading github.com/Telmate/terraform-provider-proxmox v0.0.0-20220808123439-c1de2ad98b55
go: github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox@latest: module github.com/Telmate/terraform-provider-proxmox@latest found (v0.0.0-20220808123439-c1de2ad98b55), but does not contain package github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox
`

Expected behaviour would be for this command to build the provider in the /root/terraform-provider-proxmox folder

**Comment by mleone87** [comment]
you should use makefile helpers to do that, try!
