### ISSUE TITLE
Add proxmox_user resource

### ISSUE THREAD

**Issue by danielemery** [Telmate/terraform-provider-proxmox#599]
I would like to be able to manage Proxmox users via the terraform provider.

The API documentation is [here](https://pve.proxmox.com/pve-docs/api-viewer/#/access/users) and the CRUD operations seem to be fairly standard.

I haven't worked on a provider before and haven't worked a lot with go but will try my hand at it.

Is there any reason the only providers existing so far are lxc containers and vms or has there just not been many requests for other resources as of yet?

**Comment by Tinyblargon** [comment]
Hi to help you start off, the CRUD operations for user management have already been implemented in the [library](https://github.com/Telmate/proxmox-api-go/blob/0129fa923095caeebe8aa18d2821c8196863f4ea/proxmox/config_user.go) this terraform provider uses to interact with the proxmox api. So you should be able to tap into those.

As for your question. There hasn't really been a lot of interest in people wanting to interact with more parts of proxmox. Currently I am working on implementing the CRUD operations for as many aspect of proxmox as possible in the underlying [library](https://github.com/Telmate/proxmox-api-go). Once they are eventually finalized I'll look into adding them to the terraform provider.
