### ISSUE TITLE
Error on apply

### ISSUE THREAD

**Issue by cc12258** [Telmate/terraform-provider-proxmox#6]
Could you help me debug this issue:

Error applying plan:

1 error(s) occurred:

* proxmox_vm_qemu.terraform-test1_stg: 1 error(s) occurred:

* proxmox_vm_qemu.terraform-test1_stg: Error executing command "echo $'auto eth0\\niface eth0 inet dhcp\\n' > /tmp/tf_eth0_payload": dial tcp [node_ip]:22115: getsockopt: connection refused

I'm not sure how I should be configuring the target node to allow the ssh forwarding to happen. I've played around with setting the user and ssh credentials to what appear to be allowed but am not having any luck with it.

**Comment by ggongaware** [comment]
During provisioning, the terraform-plugin makes a temporary net1. This net1 exists in proxmox as a private NAT network, with a port forward to SSH.

The attribute - 
ssh_forward_ip - should be the IP or hostname of the target node or bridge IP. This is where proxmox will create a port forward to your VM with via a user_net.

Make sure your proxmox target_node doesn't have a firewall or something that would block these port forwards to the temporary net1.

**Comment by cc12258** [comment]
What do I need to setup in terms of authentication for the SSH forward? Do I need to add a user on the target node (proxmox host) to allow the ssh forwarding?

**Comment by ggongaware** [comment]
Proxmox and qemu processes are responsible for forwarding ports from the physical proxmox node to the VM... the SSH user and keys will be inside the VM.
