### ISSUE TITLE
Proxmox API has new `import-from` parameter

### ISSUE THREAD

**Issue by jamesharr** [Telmate/terraform-provider-proxmox#605]
I'd like to add the `import-from` parameter for the disk block. I think this would be very useful.

Currently this terraform provider allows you to create a VM by using a clone, or specifying an ISO. One of the two are required. However there is a third option - most distributions create a qcow2 disk image that can be imported into a hypervizor. Disk images typically support cloud-init, perform system updates on first boot, and while the image is sized for a 10GB disk, it will grow to fit available size automatically.

Proxmox-VE now has the ability to import disks on VM create. An `import-from` parameter can be used on `diskN` to specify the disk image. This disk image is most commonly a qcow2 and the format is independent of the datastore the VM disk will be stored on. This is really nice, for example, if you're using an OS that has a pre-built "cloud" image that has cloud-init in it already.

References:
- [Proxmox VE API reference](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/config)
- [Proxmox VE Roadmap - 7.2](https://pve.proxmox.com/wiki/Roadmap#Proxmox_VE_7.2) - search for "importing disk-images"

Example pre-built images
   - [AlmaLinux 9](http://ord.mirror.rackspace.com/almalinux/9.0/cloud/x86_64/images/)
   - [Ubuntu 22.04](https://cloud-images.ubuntu.com/releases/22.04/release/) - look for the `-disk-kvm.img` variant
   - [Debian bullseye](https://cdimage.debian.org/images/cloud/bullseye/)

### Note on multi-disk VMs
Below are some notes on our specific use-case. I believe they may apply to others, however that is up for discussion.

In some cases, we actually need more than one disk. The first disk would be the system disk (the cloud-init image), typically sized 50-100GB, but we also are going to use a second or third disk that's 300-1000GB that's used for data storage. This is very similar to something like adding an extra EBS volume to an AWS EC2 instance.

I'm not sure I can imagine a use-case where we'd want to import multiple volumes, however I'm not sure I'd rule it out either. If this TF provider has an opinionated design (that's ok if it does), then a reasonable compromise might be specifying the `import-from` parameter at the QEMU block and then it's simply applied to the first disk.

The two trade-offs I see to specifying import-from at the QEMU block instead of at the Disk block:
- `import-from` only applying to the first disk is implicit behavior instead of explicit.
- It only allows a single disk import, which is probably practical.

### Note on disk paths
With the `import-from` option, disk paths are specified using a local filesystem path. For example: `/root/foo.qcow2`. In our cluster, we have a ceph-fs volume mounted cluster-wide for LXC images, ISOs, etc and even though it's not an official PVE feature, we intend to keep cloud-init images in there as well in a separate directory.

Example `import-from=/mnt/pve/ceph-fs/ci-images/AlmaLinux-9-GenericCloud-9.0-20220718.x86_64.qcow2`

Note that in the future, I suspect that the PVE developers may support the `datastore:image-file` convention as well. For example: `import-from=ceph-fs:ci-images/AlmaLinux-9-GenericCloud-9.0-20220718.x86_64.qcow2`

### Notes on alternatives
One of the shortcomings of VM templates is that either the target host needs to have access to the new VM's data-store. This means if `ci-template-ubuntu2204` is located on `pve1`, that you can't clone to a local disk on node `pve2`. You will either need to clone to a local disk on `pve1` or clone to a clustered storage (such as Ceph) on `pve2`

**Comment by jamesharr** [comment]
Added more drawbacks/limitations of the VM cloning method

**Comment by tenhishadow** [comment]
@jamesharr Hi, just an addition to "Example pre-built images:"

Would be nice to start just tiny latest-images with cloud-init already in

https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-arm64.json
https://cloud.debian.org/images/cloud/bullseye/latest/
they have raw, qcow2, tar.xz and the manifest

**Comment by jamesharr** [comment]
Due to some PVE API limitations and behaviors I've shifted efforts elsewhere.

I also very quickly hit the limitations of my understanding of this code base as well as the library it uses. Unfortunately, I won't have time to devote to learning it.

Proxmox API related issues I've run into.
- The API is non-idempotent when using import-from. The code needs to be smart enough to handle that.
- imported disks are not resized by Proxmox automatically, meaning there's another step in the process that needs to happen
- disk images are referenced by Unix filesystem path, which means only the root user can use this feature. Even generating API keys on the root account won't let you use import-from. I suspect that they'll fix this over time to allow people to reference images via volume path (my-vol:images/foo.qcow2)
- (not specifically related) there is no way to manage custom cloud-init config YAML/atteibutes via the API.

The terraform provider currently requires a template, or an iso option. That combined with the non-idempotent behavior means that this might be a much more involved change than I had originally anticipated, possibly involving structural changes.

Unfortunately, the likelihood of me completing this feature is pretty slim. Especially in the near future. I'm not sure if the proper etiquette is to close the PR if I no longer intend to work on it, or leave the work out there for someone else to pick up. Let me know what you think I should do.

**Comment by zimmertr** [comment]
This is needed for Talos. Talos has two distribution methods for Proxmox. As an ISO or as a `nocloud` raw image. Since Talos does not use Cloud Init, there is no way to provide it with an IP Address when starting from ISO. Therefore the only method to issue it a specific IP Address is via static IP Mapping on your DHCP server. Or by passing CLI parameters to GRUB. Otherwise you are intended to retrieve its IP Address from the console output or from what you see on your new DHCP server leases. 

If you instead start from the `nocloud` image, you can provide it Cloud Init data. However, since the provider cannot execute the commands necessary, this must be done via Ansible or a shell script. EG:

```bash
qm create 101 --name talos-template
qm importdisk 101 /var/lib/vz/template/iso/talos-amd64.raw FlashPool
qm set 101 --scsi0 FlashPool:vm-101-disk-0 
qm template 101
```

After which you can reference the template via Clone and provide Cloud Init information.
