### ISSUE TITLE
30 second sleep in vm clone

### ISSUE THREAD

**Issue by sei-aschlackman** [Telmate/terraform-provider-proxmox#608]
In resourceVmQemuCreate, there is a hard-coded 30 second sleep found [here](https://github.com/Telmate/terraform-provider-proxmox/blob/d8ccd4cc37920ef74001ab814bbcecd0838c097f/proxmox/resource_vm_qemu.go#L966). Is this sleep necessary for all cases? I'm able to clone and power on a vm much faster through the Proxmox web UI and it would be helpful to me to be able to avoid the long delay when deploying through the terraform provider.

Would it be possible to turn this sleep value into an argument of the resource, while leaving the default at the current 30 seconds?

**Comment by mleone87** [comment]
Non it's parametric, closing
