### ISSUE TITLE
Prevent auto-restart to VMs even when there is a change

### ISSUE THREAD

**Issue by halradaideh** [Telmate/terraform-provider-proxmox#617]
some changes force a restart to the vm randomly

like for example if you change the disk size, sometimes the provider triggers a restart and sometimes it put it as a pending change for the VM

we would like to request to allow or prevent proxmox from restarting the vms even if there is a change that requires a restart,

**Comment by clincha** [comment]
If you've got a couple of scenarios where it's running restarts vs putting in a pending change might be worth debugging it and putting in a PR? This project has a **lot** of open issues and this issue is too vague for anyone to really dig into apart from you.

> some changes force a restart to the vm randomly
Certainly won't be random.

**Comment by halradaideh** [comment]
I faced it again, and somehow I did not see your reply.

we face it randomly when we increase the non-root disk size, sometimes VMs won't restart and sometimes they do.
It would be nice to notify the user on the terraform plan that this change will cause a VM restart, and if there is a way to prevent such an action even if it is required.
