### ISSUE TITLE
Autogenerated MAC address with multiple interfaces duplicated

### ISSUE THREAD

**Issue by CCob** [Telmate/terraform-provider-proxmox#62]
When creating a proxmox qemu resource similar to snippet below
```
    # Setup the network interface
    network {
        id = 0
        model = "virtio"
        bridge = "vmbr1"
    }

    # Setup the network interface
    network {
        id = 1
        model = "virtio"
        bridge = "vmbr0"
    } 
```
The generated interface MAC address ends up being the same on both network interfaces which causes problems in the guest OS

**Comment by henryx** [comment]
Problem still remaining

**Comment by akadetonator** [comment]
Is there any fix of this? I am running into the same issue regardless of the version of Telmate version.

**Comment by Raumy** [comment]
Hello,

Same question, is there any fix or something to avoid this problem ? I've got two interfaces with same mac address so VM is unreacheable.....
