### ISSUE TITLE
500 QEMU guest agent is not running while sysprepping

### ISSUE THREAD

**Issue by ke1satsu** [Telmate/terraform-provider-proxmox#620]
Hi,

I'm trying to deploy a Windows Server 2022 via Cloudbase + Sysprep and it's working fine. However, during the last moments of deployment it appears that the Proxmox provider determines that QEMU Guest agent is not running and exits with an error. Mere seconds after that error the deployment finishes and I can see the QEMU guest agent report data back to the Proxmox gui, and I can ping it from command line.

Is there an option to manually set the timeout, so that the provider will give the machine a chance to finish provisioning before checking QEMU guest agent?

**Comment by ke1satsu** [comment]
I tried using the deprecated option guest_agent_ready_timeout = 300 but that did not help.

**Comment by ke1satsu** [comment]
I'm not sure if it matters, but there is a period when the guest agent is running, and the machine reboots. I guess that the provider attempts to detect QEMU guest agent before it comes back online again.

**Comment by mleone87** [comment]
next version will have customized waitings back
