### ISSUE TITLE
When using cicustom I receive a Not a directory error.

### ISSUE THREAD

**Issue by MarkLFT** [Telmate/terraform-provider-proxmox#622]
I have copied the example for creating VMs with cloud-init.  But when I run it I receive an error on the cicustom line that the yml file is not a directory.  

Error: can't open '/var/lib/vz/snippets/user_data_vm-0.yml' - Not a directory

**Comment by ryanjkemper** [comment]
What argument are you using in your cicustom flag?  I'm not getting an error when I run `terraform apply`, but I am running into an issue where is seems like the values in my cicustom file are not applying as I'm not able to log into the VM after it boots up.

My cicustom parameter is:

```
cicustom = "user=local:snippets/cloud_init_deb10_vm-01.yml"
```

With the file being at `/var/lib/vz/snippets/cloud_init_deb10_vm-01.yml`

**Comment by dbrw** [comment]
> I have copied the example for creating VMs with cloud-init. But when I run it I receive an error on the cicustom line that the yml file is not a directory.
> 
> Error: can't open '/var/lib/vz/snippets/user_data_vm-0.yml' - Not a directory

I think this is happening because the file provisioner failed to upload the cloud init file. I also facing same issue, did you found the solution?
