### ISSUE TITLE
error creating LXC container: 500 Only root can pass arbitrary filesystem paths

### ISSUE THREAD

**Issue by garethhowell** [Telmate/terraform-provider-proxmox#630]
I'm getting this when I apply the following
```
terraform {
    required_providers {
        proxmox = {
            source = "telmate/proxmox"
            version = "2.9.11"
        }
    }
}

provider "proxmox" {

    # url is the hostname (FQDN if you have one) for the proxmox host you'd like to connect to to issue the commands. my proxmox host is 'prox-1u'. Add /api2/json at the end for the API
    pm_api_url = var.pm_api_url

    # api token id is in the form of: <username>@pam!<tokenId>
    pm_api_token_id = var.pm_api_token_id

    pm_api_token_secret = var.pm_api_token_secret

    pm_tls_insecure = true
}

resource "proxmox_lxc" "mail" {

    hostname = var.hostname
    ostemplate = var.template_name
    target_node = var.proxmox_node
    unprivileged = false

    ssh_public_keys = var.ssh_key
    rootfs {
        storage = "local-lvm"
        size = "2G"
    }
    network {
        name = "eth0"
        bridge = "vmbr0"
        ip = var.ipv4_address
        gw = var.gw
    }
}
```
The full error is
```
Error: error creating LXC container: 500 Only root can pass arbitrary filesystem paths. at /usr/share/perl5/PVE/Storage.pm line 486., error status: {"data":null} (params: {"arch":"amd64","cmode":"tty","console":true,"cores":1,"cpulimit":0,"cpuunits":1024,"features":"","hostname":"wireguard","memory":512,"net0":"ip=172.29.12.2/24,name=eth0,bridge=vmbr0,gw=172.29.12.1","onboot":false,"ostemplate":"debian-10-turnkey-wireguard_16.2-1_amd64.tar.gz","protection":false,"rootfs":"local-lvm:2","ssh-public-keys":"ssh-rsa <redacted>","start":false,"storage":"local","swap":0,"tags":"","tty":2,"unprivileged":false,"vmid":102})
│
│   with proxmox_lxc.wireguard,
│   on main.tf line 23, in resource "proxmox_lxc" "wireguard":
│   23: resource "proxmox_lxc" "wireguard" {
```

**Comment by mleone87** [comment]
I guess the error is self explanatory: **Only root can pass arbitrary filesystem paths.**

**Comment by garethhowell** [comment]
> I guess the error is self explanatory: **Only root can pass arbitrary filesystem paths.**

The message may be clear, but the resolution path is not, to me anyway. The token I am using is owned by the root account on the proxmox server.

**Comment by rterbush** [comment]
Curious if @garethhowell found a solution to this. I came in here looking for a solution to the same error. I learned from your example that I don't need to pass "$var.variable" when using variables and in changing my config, the problem is solved.

I don't see a case in your example where you are using the other form, but thought it might be a hint here.

**Comment by garethhowell** [comment]
Sadly, not. The problem went on the "Someday/Maybe" pile.
Thanks for the hint though, I'll go back and take a look sometime.

**Comment by Vanav** [comment]
Related:
— [allow disk/VM import from uploaded/downloaded images/ovf via API](https://bugzilla.proxmox.com/show_bug.cgi?id=4141)
— [\[PATCH v3 storage 16/17\] check_volume_access: allow superusers to pass arbitrary fs paths](https://lists.proxmox.com/pipermail/pve-devel/2022-April/052496.html)

**Comment by masterjaguar** [comment]
Since I had the same problem, I would like to write my solution here. (Actually, everything is documented; you just have to read it properly. 😄 ) -> [lxc.md](https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/resources/lxc.md)

Incorrect:
```
template_name = "debian-13-standard_13.1-2_amd64.tar.zst"
``` 
Correct: 
```
template_name = "local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst"
```
