### ISSUE TITLE
HostPCI

### ISSUE THREAD

**Issue by mirceanton** [Telmate/terraform-provider-proxmox#632]
I looked through the code a bit and saw a section for `hostpci` devices, but no instructions in the docs on how to assign a PCI device to a VM.

Is it a supported feature? Can it be done? It is a bummer now that if I create the VM with terraform, then i have to assign the pci device with something like ansible or a script, which then makes terraform remove the device when applied again

**Comment by angelbarrera92** [comment]
Maybe because: https://github.com/Telmate/terraform-provider-proxmox/issues/638
