### ISSUE TITLE
Changes requiring reboot on VMs with HA configured fail to start VM after change.

### ISSUE THREAD

**Issue by doubletwist13** [Telmate/terraform-provider-proxmox#635]
When terraform changes require a VM to stop and start, if th VM is configured for HA (set to 'started') it seems that when the provider tells the VM to shut down, Proxmox is automatically changing the HA state to 'stopped' - but the provider doesn't recognize that, so when it tells the VM to start back up, proxmox ignores it (or fails to start) bceause Proxmox still sees the HA state set to 'stopped'. 

So the provider is returning success but the VM has been shut down and won't start up again unless the HA state is changed back to 'started' - whether that's done manually, or by applying terraform again if `hastate=started` is included in the tf file for that resource.

```
Proxmox: 7.2-11
Terraform v1.3.2 on linux_amd64
+ provider registry.terraform.io/telmate/proxmox v2.9.11
```

**Comment by Cylindric** [comment]
I still see this today :(

Proxmox: 7.3.6
Terraform v1.4.0
+ provider registry.terraform.io/telmate/proxmox v2.9.13

Means I have to run all `terraform apply` twice
