### ISSUE TITLE
LXC changing privilege of unprivileged Container results in 400

### ISSUE THREAD

**Issue by passivedragon** [Telmate/terraform-provider-proxmox#641]
Changing the desired state from `unprivileged = true` to `unpriviledged = false` of a proxmox_lxc resource results in an `Error 400, Parameter verification failed`.

I am aware that what I am doing may not be the smartest, but the error appears regardless of my stupidity.

I'm happy to provide information about my setup and code if this isn't directly reproducible.

For now, I'll resort to destroying and recreating.

**Comment by h0tw1r3** [comment]
Proxmox does not support this, even from their own web interface.

**Comment by passivedragon** [comment]
Proxmox does support destroying and creating containers, however. There are quite a few features Proxmox does not provide a visual frontend for, so that doesn't really say too much.
I can easily believe that going that way is impossible as it stands, but that doesn't really change things from my point of view. I'll try to explain a bit better:

What I would expect to happen is one of two cases:
1. Terraform quietly changes the container to unprivileged (if impossible, so be it)
2. Terraform marks the container as needing to be recreated, so it destroys and then creates a new one

Neither of these happens, what happens is that an error is returned upon trying to enforce the state, which to me suggests it is trying the first option, but fails.
