### ISSUE TITLE
Publish 2.9.12?

### ISSUE THREAD

**Issue by briandipalma** [Telmate/terraform-provider-proxmox#645]
I'm seeing this error when upgrading my providers:

```
Could not retrieve the list of available versions for provider telmate/proxmox: no available
releases match the given constraints 2.9.12
```

**Comment by habib-the-sweet** [comment]
Still relevant. Only 2.9.11 available

**Comment by tnyeanderson** [comment]
My whole infrastructure requires the change from #495 which is included in v2.9.12

Thanks for all the hard work on the release. Please publish v2.9.12 so we can enjoy it! :)

**Comment by HEP85** [comment]
Does anyone know what is blocking this?
We also need 2.9.12 because of #495 and are currently using developer override with the package downloaded from GitHub releases page as a workaround.

**Comment by codezninja** [comment]
@mleone87 is there a reason why this can't be published on the terraform registry yet?

**Comment by mleone87** [comment]
sorry for 2.9.12 mess, closing
