### ISSUE TITLE
DIsk size not working

### ISSUE THREAD

**Issue by sylflo** [Telmate/terraform-provider-proxmox#65]
I am trying to use the disk property. But I can not make it work, I am using it like this 

```
disk {
    id = 0
    type = "virtio"
    storage = "local"
    storage_type = "lvm"
    size = "50GB"
    backup = true
  }
```
The disk is created but has always the default value "32GB". Am I doing something wrong ?

**Comment by lequi** [comment]
@sylflo You can try with:

size = "50G"
instead of
size = "50GB"

(GB to G)
I have try changed and it work.
