### ISSUE TITLE
panic: interface {} is nil and suggestions

### ISSUE THREAD

**Issue by andrewg-xyz** [Telmate/terraform-provider-proxmox#652]
While attempting a cloud init clone, I would repeatedly get a panic error

`panic: interface conversion: interface {} is nil, not string`

Even digging into the stack trace didn't provide much insight into the error. I had to manually debug to really pinpoint the issue. Ultimately, I had missed the `network` configuration

i.e.
```
  network {
    model = "virtio"
    bridge = "vmbr0"
  }
```

I have three topics, for discussion:

1) Would you be open to adding some docs around debugging? Having now done it, it wasn't difficult, but a few pointers could accelerate others attempting to debug.

2) Have you considered validating configuration? Something that would have caught this error or thrown a warning ahead of time.

3) I'm not sure this is correct, but I could add some error handling around https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L1973 (the line that the panic actually occurred, as the 'net0' device didn't exist.

---
proxmox version: 7.2-3
proxmox provider version: 2.9.12

**Comment by Jadesgit** [comment]
I experienced the same issue following this guide https://austinsnerdythings.com/2021/09/01/how-to-deploy-vms-in-proxmox-with-terraform/. Here is the stack trace from Terraform's output:

╷
│ Error: Plugin did not respond
│ 
│   with proxmox_vm_qemu.docker-node[0],
│   on main.tf line 22, in resource "proxmox_vm_qemu" "docker-node":
│   22: resource "proxmox_vm_qemu" "docker-node" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain
│ more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.11 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 36 [running]:
github.com/Telmate/terraform-provider-proxmox/proxmox._resourceVmQemuRead(0xc000334c80, {0xb2bec0?, 0xc000540c30})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1559 +0x27dd
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuRead(...)
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1359
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc000334c80, {0xb2bec0?, 0xc000540c30})
        github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1040 +0x2412
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xd847f0?, {0xd847f0?, 0xc000303d10?}, 0xd?, {0xb2bec0?, 0xc000540c30?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000452700, {0xd847f0, 0xc000303d10}, 0xc000514340, 0xc000334a00, {0xb2bec0, 0xc000540c30})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00030b188, {0xd847f0?, 0xc000303bf0?}, 0xc000540e60)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000366320, {0xd847f0?, 0xc0000f61e0?}, 0xc0004f6070)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc29f00?, 0xc000366320}, {0xd847f0, 0xc0000f61e0}, 0xc0004f6000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000470000, {0xd87268, 0xc000475ba0}, 0xc0000fe000, 0xc000472ab0, 0x1212d00, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc000470000, {0xd87268, 0xc000475ba0}, 0xc0000fe000, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-proxmox_v2.9.11 plugin crashed!

Here is my terraform config:

`terraform {
  required_providers {
    proxmox = {
      source = "Telmate/proxmox"
      version = "2.9.11"
    }
  }
}

provider "proxmox" {
    pm_api_url = "https://192.168.0.6:8006/api2/json"
    pm_user = "terraform-prov@pve"
    pm_password = var.pm_password
    pm_log_enable = true
    pm_debug = true
    pm_tls_insecure = true
    pm_log_levels = {
      _default = "debug"
      _capturelog = ""
    }
}
resource "proxmox_vm_qemu" "docker-node" {
  count = 1
  name = "docker-node-${count.index + 1}"
  target_node = var.proxmox_host
  clone = var.template_name
  agent = 1
  os_type = "cloud-init"
  cores = 2
  sockets = 1
  cpu = "host"
  memory = 6144
  scsihw = "virtio-scsi-pci"

disk {
    slot = 0
    size = "10G"
    type = "scsi"
    storage = "Adata_disk"
    iothread = 1
  }

network {
    model = "virtio"
    bridge = "vmbr1"
  }

lifecycle {
  ignore_changes = [
    network,
  ]
}
ipconfig0 = "ip=192.168.0.2${count.index + 1}/24,gw=192.168.0.1"
sshkeys = <<EOF
${var.ssh_key}
EOF
  }
`

**Comment by mleone87** [comment]
please update version and stop using this tutorial as it contains wrong examples

```
lifecycle {
ignore_changes = [
network,
]
}
```

**Comment by Jadesgit** [comment]
I ran into the issue on this and the new version. I downgraded to try that since the release was so new. I believe the issue was that I had to grant my Proxmox user permissions on the storage pool. It works great now and I removed the wrong example from my configuration. Thanks for taking a look.
