### ISSUE TITLE
Set machine type

### ISSUE THREAD

**Issue by sebdanielsson** [Telmate/terraform-provider-proxmox#659]
Would be nice if we could specify the machine type for the VM. I'd like to use Q35 for example.

Also, thank you for this awesome provider!

**Comment by brutesque** [comment]
+1

**Comment by dronenb** [comment]
This was added in #684, but it looks like it isn't documented yet. Add this to your block:
```
resource "proxmox_vm_qemu" "examplename" {
  machine     = "q35"
  ... (shortened for brevity)
}
```
