### ISSUE TITLE
Setting macaddr result in Error

### ISSUE THREAD

**Issue by yannickgranger** [Telmate/terraform-provider-proxmox#660]
Version 2.9.11
Proxmox 7.3.4

Error: 400 Parameter verification failed.

when setting : 

```
 network {
    bridge = "vmbr0"
    model  = "virtio"
    macaddr = var.macaddr
 }

```

plan:

```
+ network {
    + bridge    = "vmbr0"
    + firewall  = false
    + link_down = false
    + macaddr   = "a3:e9:3d:22:fc:ae"
    + model     = "virtio"
    + queues    = (known after apply)
    + rate      = (known after apply)
    + tag       = -1
  }
```

**Comment by browningluke** [comment]
I ran into the same issue as you. It's because the macaddr you are using is multicast; Proxmox only accepts unicast addresses.

If you try use a unicast address instead, it should resolve the issue.
