### ISSUE TITLE
[Feature Request] Add ability to create EFI Disks

### ISSUE THREAD

**Issue by scottbot95** [Telmate/terraform-provider-proxmox#672]
### Problem
When creating new VMs it is currently only possible to create a VM with an EFI disk by using Full Clone on a template that already has an EFI disk. 

### Impact
In combination with #460, this means that it is not possible to create a fresh VM or a Linked Clone with UEFI bios. The inability to use Linked Clones in particular can lead to significant, additional, unnecessary disk space being used.

### Proposal
Add a new `efidisk` block with arguments to configure the at least the storage/volume name, format, efitype, and disk size.

**Comment by nickbroon** [comment]
Potential duplicated of #341 ?

**Comment by scottbot95** [comment]
Oh yeah totally. Not sure how I missed that before! Closing in favor of #341
