### ISSUE TITLE
[Feature Request] Ability to Provide `storage` field when Cloning

### ISSUE THREAD

**Issue by scottbot95** [Telmate/terraform-provider-proxmox#673]
### Problem
The `storage` field is marked as deprecated in `promox_vm_qemu` resources as it is normally replaced by the newer `disk.<name>.storage` argument.

### Impact
This flag is the only way to clone a VM into a different storage than the template. If it were to be removed in the future, it would be impossible create clones on a different storage than the original template/VM.

### Request
Either un-deprecate `storage` on `promox_vm_qemu` when `clone` is set, or provide an alternative mechanism to set that field during the clone request (ie an escape hatch to pass arbitrary values during the API call)

**Comment by scottbot95** [comment]
Hmm actually it looks like if just just provide the disks roughly matching what the cloned base image has, you can provide `storage` in each of them and Proxmox is smart enough to automagically link the disks up with the ones from the clone template. It may be slightly more convenient to only provide `storage` once at a top level to avoid unnecessary moving of disk images and duplication of code, however manually listing all disks is perfectly acceptable for my use-case so closing issue.

**Comment by mleone87** [comment]
hello @scottbot95, I'm not sure how a storage at top level would be better than having the possibility to granularity chose every storage for every cloned disk 🤔

In the first case you move(if needed) all disk to one storage, in the second you decide what do you want to do with every disk, or do nothing and it will default to source disk

**Comment by scottbot95** [comment]
Yeah I was mostly just misunderstanding the relationship between the terraform attributes and how that translates to the actual PVE API call. I think I was initially just using the granular disks wrong, and also didn't realize that this provider is smart enough to pass a reasonable value for `storage` in the initial `/nodes/{node}/qemu/{vmid}/clone` request which avoids unnecessary copying of the disk images.

A more meaningful request, perhaps, that might have come out of this would be to add an escape hatch to let you add additional arbitrary values to PVE request on clone/configure. But that is a whole can of worms, and may not be the direction this project wants to take.
