### ISSUE TITLE
Docs Typo 

### ISSUE THREAD

**Issue by 888iee** [Telmate/terraform-provider-proxmox#680]
I was reading and testing out the docs but I got an error. I also know that the error was just a typo.

# Error
`400 Parameter verification failed. privs: invalid format - invalid privilege 'VM.Migration'`
# Origin
[Getting Started docs](https://registry.terraform.io/providers/Telmate/proxmox/latest/docs)
The second command block replace `VM.Migration` with `VM.Migrate`

✌🏼

**Comment by mleone87** [comment]
fixed!
