### ISSUE TITLE
Fail to create qemu vm with 2.9.13

### ISSUE THREAD

**Issue by nicolas-brousse** [Telmate/terraform-provider-proxmox#681]
I've updated provider to use 2.9.13 version and test https://github.com/Telmate/terraform-provider-proxmox/pull/669. But since I've got and error.

I've tried to create a fresh small qemu config to check if something else have changed but didn't found.

With the following config:
```terraform
resource "proxmox_vm_qemu" "test" {
  target_node = "pve1"
  name        = "test"
  clone       = "ubuntu-22-04"

  scsihw = "virtio-scsi-pci"

  disk {
    type    = "scsi"
    size    = format("%dG", 5)
    storage = "ssd"
    discard = "on"
    # backup = false
  }
}
```

I've got the following error:
```
$ terraform plan

╷
│ Error: bool is required
│ 
│ 
╵
╷
│ Error: bool is required
│ 
│ 
╵
```

I've try to downgrade in `2.9.11` and this works (without backup part).

**Comment by tnyeanderson** [comment]
Are you getting the error with the `backup` line commented out? What about if you uncomment it?

**Comment by nicolas-brousse** [comment]
Here is my complete `main.tf` file

```terraform
terraform {
  required_providers {
    proxmox = {
      source  = "Telmate/proxmox"
      version = "2.9.13"
    }
  }
  required_version = ">= 1.1"
}

provider "proxmox" {
  pm_api_url = "https://${var.pm_host}:8006/api2/json"

  pm_user     = var.pm_user
  pm_password = var.pm_password
}

resource "proxmox_vm_qemu" "test" {
  target_node = "pve1"
  name        = "test"
  clone       = "ubuntu-22-04"

  scsihw = "virtio-scsi-pci"

  disk {
    type    = "scsi"
    size    = format("%dG", 5)
    storage = "ssd"
    discard = "on"
    backup  = false
  }
}
```

I tried with `backup = false`, `backup = true` and without `backup`. And I've got same error message.

```
% terraform -v
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/telmate/proxmox v2.9.13
```

**Comment by mleone87** [comment]
Edit state file and set utenti bool
________________________________
Da: Nicolas Brousse ***@***.***>
Inviato: Tuesday, February 7, 2023 7:55:10 PM
A: Telmate/terraform-provider-proxmox ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: Re: [Telmate/terraform-provider-proxmox] Fail to create qemu vm with 2.9.13 (Issue #681)


Here is my complete main.tf file

terraform {
  required_providers {
    proxmox = {
      source  = "Telmate/proxmox"
      version = "2.9.13"
    }
  }
  required_version = ">= 1.1"
}

provider "proxmox" {
  pm_api_url = "https://${var.pm_host}:8006/api2/json"

  pm_user     = var.pm_user
  pm_password = var.pm_password
}

resource "proxmox_vm_qemu" "test" {
  target_node = "pve1"
  name        = "test"
  clone       = "ubuntu-22-04"

  scsihw = "virtio-scsi-pci"

  disk {
    type    = "scsi"
    size    = format("%dG", 5)
    storage = "ssd"
    discard = "on"
    backup  = false
  }
}

I tried with backup = false, backup = true and without backup. And I've got same error message.

% terraform -v
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/telmate/proxmox v2.9.13

**Comment by nicolas-brousse** [comment]
@mleone87 good catch, that was the point! Thanks for your reactivity!

**Comment by Cylindric** [comment]
Having to manually edit state means this should have been a breaking change!

**Comment by dR3b** [comment]
> Edit state file and set it to bool

How can i do this?

**Comment by tnyeanderson** [comment]
Edit the `terraform.tfstate` file, look for `backup:` values, and replace them with the equivalent boolean value (`true` or `false`)

**Comment by dR3b** [comment]
@tnyeanderson Ahhh thanks!
