### ISSUE TITLE
Default value for `boot` order is deprecated

### ISSUE THREAD

**Issue by tnyeanderson** [Telmate/terraform-provider-proxmox#682]
Must have missed [this](https://github.com/Telmate/terraform-provider-proxmox/blob/6c43381a4c37abfa0df989cd6888dc6656a21888/docs/resources/vm_qemu.md?plain=1#L143) in my PR. The `cdn` default value is not accurate and is deprecated. Not sure what the "true" default value is.

**Comment by mleone87** [comment]
I like to follow proxmox defaults, so no boot default !

**Comment by tnyeanderson** [comment]
Seems that https://github.com/tnyeanderson/terraform-provider-proxmox/blob/772faeffe76123fe7b2048345b667b09d0d9af40/proxmox/resource_vm_qemu.go#L100 should be removed then, and the docs updated :)

**Comment by mleone87** [comment]
On upstream code i removed that and some other defaults!
