### ISSUE TITLE
MAC address value cannot be empty

### ISSUE THREAD

**Issue by NlVlN** [Telmate/terraform-provider-proxmox#691]
## Issue
After upgrading from `2.9.11` to `2.9.13` the following error appears when no MAC address has been provided:
```
╷
│ Error:  is not a valid unicast MAC address
│ 
│   with proxmox_vm_qemu.node1,
│   on main.tf line 27, in resource "proxmox_vm_qemu" "node1":
│   27:       macaddr =  var.node1_macaddr
│ 
╵
```
## Terraform configuration
`variables.tf`:
```
variable "node1_macaddr" {
  description = "MAC address of the node"
  default = ""
}
```

`main.tf`:
```
resource "proxmox_vm_qemu" "node1" {
    [truncated]
    name = var.node1_name
    memory = var.vm_memory
    cores = var.vm_cores

    network {
      model = "virtio"
      bridge = "vmbr0"
      macaddr =  var.node1_macaddr
    }
```

## Issue source
The issue has been introduced in 93e1cefd77c530adf23000f32740520f87700f14

## Solution
Fix has been proposed in #690 

## Reasoning
Not having to specify MAC addresses is useful when creating non-prod environments meant only for CI tests and destroyed afterwards.

**Comment by mleone87** [comment]
nice catch, thanks
