### ISSUE TITLE
"cloud-init parameters only supported on clones or updates"

### ISSUE THREAD

**Issue by Ramblurr** [Telmate/terraform-provider-proxmox#701]
Something has broken in a recent version of the provider.

This worked fine in version v2.9.10:

```terraform
resource "proxmox_vm_qemu" "node0" {
  name        = "${var.cluster_name}-controlplane-0"
  iso         = var.iso_image_location
  target_node = var.pve_nodes[0]
  full_clone  = false
  agent       = var.qemu_guest_agent
  vmid        = "200"
  qemu_os     = "l26" # Linux kernel type
  memory      = "8192"
  cores       = 4
  sockets     = 1
  numa        = true
  hotplug     = "network,disk,usb"
  network {
    model   = "virtio"
    bridge  = var.network_bridge
    macaddr = "1a:10:50:00:00:00"
  }
  disk {
    type    = "virtio"
    size    = var.boot_disk_size
    storage = var.boot_disk_storage_pool
  }
}

```

But now in version v2.9.13 it errors with:

```
╷
│ Error: cloud-init parameters only supported on clones or updates
│ 
│   with proxmox_vm_qemu.node0,
│   on homelab.tf line 1, in resource "proxmox_vm_qemu" "node0":
│    1: resource "proxmox_vm_qemu" "node0" {
│ 
```

**Comment by ccadruvi** [comment]
Running into the same issue, this would be fixed in https://github.com/Telmate/proxmox-api-go/pull/238. Requires a new release of the terraform-proxmox-provider once this PR is merged.

**Comment by SebTardif** [comment]
@ccadruvi It's quite a simple test case that fail. Some smoke test would be useful.

**Comment by VirtualDisk** [comment]
I'm experiencing the same. Hoping this can be merged soon.

**Comment by szinn** [comment]
Looks like it is merged - new release? I'm blocked on this as well.

**Comment by reesericci** [comment]
Yeah - this is blocking me, and I have a very simple configuration

**Comment by Ramblurr** [comment]
definitely not stale.. we're still stuck on `v2.9.10` because of this bug

**Comment by HaveFun83** [comment]
any news here?

**Comment by Ramblurr** [comment]
definitely not stale.. we're still stuck on v2.9.10 because of this bug
