### ISSUE TITLE
LXC: extra mount and device options 

### ISSUE THREAD

**Issue by Subbeh** [Telmate/terraform-provider-proxmox#714]
I have the following LXC config file defined for an existing container which I'm trying to convert into a Terraform job.

Is there any way to specify the `lxc.mount.entry` and `lxc.xgroup2.devices.allow` options accordingly?

```
arch: amd64
cores: 2
features: mount=nfs
hostname: test
memory: 4096
net0: name=eth0,bridge=vmbr0,firewall=1,hwaddr=xx:xx:xx:xx:xx:xx,ip=dhcp,ip6=dhcp,type=veth
onboot: 1
ostype: ubuntu
rootfs: ext:vm-101-disk-1,size=20G
swap: 0
lxc.cgroup2.devices.allow: c 226:0 rwm
lxc.cgroup2.devices.allow: c 226:128 rwm
lxc.cgroup2.devices.allow: c 29:0 rwm
lxc.mount.entry: /dev/fb0 dev/fb0 none bind,optional,create=file
lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
lxc.mount.entry: /dev/dri/renderD128 dev/renderD128 none bind,optional,create=file
```

**Comment by bennettsmj** [comment]
Hi @Subbeh, this isn't an answer to your question exactly, but the way I got around this is by using a Terraform `file` and `remote-exe` provisioner. The `file` provisioner copies over a shell script to the pve node, and the `remote-exec` provisioner executes the script which adds any extra config to the appropriate `/etc/pve/VMID.conf` if it's not already present. The script uses `pct` to ensure the container is not running, applies the "patches" to the config, then (re)starts the container.  It's a hack/workaround but happy to share the details with you if you want.

**Comment by h0tw1r3** [comment]
@Subbeh There is no way to manage lxc.* configuration from the Proxmox API.

**Comment by ghanjiboy** [comment]
@bennettsmj , would you be able to share the solution with me as well?  Thanks!
