### ISSUE TITLE
Sys.Console requirement since v2.9.14

### ISSUE THREAD

**Issue by gwenow** [Telmate/terraform-provider-proxmox#726]
Hello,

I have noticed since using v2.9.14 (previously v2.9.13), the provider requires additionally Sys.Console Sys.Modify VM.Migrate role permissions.

I have found the issues regarding the requirement for Sys.Modify. (https://github.com/Telmate/terraform-provider-proxmox/pull/688)

VM.Migrate also makes a lot of sense for migrations triggered by the provider.

But why has Sys.Conlose been added here aswell: https://github.com/Telmate/terraform-provider-proxmox/pull/683/files#diff-2a95ccf1660fc0de50bdda8fad339f4ac84e9a991e00f5ec569caa4a49b209b9

As far as i can see via the proxmox role permissions documentation (https://pve.proxmox.com/wiki/User_Management), grants a shell.

Could anybody point out to me what permissions are required for which functions of the provider?

And, is there a way to define those requirements? Or is my only option to customise and build the provider from source?
I am trying to follow the: _As little as possible, as much as necessary_ credo when it comes to permissions.

Thank you a lot. Gwen

**Comment by mleone87** [comment]
I can bet that I read that it was required for VM autostart, but it seems not.
