### ISSUE TITLE
Disks the same slot, but different controllers (i.E. ide0 for cloud-init and scsi0 for boot-drive) cause disk-deletions and nondeterministic behavior 

### ISSUE THREAD

**Issue by jsaalfeld** [Telmate/terraform-provider-proxmox#744]
Create new Virtual Machine in Proxmox (without Terraform!): 

```
 * General:
  * Any name, I choose "TF-RESET-TEST"
  * ID doesnt really matter, i choose 3500
 * OS:
  * "Do not use any media"
  * Guest OS Type: Other, Version: -
 * System:
  * Leave all to default
  * Check that SCSI Controller is set to VirtIO SCSI Single
 * Disks:
  * Bus: SCSI / 0
  * Storage: I choose our Proxmox Ceph
  * Size: 5G
  * No SSD Emulation
  * Backup enabled
  * No Discard
  * IO Thread enabled
 * CPU:
  * 1 Socket
  * 1 CPU
  * Leave architecture on "default"
 * Memory:
  * Ballooning active
  * Size: 2048
 * Network:
  * Choose your standard settings for testing machines
```

 * After creation, add an Cloud-Init Drive at `ide0` on the same target as the
   usual Disk
 * Add a second Disk at 5G to your machine at `scsi1` with the same settings as
   the other Disk

Go to your local console and create a new directory and add the `main.tf`:
```
terraform {
  required_providers {
    proxmox = {
      source  = "telmate/proxmox"
      version = "2.9.14"
    }
  }
}

provider "proxmox" {
  pm_api_url      = "https://#IP:8006/api2/json"
  pm_tls_insecure = true
  pm_user         = "#USER@pve"
  pm_password     = "#PASS"
}
```

And now - Import!:

```
terraform init

echo 'resource "proxmox_vm_qemu" "TF-RESET-TEST" {
  # (resource arguments)
}' > TF-RESET-TEST.tf

terraform import proxmox_vm_qemu.TF-RESET-TEST #NODE-NAME/qemu/3500

terraform state show -no-color proxmox_vm_qemu.TF-RESET-TEST > TF-RESET-TEST.tf

```

first of all, remove the entries, that are only information sources and can't be
set:
```
sed '/storage_type/d' -i TF-RESET-TEST.tf
sed '/unused_disk/d' -i TF-RESET-TEST.tf
sed '/reboot_required/d' -i TF-RESET-TEST.tf
sed '/id/d' -i TF-RESET-TEST.tf
terraform fmt
```

Check if all disks are there... They most likely wont...

This ist some other funny behavour already discussed in topics like
* https://github.com/Telmate/terraform-provider-proxmox/issues/700
* https://github.com/Telmate/terraform-provider-proxmox/issues/503
* https://github.com/Telmate/terraform-provider-proxmox/issues/132

It seems that only the disk in slot 0 is having a troubles being recognized.
The disk in slot1 has no issues whatsoever:
```
resource "proxmox_vm_qemu" "TF-RESET-TEST" {
  agent                  = 0
  balloon                = 0
  bios                   = "seabios"
  boot                   = "order=scsi0;ide2;net0"
  cores                  = 1
  cpu                    = "host"
  define_connection_info = false
  force_create           = false
  full_clone             = false
  hotplug                = "network,disk,usb"
  id                     = "#NODE/qemu/3500"
  kvm                    = true
  memory                 = 2048
  name                   = "TF-RESET-TEST"
  numa                   = false
  onboot                 = true
  oncreate               = false
  qemu_os                = "other"
  reboot_required        = false
  scsihw                 = "virtio-scsi-single"
  sockets                = 1
  tablet                 = true
  target_node            = #NODE
  unused_disk            = []
  vcpus                  = 0

  disk {
    backup             = true
    cache              = "none"
    file               = "vm-3500-disk-1"
    format             = "raw"
    iops               = 0
    iops_max           = 0
    iops_max_length    = 0
    iops_rd            = 0
    iops_rd_max        = 0
    iops_rd_max_length = 0
    iops_wr            = 0
    iops_wr_max        = 0
    iops_wr_max_length = 0
    iothread           = 1
    mbps               = 0
    mbps_rd            = 0
    mbps_rd_max        = 0
    mbps_wr            = 0
    mbps_wr_max        = 0
    replicate          = 0
    size               = "5G"
    slot               = 1
    ssd                = 0
    storage            = "medium0"
    type               = "scsi"
    volume             = "medium0:vm-3500-disk-1"
  }

  network {
    bridge    = "vmbr0"
    firewall  = true
    link_down = false
    macaddr   = "3E:27:EC:30:03:EF"
    model     = "virtio"
    mtu       = 0
    queues    = 0
    rate      = 0
    tag       = 1327
  }
}
```

When you see both drives, you encountered an nondeterministic behavior. You can
still reproduce the error, if you try to `terraform plan` and therefore
refresh your state. At some point you will encounter this error or the other way
round, you will reach a state, where both drives are recognized correctly. 

One of the issues lead me to think, that the proxmox provider is having issues
recognizing that slot number can be equal on different drive controllers.

Since cloud-init defaults to `ide0` and the first drive is on `scsi0` it may
think, that one slot has 2 drives and therefore can't manage the state for
that.

To validate the issue, delete the local state:

```
terraform state rm proxmox_vm_qemu.TF-RESET-TEST
```

Now detach the drive in `scsi0` and re-add it in as `scsi2`. Also, detach the
CD-Drive (since it is in `ide2`).

Now re-import and re-fix your Terraform File:

```
terraform import proxmox_vm_qemu.TF-RESET-TEST #NODE/qemu/3500
terraform state show -no-color proxmox_vm_qemu.TF-RESET-TEST > TF-RESET-TEST.tf
sed '/storage_type/d' -i TF-RESET-TEST.tf
sed '/unused_disk/d' -i TF-RESET-TEST.tf
sed '/reboot_required/d' -i TF-RESET-TEST.tf
sed '/id/d' -i TF-RESET-TEST.tf
terraform fmt
```

And you will see both devices recognized correctly and at any given point with every plan and refresh.

This nondeterministic behavior can cause serious issues with discs getting deleted by accident or resetting orders of discs and other troubles.

I have worked around this issue by deleting the disk-section of every machine and adding a `lifecycle_ignore`-section:
```
lifecycle {
  ignore_changes = [
    disk
  ]
}

```

This has been tested with Terraform 1.4.4 and Proxmox Version 7.3.

**Comment by jsaalfeld** [comment]
After some further testing, it turn out, that using 2 different controllers (i.E. `ide` and `scsi`) for disks will result in the same nondeterministic behavior, no matter if you import a machine or you create it via terraform itself. Changing something in the disks, after you created the initial machine will always result in failure.

If you change the controller of the drive from `scsi` to `ide` however, will fix all issues. So the initial statemant stays true, but there is a workaround by using only `ide` as disk controller.

**Comment by MMquant** [comment]
We are having similar issue when cloning from the template which has `ide0` cloud-init drive and `scsi0` HDD drive.
Cloning from this template **randomly** creates "good" and "bad" VMs. It seems like there is a race condition in the provider's parallel API calls.

**template image**
```
# qm config 8000
...
ide0: ceph:vm-8000-cloudinit,media=cdrom
...
scsi0: ceph:base-8000-disk-0,size=5324M
...
```

Good working VM (same slot number and different VM disk names)
```
# qm config 261
...
ide0: ceph:vm-261-cloudinit,media=cdrom,size=4M
...
scsi0: ceph:vm-261-disk-0,size=10G
... 
```

Bad not working VM (same slot number and same VM disk names). This VM won't boot.
```
# qm config 261
...
ide0: ceph:vm-261-cloudinit,media=cdrom,size=4M
...
scsi0: ceph:vm-261-cloudinit,size=10G
... 
```

The template image is build using Packer. There is no option to set up the `slot` for the cloud-init drive which could solve the problem.

Another solution would be to use the Terraform parameters

`proxmox_vm_qemu > disk > file`
or
`proxmox_vm_qemu > disk > slot`

neither of them works, they seem to be ignored.

Finally we found a temporary fix by deleting the `ide0` disk and created a new one on `ide2` by 
```
qm set 8000 --delete ide0
qm set 8000 --ide2 ceph:cloudinit
```
cloning from such template works flawlessly.

**Comment by jsaalfeld** [comment]
not stale

**Comment by Darkentik** [comment]
Do you have a workaround for this @jsaalfeld ?
I started these days with terraform and proxmox at home and came into this issue here too.
Thanks. :)

**Comment by jsaalfeld** [comment]
I ignore disks for now, unfortunately. Didn't find anything else

**Comment by jsaalfeld** [comment]
not stale
