### ISSUE TITLE
Cloudinit Images not consistently deleted

### ISSUE THREAD

**Issue by 0HFgX1pM8hUbvsCpAl3D** [Telmate/terraform-provider-proxmox#747]
When running terraform destroy, cloudinit images will occasionally fail to be deleted. Any subsequent runs will fail redeploying the resources due to the disks already existing.

**Comment by mleone87** [comment]
Can you provide evidences that is not related to you proxmox host configuration/issue?

**Comment by jsaalfeld** [comment]
I have the same issue, when constantly destroying and recreating a machine at the same id. There is no evidence in Proxmox itself, that it couldn't be deleted. Terraform will just state:

```
proxmox_vm_qemu.rke-machine-4: Destroying... [id=pve-ni-04/qemu/3056]
proxmox_vm_qemu.rke-machine-4: Destruction complete after 3s
proxmox_vm_qemu.rke-machine-4: Creating...
proxmox_vm_qemu.rke-machine-4: Still creating... [10s elapsed]
proxmox_vm_qemu.rke-machine-4: Still creating... [20s elapsed]
╷
│ Error: scsi0 - cloud-init drive is already attached at 'ide0'
│ 
│   with proxmox_vm_qemu.rke-machine-4,
│   on rke-machine-4.tf line 22, in resource "proxmox_vm_qemu" "rke-machine-4":
│   22: resource "proxmox_vm_qemu" "rke-machine-4" {
│ 
```

When you try to recreate your machine. It seems like the `cloud-init` disk isn't fully de-provisioned at the time of re-creation.

**Comment by michaelfranzl** [comment]
I'm seeing the same issue occasionally during `terraform destroy`: `Error: scsi0 - cloud-init drive is already attached at 'ide0'`

**Comment by bricecamus** [comment]
Same here and it's not consistent.
As mentioned by @Sm0rezDev at #704, by rolling back to 2.9.11 the issue is mitigated.

**Comment by jsaalfeld** [comment]
not stale

**Comment by kthezelais** [comment]
Same issue here

**Comment by jsaalfeld** [comment]
not stale
