### ISSUE TITLE
Add support for changing authorized_keys without destroynig LXC

### ISSUE THREAD

**Issue by leondrefoto** [Telmate/terraform-provider-proxmox#755]
It can be done by CLI with _pct enter_ command e.g.:
`"mkdir -p /root/.ssh && echo "<pub-key>" >> /root/.ssh/authorized_keys" | pct enter <vmid>`

so I suppose it  can be done by provider

source: https://forum.proxmox.com/threads/pct-exec-with-parameters.26053/

**Comment by GamerBene19** [comment]
AFAIK this provider currently only makes use of the Proxmox API (which does not support this operation).
While technically possible (see your command) I suspect it would need quite a lot of change to implement such a feature in this provider. Also your command only handles adding _one_ key and one would need a solution to delete key(s).
