### ISSUE TITLE
All disk properties config show `-> null` as needed change.

### ISSUE THREAD

**Issue by TechDufus** [Telmate/terraform-provider-proxmox#763]
Terraform `v1.4.6`
on `linux_amd64`
\+ provider registry.terraform.io/telmate/proxmox `v2.9.11`
Small context, I'm unable to upgrade to newer provider versions. (See https://github.com/Telmate/terraform-provider-proxmox/issues/762)

When running a plan, even after applying, all VMs show every property needs to change `-> null` even if I set every value in the `disk {}` block, which isn't necessary.

```hcl
- disk {
          - backup             = 0 -> null
          - cache              = "none" -> null
          - file               = "vm-112-cloudinit" -> null
          - format             = "raw" -> null
          - iops               = 0 -> null
          - iops_max           = 0 -> null
          - iops_max_length    = 0 -> null
          - iops_rd            = 0 -> null
          - iops_rd_max        = 0 -> null
          - iops_rd_max_length = 0 -> null
          - iops_wr            = 0 -> null
          - iops_wr_max        = 0 -> null
          - iops_wr_max_length = 0 -> null
          - iothread           = 0 -> null
          - mbps               = 0 -> null
          - mbps_rd            = 0 -> null
          - mbps_rd_max        = 0 -> null
          - mbps_wr            = 0 -> null
          - mbps_wr_max        = 0 -> null
          - media              = "cdrom" -> null
          - replicate          = 0 -> null
          - size               = "4M" -> null
          - slot               = 1 -> null
          - ssd                = 0 -> null
          - storage            = "lvm-thin-06" -> null
          - storage_type       = "lvmthin" -> null
          - type               = "scsi" -> null
          - volume             = "lvm-thin-06:vm-112-cloudinit" -> null
        }
```
Naturally, being flooded with all VMs needing changed for each plan gets in the way of seeing real pending state changes.

**Comment by TechDufus** [comment]
> Are you creating a VM via cloning? I'm hitting the same thing (and it seems like many others are too #655). I'm trying to figure out if this has to do with cloning a VM and not overriding the set parameters of the template?

Correct.. I set up a VM that I use as a template (I don't actually make it a template) and I clone from it and use cloud-init.

**Comment by chrisbenincasa** [comment]
Yea that is a exactly what I'm doing as well. My guess is that the provider isn't ignoring all of the settings in the clone case

**Comment by eremem** [comment]
Exactly the same problem when cloning from a template.
```
Terraform v1.5.3
on windows_amd64
+ provider registry.terraform.io/telmate/proxmox v2.9.14
```

**Comment by noahccoker** [comment]
Having the same issue too, hope this can get prioritized soon

**Comment by TechDufus** [comment]
Ping. any updates on this?

**Comment by luispabon** [comment]
The workaround for me is to specify a disk stanza that matches the disk set up on the templated VM, like so:

**VM template:**
![image](https://github.com/Telmate/terraform-provider-proxmox/assets/6388823/11fa23a0-cf11-495d-a33b-6267566138b8)

**Matching disk config:**
![image](https://github.com/Telmate/terraform-provider-proxmox/assets/6388823/29dbed00-0f94-40c2-84f7-206270243f47)
