### ISSUE TITLE
Implementation: New disk schema

### ISSUE THREAD

**Issue by Tinyblargon** [Telmate/terraform-provider-proxmox#778]
@mleone87 I have started on making the Terraform provider leverage the new disk implementation referenced https://github.com/Telmate/proxmox-api-go/pull/255

I was wonder if the new schema structure referenced in [vm_qemu.md](https://github.com/Tinyblargon/terraform-provider-proxmox/blob/Overhaul-Qemu-Disks/docs/resources/vm_qemu.md) and [pxe_example.tf](https://github.com/Tinyblargon/terraform-provider-proxmox/blob/Overhaul-Qemu-Disks/examples/pxe_example.tf) is satisfactory? As this would introduce a breaking change upgrade the provider to v3.0.0

**Comment by mleone87** [comment]
Hey @Tinyblargon !
why not something similar??
```
disks {
        scsi {
            scsi0 {
                   ...
                    size               = 32
                    storage            = "local-lvm"
            }
        }
        sata {
            sata0 {
                   ...
                    size               = 32
                    storage            = "local-lvm"
            }
        }
    }
```

Other strucures would fit also

**Comment by Tinyblargon** [comment]
@mleone87 

Changing `disk_0` to `ide0`, `sata0`, `scsi0`, `virtio0` is a good idea as it makes it more clear with which kind of disks the user is working with. Especially when `scsi` can have 30+ drives.

Personally, I'd prefer to keep the sub schema of `cdrom`, `disk`, `passthrough` as it defines more clearly which settings belong to which kind of disk. But i also see the argument for merging them as the vast majority of the users would only use the `disk` option. I'm gonna look into making the configuration constraints work with a structure where `cdrom`, `disk`, `passthrough` share the same schema.

**Comment by mleone87** [comment]
oh I see what you mean with disk/cdrmo/passthrough sub-objects, I forgot about that!

I would avoid too much recursion in disk object since it would be difficult to understand and, also, I would keep the cdrom/disk/passthrough objects separates as they are in proxmox API

**Comment by Tinyblargon** [comment]
@mleone87 am i interpenetrating your last comment correctly with this schema?

```
disks {
  ide {
    //<arguments omitted for brevity...>
  }
  sata {
    //<arguments omitted for brevity...>
  }
  scsi {
    //<arguments omitted for brevity...>
  }
  virtio {
    virtio0 {
      cdrom {
        iso = "local:iso/proxmox-ve_7.4-1.iso"
      }
    }
    virtio1 {
      disk {
        size    = 32
        storage = "local-lvm"
        //<arguments omitted for brevity...>
      }
    }
    virtio2 {
      passthrough {
        file = "/dev/disk/by-id/nvme-Seagate_FireCuda_SSD"
        //<arguments omitted for brevity...>
      }
    }
    //<arguments omitted for brevity...>
  }
}
```

**Comment by mleone87** [comment]
@Tinyblargon yeah!
