### ISSUE TITLE
New disk gets created on VM change --> VM becomes unbootable after reboot.

### ISSUE THREAD

**Issue by hagaram** [Telmate/terraform-provider-proxmox#779]
Hi,

I'm experiencig simillar bug to this one.
https://github.com/Telmate/terraform-provider-proxmox/issues/283

When I try to change IP address of cloud init, the new drive gets created and VM is set to boot from it --> of course it won't boot. So I have to manually change the disks in proxmox UI. 

```
Fri, 26 May 2023 09:04:27 +0200 DBG github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1583 > [READ] Disk Processed 'map[backup:0 discard:on file:vm-105-disk-0 format:raw iothread:1 size:20G slot:0 storage:data-nvme 
storage_type:zfspool type:virtio volume:data-nvme:vm-105-disk-0]' loggerName=resource_vm_read vmid=105
2023/05/26 09:04:27 [ERROR] setting state: disk.0.backup: '' expected type 'bool', got unconvertible type 'int', value: '0'.
```
In the state file, there is false/true set correctly. The zero value is IMHO retrieved from proxmox API. 0 can be seen also in Proxmox UI.

Why is the 0 treated explicitly as int? Is there any known workaround, or do I have to downgrade?

**Comment by ZacksHomeLab** [comment]
I've been creating my own terraform module for Proxmox and I have came across a few gotchas, especially with disks. I may be able to help. If you specifically set backup to false in your disk configuration, like so:

```
disks = [
    {
      backup   = false
      discard  = 1
      format   = "raw"
      iothread = 1
      size     = "20G"
      storage  = "data-nvme"
      type     = "virtio"
    }
  ]
```

Do you still get the same error?
