### ISSUE TITLE
Add support of creating disk from image file (`import-from` API)

### ISSUE THREAD

**Issue by Vanav** [Telmate/terraform-provider-proxmox#787]
Please, add support to create disk from image file. This will allow to create templates or VMs from official images (e.g. [Ubuntu image](https://cloud-images.ubuntu.com/releases/jammy/release/ubuntu-22.04-server-cloudimg-amd64.img)) or from user images.

It should be possible to create a VM from scratch in one run using only Terraform:
1) upload image file from URL to Proxmox (seems not possible with Proxmox API?)
2) create disk from uploaded image file (`import-from` API)
3) create VM or template and attach this disk to it

API: https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu - POST - `import-from`
Already used in tests: https://github.com/Telmate/proxmox-api-go/blob/41e6ffadedb1c3a41d5259bac250d12a5d104558/test/api/CloudInit/cloudinit_test.go#L26
Example: https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_cloud_init

P.S. Is there a way to mark a created VM as a template?

**Comment by Alexander-Komyakov** [comment]
Please, send me command curl: upload image file from URL to Proxmox

**Comment by Alexander-Komyakov** [comment]
thank you, please send an example of a curl request

чт, 10 окт. 2024 г. в 10:30, CRASH-Tech ***@***.***>:
