### ISSUE TITLE
Unable to create VMs in a proxmox cluster with local storage on other nodes than the first

### ISSUE THREAD

**Issue by deubert-it** [Telmate/terraform-provider-proxmox#788]
In this scenario there are three hosts kvm01, kvm02, kvm03.
Each of these hosts has local disks attached, so the storage is called kvm01-storage, kvm02-storage, kvm03-storage. The storage is not shared.

It does not seem to matter if connecting to the proxmox api for kvm01, kvm02 or kvm03, there is always the same result when trying to create a qemu vm with storage that is not attached to kvm01. So kvm01-storage works, everything else gives the following error:

```
Error: 500 storage 'kvm02-storage' is not available on node 'kvm01'

with proxmox_vm_qemu.qemu-test01,
on main.tf line 123, in resource "proxmox_vm_qemu" "qemu-test01":
123: resource "proxmox_vm_qemu" "qemu-test01" {
```

main.tf:
```
resource "proxmox_vm_qemu" "qemu-test01" {
  name        = "qemu-test01"
  target_node = "kvm02"
  clone       = "debian-11-cloudinit-template"

  qemu_os     = "other"

  vmid        = 1120
  memory      = 4096
  sockets     = 2
  cores       = 2
  cpu         = "kvm64"

  agent       = 1

  disk {
    type      = "scsi"
    storage   = "kvm02-storage"
    size      = "32G"
  }

  network {
    model     = "e1000"
    firewall  = false
    bridge    = "vmbr1"
  }

  ssh_user        = "debian"
  ssh_private_key = <<EOF
-----BEGIN OPENSSH PRIVATE KEY-----
...
-----END OPENSSH PRIVATE KEY-----
EOF

  os_type   = "cloud-init"
  ipconfig0 = "ip=10.0.0.120/24,gw=10.0.0.1"

  sshkeys = <<EOF
...
EOF
}
```

The same tf configuration will work with kvm01/kvm01-storage. Setting the proxmox_url to either kvm01/kvm02/kvm03 makes no difference.

**Comment by ralphte** [comment]
I have the exact same problem.

**Comment by david-guenault** [comment]
i did not notive this kind of thing. but when i read the error 

```
Error: 500 storage 'kvm02-storage' is not available on node 'kvm01'
```
it is prety obvious that kvm01 will not find kvm02-storage since it is on ..... kvm02 node. 

What i do is i name the local storage the same on each node (if i want to use local storage). and the template must be available on the node creating the vms (so in your case each node that will clone a template). This is a known (and obvious) limitation of using local-storage.

**Comment by david-guenault** [comment]
hum may be i'm saying shit. If your storage is a shared storage (nfs for example) you should be able to clone to another node without any issue. So question is do you use local-storage or shared-storage ?
