### ISSUE TITLE
terraform apply exits with error state when rebooting vm

### ISSUE THREAD

**Issue by RobertSkawinski** [Telmate/terraform-provider-proxmox#796]
Hi,

when setting up a new VM with Terraform in Proxmox, I need to reboot the VM at the end to receive valid guest agent values.
To achieve that, I use reboot at the end of the remote-exec commands, but this leads to an error, for example:

```
│ Error: remote-exec provisioner error
│ 
│   with proxmox_vm_qemu.srv-k8s-nodes["srv-k8s-03"],
│   on vm-kubernetes.tf line 81, in resource "proxmox_vm_qemu" "srv-k8s-nodes":
│   81:     provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_1347498485.sh": wait: remote command exited without exit status or exit signal
```

Is this an issue in remote-exec or should I use a different way to reboot the vm at the end.

**Comment by david-guenault** [comment]
hey there ! which guest os do you use ? for ubuntu 2x.xx it is not mandatory to reboot the vm.

**Comment by RobertSkawinski** [comment]
Hi, sorry for the late reply.
I'm using Ubuntu 22.04 and the guest tools are not starting right after the installation without a reboot
