### ISSUE TITLE
Unable to clone from template

### ISSUE THREAD

**Issue by scholdan** [Telmate/terraform-provider-proxmox#799]
From v2.9.11 to v2.9.14, something has changed with disks.
I have a template that looks like this:

![image](https://github.com/Telmate/terraform-provider-proxmox/assets/23090427/3cc9e009-3eb3-448f-87b8-f6dbd6f64b05)

If I clone that machine with v2.9.14, then I encounter two issues:
First, I receive an error saying that "ide0" already exists. I can simply remove the cloud-init drive from my template to solve this issue.
However, it also creates a new disk for the OS and marks the 10GB disk of the image as unused. In v2.9.11, it simply resized the existing disk.

**Comment by scholdan** [comment]
Here's the corrected version:

The issue with the OS disk seems to have disappeared. I believe the problem lies with the cloud-init, as I just ran three builds:

1. Build failed because the VM was not being provisioned due to a missing cloud-init drive.
2. Build was successful after I added the cloud-init drive back to the template.
3. Build failed, even though the code used was identical to the second build, see below

```
╷
│ Error: scsi0 - cloud-init drive is already attached at 'ide0'
│ 
│   with proxmox_vm_qemu.vm,
│   on vm.tf line 1, in resource "proxmox_vm_qemu" "vm":
│    1: resource "proxmox_vm_qemu" "vm" {
│ 
╵
```

**Comment by scholdan** [comment]
It appears that there is an issue where the cloud-init disk is being cloned to a SCSI device. Here are the corrected descriptions for the two updates:

Update for VM 1012:

BIOS: seabios
CI Password: [hidden]
CI User: deploy
Cores: 4
CPU: EPYC
Hotplug: network, disk, USB
IP Config 0: IP=10.10.18.32/23, Gateway=10.10.18.1
KVM: 1
Memory: 8192
Name: proxmox-linux
Nameservers: 10.10.8.10, 10.10.8.11
Network 0: Virtio=A2:82:15:34:28:AD, Bridge=vmbr0, Tag=18
NUMA: 1
On Boot: 0
**SCSI 0: proxmox-rbd:vm-1012-disk-0, Size=72G, IO Thread=1**
SCSI HW: virtio-scsi-single
Sockets: 2
SSH Keys: ssh-ed25519something
Tablet: 1
Task: OK
Update for VM 1012:

BIOS: seabios
CI Password: [hidden]
CI User: deploy
Cores: 4
CPU: EPYC
Hotplug: network, disk, USB
IP Config 0: IP=10.10.18.33/23, Gateway=10.10.18.1
KVM: 1
Memory: 8192
Name: proxmox-linux
Nameservers: 10.10.8.10, 10.10.8.11
Network 0: Virtio=2E:33:50:51:A4:B4, Bridge=vmbr0, Tag=18
NUMA: 1
On Boot: 0
**SCSI 0: proxmox-rbd:vm-1012-cloudinit, Size=72G, IO Thread=1**
SCSI HW: virtio-scsi-single
Sockets: 2
SSH Keys: ssh-ed25519something
Tablet: 1
Task: ERROR - SCSI0: Cloud-init drive is already attached at 'ide0'

**Comment by romantomjak** [comment]
Just ran into the same issue. Are you also seeing that it wants to recreate the VM because it did not clone the VM description from the template?

**Comment by oliverjkb** [comment]
Yup, I can reproduce this behaviour. 
With 
```
terraform 1.4.6
Proxmox VE 7.3.3
proxmox-provider 2.9.14
```
when cloning from a vm image and having defined a disk of type `virtio` or even `scsi`  it will fail with error message 
`TASK ERROR: virtio0 - cloud-init drive is already attached at 'ide0'`  or  
`TASK ERROR: scsi0 - cloud-init drive is already attached at 'ide0'`
depending on the disk definition.

**Comment by XDjackieXD** [comment]
I have the same issue with the cloud init drive where it tries to reattach the cloudinit disk to virtio0.
I'm running proxmox-provider 2.9.14 and proxomox ve 8.0.4.
