### ISSUE TITLE
unexpected EOF

### ISSUE THREAD

**Issue by cc12258** [Telmate/terraform-provider-proxmox#8]
I was getting this error repeatedly but it would randomly work:

```
Error applying plan:

2017/11/08 10:51:31 [DEBUG] plugin: waiting for all plugin processes to complete...
2017-11-08T10:51:31.784-0700 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
1 error(s) occurred:

* proxmox_vm_qemu.test01: 1 error(s) occurred:

* proxmox_vm_qemu.test01: unexpected EOF
```

Further up in the debug log I noticed this error:

```
HTTP/1.1 500 can't clone to non-shared storage 'local'
```

Then realized it must be randomly picking the template from one of the hosts and then trying to do a full clone to the target host. I was using the same template name across all the proxmox hosts and this caused the issue. I updated the template name to append the target host name. In case anyone else hits this, maybe the provisioner can be updated so that it finds the ID of the template to clone from on the target host in a clustered environment.

**Comment by ggongaware** [comment]
It could prioritize the target_host then go looking across the cluster.

**Comment by kneufeld** [comment]
I wish I'd found this comment earlier, the `target_node` _must_ be the same as the node of where your template lives.

**Comment by parithosh** [comment]
Can confirm, had the same issue today. I had 2 templates on 2 nodes with the same name. Even though I set `target_node`, it still complained about non-shared storage `local`. I just switched the two templates to have names reflecting the node and it worked without an issue.

**Comment by DreamyProtect** [comment]
Hi

I juste had the issue trying toset up terraform on proxmox in my company, is there any way to prioritize chosing the template on the node if present, directly into the provider instead of having to name the templates differently ? I'm willing to contribute and create a PR if that's the case.

**Comment by DreamyProtect** [comment]
At first glance, the issue appear to be [here](https://github.com/Telmate/proxmox-api-go/blob/fea68269e6b015493b0f454dd967c8a6f2651bec/proxmox/client.go#L174) (in the proxmox api client). The returned VM ref appear to be the ref of the first occurence of the list. We could pass the node we want to clone the VM on as argument and return the VMref of the Template on the node if found, or return the first occurence otherwise.
