### ISSUE TITLE
Hashicorp Official Provider

### ISSUE THREAD

**Issue by sticky-note** [Telmate/terraform-provider-proxmox#80]
Any plan to become a proxmox technology partner ?
https://www.proxmox.com/en/partners/technology-partner
And then become an official provider ?
Docs can be found here: https://www.proxmox.com/en/partners/technology-partner
It can be worth it to become official, as the provider will be well coded/documented/maintained and reviewed by Hashicorp themself.
What is more, Hashicorp can accompany to meet their standard, which means more eyes on the codebase.
The initial plan can be doing a `todos` list and ameliorate it over time when we can get more informations

**Comment by AcidCrash1337** [comment]
Comments on issue #227 mentions that it is available in the registry.  Does that mean this ticket or #29 can be closed?

**Comment by AcidCrash1337** [comment]
Comments on issue #227 mentions that it is available in the registry.  Does that mean this ticket or #29 can be closed?
