### ISSUE TITLE
terraform destroy fails on stopped lxc container

### ISSUE THREAD

**Issue by luciusf** [Telmate/terraform-provider-proxmox#801]
**Actual behaviour**

When running `terraform destroy` on newly created lxc container which are *not* running, it fails
When the lxc container is running, `terraform destroy` shuts it down, and destroys the components

    myuser@mynode tf-folder % terraform destroy
    proxmox_lxc.basic: Refreshing state... [id=pve/lxc/101]
    
    Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
    following symbols:
      - destroy
    
    Terraform will perform the following actions:
    
      # proxmox_lxc.basic will be destroyed
      - resource "proxmox_lxc" "basic" {

    (... shortened ...)

    proxmox_lxc.basic: Destroying... [id=pve/lxc/101]
    ╷
    │ Error: 500 CT 101 not running
    │ 
    │ 
    ╵

**Expected behaviour**

The terraform provider should remove the resource, also when it is not running. 

**Steps to reproduce**

Deploy the following with `terraform apply`, and after the successful provisioning, run `terraform destroy`

    resource "proxmox_lxc" "basic" {
      target_node = "pve"
      hostname    = "tf-destroy-test"
      # ostemplate   = "local:vztmpl/alpine-3.18-default_20230607_amd64.tar.xz"
      # ostemplate   = "local:vztmpl/debian-11-standard_11.7-1_amd64.tar.zst"
      ostemplate   = "local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
      password     = "ultrasafe-password"
      unprivileged = true
    
      rootfs {
        storage = "local-zfs"
        size    = "8G"
      }
    
      network {
        name   = "eth0"
        bridge = "vmbr0"
        ip     = "dhcp"
      }
    }

My used `provider.tf`

    terraform {
      required_providers {
        proxmox = {
          source  = "telmate/proxmox"
          version = "2.9.14"
        }
      }
    }

**Comment by mlazzarotto** [comment]
Same here. Using provider version 2.9.14 and Proxmox version 8.0.3.
