### ISSUE TITLE
[Doc] How to define status of vm?

### ISSUE THREAD

**Issue by hasechris** [Telmate/terraform-provider-proxmox#817]
Hi,

i am in the first 4 hours of testing with terraform and this module. Sadly i cant find the parameter, which defines the status the vm should be (started, stopped)? I found hastate, but i have a single proxmox node which does not have HA.

Greetings
hasechris

**Comment by KlutzyBubbles** [comment]
To my knowledge there is start stop status for newly created vms or containers but doesnt have any effect on existing resources.

for `proxmox_qemu_vm` the option would be `oncreate` as seen [here](https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/vm_qemu#:~:text=and%20shutdown%20behaviour-,oncreate,-bool)
for `proxmox_lxc` the option would be `start` as seen [here](https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/lxc#start)
