### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bartholdbos** [Telmate/terraform-provider-proxmox#821]
@ggongaware @mleone87 Would it be possible to do a new release for this repository. I would like to use a new feature for cloud-init disks which has been merged but not yet released. This is about https://github.com/Telmate/terraform-provider-proxmox/pull/748

**Comment by M0NsTeRRR** [comment]
Linked to #808

**Comment by glitchcrab** [comment]
Telmate folks seem to have been very quiet lately, it's a little concerning.

**Comment by gbrackley** [comment]
Is there somewhere else we can request a new release? Raising an issue here doesn't seem to be working. There are some patches to v2.9.14 that fix crashes in my Terraform scripts.
