### ISSUE TITLE
Add CPU affinity

### ISSUE THREAD

**Issue by Laurent977** [Telmate/terraform-provider-proxmox#833]
I would like to know if it's possible to add CPU affinity in the top level block like: 
`cpu_affinity = 96-111,114-127,224-239,242-255`

thanks in advance,

**Comment by Laurent977** [comment]
Do we have any information for this features in the "roadmap" ?

**Comment by sre42** [comment]
Any plans of adding cpu affinity in?

**Comment by Tinyblargon** [comment]
@sre42 I'll add this to the roadmap.
