### ISSUE TITLE
PVE 8.0.4 Permissions | PVESDNUser role

### ISSUE THREAD

**Issue by easmithdev** [Telmate/terraform-provider-proxmox#838]
Terraform Version: 1.5.6
Telmate/Proxmox Version: 2.9.14

Hello all. I recently updated my PVE from 7.4.X to 8.0.4. It appears that PVE 8.0.4 now creates a "SDN localnetwork" on every node regardless as to whether you use the SDN feature or not. I noticed that when trying to create new resources using telmate/proxmox 2.9.14 with PVE 8.0.4, terraform will not throw an error in regard to permissions, but will instead give the appearance that it's creating the resource when in fact  nothing is happening. **_The issue is that the PVE user/token that terraform is using to access the PVE API needs the "PVESDNUser" role associated to its permissions when working with PVE version 8.0.4_**. Perhaps a check for this permission can be added to the next release of the telmate/proxmox provider. 

**Workaround:** When using PVE 8.0.4 with telmate/proxmox 2.9.14, and the resource appears to be continually looping at "still creating" with no apparent change to the PVE environment, check to see if the "PVESDNUser" role is associated to the PVE user/token that is being used by terraform. If not, then add it. That should resolve the problem.

**Comment by glitchcrab** [comment]
There is already a PR open for this https://github.com/Telmate/terraform-provider-proxmox/pull/809

No idea when the telmate crew will actually merge it though, they seem to have gone very quiet.
