### ISSUE TITLE
Error re Size Value for Physical Mountpoints

### ISSUE THREAD

**Issue by daneski13** [Telmate/terraform-provider-proxmox#844]
This may be an edge case with storages/partitions with an odd number of bytes available. The error:

```
Error: mountpoint.1.size: '' expected type 'string', got unconvertible type 'int', value: '1407374883553'
```

## Steps to Reproduce

Specify a physical volume/storage/mp for a container. In my case, this is an ext4 formatted partition that is available for my file server container.

```
  mountpoint {
    key     = "1"
    slot    = 1
    storage = "/mnt/pve/rust"
    volume  = "/mnt/pve/rust"
    mp      = "/mnt/rust"
    size    = "1.28T"
  }
```

When this mountpoint does not yet exist there is not any issue. However, the size value here will be ignored as the real mountpoint will use the actual size available to the volume. This ends up being represented as an integer for the byte size of the volume in Proxmox. Attempting to re-run `terraform apply` in an attempt to update any changes I want to my resources will error.

**Comment by zinefer** [comment]
It's been a while but this might be the same issue: https://github.com/Telmate/terraform-provider-proxmox/issues/277

**Comment by daneski13** [comment]
Agreed, seems the root of the problem is how bind mounts are currently handled. As it stands a size value is unnecessarily required. I assume Proxmox overwrites whatever is specified for size upon creation which becomes a conflict when the provider pulls the current state from the server.
