### ISSUE TITLE
Alternative way of setting `sshkeys` on a `proxmox_vm_qemu` resource

### ISSUE THREAD

**Issue by aleprovencio** [Telmate/terraform-provider-proxmox#846]
Hi!

While using the `proxmox_lxc` resource I'm able to set ssh keys by just providing a file path, like:

```
ssh_public_keys = file("~/.ssh/some-key")
```

However, I'm not able to to use the `sshkeys` variable from a `proxmox_vm_qemu` in the same manner, which fails with `500 SSH public key validation error`

Is hard coding the key the only way or maybe there's an alternative?

**Comment by dronenb** [comment]
@aleprovencio I am not having this issue. I was able to do exactly what you are trying to do. [Relevant snippet](https://github.com/dronenb/HomeLab/blob/23a18d3e289c822a97855c7c64aa136d71d5dddd/kubernetes/cluster-bootstrap/k3s/terraform/proxmox_vm/main.tf#L26)

I was also able to set this via keys from GitHub: [Snippet](https://github.com/dronenb/HomeLab/blob/main/kubernetes/cluster-bootstrap/k3s/terraform/proxmox_vm/main.tf#L30)

Both of these work fine. I am using provider [2.9.14](https://github.com/dronenb/HomeLab/blob/main/kubernetes/cluster-bootstrap/k3s/terraform/providers.tf). Are you on a different version?

**Comment by aleprovencio** [comment]
Thanks for you reply @dronenb, without it I could not spot the dumb mistake I was doing, which was pointing to a private key instead of its public version. 

:man_facepalming:
