### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by piedro** [Telmate/terraform-provider-proxmox#85]
go install github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox
go install github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provisioner-proxmox

404 not found

**Comment by czepesch** [comment]
go get github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox
go install github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox

go get github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provisioner-proxmox
go install github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provisioner-proxmox

thats how i installed

**Comment by cospeedster** [comment]
My way of installation:
1. install go
    ```bash
    sudo apt install golang -y
    ```
2. Download Proxmox 4 Terraform
    ```bash
    git clone https://github.com/Telmate/terraform-provider-proxmox.git
    ```
3. Install
    ```bash
    cd terraform-provider-proxmox/
    make setup
    make
    make install
    ```
4. Copy plugin for terraform
    ```bash
    cp ~/go/bin/* ~/.terraform.d/plugins
    ```
