### ISSUE TITLE
Terraform Destroy with stopped LXC containers fails

### ISSUE THREAD

**Issue by richjjoh** [Telmate/terraform-provider-proxmox#857]
Performing a terraform destroy, on stopped LXC containers fails. 

> terraform destroy
> proxmox_lxc.basic_10: Refreshing state... [id=pve/lxc/105]
> proxmox_lxc.basic_20: Refreshing state... [id=pve/lxc/103]
> 
> Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
>   - destroy
> 
> Terraform will perform the following actions:
> 
>   # proxmox_lxc.basic_10 will be destroyed
>   - resource "proxmox_lxc" "basic_10" {
>       - arch                 = "amd64" -> null
>       - bwlimit              = 0 -> null
>       - cmode                = "tty" -> null
>       - console              = true -> null
>       - cores                = 1 -> null
>       - cpulimit             = 0 -> null
>       - cpuunits             = 1024 -> null
>       - force                = false -> null
>       - hostname             = "lxc-basic1" -> null
>       - id                   = "pve/lxc/105" -> null
>       - ignore_unpack_errors = false -> null
>       - memory               = 512 -> null
>       - onboot               = false -> null
>       - ostemplate           = "homelab:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst" -> null
>       - ostype               = "ubuntu" -> null
>       - password             = (sensitive value) -> null
>       - protection           = false -> null
>       - restore              = false -> null
>       - start                = false -> null
>       - swap                 = 0 -> null
>       - target_node          = "pve" -> null
>       - template             = false -> null
>       - tty                  = 2 -> null
>       - unique               = false -> null
>       - unprivileged         = true -> null
>       - unused               = [] -> null
> 
>       - network {
>           - bridge   = "vmbr0" -> null
>           - firewall = false -> null
>           - hwaddr   = "8E:CF:C3:A3:20:8C" -> null
>           - ip       = "dhcp" -> null
>           - mtu      = 0 -> null
>           - name     = "eth0" -> null
>           - rate     = 0 -> null
>           - tag      = 0 -> null
>           - type     = "veth" -> null
>         }
> 
>       - rootfs {
>           - acl       = false -> null
>           - quota     = false -> null
>           - replicate = false -> null
>           - ro        = false -> null
>           - shared    = false -> null
>           - size      = "8G" -> null
>           - storage   = "local-lvm" -> null
>           - volume    = "local-lvm:vm-105-disk-0" -> null
>         }
>     }
> 
>   # proxmox_lxc.basic_20 will be destroyed
>   - resource "proxmox_lxc" "basic_20" {
>       - arch                 = "amd64" -> null
>       - bwlimit              = 0 -> null
>       - cmode                = "tty" -> null
>       - console              = true -> null
>       - cores                = 1 -> null
>       - cpulimit             = 0 -> null
>       - cpuunits             = 1024 -> null
>       - force                = false -> null
>       - hostname             = "lxc-basic2" -> null
>       - id                   = "pve/lxc/103" -> null
>       - ignore_unpack_errors = false -> null
>       - memory               = 512 -> null
>       - onboot               = false -> null
>       - ostemplate           = "homelab:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst" -> null
>       - ostype               = "ubuntu" -> null
>       - password             = (sensitive value) -> null
>       - protection           = false -> null
>       - restore              = false -> null
>       - start                = false -> null
>       - swap                 = 0 -> null
>       - target_node          = "pve" -> null
>       - template             = false -> null
>       - tty                  = 2 -> null
>       - unique               = false -> null
>       - unprivileged         = true -> null
>       - unused               = [] -> null
> 
>       - network {
>           - bridge   = "vmbr0" -> null
>           - firewall = false -> null
>           - hwaddr   = "0A:C7:03:03:26:DF" -> null
>           - ip       = "dhcp" -> null
>           - mtu      = 0 -> null
>           - name     = "eth0" -> null
>           - rate     = 0 -> null
>           - tag      = 0 -> null
>           - type     = "veth" -> null
>         }
> 
>       - rootfs {
>           - acl       = false -> null
>           - quota     = false -> null
>           - replicate = false -> null
>           - ro        = false -> null
>           - shared    = false -> null
>           - size      = "8G" -> null
>           - storage   = "local-lvm" -> null
>           - volume    = "local-lvm:vm-103-disk-0" -> null
>         }
>     }
> 
> Plan: 0 to add, 0 to change, 2 to destroy.
> 
> Do you really want to destroy all resources?
>   Terraform will destroy all your managed infrastructure, as shown above.
>   There is no undo. Only 'yes' will be accepted to confirm.
> 
>   Enter a value: yes
> 
> proxmox_lxc.basic_20: Destroying... [id=pve/lxc/103]
> proxmox_lxc.basic_10: Destroying... [id=pve/lxc/105]
> ╷
> │ Error: 500 CT 105 not running
> │ 
> │ 
> ╵
> ╷
> │ Error: 500 CT 103 not running

Starting the instances, performing a destroy works as expected.

**Comment by luciusf** [comment]
fyi - https://github.com/Telmate/terraform-provider-proxmox/issues/801 
Unfortunately it seems at this point, the telmate/proxmox-terraform-provider at this point is abandonware, and [no one seems to be able to step up and take over](https://github.com/Telmate/terraform-provider-proxmox/issues/863).

**Comment by sergeycherepanov** [comment]
The issue still present

**Comment by codylo** [comment]
Yes this is still present. The LXC have to be started in order to destroy.

```
Plan: 0 to add, 0 to change, 2 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

proxmox_lxc.lxc-mini: Destroying... [id=mini/lxc/131]
proxmox_lxc.lxc-prox1: Destroying... [id=prox1/lxc/132]
╷
│ Error: 500 CT 132 not running
│ 
│ 
╵
╷
│ Error: 500 CT 131 not running
│ 
│ 
╵
```
