### ISSUE TITLE
nodes/node/qemu-server/103.conf does not exist

### ISSUE THREAD

**Issue by utf18** [Telmate/terraform-provider-proxmox#86]
when i try to clone an existing template with the cloud-init from the examples i get the error message

```
proxmox_vm_qemu.cloudinit-test: Creating...

Error: 500 Configuration file 'nodes/nuc/qemu-server/103.conf' does not exist

  on main.tf line 7, in resource "proxmox_vm_qemu" "cloudinit-test":
   7: resource "proxmox_vm_qemu" "cloudinit-test" {

```

i cannot find anything else in google besides the unlock vm command, which did not help

best Benjamin

**Comment by ggongaware** [comment]
Looks like something internally is missing in proxmox. Check if that file exists on the proxmox host, if you're running a multi-node cluster check that all the nodes are syncing properly.

**Comment by ben-st** [comment]
hi thanks for the quick feedback :)

the thing is i don't really understand whats happening.
i try to clone from a machine which i created in this process:
https://pve.proxmox.com/wiki/Cloud-Init_Support

ubuntu server with cloud-init, which i migrated to a template.

i tried running it with trace these are the last lines before the error

```
it should create said file in the process, i think, because in the path are other config files from other already existing machines.
2019-09-14T09:29:58.821+0200 [DEBUG] plugin.terraform-provider-proxmox: Connection: close
2019-09-14T09:29:58.821+0200 [DEBUG] plugin.terraform-provider-proxmox: Content-Length: 13
2019-09-14T09:29:58.821+0200 [DEBUG] plugin.terraform-provider-proxmox: Cache-Control: max-age=0
2019-09-14T09:29:58.821+0200 [DEBUG] plugin.terraform-provider-proxmox: Content-Type: application/json;charset=UTF-8
2019-09-14T09:29:58.821+0200 [DEBUG] plugin.terraform-provider-proxmox: Date: Sat, 14 Sep 2019 07:29:58 GMT
2019-09-14T09:29:58.821+0200 [DEBUG] plugin.terraform-provider-proxmox: Expires: Sat, 14 Sep 2019 07:29:58 GMT
2019-09-14T09:29:58.821+0200 [DEBUG] plugin.terraform-provider-proxmox: Pragma: no-cache
2019-09-14T09:29:58.821+0200 [DEBUG] plugin.terraform-provider-proxmox: Server: pve-api-daemon/3.0
2019-09-14T09:29:58.821+0200 [DEBUG] plugin.terraform-provider-proxmox:
2019-09-14T09:29:58.821+0200 [DEBUG] plugin.terraform-provider-proxmox: {"data":null})
2019/09/14 09:29:58 [DEBUG] proxmox_vm_qemu.cloudinit-test: apply errored, but we're indicating that via the Error pointer rather than returning it: 500 Configuration file 'nodes/nuc/qemu-server/100.conf' does not exist
2019/09/14 09:29:58 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/09/14 09:29:58 [TRACE] EvalMaybeTainted: proxmox_vm_qemu.cloudinit-test encountered an error during creation, so it is now marked as tainted
2019/09/14 09:29:58 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/09/14 09:29:58 [TRACE] EvalWriteState: removing state object for proxmox_vm_qemu.cloudinit-test
2019/09/14 09:29:58 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2019/09/14 09:29:58 [TRACE] EvalApplyProvisioners: proxmox_vm_qemu.cloudinit-test has no state, so skipping provisioners
2019/09/14 09:29:58 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2019/09/14 09:29:58 [TRACE] EvalMaybeTainted: proxmox_vm_qemu.cloudinit-test encountered an error during creation, so it is now marked as tainted
2019/09/14 09:29:58 [TRACE] <root>: eval: *terraform.EvalWriteState
2019/09/14 09:29:58 [TRACE] EvalWriteState: removing state object for proxmox_vm_qemu.cloudinit-test
2019/09/14 09:29:58 [TRACE] <root>: eval: *terraform.EvalIf
2019/09/14 09:29:58 [TRACE] <root>: eval: *terraform.EvalIf
2019/09/14 09:29:58 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2019/09/14 09:29:58 [TRACE] <root>: eval: *terraform.EvalApplyPost
2019/09/14 09:29:58 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: 500 Configuration file 'nodes/nuc/qemu-server/100.conf' does not exist
2019/09/14 09:29:58 [ERROR] <root>: eval: *terraform.EvalSequence, err: 500 Configuration file 'nodes/nuc/qemu-server/100.conf' does not exist
2019/09/14 09:29:58 [TRACE] [walkApply] Exiting eval tree: proxmox_vm_qemu.cloudinit-test
2019/09/14 09:29:58 [TRACE] vertex "proxmox_vm_qemu.cloudinit-test": visit complete
2019/09/14 09:29:58 [TRACE] dag/walk: upstream of "provider.proxmox (close)" errored, so skipping
2019/09/14 09:29:58 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2019/09/14 09:29:58 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019/09/14 09:29:58 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2019/09/14 09:29:58 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2019/09/14 09:29:58 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate

2019/09/14 09:29:58 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
Error: 500 Configuration file 'nodes/nuc/qemu-server/100.conf' does not exist

  on main.tf line 7, in resource "proxmox_vm_qemu" "cloudinit-test":
   7: resource "proxmox_vm_qemu" "cloudinit-test" {


2019/09/14 09:29:58 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2019-09-14T09:29:58.849+0200 [DEBUG] plugin: plugin process exited: path=/Users/benjamin/.terraform.d/plugins/darwin_amd64/terraform-provider-proxmox pid=74056
2019-09-14T09:29:58.849+0200 [DEBUG] plugin: plugin exited

```

**Comment by ben-st** [comment]
this is the main.tf i am using from the examples dir.

```


provider "proxmox" {
    pm_tls_insecure = true
}

resource "proxmox_vm_qemu" "cloudinit-test" {
    name = "terraform"
    desc = "A test for using terraform and cloudinit"

    # Node name has to be the same name as within the cluster
    # this might not include the FQDN
    target_node = "nuc"

    # The destination resource pool for the new VM
    pool = "pool0"

    # The template name to clone this vm from
    clone = "VM 9000"

    # Activate QEMU agent for this VM
    agent = 1

    os_type = "cloud-init"
    cores = "2"
    sockets = "1"
    cpu = "host"
    memory = "2048"
    scsihw = "lsi"

    # Setup the disk. The id has to be unique
    disk {
        id = 0
        size = 32
        type = "virtio"
        storage = "local"
        storage_type = "disk"
        iothread = true
    }

    # Setup the network interface and assign a vlan tag: 256
    network {
        id = 0
        model = "virtio"
        bridge = "vmbr0"
        tag = 256
    }

    # Setup the ip address using cloud-init.
    # Keep in mind to use the CIDR notation for the ip.
    ipconfig0 = "ip=192.168.0.1/24,gw=192.168.0.1"

    sshkeys = <<EOF
    <my-pub-key>
    EOF
}
```

**Comment by djoubert** [comment]
I am experiencing the same error. This specifically happens when I attempt to clone from a template with a cloud-init drive attached. If I clone from a template with not cloud-init drive attached, the clone is successful.

**Comment by ben-st** [comment]
same here the machine to clone is a cloud-init template

**Comment by M0NsTeRRR** [comment]
Hey i'm experiencing the same error.
I've 3 proxmox nodes. My template is in cephFS store.
I've tried to create 1 VM / Node from this template (with cloud-init driver and without) all time after 5mn10 elapsed on terraform i got the error.
```
Error: 500 Configuration file 'nodes/server2/qemu-server/104.conf' does not exist

  on modules/proxmox_VM/main.tf line 1, in resource "proxmox_vm_qemu" "rancher2":
   1: resource "proxmox_vm_qemu" "rancher2" {



Error: 500 can't lock file '/var/lock/qemu-server/lock-103.conf' - got timeout

  on modules/proxmox_VM/main.tf line 1, in resource "proxmox_vm_qemu" "rancher2":
   1: resource "proxmox_vm_qemu" "rancher2" {



Error: 500 Configuration file 'nodes/server3/qemu-server/105.conf' does not exist

  on modules/proxmox_VM/main.tf line 1, in resource "proxmox_vm_qemu" "rancher2":
   1: resource "proxmox_vm_qemu" "rancher2" {
```
If i try with only one VM (with cloud-init driver and without) I got the same error if it takes more than 5 minutes 10, if it takes less it works (depending of cloning speed).

Version :
terraform 0.12.16\
go 1.13\
terraform-provider-proxmox c4f2bac

**Comment by gentoo9ball** [comment]
Anyone figure this out, or a workaround?

**Comment by SudoLogic** [comment]
I'm running into this.

I have a vm with vmid 100 and 101, but everything else is using much higher numbers, so when it complained about 102.conf missing, it was telling. I suspected it was trying to create 102.conf and failing, possibly because it couldn't create a conf file. I watched the conf directory and ran it, and no, it definitely created, but then it failed. Ran it again and cat'd the file in the second it existed:

`# qmclone temporary file
lock: clone`

Ok, so its probably failing on clone. Go check those logs:

`
create full clone of drive ide2 (local-lvm:vm-199-cloudinit)
TASK ERROR: clone failed: unable to parse volume filename 'vm-102-cloudinit'`

That's something, but now I'm stuck. I've verified I can clone the template with the same settings on the command line. I've also figured out it works fine if I set full_clone = false. But I want full clones.

**Comment by SudoLogic** [comment]
Figured it out, at least for me.

I use local-lvm storage for my cloud init drives, and apparently the api can't read from that?

I ran this: `qm set 99002 --ide2 local:cloudinit` to remount the cloudinit drive as local instead of local-lvm, and that seems to have fixed it.

**Comment by frjaraur** [comment]
I think this problem still open. Is there any workaround, I am experiencing the same errors.

**Comment by alteredtech** [comment]
Had this issue. What I found to work around. Just replace 109 with your vmid giving you issues.
This is the error I was getting.
clone failed: zfs error: cannot create nodes/pve/qemu-server/109.conf does not exist
clone failed: zfs error: cannot create 'local-storage/vm-109-cloudinit': dataset already exists

What I did to get rid of these errors was to first find anything with vm-109
`find / -name vm-109`
Then delete all the files that return.
Then for me, I had a zfs pool. I needed to look there as well.
`zfs list`
In this list should show a pool/dataset. You'll want to delete one that matches the error you are getting. In my case it was local-storage/vm-109-cloudinit.
`zfs destroy local-storage/vm-109-cloudinit`

Now that every referring to that vmid is deleted you should be able to terraform apply without issues.
