### ISSUE TITLE
Idempotency problem - Mac address must be left to computed. 

### ISSUE THREAD

**Issue by helldorado** [Telmate/terraform-provider-proxmox#88]
hello, 
first of all, thanks for this great provider. 

A major regression was introduced with this change form commit https://github.com/Telmate/terraform-provider-proxmox/commit/bf98b941f7bdfea2d4c19239d04d4b57c19f9da6 

This completely breaks the provider's idempotency and is unusable in production.

Some issues like #82 is related to this commit.

I don’t see the point of generating or providing a MAC address while Proxmox API already does the job and returns the result in its answer.

I patched locally for our needs. Is there any chance to rollback to `Computed: true` ?
If this is not possible, a refactoring of the function https://github.com/Telmate/proxmox-api-go/blob/master/proxmox/config_qemu.go#L661-L704 will be necessary, and we can make a patch for the community.

Best regards.

**Comment by mbuiro** [comment]
You can sort of get around this by hardcoding the MAC address yourself:

```
    # Setup the network interface 
    network {
        id = 0
        model = "virtio"
        bridge = "vmbr0"
        firewall = false
        macaddr = "DE:1E:8C:42:E8:52"
    }
```

Unfortunately, the next idempotency issue stems from the cloud init password:

```
# proxmox_vm_qemu.cloudinit-test will be updated in-place
  ~ resource "proxmox_vm_qemu" "cloudinit-test" {
        agent        = 1
        boot         = "cdn"
        bootdisk     = "virtio0"
      ~ cipassword   = "**********" -> "supersecretpassword"
```

**Comment by alexanderek** [comment]
> Unfortunately, the next idempotency issue stems from the cloud init password

How can this be fixed?

**Comment by cospeedster** [comment]
I mentioned a work around here: Telmate/terraform-provider-proxmox#112
