### ISSUE TITLE
 Warning: define_connection_info is %t, no further action.

### ISSUE THREAD

**Issue by pescobar** [Telmate/terraform-provider-proxmox#891]
If I use `define_connection_info = false` for a `proxmox_vm_qemu` resource I always get this warning:

```
Warning: define_connection_info is %t, no further action.
```

**Comment by pescobar** [comment]
This issue still persists with latest release [v3.0.1-rc1](https://github.com/Telmate/terraform-provider-proxmox/releases/tag/v3.0.1-rc1)

**Comment by LeoShivas** [comment]
I confirm, bug still present in https://github.com/Telmate/terraform-provider-proxmox/releases/tag/v3.0.1-rc1
