### ISSUE TITLE
2.9.14 version of the provider is not working on the proxmox 8.1.3

### ISSUE THREAD

**Issue by adelrizaev** [Telmate/terraform-provider-proxmox#898]
There are two main issues:
1. Plugin crush panic: interface conversion: interface {} is string, not float64 (This can be work-arounded by using MaartendeKruijf/proxmox provider)
2. Duplicate disk created when clonnig from the template.

Is there any provider version which fixes both issues?
Otherwise the provider cant be used at all.
Thank you very much!

**Comment by pescobar** [comment]
check comments in these issues
 https://github.com/Telmate/terraform-provider-proxmox/issues/863  
 https://github.com/Telmate/terraform-provider-proxmox/issues/884
  https://github.com/Telmate/terraform-provider-proxmox/issues/887

**Comment by adelrizaev** [comment]
@pescobar thank you, i already checked them. But i want to use the provider in proper way like:
```
terraform {
  required_providers {
    proxmox = {
      source = "telmate/proxmox"
      version = "2.9.1x"
      #source = "MaartendeKruijf/proxmox"
      #version = "0.0.1"
      #source = "TheGameProfi/proxmox"
      #version = "2.9.16"
    }
  }
}
```
:-)))

I mean this provider is the most downloaded one from all providers.
Otherwise, the idea of stable IaC on proxmox is not achievable.
Can i help somehow?

**Comment by pescobar** [comment]
AFAIK the only way to get a working provider today is to build the latest code in master yourself. There are some docs in the issues I linked before

If you want to contribute to maintain the project you can join the discussion in https://github.com/Telmate/terraform-provider-proxmox/issues/884

**Comment by electropolis** [comment]
> Hi! Check work RC v3.0.1-rc1 on Terraform 1.6.6 / 1.7.1 with ProxMox 8.1.3. The error is gone. Everything works well. Thanks to all!

cloudinit doesn't work :/

**Comment by thdonatello** [comment]
@electropolis cloudinit works in v3.0.1-rc1. But there is a big problem with `disks`. This provider is awful!

**Comment by electropolis** [comment]
> @electropolis cloudinit works in v3.0.1-rc1. But there is a big problem with `disks`. This provider is awful!

cloudinit with snippets doesn't work at all. Disks ? what problem?

**Comment by thdonatello** [comment]
with snippets to?! Oh sh* )))
[Here](https://github.com/Telmate/terraform-provider-proxmox/issues/907) is problem with disks.

**Comment by electropolis** [comment]
> with snippets to?! Oh sh* ))) [Here](https://github.com/Telmate/terraform-provider-proxmox/issues/907) is problem with disks.

I managed to have it work as @Tinyblargon described here

I don't have any problem with disks but as I see in that issue there is no possibility to create disks in loop.

**Comment by thdonatello** [comment]
Yep )

**Comment by electropolis** [comment]
> Yep )

The only solution is to defined different `tf` file for servers with more than one disk. But for me it doesn't make sense. Probably I will set different tf file for different vm types. This is one is perfect for creating nodes for k3s purpose.

**Comment by thdonatello** [comment]
I want to create k8s cluster ) But I want to use different disks for system, logs and overlays. And two or more network interfaces.

**Comment by electropolis** [comment]
Having additional disk in that cluster doesn't make sense in my opinion. Every node doesn't have any additional disk. Those additional disks are sharable object storage so Node can use RWX. Network interfaces? Network interfaces can be easily attached from cloudinit using `network-config`
