### ISSUE TITLE
Clone wait should be configurable

### ISSUE THREAD

**Issue by AleRousse** [Telmate/terraform-provider-proxmox#90]
Hi,

So I am getting this following error message when I try to create a VM that required a large resize on the template's disk.

`Error: 500 command '/usr/bin/qemu-img resize -f qcow2 /mnt/pve/storage-vmpool/images/101/vm-101-disk-0.qcow2 75161927680' failed: got timeout`

This is mostly thrown because the create sequence is too fast and terraform is not waiting for the full resize to be done before trying to start the VM.

A PR will follow

Thanks

**Comment by M0NsTeRRR** [comment]
Facing the same problem, I hope it will be merged soon :)
