### ISSUE TITLE
[3.0.1-rc1] Should we move efidisk to new disks schema before release?

### ISSUE THREAD

**Issue by riverar** [Telmate/terraform-provider-proxmox#914]
Should we also consider moving the recently added `efidisk` to the new disks schema?

Old:
```tf
efidisk {
  efitype = "4m"
  storage = "local"
}
```

Suggested new:
```tf
disks {
  # ...
  efidisk {
    efitype = "4m"
    storage = "local"
  }
}
```

**Comment by gbrackley** [comment]
I had a little think about this ... and I have had a play with the new `disks` schema.

I am seeing the `disks` schema as being about **storage**. Given this I have posed the question as "Is efidisk about storage?"

I am seeing the efidisk as a host (where host is the VM) based resource. It is not about having storage available for the host operating system and applications. The efi disk is used to help get the VM running. So, my conclusion is **no**, the efi configuration should not be part of the storage configuration.  

I have been using Flatcar Linux and this project publishes both EFI code and EFI vars - it would be useful if both could be provisioned. QEMU has the ability to provision both (as different pflash devices).

As an aside a **really** hope the design of the `disks` parameter is simplified so that it is usable in Terraform modules.

**Comment by hestiahacker** [comment]
As much as I don't want to hold up the 3.0 release, I think we should wait until we have this efidisk change in there so we can avoid another breaking change in the near future.

The only exception would be if nobody is currently planning on implementing this, in which case there's no reason to hold up the release indefinitely for a feature which might never be implemented.

**Comment by riverar** [comment]
> I have been using Flatcar Linux and this project publishes both EFI code and EFI vars - it would be useful if both could be provisioned. QEMU has the ability to provision both (as different pflash devices).

Not sure proxmox supports this, can you double check? https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/config

> As much as I don't want to hold up the 3.0 release, I think we should wait until we have this efidisk change in there so we can avoid another breaking change in the near future.

Seems like we're split on whether it should be in the new disks schema or not. Thoughts @Tinyblargon?

**Comment by riverar** [comment]
I can do it, but there's an outstanding question of whether we should. @gbrackley is voting no (https://github.com/Telmate/terraform-provider-proxmox/issues/914#issuecomment-1938146136) and is convincing, while I was initially soft yes (https://github.com/Telmate/terraform-provider-proxmox/issues/914#issue-2104296956).

I don't mind either way, was hoping to hear from @Tinyblargon as they drove the refactor and understands the goals there.

**Comment by riverar** [comment]
(Some small addition to context here: efidisk use is effectively required for all modern Windows VMs.)

Decision sounds good to me, we can leave as-is and if interest rises, slot it in during the 4.0 breaking change window. Thanks for the consideration all!

**Comment by gbrackley** [comment]
And some more context...

Once we strip back the terraform, the proxmox API and the proxmox scripts, this is about configuring a `pflash` device at the QEMU level.

From the [manual](https://www.qemu.org/docs/master/system/qemu-manpage.html):

> if=interface
>
>    This option defines on which type on interface the drive is connected. Available types are: ide, scsi, sd, mtd, floppy, pflash, virtio, none.

So at at the QEMU level, the `pflash` is treated the same as any other disks. On this basis, should the other types also be consider to be added to the disks structure?

From another angle, my understanding is, the pflash storage is a machine level thing that is usually soldered onto the motherboard. This will be NOR flash.  This is used in the boot process to load drivers (code) and data (configuration).

Windows and other OS are likely to want this for secure/trusted boot.

This is **not** the same as the EFI System Partition (ESP), which is usually a little FAT partition on a SATA/IDE/SCSI drive.

### IMHO

- please make `disks` simpler and able to be used in a module. As a module writer I want to be able to pass the `disks` parameter through the module (with or without modification).
- consider a design that allows the disks to be broken out as independent resources (this is going to be a hard ask as of today with the Proxmox API and the Proxmox design might not fully support this).  If I was provisioning VMs at any major cloud provider this would be the style of terraform I would expect.

## Links

- https://www.qemu.org/docs/master/system/qemu-manpage.html
- https://subscription.packtpub.com/book/programming/9781784392536/3/ch03lvl1sec29/booting-with-uefi-firmware

**Comment by Tinyblargon** [comment]
Closing in favor of getting a new release completed.
