### ISSUE TITLE
Cloning VM

### ISSUE THREAD

**Issue by solairen** [Telmate/terraform-provider-proxmox#915]
### Question
---------------

Hi, how can I clone VM from my template? I have changed the `disk` block and it technically clones the VM from my template but removes `ide2` where the cloud-init disk is stored and this causes the problem when it runs.

![missing-cloud-init](https://github.com/Telmate/terraform-provider-proxmox/assets/45487024/925f2185-5e49-4e68-9e6d-f21e94225525)

It should look like this:

![cloud-init](https://github.com/Telmate/terraform-provider-proxmox/assets/45487024/2f401c82-b629-4458-bf7e-5291a9b6b1c1)

### Version

3.0.1-rc1

### Config
------------

```tf
resource "proxmox_vm_qemu" "instance" {
  name        = var.instance_name
  target_node = var.proxmox_host
  clone       = var.proxmox_template_name
  bootdisk    = "scsi0"
  agent       = 1
  os_type     = "cloud-init"
  cores       = var.cpu_cores
  sockets     = 1
  cpu         = "host"
  memory      = var.memory_number
  scsihw      = "virtio-scsi-pci"
  numa        = true
  hotplug     = "network,disk,usb,cpu,memory"
  tags        = var.tags
  full_clone  = true
  onboot      = true

  disks {
    scsi {
      scsi0 {
        disk {
          storage = var.storage
          size = var.storage_size
        }
      }
    }
  }

  network {
    model  = "virtio"
    bridge    = "vmbr0"
  }

  lifecycle {
    create_before_destroy = true
  }

  connection {
    type        = "ssh"
    user        = "hostuser"
    private_key = file("/home/${var.container_user}/.ssh/id_ed25519")
    host        = self.default_ipv4_address
  }

  provisioner "remote-exec" {
    inline = [
      "sudo sed -i 's/#Port 22/Port ${var.ansible_ssh_port}/' /etc/ssh/sshd_config",
      "sudo systemctl restart sshd"
    ]
  }
}
```

**Comment by Tinyblargon** [comment]
@solairen the `cloud-init` disk should be created as `ide3` when `cloudinit_cdrom_storage:` is set along with any cloud init setting such as `ciuser`.

**Comment by Qarasique** [comment]
@Tinyblargon May you please show example, how now just clone from cloud-init capable templates ?

**Comment by Tinyblargon** [comment]
@Qarasique Adding the following should let it make a `cloud-init` disk:

```hcl
resource "proxmox_vm_qemu" "instance" {
// omitted for brevity
  cloudinit_cdrom_storage = "local-lvm"
  ciuser = "root"
// omitted for brevity
}
```

**Comment by solairen** [comment]
@Tinyblargon thanks! added `cloudinit_cdrom_storage` and `ciuser` helped!
