### ISSUE TITLE
[3.0.1-rc1] vm_state bug or not?

### ISSUE THREAD

**Issue by Aggression** [Telmate/terraform-provider-proxmox#938]
Hi,

How vm_state should work? 
I observe the following behavior
1) if set vm_state = "running" at vm creating, vm will be created and turned on
2) if set vm_state = "stopped", vm will be turned off
3) If vm is turned off and you will set vm_state = "running", terraform will write that it will change vm_state from "stopped" to "running". But nothing happening, looks like it do nothing. There is no new tasks in proxmox.

Proxmox version is 7.4-3

Is it a bug?

**Comment by Tinyblargon** [comment]
@Aggression This is definitely a bug.

**Comment by JordanAdams** [comment]
+1 on this

**Comment by padilhafe** [comment]
+1 on this
i am using proxmox 8.1.3
