### ISSUE TITLE
Add/Remove Disks from Template doesn't work

### ISSUE THREAD

**Issue by cospeedster** [Telmate/terraform-provider-proxmox#94]
Hello everybody,

My Template has two disks (one for Boot and one for system). Now I want to add third disk for data after cloning (or while cloning). So terraform is cloning the template, resizing disk one and two, but fails on disk three, because it's not existent.
Error:
`TASK ERROR: rbd error: rbd: error opening image vm-270-disk-2: (2) No such file or directory`

In my `.tf` file i have three disks. The size after resizing is a bit unexpected, but I think I have to do some more research for that. The third disk looks like this:
```HCL
disk {
    id           = 2
    size         = "60G"
    type         = "scsi"
    storage      = "POOL"
    storage_type = "rbd"
    iothread     = false
  }
```
**Is there any chance to get this disk created by terraform?**

Another thing is to remove a disk. For test purposes i removed the second disk and found out that the disk wasn't removed after cloning. Is this behavior required for something?

**Need help, please :)**

**Comment by billimek** [comment]
I'm struggling with how to implement more disks too.

**Comment by cospeedster** [comment]
Let me here from you when you find out something, @billimek.

**Comment by cospeedster** [comment]
@billimek Did you found something out?

**Comment by billimek** [comment]
@cospeedster not yet.  However, I see that [this PR](https://github.com/Telmate/proxmox-api-go/pull/61) was merged which suggests that it may be fixed now?

I have yet to test this, however.

**Comment by cospeedster** [comment]
@billimek No, it should just fix an error on cloning a template which contains multiple disks.

Sadly, adding Disks don't work..

**Comment by V-Paranoiaque** [comment]
The lib needs to be updated in the project, https://github.com/Telmate/terraform-provider-proxmox/pull/113
If you want the fix before, you can compile with GO111MODULE=off

**Comment by cospeedster** [comment]
@V-Paranoiaque Thanks for your response.
What do you mean with "The lib needs to be updated in the project" ?
Can you show me how to do that?

**Comment by cospeedster** [comment]
Well, I was a bit confused. I now saw your reference to your PR. @V-Paranoiaque

**Comment by V-Paranoiaque** [comment]
The versions of the libs are specified in go.mod and go.sum. So even if there is a breaking change in a lib, the plugin still uses a version who is working.

You can disable it and install with the following line but it's not recommended
``
export GO111MODULE=off && 
go install github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provisioner-proxmox && 
go install github.com/Telmate/terraform-provider-proxmox/cmd/terraform-provider-proxmox && 
terraform init
``

**Comment by cospeedster** [comment]
@billimek 
Adding and removing disks is now working properly.
Thank you @V-Paranoiaque !
