### ISSUE TITLE
section  disks {} not work in latest versions terraform and proxmox

### ISSUE THREAD

**Issue by yokozu777** [Telmate/terraform-provider-proxmox#952]
locks of type "disks" are not expected here. Did you mean "disk"

**Comment by tuxthepenguin84** [comment]
Looks like some changes to the way disks are done
https://github.com/Telmate/terraform-provider-proxmox/blob/master/examples/pxe_example.tf#L52

**Comment by TAAGECH9** [comment]
Absolutely. There is currently one open PR that explains it in detail -> https://github.com/Telmate/terraform-provider-proxmox/pull/948
