### ISSUE TITLE
Token permissions only for resource pool and not for global path

### ISSUE THREAD

**Issue by marvkos** [Telmate/terraform-provider-proxmox#958]
Hello,

my API token only has the necessary permissions for a specific resource pool. The provider only checks the permissions for the global path. That is why the terraform command fails. ```Error: permissions for user/token <userid> are not sufficient, ...```

Example: 

API Token has Administration permissions for ```pool/XYZ```

The provider checks the permissions for ```/api2/json/access/permissions?userid=<userid>&path=/```

Is it possible to change the permission route to ```/api2/json/access/permissions?userid=<userid>&path=/pool/XYZ```

Thank you

**Comment by scmanjarrez** [comment]
It used to work with version 2.9.11. At least the permission checks were not there in that version.

**Comment by konstantin-kornienko** [comment]
I'd suggest to have an option to skip permissions check at all.
Out technical user account in Proxmox has permissions to only one Pool. It fails now on 3.0.1-rc1

**Comment by maksimsamt** [comment]
To get working  3.0.1-rc2 with user/token with privilege separation and pool's fine-grained permissions here is an example how it could be achieved  - https://github.com/Telmate/terraform-provider-proxmox/issues/784#issuecomment-2135266013
