### ISSUE TITLE
Docs: Example `cloud-init`

### ISSUE THREAD

**Issue by Tinyblargon** [Telmate/terraform-provider-proxmox#959]
# **Please do note this is about the latest state of the master branch, not release v3.0.1-rc1**

### Create base vm

We first create a vm with id: `9000` and name: `cloudinit-template`.

After the vm is created we remove as much hardware as possible, everything else we'll  leave as default.

You should now have the following:
![image](https://github.com/Telmate/terraform-provider-proxmox/assets/76069640/afc9378e-deed-4f18-8b06-0b40a3748ea8)

Terraform enforces the full configuration of the cloned vm. This means Terraform will remove any hardware that isn't accounted for in the Terraform config. _If it doesn't do this it's a bug, please report it._

### Add cloud-init image

We will now add an OS image that has `cloud-init` support, for this example I used the the `debian-12-genericcloud-amd64.qcow2` that can be downloaded form https://cloud.debian.org/images/cloud/bookworm/latest/

To add the disk run the following command on the shell of you PVE.
```bash
wget https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2 --output-document /tmp/debian-12-genericcloud-amd64.qcow2
qm importdisk 9000 /tmp/debian-12-genericcloud-amd64.qcow2 local-lvm
```

The disk is added as a detached disk, now you can add it as `ide0`.

Your final setup should look like this:
![image](https://github.com/Telmate/terraform-provider-proxmox/assets/76069640/b38486eb-c711-4f33-b94d-075fd327abe0)

## CiCustom

to use `cicustom` a `snipped` must be created, mine is located at `/var/lib/vz/snippets/ci-custom.yml`

```yml
runcmd:
    - apt update
    - apt install -y qemu-guest-agent
    - systemctl start qemu-guest-agent
    - reboot
```

## Terraform config

```hcl
resource "proxmox_vm_qemu" "cloudinit-test" {
    name = "test1"
    target_node = "pve8"
    clone = "cloudinit-template"
    os_type = "cloud-init"
    boot = "order=ide0"
    cloudinit_cdrom_storage = "local-lvm"
    ciuser = "root"
    cipassword = "Enter123!"
    cicustom = "vendor=local:snippets/ci-custom.yml" # /var/lib/vz/snippets/ci-custom.yml
    disks {
        ide {
            ide0 {
                disk {
                    size = 8
                    storage = "local-lvm"
                }
            }
        }
    }
    network {
        bridge    = "vmbr0"
        model     = "virtio"
    }
    ipconfig0 = "ip=dhcp"
}
```

**Comment by Tinyblargon** [comment]
@electropolis

The `disks` and `boot` properties you've correctly adapted to your setup.

The `cloud-init` disk will be added by Terraform as `ide3` I included it in the template to demonstrate that it will be removed from `ide1` and added as `ide3`, as this previously gave an error for some people.

I don't think it is different form the official Proxmox guide, just formatted differently so it's easier to find if there is a Terraform config issue.

I'll make this guide a bit more extensive, as i did skip over some details.

**Comment by electropolis** [comment]
> The `cloud-init` disk will be added by Terraform as `ide3`

I would love to have terraform add this disk finally as `ide3` as I constantly can't reach the point where it does. I struggled with many different setups and no combination works. That's why I was trilled when you posted. 



> I don't think it is different form the official Proxmox guide

Yeah I see now it doesn't as you mention that you omitted some steps only in the post. But I look forward to have your full setup as I don't see where I do make something different. I think I make the exact setup. I also tried with `ide3` when creating the template by setting `cloudinit` as `ide3`

```qm set 9000 --ide2 local-lvm:cloudinit```
and still it was removing the cloudinit file when changing the scsi0 disk size and suddenly after that cdrom appeared and cloudinit disappeared.

**Comment by Tinyblargon** [comment]
@electropolis did you run it against a local build of the `master` branch? As `v3.0.1-rc1` does not include these changes.

**Comment by electropolis** [comment]
> @electropolis did you run it against a local build of the `master` branch? As `v3.0.1-rc1` does not include the latest fixes that make this setup possible.
> 
> This is our guide for the local build: https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/guides/installation.md#manual-build--install

Nah, I was using `tf init` . I wasn't cloning the repo manually. I will try it. And give a feedback here after tests.

**Comment by electropolis** [comment]
@Tinyblargon why when installing it manually 

```
❯ rm .terraform.lock.hcl
❯ rm .terraform
rm: .terraform: is a directory
❯ rm -rf .terraform
❯ tf init

Initializing the backend...

Initializing provider plugins...
- Finding telmate/proxmox versions matching ">= 1.0.0"...
- Finding latest version of hashicorp/null...
- Finding latest version of hashicorp/local...
- Finding latest version of hashicorp/template...
- Installing telmate/proxmox v2.9.14...
- Installed telmate/proxmox v2.9.14 (self-signed, key ID A9EBBE091B35AFCE)
- Installing hashicorp/null v3.2.2...
- Installed hashicorp/null v3.2.2 (signed by HashiCorp)
- Installing hashicorp/local v2.4.1...
- Installed hashicorp/local v2.4.1 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (unauthenticated)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

╷
│ Warning: Incomplete lock file information for providers
│
│ Due to your customized provider installation methods, Terraform was forced to calculate lock file checksums locally for the following providers:
│   - hashicorp/template
│
│ The current .terraform.lock.hcl file only includes checksums for darwin_arm64, so Terraform running on another platform will fail to install these providers.
│
│ To calculate additional checksums for another platform, run:
│   terraform providers lock -platform=linux_amd64
│ (where linux_amd64 is the platform to generate)
╵

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
❯ tf plan
╷
│ Error: Unsupported block type
│
│   on main.tf line 15, in resource "proxmox_vm_qemu" "cloudinit":
│   15:   disks {
│
│ Blocks of type "disks" are not expected here. Did you mean "disk"?
╵
```
it looks for disk instead of disks ? I see there is `v.2.9.14` version installed that doesn't have `disks` in code. So how you handle the `disks` inside your resource?

**Comment by Tinyblargon** [comment]
@electropolis I think that in your case the provider should be configured like this:
```hcl
terraform {
  required_providers {
    proxmox = {
      source  = "localhost/telmate/proxmox"
      version >= "1.0.0"
    }
  }
}

```

**Comment by electropolis** [comment]
> @electropolis I think that in your case the provider should be configured like this:
> 
> ```hcl
> 
> terraform {
> 
>   required_providers {
> 
>     proxmox = {
> 
>       source  = "localhost/telmate/proxmox"
> 
>       version >= "1.0.0"
> 
>     }
> 
>   }
> 
> }
> 
> 
> 
> ```

Exactly. Did some debug after my post and yes. It should be with `localhost/...` , so why there is without `localhost` or `registry...` ?

**Comment by electropolis** [comment]
@Tinyblargon 

![image](https://github.com/Telmate/terraform-provider-proxmox/assets/16556636/bf716826-f65d-48ee-8980-619f203b0e05)

Finally works! Thank you for your guidance. Btw check the documentation with that provider setup `localhost/...` 
`cicustom` works

**Comment by electropolis** [comment]
> @Tinyblargon
> 
> ![image](https://private-user-images.githubusercontent.com/16556636/311451700-bf716826-f65d-48ee-8980-619f203b0e05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMDY1MTAsIm5iZiI6MTcxMDAwNjIxMCwicGF0aCI6Ii8xNjU1NjYzNi8zMTE0NTE3MDAtYmY3MTY4MjYtZjY1ZC00OGVlLTg5ODAtNjE5ZjIwM2IwZTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE3NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MDM0N2Y5NTY1ZmUwODU4NTg2MzI0M2E2NjFjYTdjNjIwYTNmMzM5YWFiY2VkMDkyODViYjVhYTdhOTdlZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qdzQi5tSU0tw0w8yXHyPnSuwYYsJbbmVEcqIk8VbqjI)
> 
> Finally works! Thank you for your guidance. Btw check the documentation with that provider setup `localhost/...` `cicustom` works
> 
> ```
> local_file.cloud_init_network-config_file[0]: Creating...
> local_file.cloud_init_user_data_file[0]: Creation complete after 0s [id=2cad6635c2ab8fd04c7297e089a50b9299dfd7ec]
> local_file.cloud_init_network-config_file[0]: Creation complete after 0s [id=584397ad1c649775dfef64cff2484d781972e34c]
> null_resource.cloud_init_network-config_files[0]: Creating...
> null_resource.cloud_init_config_files[0]: Creating...
> null_resource.cloud_init_network-config_files[0]: Provisioning with 'file'...
> null_resource.cloud_init_config_files[0]: Provisioning with 'file'...
> null_resource.cloud_init_config_files[0]: Still creating... [10s elapsed]
> null_resource.cloud_init_network-config_files[0]: Still creating... [10s elapsed]
> null_resource.cloud_init_config_files[0]: Still creating... [20s elapsed]
> null_resource.cloud_init_network-config_files[0]: Still creating... [20s elapsed]
> null_resource.cloud_init_network-config_files[0]: Still creating... [30s elapsed]
> null_resource.cloud_init_config_files[0]: Still creating... [30s elapsed]
> null_resource.cloud_init_config_files[0]: Still creating... [40s elapsed]
> null_resource.cloud_init_network-config_files[0]: Still creating... [40s elapsed]
> null_resource.cloud_init_config_files[0]: Still creating... [50s elapsed]
> null_resource.cloud_init_network-config_files[0]: Still creating... [50s elapsed]
> null_resource.cloud_init_config_files[0]: Creation complete after 52s [id=441540502752639479]
> null_resource.cloud_init_network-config_files[0]: Creation complete after 52s [id=529443998753148410]
> proxmox_vm_qemu.cloudinit["srv-app-1"]: Creating...
> proxmox_vm_qemu.cloudinit["srv-app-1"]: Still creating... [10s elapsed]
> proxmox_vm_qemu.cloudinit["srv-app-1"]: Still creating... [20s elapsed]
> proxmox_vm_qemu.cloudinit["srv-app-1"]: Still creating... [30s elapsed]
> proxmox_vm_qemu.cloudinit["srv-app-1"]: Still creating... [40s elapsed]
> proxmox_vm_qemu.cloudinit["srv-app-1"]: Still creating... [50s elapsed]
> proxmox_vm_qemu.cloudinit["srv-app-1"]: Still creating... [1m0s elapsed]
> proxmox_vm_qemu.cloudinit["srv-app-1"]: Still creating... [1m10s elapsed]
> proxmox_vm_qemu.cloudinit["srv-app-1"]: Still creating... [1m20s elapsed]
> proxmox_vm_qemu.cloudinit["srv-app-1"]: Still creating... [1m30s elapsed]
> proxmox_vm_qemu.cloudinit["srv-app-1"]: Creation complete after 1m34s [id=pve1-hw/qemu/100]```
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/16556636/311456096-6b7b2b1d-fbf3-4bc0-b5d9-4bee03b17640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMDY1MTAsIm5iZiI6MTcxMDAwNjIxMCwicGF0aCI6Ii8xNjU1NjYzNi8zMTE0NTYwOTYtNmI3YjJiMWQtZmJmMy00YmMwLWI1ZDktNGJlZTAzYjE3NjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDE3NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YWVkMzNkYjYzMDgzZjQ0NjI3NzM3YmVkYjJiNDE2YWJjMmEwMGMzMTljYmVhYWU3NjIwNDEwMzdjODE3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hxKqmA2e8PHT2ytjTHXfUikq9ox55GJBHUmN0aNA36A) with installation of qemu-agent :) and `agent = 1`

But do you have something like this every time running `tf plan` ?

```
❯ tf plan
data.template_file.user_data["srv-app-1"]: Reading...
data.template_file.network-config["srv-app-1"]: Reading...
data.template_file.network-config["srv-app-1"]: Read complete after 0s [id=3cff359ae68e0ec1e0103822dfa8ee40b28e9adbd9782900a4fa43e3d7b06b74]
data.template_file.user_data["srv-app-1"]: Read complete after 0s [id=9b3ae8dce58a70b5e77c922247ceb5454381fadfeb5477af367a71b8ab595197]
local_file.cloud_init_network-config_file[0]: Refreshing state... [id=584397ad1c649775dfef64cff2484d781972e34c]
local_file.cloud_init_user_data_file[0]: Refreshing state... [id=2cad6635c2ab8fd04c7297e089a50b9299dfd7ec]
null_resource.cloud_init_network-config_files[0]: Refreshing state... [id=529443998753148410]
null_resource.cloud_init_config_files[0]: Refreshing state... [id=441540502752639479]
proxmox_vm_qemu.cloudinit["srv-app-1"]: Refreshing state... [id=pve1-hw/qemu/100]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # proxmox_vm_qemu.cloudinit["srv-app-1"] will be updated in-place
  ~ resource "proxmox_vm_qemu" "cloudinit" {
        id                      = "pve1-hw/qemu/100"
        name                    = "srv-app-1"
      - qemu_os                 = "other" -> null
        # (33 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
``` 
It cavil the `qemu_os` and wants to set it to null.

**Comment by Tinyblargon** [comment]
@electropolis happy to help. I've created #961 for the `qemu_os` diff issue.

**Comment by electropolis** [comment]
> @electropolis happy to help. I've created #961 for the `qemu_os` diff issue.

Yeah I've just deleted that post as it's just being resolved when adding the `qemu_os` to `resource`. But would be great if that could be set as a default to null.

**Comment by hestiahacker** [comment]
Since this was mentioned in 3.0.1-rc4, I'd just like to mention that we should make sure the release notes mentioned the breaking change of removing `cloudinit_cdrom_storage`.

It is already documented [here](https://github.com/Telmate/terraform-provider-proxmox/blob/master/docs/guides/cloud_init.md?plain=1#L159) but since this just bit me while I was testing 3.0.1-rc3 I figured I'd mention it so make sure it hits the release notes when the official v3.0.1 is released.
