### ISSUE TITLE
Attribute for ipv6

### ISSUE THREAD

**Issue by MaxSonicDev** [Telmate/terraform-provider-proxmox#966]
Hi ! 

I have a limitation with the current attribute. I can automate the creation of DNS record with the default_ipv4_address attribute, but I just noticed that there is no default_ipv6_address attribute available to retrieve the IPv6 address of the virtual machine using the QEMU guest agent.

is there a technical limitation of the provider or is it just not implemented yet?

**Comment by Tinyblargon** [comment]
Related to #974

**Comment by Tinyblargon** [comment]
Fixed by v3.0.1-rc2
