### ISSUE TITLE
Need help with the new disk handling format

### ISSUE THREAD

**Issue by myplixa** [Telmate/terraform-provider-proxmox#969]
Good time, dear community.
I would like your help in updating a part of the code for creating disks on a virtual machine.
I recently decided to upgrade my Proxmox cluster to the latest version and at the same time update my module for deploying virtual machines, and stumbled with the new format for working with disks.

Example input variable ``` vm_disk_sizes   = ["20G", "10G"] ```
variable.tf
```
variable "vm_disk_sizes" {
  description = "Size of the disk in GigaBytes"
  type        = list(string)
  default     = ["10G"]
}
```
main.tf
```
dynamic "disk" { 
    for_each = { for index, val in local.vm_disk_sizes : tostring(index) => val }
    content {
      storage  = local.vm_storage_name
      size     = disk.value
      type     = "virtio"
      iothread = 1
      aio      = "native"
    }
  }
```

**Comment by aegrodin** [comment]
I believe the main discussion is here: https://github.com/Telmate/terraform-provider-proxmox/issues/907
