### ISSUE TITLE
Terraform lxc: Device ids

### ISSUE THREAD

**Issue by in0rdr** [Telmate/terraform-provider-proxmox#98]
The [PVE API](https://pve.proxmox.com/pve-docs/api-viewer/) does not provide the `id` parameter for device configuration, e.g., the network interfaces (`net[n]`) or the mountpoints (`mp[n]`). Instead, the devices are expected to be added as configuration maps with the suffix `n`. For instance:
```
"net1":"name=eth0,bridge=vmbr0,hwaddr=B6:DA:AE:0E:55:22,ip=dhcp,ip6=dhcp,type=veth"
"net2":"name=eth1,bridge=vmbr0,hwaddr=92:AD:68:14:BE:56,ip=dhcp,ip6=dhcp,type=veth"
```

This poses the question, if it is necessary for users of the Terraform provider to explicitly specify the device `id`. For qemu resources it is [necessary to specify the `id` explicitly](https://github.com/Telmate/terraform-provider-proxmox/blob/master/examples/cloudinit_example.tf).

This issue exists to discuss the two approaches for lxc resources:
1. specify `id`s explicitly
2. or create helper functions for implicit handling of the device ids (transparent to the users of the Terraform provider)

For this reason, two patches exists that are identical in their behavior, but different in configuration (`.tf`):
1. https://github.com/Telmate/terraform-provider-proxmox/compare/master...in0rdr:fix/issues/44/copy_code
2. https://github.com/Telmate/terraform-provider-proxmox/compare/master...in0rdr:fix/issues/44/remove_id

The differences in configuration for Terraform users:
```
# approach (1) with explicit id
    network {
        id = 1
        name = "eth0"
        bridge = "vmbr0"
        ip = "dhcp"
        ip6 = "dhcp"
    }
```

```
# approach (2) with implicit id
    network {
        #id = 1
        name = "eth0"
        bridge = "vmbr0"
        ip = "dhcp"
        ip6 = "dhcp"
    }
```

From the code perspective, approach (2) looks prettier to me.

**Comment by gentoo9ball** [comment]
@in0rdr I'm with you. I think the id field can be generated. I vote approach 2. I don't see a need to reference it. If we have our networks in a map, similar to how I'm using my dynamic block, then I can still have an ID field, just not use it in the network block definition, thus not loosing any functionality that I can think of right now.

**Comment by in0rdr** [comment]
@gentoo9ball Thank you for the review.

> won't an 'if' block suffice to include/exclude the id field?

That should do the trick.

> why shouldn't ID be generated automatically for Qemu VMs as well?

IDs allow you to specify the absolute order/placement of your devices explicitly, including some kind of "distance" measure (e.g., you could start with id `4` followed by a device with id `88`). I am unsure how this is useful. Maybe your application requires the storage mounts (`/dev/sd{a,b,c,..}`) in a certain order? But then you could simply shift the devices and arrange them in ascending order in the list of devices (with implicit ids). The order is important, but only relative to the other devices. And how could the absolute id be important for network interfaces? The order maybe, I agree, but as just argued before this is always relative to the other devices in the list. The relative order of the devices can still be changed without explicit knowledge of their ids. Thus, I created #102. For the Qemu device IDs, maybe it is necessary to test such an approach with implicit IDs (and create another ticket..)
