### ISSUE TITLE
Too many redirections Error

### ISSUE THREAD

**Issue by lordsaibat** [Telmate/terraform-provider-proxmox#981]
During deployment of VM instances the plugin stops responding.

[31m│[0m [0m[1m[31mError: [0m[0m[1mRequest cancelled[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with module.proxmox-hindC-main.proxmox_vm_qemu.qemu_resource,
[31m│[0m [0m  on .terraform/modules/proxmox-hindC-main/proxmox/qemu/qemu.tf line 8, in resource "proxmox_vm_qemu" "qemu_resource":
[31m│[0m [0m   8: resource "proxmox_vm_qemu" "qemu_resource" [4m{[0m[0m
[31m│[0m [0m
[31m│[0m [0mThe plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with module.proxmox-hindS-main.proxmox_vm_qemu.qemu_resource,
[31m│[0m [0m  on .terraform/modules/proxmox-hindS-main/proxmox/qemu/qemu.tf line 8, in resource "proxmox_vm_qemu" "qemu_resource":
[31m│[0m [0m   8: resource "proxmox_vm_qemu" "qemu_resource" [4m{[0m[0m
[31m│[0m [0m
[31m│[0m [0mThe plugin encountered an error, and failed to respond to the
[31m│[0m [0mplugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
[31m│[0m [0mcontain more details.
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1m599 Too many redirections[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with module.proxmox1-hindC-main.proxmox_vm_qemu.qemu_resource,
[31m│[0m [0m  on .terraform/modules/proxmox1-hindC-main/proxmox/qemu/qemu.tf line 8, in resource "proxmox_vm_qemu" "qemu_resource":
[31m│[0m [0m   8: resource "proxmox_vm_qemu" "qemu_resource" [4m{[0m[0m
[31m│[0m [0m
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1m599 Too many redirections[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with module.proxmox1-hindS-main.proxmox_vm_qemu.qemu_resource,
[31m│[0m [0m  on .terraform/modules/proxmox1-hindS-main/proxmox/qemu/qemu.tf line 8, in resource "proxmox_vm_qemu" "qemu_resource":
[31m│[0m [0m   8: resource "proxmox_vm_qemu" "qemu_resource" [4m{[0m[0m
[31m│[0m [0m
[31m╵[0m[0m

Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:

panic: interface conversion: interface {} is string, not float64

goroutine 54 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc0000c0718, 0xc9d509?)
	github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0002ad300, {0xb66f60?, 0xc000452230})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:972 +0x2c4d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xdd7840?, {0xdd7840?, 0xc0003ea360?}, 0xd?, {0xb66f60?, 0xc000452230?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000110ee0, {0xdd7840, 0xc0003ea360}, 0xc000435ad0, 0xc0002ad180, {0xb66f60, 0xc000452230})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00039df38, {0xdd7840?, 0xc0003ea240?}, 0xc000146cd0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000250320, {0xdd7840?, 0xc00043e870?}, 0xc00044ebd0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc6bc20?, 0xc000250320}, {0xdd7840, 0xc00043e870}, 0xc00044eb60, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d81e0, {0xddb420, 0xc000007a00}, 0xc000520000, 0xc0003a9c80, 0x128f7a0, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0001d81e0, {0xddb420, 0xc000007a00}, 0xc000520000, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
panic: interface conversion: interface {} is string, not float64

goroutine 58 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc0000c2718, 0xc9d509?)
	github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc00037cf80, {0xb66f60?, 0xc0004500a0})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:972 +0x2c4d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xdd7840?, {0xdd7840?, 0xc00024f290?}, 0xd?, {0xb66f60?, 0xc0004500a0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00010eee0, {0xdd7840, 0xc00024f290}, 0xc000366f70, 0xc00037ce00, {0xb66f60, 0xc0004500a0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00031df08, {0xdd7840?, 0xc00024f170?}, 0xc000450550)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000258280, {0xdd7840?, 0xc00024e780?}, 0xc00025c070)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc6bc20?, 0xc000258280}, {0xdd7840, 0xc00024e780}, 0xc00025c000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d81e0, {0xddb420, 0xc0000076c0}, 0xc00045a000, 0xc000329c80, 0x128f7a0, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0001d81e0, {0xddb420, 0xc0000076c0}, 0xc00045a000, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!

**Detailed logs**

CSRFPreventionToken: 661A7AED:DWeuzNnBrv9lEe5MftzxGxQPf+gDa6TT+bll6DylQVo
Accept-Encoding: gzip

2024/04/13 08:32:55 >>>>>>>>>> REQUEST:
GET /api2/json/nodes/proxmox1/tasks/UPID:proxmox1:0007A54C:206EC677:661A7AED:qmclone:2000:root@pam:/status HTTP/1.1
Host: 192.168.69.5:8006
User-Agent: Go-http-client/1.1
Accept: application/json
Authorization: PVEAuthCookie=PVE:root@pam:661A7AED::XXXXXXX
CSRFPreventionToken: 661A7AED:DWeuzNnBrv9lEe5MftzxGxQPf+gDa6TT+bll6DylQVo
Accept-Encoding: gzip

2024/04/13 08:32:59 <<<<<<<<<< RESULT:
HTTP/1.1 599 Too many redirections
Connection: close
Cache-Control: max-age=0
Date: Sat, 13 Apr 2024 12:32:59 GMT
Expires: Sat, 13 Apr 2024 12:32:59 GMT
Pragma: no-cache
Server: pve-api-daemon/3.0

2024/04/13 08:32:59 <<<<<<<<<< RESULT:
HTTP/1.1 599 Too many redirections
Connection: close
Cache-Control: max-age=0
Date: Sat, 13 Apr 2024 12:32:59 GMT
Expires: Sat, 13 Apr 2024 12:32:59 GMT
Pragma: no-cache
Server: pve-api-daemon/3.0

**Comment by arty-hlr** [comment]
@lordsaibat Can you please mention why this has been closed? This is like stackoverflow posts where the author writes "Fixed it!"...
