### ISSUE TITLE
Windows VMs giving diff on `machine` to `null`

### ISSUE THREAD

**Issue by erya777** [Telmate/terraform-provider-proxmox#984]
When trying to run apply against windows host (qemu_os is win10) `machine` property always produces a change to null without any real effect:
```
proxmox_vm_qemu.server["wintest"]: Refreshing state... [id=hv-02/qemu/282]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # proxmox_vm_qemu.server["wintest"] will be updated in-place
  ~ resource "proxmox_vm_qemu" "server" {
        id                        = "hv-02/qemu/282"
      - machine                   = "pc-i440fx-7.2" -> null
        name                      = "wintest"
        # (41 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }
```

`machine` property on Windows hosts is getting created at VM creation time and is not supposed to change at all to avoid different issues (thread https://forum.proxmox.com/threads/machine-type-latest-missing-for-windows.86015/)

Current workaround to avoid constant changes is to use TF's lifecycle ignore_changes block like this:
```
resource "proxmox_vm_qemu" "server" {
  name = "bla-bla"
  qemu_os = "win10"
  .....
  lifecycle {
    ignore_changes = [machine]
  }
```

**Comment by Tinyblargon** [comment]
The machine type is overruled by the OS type, The case where this diffs to `null` should be suppressed. `machine` can't have a default due to it's dependence on the OS type.
