### ISSUE TITLE
Can't create LXC on non cluster proxmox node

### ISSUE THREAD

**Issue by Jungo495** [Telmate/terraform-provider-proxmox#99]
Hi. Trying to create LXC node and get error
Error: Error creating LXC container: 500 storage 'shared' does not exists, error status: {"data":null} 

my local-lvm storage use thin LVM thin and not support shared type
but i easily can create LXC with ansible

in resource "proxmox_lxc" i use
storage = "local-lvm"
can you advice please how to solve this error without changing storage type?

**Comment by Jungo495** [comment]
solved!
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

**Comment by BenGig** [comment]
Bump: can be closed
