### ISSUE TITLE
Cannot set "Upgrade packages" to "No" because of missing property

### ISSUE THREAD

**Issue by evgfilim1** [Telmate/terraform-provider-proxmox#997]
Proxmox 8.1.10 has an "Upgrade packages" item in "Cloud-init" config.
![Upgrade packages item](https://github.com/Telmate/terraform-provider-proxmox/assets/17182159/e85bba36-f8e9-44ae-b242-968d78b01946)
![Upgrade packages dialog](https://github.com/Telmate/terraform-provider-proxmox/assets/17182159/0172ae30-51b5-4040-a85d-d2952857b625)

But I can't turn it off via terraform. My `.tf` file:
```hcl
terraform {
  required_providers {
    proxmox = {
      source  = "telmate/proxmox"
      version = "3.0.1-rc1"
    }
  }
}

provider "proxmox" {
  pm_api_url          = var.pm_api_url
  pm_api_token_id     = var.pm_api_token_id
  pm_api_token_secret = var.pm_api_token_secret
}

# ... omitted ...

locals {
  ipconfigs = {
    for i, network in var.networks :
    "ipconfig${i}" => network.ipconfig
    if network.ipconfig != null
  }
}

resource "proxmox_vm_qemu" "pve_vm" {
  name        = var.vm_name
  target_node = var.node
  desc        = var.description
  clone       = var.clone_from
  sockets     = var.cpu_sockets
  cores       = var.cpu_cores
  memory      = var.ram_size
  os_type     = var.provisioning_type
  qemu_os     = var.qemu_os_type
  vmid        = var.vm_id
  scsihw      = var.scsi_hw
  agent       = var.qemu_ga_enabled ? 1 : 0
  full_clone  = var.do_full_clone
  tags        = var.tags
  boot        = "order=${var.boot_order}"
  ciuser      = var.default_user_name
  cipassword  = var.default_user_password
  sshkeys     = (
    length(var.default_user_ssh_pubkeys) > 0
    ? join("\n", var.default_user_ssh_pubkeys)
    : null
  )
  nameserver   = var.dns_config.nameserver
  searchdomain = var.dns_config.search
  ipconfig0    = lookup(local.ipconfigs, "ipconfig0", null)
  ipconfig1    = lookup(local.ipconfigs, "ipconfig1", null)
  ipconfig2    = lookup(local.ipconfigs, "ipconfig2", null)
  ipconfig3    = lookup(local.ipconfigs, "ipconfig3", null)
  dynamic "network" {
    for_each = var.networks
    content {
      model  = "virtio"
      bridge = network.value.bridge
    }
  }
  disks {
    scsi {
      scsi0 {
        disk {
          size    = var.disk_size
          storage = var.disk_storage
          backup  = var.disk_do_backup
        }
      }
    }
  }
  serial {
    id   = 0
    type = "socket"
  }
  vga {
    type = "serial0"
  }
  cloudinit_cdrom_storage = "local-lvm"
}
```

It would be nice to add a `ciupgrade` or something similar to turn on/off auto upgrading packages on boot.

**Comment by maksimsamt** [comment]
@Tinyblargon,
Do you plan to implement this feature?
+1 for adding

**Comment by Tinyblargon** [comment]
@maksimsamt yes, but it will first need to be added to the upstream proxmox SDK.

**Comment by Tinyblargon** [comment]
I am currently working on this upstream. It's gonna be a bit more work than just adding a setting. This is a good moment to group all the cloud-init things into a separate data structure.

**Comment by Tinyblargon** [comment]
https://github.com/Telmate/proxmox-api-go/pull/339

**Comment by Tinyblargon** [comment]
@evgfilim1 Could you check if #1049 fixes this for you?

**Comment by maksimsamt** [comment]
@Tinyblargon,
I've checked and tested #1049 `ciupgrade` argument and it works.
It can be disabled (false) and reverted back (true).
One note, this change should initiate automatic reboot after `ciupgrade`  change if `automatic_reboot` is enabled.
The current implementation does not trigger a reboot.

**Comment by Tinyblargon** [comment]
@maksimsamt agreed, but it only needs to reboot when it goes from `False` to `True`

**Comment by Tinyblargon** [comment]
@maksimsamt changing `ciupgrade` from `false` to `true` now restarts the VM

**Comment by Tinyblargon** [comment]
Setting `ciupgrade` on PVE versions lower than 8.0.0 causes issue https://github.com/Telmate/proxmox-api-go/issues/344

**Comment by JosBritton** [comment]
> @evgfilim1 Could you check if #1049 fixes this for you?

Tested #1049 and works well, a great QoL feature.
